// 30 günlük ders içeriği. Her ders: t = başlık, n = kısa ipucu, p = [hedef dilde cümle, Türkçesi].
// Ders günü, o dilde daha önce çalışılan gün sayısına göre ilerler (bkz. index.html → getLessonDay).
// İçeriği olmayan diller index.html'deki tek derslik varsayılana düşer.
window.LESSONS = {
  en: [
    {t:'Mesleki tanışma', n:'Adını, rolünü ve deneyimini tek akışta söyle. Cümleleri kendi durumuna göre uyarla.', p:[
      ["Hi, I'm Ahmet. I work in cybersecurity.", 'Merhaba, ben Ahmet. Siber güvenlikte çalışıyorum.'],
      ["I'm responsible for keeping our systems secure.", 'Sistemlerimizi güvende tutmaktan sorumluyum.'],
      ["I've been in this field for a few years.", 'Birkaç yıldır bu alandayım.'],
      ['What do you do?', 'Sen ne iş yapıyorsun?'],
      ["It's great to finally meet you.", 'Sonunda tanıştığımıza çok sevindim.']]},
    {t:'İşini anlatmak', n:'Rutin işler için present simple: I check, I monitor, I review.', p:[
      ['I monitor our network for unusual activity.', 'Ağımızı olağandışı etkinliklere karşı izliyorum.'],
      ['I review security alerts every morning.', 'Her sabah güvenlik uyarılarını incelerim.'],
      ['I work closely with the IT team.', 'BT ekibiyle yakın çalışırım.'],
      ['Most of my work is remote.', 'İşimin çoğu uzaktan.'],
      ['The best part of my job is solving problems.', 'İşimin en güzel yanı problem çözmek.']]},
    {t:'Günlük iş rutini', n:'Sıklık zarfları fiilden önce gelir: I usually start, I rarely finish.', p:[
      ['I usually start work at nine.', 'Genelde işe dokuzda başlarım.'],
      ['First, I check my emails.', 'Önce e-postalarımı kontrol ederim.'],
      ['We have a short meeting every day.', 'Her gün kısa bir toplantımız olur.'],
      ['I rarely finish before six.', 'Nadiren altıdan önce bitiririm.'],
      ['After work, I try to relax.', 'İşten sonra dinlenmeye çalışırım.']]},
    {t:'Kısa sohbet (small talk)', n:'"isn\'t it?" gibi soru ekleri sohbeti açık tutar; sonunu düşen tonla söyle.', p:[
      ['How was your weekend?', 'Hafta sonun nasıldı?'],
      ["Busy week, isn't it?", 'Yoğun bir hafta, değil mi?'],
      ['Have you been here before?', 'Daha önce burada bulundun mu?'],
      ["The weather's been terrible lately.", 'Son zamanlarda hava berbat.'],
      ['Anyway, I should get back to work.', 'Neyse, işe dönsem iyi olur.']]},
    {t:'Açıklama istemek', n:'Anlamadığında susma; bu kalıplar konuşmayı senin kontrolünde tutar.', p:[
      ['Sorry, could you say that again?', 'Pardon, tekrar söyler misiniz?'],
      ['What do you mean by that?', 'Bununla ne demek istiyorsunuz?'],
      ['Could you speak a bit more slowly?', 'Biraz daha yavaş konuşabilir misiniz?'],
      ['Just to confirm, the deadline is Friday?', 'Teyit edeyim, son tarih cuma mı?'],
      ['Let me make sure I understand.', 'Doğru anladığımdan emin olayım.']]},
    {t:'Toplantı ayarlamak', n:'Söz verirken "I\'ll" (I will) kullanılır: I\'ll send, I\'ll check.', p:[
      ['Are you free on Thursday afternoon?', 'Perşembe öğleden sonra müsait misin?'],
      ['How about 3 p.m.?', "Saat 3'e ne dersin?"],
      ['That works for me.', 'Bana uyar.'],
      ['Can we move the meeting to next week?', 'Toplantıyı gelecek haftaya alabilir miyiz?'],
      ["I'll send you a calendar invite.", 'Sana takvim daveti göndereceğim.']]},
    {t:'E-posta kalıpları', n:'Kısa ve net yaz: selam, amaç, istek, kapanış.', p:[
      ["I hope you're doing well.", 'Umarım iyisinizdir.'],
      ["I'm writing to ask about the new policy.", 'Yeni politika hakkında sormak için yazıyorum.'],
      ['Please find the report attached.', 'Rapor ektedir.'],
      ['Let me know if you have any questions.', 'Sorunuz olursa bana bildirin.'],
      ['Best regards, Ahmet', 'Saygılarımla, Ahmet']]},
    {t:'Geçmiş projeler', n:'Bitmiş ve zamanı belli olaylar için past simple: last year, in 2023.', p:[
      ['Last year, we moved our servers to the cloud.', 'Geçen yıl sunucularımızı buluta taşıdık.'],
      ['I led a small team of three people.', 'Üç kişilik küçük bir ekibe liderlik ettim.'],
      ['It took about six months.', 'Yaklaşık altı ay sürdü.'],
      ['We faced a few problems at the start.', 'Başta birkaç sorunla karşılaştık.'],
      ['In the end, the project was a success.', 'Sonunda proje başarılı oldu.']]},
    {t:'Deneyim anlatmak', n:'Zamanı belirsiz deneyim ve yeni biten işler için present perfect: ever, never, just, yet, already.', p:[
      ['Have you ever worked abroad?', 'Hiç yurt dışında çalıştın mı?'],
      ["I've never been to France.", "Hiç Fransa'ya gitmedim."],
      ["I've just finished the report.", 'Raporu az önce bitirdim.'],
      ["We haven't fixed the bug yet.", 'Hatayı henüz düzeltmedik.'],
      ['She has already joined the call.', 'O çoktan görüşmeye katıldı.']]},
    {t:'Teknik sorun anlatmak', n:'"keep + -ing" tekrar eden, can sıkıcı bir durumu anlatır: it keeps crashing.', p:[
      ['The system keeps crashing.', 'Sistem sürekli çöküyor.'],
      ["I can't log in to my account.", 'Hesabıma giriş yapamıyorum.'],
      ['It started after the last update.', 'Son güncellemeden sonra başladı.'],
      ['Have you tried restarting it?', 'Yeniden başlatmayı denedin mi?'],
      ["The error message says 'access denied'.", "Hata mesajı 'erişim reddedildi' diyor."]]},
    {t:'Talimat vermek', n:'Talimat için emir kipi: cümleye fiille başla. Sıra için first, then, once.', p:[
      ['Click on the settings icon.', 'Ayarlar simgesine tıkla.'],
      ["Then choose 'Security'.", "Sonra 'Güvenlik'i seç."],
      ['Make sure the box is checked.', 'Kutunun işaretli olduğundan emin ol.'],
      ["Don't close the window yet.", 'Pencereyi henüz kapatma.'],
      ["Once it's done, restart your computer.", 'Bittiğinde bilgisayarını yeniden başlat.']]},
    {t:'Güçlü şifreler', n:'Tavsiye için "should", kesin kural için "always / never".', p:[
      ['Use a long password with random words.', 'Rastgele kelimelerden oluşan uzun bir şifre kullan.'],
      ['Never reuse the same password.', 'Aynı şifreyi asla tekrar kullanma.'],
      ['A password manager makes this easier.', 'Şifre yöneticisi bunu kolaylaştırır.'],
      ['Turn on two-factor authentication.', 'İki adımlı doğrulamayı aç.'],
      ['You should change it if it leaks.', 'Sızarsa değiştirmelisin.']]},
    {t:'Oltalama (phishing)', n:'"look + sıfat" bir izlenimi anlatır: looks suspicious, looks fine.', p:[
      ['This email looks suspicious.', 'Bu e-posta şüpheli görünüyor.'],
      ["The sender's address is slightly different.", 'Gönderenin adresi biraz farklı.'],
      ["Don't click on the link.", 'Bağlantıya tıklama.'],
      ["They're trying to steal your password.", 'Şifreni çalmaya çalışıyorlar.'],
      ['Please report it to the security team.', 'Lütfen güvenlik ekibine bildir.']]},
    {t:'Olay bildirmek', n:'Edilgen yapı, yapanın bilinmediği durumda kullanılır: has been compromised = ele geçirildi.', p:[
      ['I think my laptop has been compromised.', 'Sanırım dizüstü bilgisayarım ele geçirildi.'],
      ['I noticed it about an hour ago.', 'Yaklaşık bir saat önce fark ettim.'],
      ["I've disconnected it from the network.", 'Onu ağdan ayırdım.'],
      ['No files seem to be missing.', 'Eksik dosya yok gibi görünüyor.'],
      ['What should I do next?', 'Şimdi ne yapmalıyım?']]},
    {t:'Öneride bulunmak', n:'"suggest" fiilinden sonra -ing gelir: I suggest testing.', p:[
      ["Why don't we update everything tonight?", 'Neden bu gece her şeyi güncellemiyoruz?'],
      ['I suggest testing it first.', 'Önce test etmeyi öneriyorum.'],
      ['Maybe we could ask the vendor.', 'Belki tedarikçiye sorabiliriz.'],
      ['It might be a good idea to back up the data.', 'Verileri yedeklemek iyi bir fikir olabilir.'],
      ["Let's discuss it tomorrow.", 'Yarın konuşalım.']]},
    {t:'Katılmak ve katılmamak', n:'Katılmadığını yumuşat: I\'m afraid…, I see your point, but…', p:[
      ['I completely agree with you.', 'Sana tamamen katılıyorum.'],
      ["That's a good point.", 'Bu iyi bir nokta.'],
      ['I see what you mean, but…', 'Ne demek istediğini anlıyorum ama…'],
      ["I'm not sure about that.", 'Bundan emin değilim.'],
      ["I'm afraid I disagree.", 'Korkarım katılmıyorum.']]},
    {t:'Gelecek planları', n:'Plan: going to; kesinleşmiş program: present continuous; tahmin: will.', p:[
      ["I'm going to take a certification exam.", 'Bir sertifika sınavına gireceğim.'],
      ["We're launching the new system next month.", 'Yeni sistemi gelecek ay devreye alıyoruz.'],
      ["I'll probably work from home tomorrow.", 'Yarın muhtemelen evden çalışacağım.'],
      ['My goal is to reach B2 by next year.', "Hedefim gelecek yıla kadar B2'ye ulaşmak."],
      ['What are your plans for the summer?', 'Yaz için planların neler?']]},
    {t:'Seçenekleri karşılaştırmak', n:'Kısa sıfat: -er / -est; uzun sıfat: more / most.', p:[
      ['This tool is faster than the old one.', 'Bu araç eskisinden daha hızlı.'],
      ["It's more expensive, but it's safer.", 'Daha pahalı ama daha güvenli.'],
      ['The second option is the cheapest.', 'İkinci seçenek en ucuzu.'],
      ['Both options are equally good.', 'İki seçenek de eşit derecede iyi.'],
      ["It's not as easy as it looks.", 'Göründüğü kadar kolay değil.']]},
    {t:'Görüntülü görüşme', n:'"Let me…" = …ayım: let me check, let me share.', p:[
      ['Can you hear me?', 'Beni duyabiliyor musun?'],
      ["You're on mute.", 'Mikrofonun kapalı.'],
      ['Sorry, you broke up for a second.', 'Pardon, bir saniye sesin kesildi.'],
      ['Let me share my screen.', 'Ekranımı paylaşayım.'],
      ['Can everyone see my screen?', 'Herkes ekranımı görebiliyor mu?']]},
    {t:'Kibarca yardım istemek', n:'"Would you mind" sonrasında -ing gelir: would you mind checking…', p:[
      ['Could you do me a favour?', 'Bana bir iyilik yapar mısın?'],
      ['Would you mind checking this for me?', 'Bunu benim için kontrol eder misin?'],
      ["I'd really appreciate your help.", 'Yardımın için çok minnettar olurum.'],
      ['Do you have a minute?', 'Bir dakikan var mı?'],
      ["Thanks, that's really helpful.", 'Teşekkürler, çok faydalı oldu.']]},
    {t:'Bir süreci anlatmak', n:'Süreç anlatırken edilgen yapı yaygındır: access is granted, data is encrypted.', p:[
      ['First, the user enters a password.', 'Önce kullanıcı şifresini girer.'],
      ['Next, the system sends a code.', 'Sonra sistem bir kod gönderir.'],
      ['After that, the user types the code.', 'Ardından kullanıcı kodu yazar.'],
      ['Finally, access is granted.', 'Son olarak erişim verilir.'],
      ['The whole process takes a few seconds.', 'Tüm süreç birkaç saniye sürer.']]},
    {t:'Riskleri anlatmak', n:'Olasılık bildiren sözcükler: could, might, unlikely, possible.', p:[
      ["If we don't patch this, attackers could get in.", 'Bunu yamamazsak saldırganlar içeri girebilir.'],
      ['The risk is low, but the impact is high.', 'Risk düşük ama etkisi yüksek.'],
      ['This could cause a data breach.', 'Bu bir veri ihlaline yol açabilir.'],
      ['We need to reduce the risk.', 'Riski azaltmamız gerekiyor.'],
      ["It's unlikely, but it's possible.", 'Pek olası değil ama mümkün.']]},
    {t:'Durum güncellemesi', n:'Ne bitti, ne sürüyor, ne bekleniyor: üç cümle yeter.', p:[
      ["Here's a quick update.", 'İşte kısa bir güncelleme.'],
      ["We're on track.", 'Plana uygun ilerliyoruz.'],
      ['Most of the work is done.', 'İşin çoğu bitti.'],
      ["We're still waiting for approval.", 'Hâlâ onay bekliyoruz.'],
      ["I'll keep you posted.", 'Seni haberdar edeceğim.']]},
    {t:'Gecikme ve son tarih', n:'"due to" + isim = …nedeniyle: due to a technical issue.', p:[
      ["I'm afraid we're running behind schedule.", 'Korkarım programın gerisindeyiz.'],
      ['We need two more days.', 'İki güne daha ihtiyacımız var.'],
      ['The delay is due to a technical issue.', 'Gecikme teknik bir sorundan kaynaklanıyor.'],
      ['Can we extend the deadline?', 'Son tarihi uzatabilir miyiz?'],
      ['Sorry for the inconvenience.', 'Verdiğimiz rahatsızlık için özür dileriz.']]},
    {t:'İş seyahati', n:'"I\'d like" (I would like), "I want"ten daha kibardır.', p:[
      ["I'd like to check in, please.", 'Giriş yapmak istiyorum, lütfen.'],
      ["I'm here for a conference.", 'Bir konferans için buradayım.'],
      ['Could I have a receipt, please?', 'Fiş alabilir miyim, lütfen?'],
      ['Is there a shuttle to the airport?', 'Havaalanına servis var mı?'],
      ['My flight has been delayed.', 'Uçuşum rötar yaptı.']]},
    {t:'Teknoloji hakkında fikir', n:'Fikir kalıpları: In my opinion…, Personally…, What\'s your take?', p:[
      ['In my opinion, AI is a useful tool.', 'Bence yapay zekâ faydalı bir araç.'],
      ['It saves time, but it can make mistakes.', 'Zaman kazandırıyor ama hata yapabiliyor.'],
      ['Personally, I prefer open-source software.', 'Ben şahsen açık kaynak yazılımı tercih ederim.'],
      ['Privacy is becoming more important.', 'Gizlilik giderek daha önemli hâle geliyor.'],
      ["What's your take on this?", 'Bu konuda ne düşünüyorsun?']]},
    {t:'İş görüşmesi', n:'"good at" sonrasında -ing ya da isim gelir: good at analysing.', p:[
      ["I'm good at analysing problems.", 'Problemleri analiz etmekte iyiyim.'],
      ['I work well under pressure.', 'Baskı altında iyi çalışırım.'],
      ['One of my strengths is attention to detail.', 'Güçlü yönlerimden biri detaylara dikkat etmem.'],
      ["I'm working on my public speaking.", 'Topluluk önünde konuşma becerimi geliştiriyorum.'],
      ["I'm really interested in this role.", 'Bu pozisyonla gerçekten ilgileniyorum.']]},
    {t:'Koşul cümleleri', n:'Gerçek koşul: If + present, will. Hayalî koşul: If + past, would.', p:[
      ['If the alarm goes off, call me.', 'Alarm çalarsa beni ara.'],
      ["If I had more time, I'd study every day.", 'Daha çok vaktim olsaydı her gün çalışırdım.'],
      ['If you update the software, the bug will disappear.', 'Yazılımı güncellersen hata ortadan kalkar.'],
      ["Unless it's urgent, send an email.", 'Acil değilse e-posta gönder.'],
      ['What would you do if you were me?', 'Benim yerimde olsan ne yapardın?']]},
    {t:'Sonuç sunmak', n:'Sunum akışı: giriş, veri, yorum, özet.', p:[
      ['Let me walk you through the results.', 'Sonuçları size adım adım anlatayım.'],
      ['As you can see on this slide…', 'Bu slaytta gördüğünüz gibi…'],
      ['The number of attacks dropped by 30%.', 'Saldırı sayısı %30 azaldı.'],
      ['This shows that training works.', 'Bu, eğitimin işe yaradığını gösteriyor.'],
      ["To sum up, we're in a better position.", 'Özetle, daha iyi bir konumdayız.']]},
    {t:'2 dakikada kendini anlat', n:'Bu cümlelerle 2 dakikalık bir kayıt yap ve ilk günkü tanıtımınla karşılaştır.', p:[
      ['Let me tell you a bit about myself.', 'Size biraz kendimden bahsedeyim.'],
      ["I've been working in cybersecurity for several years.", 'Birkaç yıldır siber güvenlikte çalışıyorum.'],
      ["Recently, I've been improving my English every day.", 'Son zamanlarda İngilizcemi her gün geliştiriyorum.'],
      ['My next goal is to lead security projects.', 'Bir sonraki hedefim güvenlik projelerini yönetmek.'],
      ['Thanks for listening. Any questions?', 'Dinlediğiniz için teşekkürler. Sorunuz var mı?']]}
  ],
  fr: [
    {t:'Selamlaşma ve tanışma', n:'Bonjour gündüz, bonsoir akşam kullanılır. "Je m\'appelle" tek nefeste: jö ma-pel.', p:[
      ['Bonjour !', 'Merhaba! / Günaydın!'],
      ["Je m'appelle Ahmet.", 'Benim adım Ahmet.'],
      ["Comment tu t'appelles ?", 'Senin adın ne?'],
      ['Enchanté.', 'Memnun oldum.'],
      ['Au revoir, à demain !', 'Hoşça kal, yarın görüşürüz!']]},
    {t:'Nerelisin?', n:'Ülke adlarının çoğu dişildir: de Turquie, en France.', p:[
      ['Je viens de Turquie.', "Türkiye'den geliyorum."],
      ['Je suis turc.', "Türk'üm."],
      ["J'habite en Turquie.", "Türkiye'de yaşıyorum."],
      ["Tu viens d'où ?", 'Nerelisin?'],
      ['Tu habites où ?', 'Nerede yaşıyorsun?']]},
    {t:'Sayılar ve yaş', n:'Yaş "avoir" (sahip olmak) ile söylenir: J\'ai trente ans = otuz yaşım var.', p:[
      ['un, deux, trois, quatre, cinq', 'bir, iki, üç, dört, beş'],
      ['six, sept, huit, neuf, dix', 'altı, yedi, sekiz, dokuz, on'],
      ['Tu as quel âge ?', 'Kaç yaşındasın?'],
      ["J'ai trente ans.", 'Otuz yaşındayım.'],
      ["Il y a deux cafés.", 'İki kahve var.']]},
    {t:'Meslekler', n:'Meslek söylerken artikel kullanılmaz: Je suis ingénieur.', p:[
      ["Qu'est-ce que tu fais dans la vie ?", 'Ne iş yapıyorsun?'],
      ['Je travaille dans la cybersécurité.', 'Siber güvenlikte çalışıyorum.'],
      ['Je travaille dans une entreprise.', 'Bir şirkette çalışıyorum.'],
      ["J'aime mon travail.", 'İşimi seviyorum.'],
      ['Et toi ?', 'Ya sen?']]},
    {t:'Aile', n:'İyelik: mon père (eril), ma mère (dişil), mes parents (çoğul).', p:[
      ['Voici ma famille.', 'İşte ailem.'],
      ["J'ai un frère et une sœur.", 'Bir erkek kardeşim ve bir kız kardeşim var.'],
      ['Mon père est à la maison.', 'Babam evde.'],
      ['Tu as des enfants ?', 'Çocukların var mı?'],
      ["J'ai une grande famille.", 'Kalabalık bir ailem var.']]},
    {t:'Kafede', n:'"Je voudrais" (isterdim), "je veux"den daha kibardır.', p:[
      ["Un café, s'il vous plaît.", 'Bir kahve, lütfen.'],
      ['Je voudrais un croissant.', 'Bir kruvasan istiyorum.'],
      ["C'est combien ?", 'Ne kadar?'],
      ["L'addition, s'il vous plaît.", 'Hesap, lütfen.'],
      ['Merci beaucoup !', 'Çok teşekkürler!']]},
    {t:'Günlük rutin', n:'Dönüşlü fiiller "me" alır: je me lève, je me couche.', p:[
      ['Je me lève à sept heures.', 'Saat yedide kalkarım.'],
      ['Je prends le petit-déjeuner.', 'Kahvaltı yaparım.'],
      ['Je vais au travail.', 'İşe giderim.'],
      ['Je rentre le soir.', 'Akşam eve dönerim.'],
      ['Je me couche à onze heures.', 'Saat on birde yatarım.']]},
    {t:'Saat kaç?', n:'"Il est … heures" kalıbı: Il est deux heures = saat iki.', p:[
      ['Quelle heure est-il ?', 'Saat kaç?'],
      ['Il est huit heures.', 'Saat sekiz.'],
      ['Il est midi.', 'Saat öğlen on iki.'],
      ['À quelle heure ?', 'Saat kaçta?'],
      ['Le cours commence à neuf heures.', 'Ders dokuzda başlıyor.']]},
    {t:'Günler ve planlar', n:'Gün adları küçük harfle yazılır: lundi, mardi, samedi…', p:[
      ["Aujourd'hui, c'est lundi.", 'Bugün pazartesi.'],
      ['Demain, je travaille.', 'Yarın çalışıyorum.'],
      ['Samedi, je suis libre.', 'Cumartesi boşum.'],
      ['Tu es libre dimanche ?', 'Pazar günü boş musun?'],
      ['On se voit mardi ?', 'Salı görüşelim mi?']]},
    {t:'Hava durumu', n:'Hava çoğunlukla "il fait" ile anlatılır: il fait beau, il fait froid.', p:[
      ["Il fait beau aujourd'hui.", 'Bugün hava güzel.'],
      ['Il fait froid.', 'Hava soğuk.'],
      ['Il fait chaud.', 'Hava sıcak.'],
      ['Il pleut.', 'Yağmur yağıyor.'],
      ['Quel temps fait-il ?', 'Hava nasıl?']]},
    {t:'Sevdiklerim', n:'aimer + le/la: J\'aime le café. Olumsuz: je n\'aime pas.', p:[
      ["J'aime le café.", 'Kahveyi severim.'],
      ["Je n'aime pas le thé.", 'Çayı sevmem.'],
      ["J'adore la musique.", 'Müziğe bayılırım.'],
      ['Tu aimes le sport ?', 'Sporu sever misin?'],
      ['Je préfère le cinéma.', 'Sinemayı tercih ederim.']]},
    {t:'Markette', n:'Belirsiz miktar: du pain, de la viande, des pommes.', p:[
      ['Je voudrais du pain.', 'Biraz ekmek istiyorum.'],
      ["Un kilo de pommes, s'il vous plaît.", 'Bir kilo elma, lütfen.'],
      ['Vous avez du lait ?', 'Sütünüz var mı?'],
      ["C'est tout, merci.", 'Hepsi bu, teşekkürler.'],
      ['Je paie par carte.', 'Kartla ödüyorum.']]},
    {t:'Fiyat sormak', n:'20 vingt, 30 trente, 50 cinquante, 100 cent.', p:[
      ['Ça coûte combien ?', 'Bu ne kadar?'],
      ['Ça fait vingt euros.', 'Yirmi euro tutuyor.'],
      ["C'est trop cher.", 'Çok pahalı.'],
      ["C'est bon marché.", 'Ucuz.'],
      ['Vous acceptez la carte ?', 'Kart kabul ediyor musunuz?']]},
    {t:'Yol sormak', n:'Kibar giriş: Excusez-moi. "Où est… ?" = … nerede?', p:[
      ['Excusez-moi, où est la gare ?', 'Affedersiniz, gar nerede?'],
      ["C'est loin ?", 'Uzak mı?'],
      ['Allez tout droit.', 'Dümdüz gidin.'],
      ['Tournez à gauche.', 'Sola dönün.'],
      ["C'est à droite.", 'Sağda.']]},
    {t:'Ulaşım', n:'Araçla gitmek "en": en bus, en métro. Yürüyerek: à pied.', p:[
      ['Je prends le métro.', 'Metroya binerim.'],
      ['Je vais au travail en bus.', 'İşe otobüsle giderim.'],
      ["Un billet pour Paris, s'il vous plaît.", "Paris'e bir bilet, lütfen."],
      ['Le train part à quelle heure ?', 'Tren saat kaçta kalkıyor?'],
      ['Je vais à pied.', 'Yürüyerek gidiyorum.']]},
    {t:'Otelde', n:'"Il y a" = var. Evet/hayır sorusunda cümlenin sonunu yükselt.', p:[
      ["J'ai une réservation.", 'Rezervasyonum var.'],
      ['Pour deux nuits.', 'İki gece için.'],
      ['Le petit-déjeuner est compris ?', 'Kahvaltı dahil mi?'],
      ['Il y a le wifi ?', 'Wi-fi var mı?'],
      ['Quel est le mot de passe ?', 'Şifre ne?']]},
    {t:'Evim', n:'Tarif ederken "il y a" (var) ve "c\'est" (bu …) kullan.', p:[
      ["J'habite dans un appartement.", 'Bir dairede yaşıyorum.'],
      ['Il y a trois pièces.', 'Üç oda var.'],
      ['La cuisine est petite.', 'Mutfak küçük.'],
      ['Le salon est grand.', 'Salon büyük.'],
      ["J'aime mon quartier.", 'Mahallemi seviyorum.']]},
    {t:'Şehrim', n:'Sıfatların çoğu isimden sonra gelir; belle, grande, petite gibi kısa sıfatlar önce gelebilir.', p:[
      ['Ma ville est grande.', 'Şehrim büyük.'],
      ['Il y a beaucoup de monde.', 'Çok kalabalık.'],
      ["Il y a un musée près d'ici ?", 'Buraya yakın bir müze var mı?'],
      ["C'est une belle ville.", 'Güzel bir şehir.'],
      ['Je voudrais visiter Paris.', "Paris'i gezmek isterim."]]},
    {t:'Nasılsın, sağlık', n:'Ağrı: "J\'ai mal à…" + vücut bölümü: j\'ai mal à la tête.', p:[
      ['Ça va ?', 'Nasılsın? / İyi misin?'],
      ['Je suis fatigué.', 'Yorgunum.'],
      ["J'ai mal à la tête.", 'Başım ağrıyor.'],
      ['Je suis malade.', 'Hastayım.'],
      ['Il faut aller chez le médecin.', 'Doktora gitmek lazım.']]},
    {t:'Telefonda', n:'"Vous" resmî ya da çoğul hitaptır; tanımadığın birine her zaman vous de.', p:[
      ["Allô, c'est Ahmet.", 'Alo, ben Ahmet.'],
      ['Je peux parler à Marie ?', 'Marie ile konuşabilir miyim?'],
      ["Vous pouvez répéter, s'il vous plaît ?", 'Tekrar edebilir misiniz, lütfen?'],
      ["Plus lentement, s'il vous plaît.", 'Daha yavaş, lütfen.'],
      ['Je vous rappelle.', 'Sizi geri ararım.']]},
    {t:'Randevu almak', n:'"Je dois" + mastar = …mam gerekiyor: je dois annuler.', p:[
      ['Je voudrais prendre rendez-vous.', 'Randevu almak istiyorum.'],
      ['Vous êtes disponible jeudi ?', 'Perşembe müsait misiniz?'],
      ['Jeudi à dix heures, ça vous va ?', 'Perşembe saat onda, size uyar mı?'],
      ["Oui, c'est parfait.", 'Evet, mükemmel.'],
      ['Je dois annuler.', 'İptal etmem gerekiyor.']]},
    {t:'Dün ne yaptın?', n:'Passé composé = avoir + geçmiş ortaç: j\'ai mangé. Hareket fiilleri être alır: je suis allé.', p:[
      ["Hier, j'ai travaillé.", 'Dün çalıştım.'],
      ["J'ai mangé au restaurant.", 'Restoranda yemek yedim.'],
      ["J'ai regardé un film.", 'Bir film izledim.'],
      ['Tu as bien dormi ?', 'İyi uyudun mu?'],
      ['Je suis allé au marché.', 'Pazara gittim.']]},
    {t:'Hafta sonu', n:'"C\'était…" = …idi; geçmişi yorumlarken çok kullanılır.', p:[
      ["Qu'est-ce que tu as fait ce week-end ?", 'Bu hafta sonu ne yaptın?'],
      ["J'ai vu des amis.", 'Arkadaşlarımla görüştüm.'],
      ['Je suis resté à la maison.', 'Evde kaldım.'],
      ["J'ai fait du sport.", 'Spor yaptım.'],
      ["C'était super !", 'Harikaydı!']]},
    {t:'Yarın ne yapacaksın?', n:'Yakın gelecek: aller + mastar: je vais travailler = çalışacağım.', p:[
      ['Demain, je vais travailler.', 'Yarın çalışacağım.'],
      ['Ce soir, je vais cuisiner.', 'Bu akşam yemek yapacağım.'],
      ['On va au cinéma ?', 'Sinemaya gidelim mi?'],
      ['Je vais apprendre le français.', 'Fransızca öğreneceğim.'],
      ["Qu'est-ce que tu vas faire ?", 'Ne yapacaksın?']]},
    {t:'Hobiler', n:'Oyun ve spor dalı: jouer au…; etkinlik: faire du / de la…', p:[
      ["Qu'est-ce que tu fais le week-end ?", 'Hafta sonları ne yaparsın?'],
      ['Je lis beaucoup.', 'Çok okurum.'],
      ['Je joue au football.', 'Futbol oynarım.'],
      ['Je fais de la natation.', 'Yüzerim.'],
      ["J'écoute des podcasts.", 'Podcast dinlerim.']]},
    {t:'Mağazada', n:'Nesne zamiri fiilden önce gelir: je le prends = onu alıyorum.', p:[
      ['Je cherche une veste.', 'Bir ceket arıyorum.'],
      ["Vous l'avez en bleu ?", 'Mavisi var mı?'],
      ["Je peux l'essayer ?", 'Deneyebilir miyim?'],
      ["C'est trop petit.", 'Çok küçük.'],
      ['Je le prends.', 'Bunu alıyorum.']]},
    {t:'Restoranda', n:'Sipariş verirken "je vais prendre" ya da "je voudrais" kullan.', p:[
      ["Une table pour deux, s'il vous plaît.", 'İki kişilik bir masa, lütfen.'],
      ["Qu'est-ce que vous recommandez ?", 'Ne tavsiye edersiniz?'],
      ['Je vais prendre le poisson.', 'Balık alacağım.'],
      ["De l'eau, s'il vous plaît.", 'Su, lütfen.'],
      ["C'était délicieux.", 'Çok lezzetliydi.']]},
    {t:'Duygular', n:'Konuşan kadınsa sıfat -e alır: contente, désolée. Çoğu zaman okunuş değişmez.', p:[
      ['Je suis content.', 'Mutluyum.'],
      ['Je suis stressé.', 'Stresliyim.'],
      ["J'ai peur.", 'Korkuyorum.'],
      ['Je suis désolé.', 'Üzgünüm / Özür dilerim.'],
      ['Pas de problème.', 'Sorun değil.']]},
    {t:'İş ve bilgisayar', n:'Olumsuz: ne + fiil + pas. Günlük konuşmada "ne" çoğu zaman düşer.', p:[
      ["Mon ordinateur ne marche pas.", 'Bilgisayarım çalışmıyor.'],
      ["J'ai oublié mon mot de passe.", 'Şifremi unuttum.'],
      ["Je reçois beaucoup d'e-mails.", 'Çok e-posta alıyorum.'],
      ["Attention, c'est un faux message.", 'Dikkat, bu sahte bir mesaj.'],
      ['Je travaille à distance.', 'Uzaktan çalışıyorum.']]},
    {t:'1 dakikada kendini anlat', n:'Bu beş cümleyi birleştirip 1 dakikalık kayıt yap ve ilk günkü kaydınla karşılaştır.', p:[
      ["Je m'appelle Ahmet, je viens de Turquie.", "Adım Ahmet, Türkiye'den geliyorum."],
      ['Je travaille dans la cybersécurité.', 'Siber güvenlikte çalışıyorum.'],
      ["J'apprends le français depuis un mois.", 'Bir aydır Fransızca öğreniyorum.'],
      ["C'est difficile, mais j'adore ça.", 'Zor ama bayılıyorum.'],
      ['Je voudrais parler couramment un jour.', 'Bir gün akıcı konuşmak istiyorum.']]}
  ]
};
