// İngilizce A0 → A1, 30 ders. t: başlık (Türkçe), n: Türkçe ipucu, w: [kelime, Türkçesi] x8, p: [cümle, Türkçesi] x5
window.LESSONS = window.LESSONS || {};
window.LESSONS.en = [
  {t:'Selamlaşma', n:"'Thank' sözcüğündeki th için dil ucunu dişlerin arasına koy; 't' ya da 'f' deme. Soru kalıbı sabit: How are you?",
    w:[['hello','merhaba'],['good morning','günaydın'],['good evening','iyi akşamlar'],['goodbye','hoşça kal'],['please','lütfen'],['thank you','teşekkürler'],['yes','evet'],['no','hayır']],
    p:[['Hello, how are you?','Merhaba, nasılsın?'],["I'm fine, thank you.",'İyiyim, teşekkürler.'],['Good morning!','Günaydın!'],['See you!','Görüşürüz!'],['Thank you very much.','Çok teşekkürler.']]},
  {t:'Kendini tanıtma', n:"'I' (ben) her zaman büyük harfle yazılır. Soru sözcüğü başa gelir, 'from' sonda kalır: Where are you from?",
    w:[['name','ad, isim'],['I','ben'],['you','sen'],['Turkey','Türkiye'],['Turkish','Türk'],['where from','nereli'],['nice to meet you','memnun oldum'],['and','ve']],
    p:[['My name is Ahmet.','Benim adım Ahmet.'],["What's your name?",'Senin adın ne?'],["I'm from Turkey.","Türkiye'denim."],['Where are you from?','Sen nerelisin?'],['Nice to meet you.','Tanıştığımıza memnun oldum.']]},
  {t:'Sayılar', n:"Yaş 'have' ile değil 'be' ile söylenir: I'm thirty. Vurguya dikkat: thirTEEN (13) ama THIRty (30).",
    w:[['one','bir'],['two','iki'],['three','üç'],['four','dört'],['five','beş'],['six','altı'],['seven','yedi'],['ten','on']],
    p:[['How old are you?','Kaç yaşındasın?'],["I'm thirty years old.",'Otuz yaşındayım.'],["What's your phone number?",'Telefon numaran ne?'],['Two coffees, please.','İki kahve, lütfen.'],['I have three days.','Üç günüm var.']]},
  {t:'Nasılsın?', n:"Türkçedeki '-ım' eki İngilizcede 'I am' ile kurulur: I'm hungry. Soru için am/is/are başa gelir: Are you happy?",
    w:[['good','iyi'],['bad','kötü'],['tired','yorgun'],['happy','mutlu'],['hungry','aç'],['thirsty','susamış'],['a little','biraz'],['very','çok']],
    p:[["I'm very tired today.",'Bugün çok yorgunum.'],["I'm a little hungry.",'Biraz açım.'],['Are you happy?','Mutlu musun?'],['Not bad.','Fena değil.'],['How about you?','Sen nasılsın?']]},
  {t:'Aile', n:"'O' cinsiyete göre değişir: erkek için he, kadın için she. 'Var' için have: I have a brother. İyelik: mother's name.",
    w:[['mother','anne'],['father','baba'],['brother','erkek kardeş'],['sister','kız kardeş'],['wife / husband','eş'],['child','çocuk'],['family','aile'],['friend','arkadaş']],
    p:[['This is my family.','Bu benim ailem.'],['I have a brother.','Bir erkek kardeşim var.'],["My mother's name is Ayşe.",'Annemin adı Ayşe.'],['Do you have children?','Çocuğun var mı?'],['He is my friend.','O benim arkadaşım.']]},
  {t:'İş ve meslek', n:"Geniş zamanda soru 'do' ile kurulur: What do you do? (Ne iş yaparsın?). Meslekte a/an unutma: I'm an engineer.",
    w:[['job','iş'],['work','çalışmak'],['office','ofis'],['computer','bilgisayar'],['company','şirket'],['meeting','toplantı'],['colleague','meslektaş'],['cybersecurity','siber güvenlik']],
    p:[['What do you do?','Ne iş yapıyorsun?'],['I work in cybersecurity.','Siber güvenlikte çalışıyorum.'],['I work at a company.','Bir şirkette çalışıyorum.'],['I have a meeting today.','Bugün bir toplantım var.'],['My office is downtown.','Ofisim şehir merkezinde.']]},
  {t:'Kafede', n:"W sesi 'v' değildir: dişler dudağa değmez, dudakları yuvarlayıp 'u' gibi başla. Water ≈ 'uadır', with ≈ 'uid'.",
    w:[['coffee','kahve'],['tea','çay'],['water','su'],['milk','süt'],['sugar','şeker'],['a …, please','bir …, lütfen'],['check','hesap'],['how much','ne kadar']],
    p:[['A coffee, please.','Bir kahve, lütfen.'],['With milk, no sugar.','Sütlü, şekersiz.'],['Do you have water?','Su var mı?'],['How much is it?','Ne kadar?'],['The check, please.','Hesap, lütfen.']]},
  {t:'Yemek ve içecek', n:"Olumsuz geniş zamanda '-mem' yerine fiilden önce don't gelir: I don't eat meat. Genel sevgide 'the' yok: I like fish.",
    w:[['bread','ekmek'],['cheese','peynir'],['meat','et'],['chicken','tavuk'],['fish','balık'],['vegetables','sebze'],['fruit','meyve'],['breakfast','kahvaltı']],
    p:[['I eat bread and cheese for breakfast.','Kahvaltıda ekmek ve peynir yerim.'],['I like fish.','Balık severim.'],["I don't eat meat.",'Et yemem.'],['Are you hungry?','Aç mısın?'],['This is delicious.','Bu çok lezzetli.']]},
  {t:'Günler ve saat', n:"Günler büyük harfle yazılır: Monday. Saat ve tarih cümlesi 'It's' ile başlar: It's eight o'clock.",
    w:[['today','bugün'],['tomorrow','yarın'],['yesterday','dün'],['Monday','pazartesi'],['weekend','hafta sonu'],['time','saat, zaman'],['morning','sabah'],['evening','akşam']],
    p:[['What time is it?','Saat kaç?'],["It's eight o'clock.",'Saat sekiz.'],['Today is Monday.','Bugün pazartesi.'],["I'm working tomorrow.",'Yarın çalışıyorum.'],["I'm free on the weekend.",'Hafta sonu boşum.']]},
  {t:'Günlük rutin', n:"Saat için 'at' kullan: at seven. 'Home' önüne 'to' gelmez: go home, come home (ama go to work).",
    w:[['wake up','uyanmak'],['get up','kalkmak'],['have breakfast','kahvaltı etmek'],['go to work','işe gitmek'],['come home','eve dönmek'],['cook','yemek yapmak'],['sleep','uyumak'],['every day','her gün']],
    p:[['I get up at seven.','Saat yedide kalkarım.'],['I go to work every day.','Her gün işe giderim.'],['I come home in the evening.','Akşam eve dönerim.'],['I cook dinner in the evening.','Akşam yemek yaparım.'],['I go to bed at eleven.','Saat on birde yatarım.']]},
  {t:'Ev', n:"Sesli harfle başlayan sözcükten önce 'an': an apartment, an office. 'Var' demek için There is (tekil) / There are (çoğul).",
    w:[['house','ev'],['apartment','daire'],['room','oda'],['kitchen','mutfak'],['bathroom','banyo'],['living room','salon'],['door','kapı'],['window','pencere']],
    p:[['I live in an apartment.','Bir dairede yaşıyorum.'],['There are three rooms in my house.','Evimde üç oda var.'],['The kitchen is small.','Mutfak küçük.'],['The living room is big and bright.','Salon büyük ve aydınlık.'],['Can you close the door?','Kapıyı kapatır mısın?']]},
  {t:'Şehirde yön', n:"Emir cümlesi doğrudan fiille başlar: Go straight. Turn left. Yabancıya soru sormadan önce 'Excuse me' demek kibarlıktır.",
    w:[['where','nerede'],['right','sağ'],['left','sol'],['straight','düz'],['near','yakın'],['far','uzak'],['street','cadde'],['corner','köşe']],
    p:[['Excuse me, where is the station?','Affedersiniz, istasyon nerede?'],['Go straight.','Düz gidin.'],['Turn left.','Sola dönün.'],['Is it far?','Uzak mı?'],["It's on the corner, on the right.",'Köşede, sağda.']]},
  {t:'Ulaşım', n:"Taşıtla 'by' kullanılır: by bus, by train; yürüyerek ise 'on foot'. Does'lu soruda fiil yalın kalır: What time does it leave?",
    w:[['bus','otobüs'],['subway','metro'],['train','tren'],['taxi','taksi'],['ticket','bilet'],['stop','durak'],['car','araba'],['on foot','yürüyerek']],
    p:[['I take the subway to work.','Metroyla işe giderim.'],['One ticket, please.','Bir bilet, lütfen.'],['Where is the bus stop?','Otobüs durağı nerede?'],['What time does the train leave?','Tren saat kaçta kalkıyor?'],["I'm walking.",'Yürüyerek gidiyorum.']]},
  {t:'Alışveriş ve fiyat', n:"'Can I …?' izin ister, fiil yalın kalır: Can I pay by card? 'Too' = fazla (olumsuz), 'very' = çok: too expensive.",
    w:[['store','dükkân, mağaza'],['supermarket','market'],['price','fiyat'],['cheap','ucuz'],['expensive','pahalı'],['cash','nakit'],['card','kart'],['buy','almak, satın almak']],
    p:[['How much is this?','Bu ne kadar?'],["It's too expensive.",'Çok pahalı.'],['Can I pay by card?','Kartla ödeyebilir miyim?'],["I'll take this one.",'Bunu alıyorum.'],["I don't need a bag, thank you.",'Poşet istemiyorum, teşekkürler.']]},
  {t:'Renkler ve kıyafet', n:"Sıfat isimden önce gelir ve çoğul eki almaz: a blue jacket, black shoes. 'Try on' = üstünde denemek.",
    w:[['red','kırmızı'],['blue','mavi'],['black','siyah'],['white','beyaz'],['shirt','gömlek'],['pants','pantolon'],['shoes','ayakkabı'],['jacket','ceket']],
    p:[["I'm looking for a blue jacket.",'Mavi bir ceket arıyorum.'],['Can I try it on?','Deneyebilir miyim?'],['This is too small.','Bu çok küçük.'],['Do you have it in black?','Siyahı var mı?'],['I like the white shirt.','Beyaz gömleği seviyorum.']]},
  {t:'Hava durumu', n:"Hava anlatılırken özne 'it' olur: It's cold. Şu an olan için am/is/are + -ing: It's raining. Gelecek için will.",
    w:[['weather','hava'],['sun','güneş'],['rain','yağmur'],['snow','kar'],['wind','rüzgâr'],['hot','sıcak'],['cold','soğuk'],['cloudy','bulutlu']],
    p:[["What's the weather like today?",'Bugün hava nasıl?'],['The weather is very nice.','Hava çok güzel.'],["It's raining.",'Yağmur yağıyor.'],["It's cold today.",'Bugün soğuk.'],['It will be sunny tomorrow.','Yarın hava güneşli olacak.']]},
  {t:'Sevdiklerim', n:"Genel olarak sevilen şeyde 'the' kullanılmaz: I like music. Türkçedeki '-i' eki çevrilmez. Fiil + -ing de olur: I like swimming.",
    w:[['like','sevmek'],['music','müzik'],['movie','film'],['book','kitap'],['sports','spor'],['soccer','futbol'],['swim','yüzmek'],['read','okumak']],
    p:[['I like music.','Müziği severim.'],["I don't like soccer.",'Futbolu sevmem.'],['I read books in the evening.','Akşamları kitap okurum.'],['What kind of movies do you like?','Ne tür filmler seversin?'],['What do you like most?','En çok neyi seversin?']]},
  {t:'Köpeğim ve hayvanlar', n:"He/she/it ile geniş zamanda fiile -s eklenir: My dog likes… Köpek dişiyse 'his' yerine 'her' kullan.",
    w:[['dog','köpek'],['cat','kedi'],['park','park'],['leash','tasma'],['walk','yürüyüş'],['play','oynamak'],['ball','top'],['good boy','aferin oğlum (köpeğe)']],
    p:[['I have a dog.','Bir köpeğim var.'],['His name is Max.','Onun adı Max. (köpeğinin adını söyle)'],['We walk in the park every morning.','Her sabah parkta yürüyüş yapıyoruz.'],['My dog likes to play with his ball.','Köpeğim topla oynamayı sever.'],['Can I pet your dog?','Köpeğini sevebilir miyim?']]},
  {t:'Sağlık ve beden', n:"Ağrılar 'have' ile söylenir: I have a headache. 'Ache' ve 'stomach' sözcüklerinde ch 'k' okunur: eyk, stamık.",
    w:[['head','baş'],['stomach','mide'],['back','sırt'],['pain','ağrı'],['doctor','doktor'],['pharmacy','eczane'],['medicine','ilaç'],['sick','hasta']],
    p:[['I have a headache.','Başım ağrıyor.'],["I'm sick.",'Hastayım.'],['Where is the pharmacy?','Eczane nerede?'],['I need to see a doctor.','Doktora gitmem lazım.'],['Get well soon!','Geçmiş olsun!']]},
  {t:'Otelde', n:"'Hotel' sözcüğünde vurgu sondadır: ho-TEL. 'Is … included?' kalıbıyla neyin fiyata dahil olduğunu sorabilirsin.",
    w:[['hotel','otel'],['room','oda'],['reservation','rezervasyon'],['key','anahtar'],['night','gece'],['breakfast','kahvaltı'],['elevator','asansör'],['password','şifre (Wi-Fi)']],
    p:[['I have a reservation.','Rezervasyonum var.'],['For two nights.','İki gece için.'],['Is breakfast included?','Kahvaltı dahil mi?'],["What's the Wi-Fi password?",'Wi-Fi şifresi ne?'],['Where is the elevator?','Asansör nerede?']]},
  {t:'Restoranda', n:"Sipariş için 'I'll have …' ya da 'I'd like …' de; 'I want' kaba durabilir. Dessert (tatlı, de-ZÖRT) ≠ desert (çöl, DE-zırt).",
    w:[['table','masa'],['menu','menü'],['waiter','garson'],['order','sipariş'],['dessert','tatlı'],['drink','içecek'],['delicious','lezzetli'],['check','hesap']],
    p:[['A table for two, please.','İki kişilik bir masa, lütfen.'],['Can I have the menu?','Menüyü alabilir miyim?'],['What do you recommend?','Ne tavsiye edersiniz?'],["I'll have the fish.",'Balık alacağım.'],['It was delicious, thank you.','Çok lezzetliydi, teşekkürler.']]},
  {t:'Telefon ve randevu', n:"Telefonda 'I am Ahmet' değil 'This is Ahmet' denir. 'Could you …?' kalıbı 'Can you …?'dan daha kibardır.",
    w:[['phone','telefon'],['call','aramak'],['message','mesaj'],['appointment','randevu'],['available','müsait'],['cancel','iptal etmek'],['again','tekrar'],['slowly','yavaş(ça)']],
    p:[['Hello, this is Ahmet.','Alo, ben Ahmet.'],["I'd like to make an appointment.",'Randevu almak istiyorum.'],['Are you available on Thursday?','Perşembe müsait misiniz?'],['Could you repeat that, please?','Tekrar eder misiniz, lütfen?'],['Could you speak more slowly?','Daha yavaş konuşur musunuz?']]},
  {t:'İş yerinde', n:"Düzensiz geçmiş zaman: forget → forgot, send → sent. 'Email' sesli harfle başlar, önüne 'an' gelir: an email.",
    w:[['email','e-posta'],['password','şifre'],['screen','ekran'],['file','dosya'],['printer','yazıcı'],['help','yardım'],['problem','sorun'],['ready','hazır']],
    p:[["My computer isn't working.",'Bilgisayarım çalışmıyor.'],['I forgot my password.','Şifremi unuttum.'],['I sent you an email.','Sana bir e-posta gönderdim.'],["There's a problem.",'Bir sorun var.'],['Is everything ready for the meeting?','Toplantı için her şey hazır mı?']]},
  {t:'Dün ne yaptın? (geçmiş zaman)', n:"Düzenli fiile -ed eklenir ama çoğu zaman 't' okunur: worked 'workt', watched 'waçt'. Soruda did gelir, fiil yalın kalır.",
    w:[['yesterday','dün'],['last week','geçen hafta'],['did','yaptım'],['went','gittim'],['ate','yedim'],['watched','izledim'],['saw','gördüm'],['worked','çalıştım']],
    p:[['I worked a lot yesterday.','Dün çok çalıştım.'],['I watched a movie in the evening.','Akşam bir film izledim.'],['I went to Istanbul last week.',"Geçen hafta İstanbul'a gittim."],['I ate at a restaurant.','Restoranda yemek yedim.'],['What did you do yesterday?','Dün ne yaptın?']]},
  {t:'Yarın ne yapacaksın? (gelecek)', n:"Plan için am/is/are + going to + fiil: I'm going to meet… Konuşmada çoğu zaman 'gonna' gibi duyulur.",
    w:[['tomorrow','yarın'],['next week','gelecek hafta'],['plan','plan'],["I'm going to do",'yapacağım'],["I'm going to go",'gideceğim'],['meet','buluşmak'],['vacation','tatil'],['maybe','belki']],
    p:[['What are you going to do tomorrow?','Yarın ne yapacaksın?'],["I'm going to meet my friends tomorrow.",'Yarın arkadaşlarımla buluşacağım.'],["I'm going on vacation next week.",'Gelecek hafta tatile gideceğim.'],["Maybe we'll go to the movies.",'Belki sinemaya gideriz.'],['Do you have any plans?','Planın var mı?']]},
  {t:'Boş zaman ve hafta sonu', n:"'Evde' = at home ('in home' değil); 'dışarı çıkmak' = go out. Yakın plan -ing ile sorulur: What are you doing this weekend?",
    w:[['relax','dinlenmek'],['TV','televizyon'],['TV series','dizi'],['walk','yürüyüş'],['friends','arkadaşlar'],['movie theater','sinema'],['at home','evde'],['out','dışarı']],
    p:[['I relax at home on the weekend.','Hafta sonu evde dinlenirim.'],['I watch TV in the evening.','Akşam televizyon izlerim.'],["I'm watching a TV series.",'Bir dizi izliyorum.'],['We go out with friends.','Arkadaşlarla dışarı çıkarız.'],['What are you doing this weekend?','Bu hafta sonu ne yapıyorsun?']]},
  {t:'Havaalanı ve seyahat', n:"Havaalanında kapıya 'door' değil 'gate' denir. 'Delayed' iki hecedir, -ed 'd' okunur: di-LEYD.",
    w:[['airport','havaalanı'],['plane','uçak'],['flight','uçuş'],['passport','pasaport'],['suitcase','bavul'],['gate','kapı'],['delay','rötar'],['vacation','tatil']],
    p:[['Your passport, please.','Pasaportunuz, lütfen.'],['My flight is delayed.','Uçuşum rötarlı.'],['Where is the gate?','Kapı nerede?'],['I have one suitcase.','Bir bavulum var.'],["I'm here on vacation.",'Tatil için buradayım.']]},
  {t:'Yardım istemek', n:"'Anlamadım' İngilizcede çoğunlukla geniş zamanla söylenir: I don't understand. Bilinmeyen sözcük için: What does … mean?",
    w:[['help','yardım'],["I don't understand",'anlamadım'],["I don't know",'bilmiyorum'],['what does … mean?','… ne demek?'],['again','tekrar'],['write','yazmak'],['word','kelime'],['English','İngilizce']],
    p:[["I don't understand.",'Anlamadım.'],['What does this mean?','Bu ne demek?'],['Can you write it down?','Yazabilir misiniz?'],['Do you speak English?','İngilizce biliyor musunuz?'],['Can you help me?','Bana yardım edebilir misiniz?']]},
  {t:'Duygular ve fikirler', n:"'Agree' bir fiildir: I agree (I am agree yanlış). 'Interesting' genelde üç hece okunur: IN-trıs-ting.",
    w:[['think','düşünmek'],['I think','bence'],['I agree','katılıyorum'],['beautiful','güzel'],['difficult','zor'],['easy','kolay'],['interesting','ilginç'],['boring','sıkıcı']],
    p:[['I think this is very interesting.','Bence bu çok ilginç.'],['I agree with you.','Sana katılıyorum.'],['This language is difficult but beautiful.','Bu dil zor ama güzel.'],['This movie is boring.','Bu film sıkıcı.'],['What do you think?','Sen ne düşünüyorsun?']]},
  {t:'Kendini anlat (tekrar)', n:"Tekrar günü: am/is/are, have, geniş zamanın -s'si, did ve going to kalıplarıyla kendi hayatını yüksek sesle anlat.",
    w:[['learn','öğrenmek'],['language','dil'],['every day','her gün'],['a little','biraz'],['speak','konuşmak'],['understand','anlamak'],['goal','hedef'],['fluently','akıcı (şekilde)']],
    p:[["My name is Ahmet, and I'm from Turkey.","Benim adım Ahmet, Türkiye'denim."],['I work in cybersecurity.','Siber güvenlikte çalışıyorum.'],['I have a dog.','Bir köpeğim var.'],['I learn a little English every day.','Her gün biraz İngilizce öğreniyorum.'],['I want to speak fluently one day.','Bir gün akıcı konuşmak istiyorum.']]}
];
