// En sık 1000 Almanca kelime (lemma), sıklık sırasıyla.
// Kaynak: FrequencyWords (Hermit Dave), OpenSubtitles 2018 — https://github.com/hermitdave/FrequencyWords — CC BY-SA 4.0.
// Bu liste o kaynaktan türetilmiştir (lemmatize edildi, Türkçe anlam/okunuş/örnek eklendi) ve CC BY-SA 4.0 lisansıyla paylaşılır.
// Biçim: [kelime, Türkçesi, okunuş, örnek cümle, örneğin Türkçesi, emoji]
window.FREQ = window.FREQ || {};
window.FREQ.de = [
  ['ich', 'ben', 'İH', 'Ich bin müde.', 'Yorgunum.', ''],
  ['sie', 'o (kadın); onlar; Siz', 'Zİİ', 'Sie ist meine Schwester.', 'O benim kız kardeşim.', ''],
  ['der, die, das', 'belirli tanımlık (-ı/-i)', 'DEER, Dİİ, DAS', 'Der Mann trinkt das Wasser.', 'Adam suyu içiyor.', ''],
  ['sein', 'olmak', 'ZAYN', 'Das ist mein Haus.', 'Bu benim evim.', ''],
  ['du', 'sen', 'DUU', 'Du bist nett.', 'Sen naziksin.', ''],
  ['nicht', 'değil', 'NİHT', 'Das ist nicht gut.', 'Bu iyi değil.', ''],
  ['es', 'o (nesne)', 'ES', 'Es regnet.', 'Yağmur yağıyor.', ''],
  ['und', 've', 'UNT', 'Tee und Kaffee, bitte.', 'Çay ve kahve, lütfen.', ''],
  ['wir', 'biz', 'VİİR', 'Wir sind zu Hause.', 'Evdeyiz.', ''],
  ['was', 'ne', 'VAS', 'Was ist das?', 'Bu ne?', ''],
  ['zu', '-e, -a; çok (fazla)', 'TSUU', 'Ich gehe zu Anna.', "Anna'ya gidiyorum.", ''],
  ['er', 'o (erkek)', 'EER', 'Er ist mein Bruder.', 'O benim erkek kardeşim.', ''],
  ['ein', 'bir (belirsiz tanımlık)', 'AYN', 'Ich habe ein Auto.', 'Bir arabam var.', ''],
  ['in', 'içinde, -de', 'İN', 'Ich wohne in Berlin.', "Berlin'de oturuyorum.", ''],
  ['ja', 'evet', 'YAA', 'Ja, gern!', 'Evet, memnuniyetle!', ''],
  ['mit', 'ile', 'MİT', 'Ich komme mit dir.', 'Seninle geliyorum.', ''],
  ['wie', 'nasıl; gibi', 'Vİİ', 'Wie geht es dir?', 'Nasılsın?', ''],
  ['auf', 'üzerinde', 'AUF', 'Das Buch liegt auf dem Tisch.', 'Kitap masanın üstünde.', ''],
  ['dass', '-dığı için, ki', 'DAS', 'Ich weiß, dass du da bist.', 'Burada olduğunu biliyorum.', ''],
  ['aber', 'ama', 'AA-bır', 'Ich bin müde, aber glücklich.', 'Yorgunum ama mutluyum.', ''],
  ['so', 'böyle; öyle; çok', 'ZOO', 'Das ist so schön!', 'Bu çok güzel!', ''],
  ['haben', 'sahip olmak', 'HAA-ben', 'Ich habe einen Hund.', 'Bir köpeğim var.', ''],
  ['hier', 'burada', 'HİİR', 'Ich bin hier.', 'Buradayım.', ''],
  ['für', 'için', 'FÜÜR', 'Das ist für dich.', 'Bu senin için.', ''],
  ['von', '-den, -in', 'FON', 'Das ist ein Brief von Oma.', 'Bu, büyükannemden bir mektup.', ''],
  ['wenn', 'eğer; -dığında', 'VEN', 'Wenn du willst, komm mit.', 'İstersen gel.', ''],
  ['ihr', 'siz', 'İİR', 'Seid ihr bereit?', 'Hazır mısınız?', ''],
  ['nein', 'hayır', 'NAYN', 'Nein, danke.', 'Hayır, teşekkürler.', ''],
  ['an', '-de, -e (yanında)', 'AN', 'Das Bild hängt an der Wand.', 'Resim duvarda asılı.', ''],
  ['noch', 'hâlâ; daha', 'NOH', 'Ich bin noch hier.', 'Hâlâ buradayım.', ''],
  ['nur', 'sadece', 'NUUR', 'Ich habe nur Wasser.', 'Sadece suyum var.', ''],
  ['da', 'orada; çünkü', 'DAA', 'Ist Maria da?', 'Maria orada mı?', ''],
  ['sich', 'kendini, kendine', 'ZİH', 'Er wäscht sich.', 'O yıkanıyor.', ''],
  ['können', '-ebilmek', 'KÖ-nen', 'Ich kann schwimmen.', 'Yüzebiliyorum.', ''],
  ['gut', 'iyi', 'GUUT', 'Das Essen ist gut.', 'Yemek iyi.', ''],
  ['auch', 'de, da; ayrıca', 'AUH', 'Ich komme auch.', 'Ben de geliyorum.', ''],
  ['schon', 'zaten; artık', 'ŞOON', 'Ich bin schon da.', 'Zaten buradayım.', ''],
  ['als', '-den (daha); olarak; -dığında', 'ALS', 'Er ist größer als ich.', 'O benden daha uzun.', ''],
  ['mal', 'bir kere; hele', 'MAAL', 'Komm mal her!', 'Bir buraya gel!', ''],
  ['jetzt', 'şimdi', 'YETST', 'Ich muss jetzt gehen.', 'Şimdi gitmem lazım.', ''],
  ['dann', 'sonra; o zaman', 'DAN', 'Zuerst essen, dann schlafen.', 'Önce yemek, sonra uyku.', ''],
  ['aus', '-den (içinden)', 'AUS', 'Ich komme aus der Türkei.', "Türkiye'denim.", ''],
  ['mein', 'benim', 'MAYN', 'Das ist mein Vater.', 'Bu benim babam.', ''],
  ['um', 'etrafında; saat (-de)', 'UM', 'Wir essen um acht Uhr.', 'Saat sekizde yemek yiyoruz.', ''],
  ['werden', 'olmak (-leşmek); -ecek', 'VEER-den', 'Es wird kalt.', 'Hava soğuyor.', ''],
  ['doch', 'ama; tabii ki (evet)', 'DOH', 'Doch, das stimmt!', 'Aksine, bu doğru!', ''],
  ['alle', 'hepsi, herkes, tüm', 'A-le', 'Alle sind hier.', 'Herkes burada.', ''],
  ['wissen', 'bilmek', 'Vİ-sen', 'Ich weiß es nicht.', 'Bilmiyorum.', ''],
  ['kein', 'hiç, yok (olumsuz)', 'KAYN', 'Ich habe keine Zeit.', 'Hiç vaktim yok.', ''],
  ['oder', 'veya', 'OO-dır', 'Tee oder Kaffee?', 'Çay mı kahve mi?', ''],
  ['nach', '-e doğru; sonra', 'NAAH', 'Ich fahre nach Hause.', 'Eve gidiyorum.', ''],
  ['nichts', 'hiçbir şey', 'NİHTS', 'Ich sehe nichts.', 'Hiçbir şey görmüyorum.', ''],
  ['man', 'insan (genel özne)', 'MAN', 'Hier darf man nicht rauchen.', 'Burada sigara içilmez.', ''],
  ['müssen', 'zorunda olmak', 'MÜ-sen', 'Ich muss arbeiten.', 'Çalışmak zorundayım.', ''],
  ['wollen', 'istemek', 'VO-len', 'Ich will nach Hause.', 'Eve gitmek istiyorum.', ''],
  ['gehen', 'gitmek', 'GEE-en', 'Wir gehen ins Kino.', 'Sinemaya gidiyoruz.', ''],
  ['wo', 'nerede', 'VOO', 'Wo ist der Bahnhof?', 'Tren istasyonu nerede?', ''],
  ['etwas', 'bir şey; biraz', 'ET-vas', 'Ich möchte etwas trinken.', 'Bir şey içmek istiyorum.', ''],
  ['mehr', 'daha çok', 'MEER', 'Ich brauche mehr Zeit.', 'Daha çok zamana ihtiyacım var.', ''],
  ['bei', 'yanında; -de', 'BAY', 'Ich bin bei meiner Mutter.', 'Annemin yanındayım.', ''],
  ['also', 'yani; o hâlde', 'AL-zo', 'Also, gehen wir!', 'O hâlde, gidelim!', ''],
  ['bitte', 'lütfen; buyurun', 'Bİ-te', 'Ein Wasser, bitte.', 'Bir su, lütfen.', ''],
  ['immer', 'her zaman', 'İ-mır', 'Er ist immer müde.', 'O hep yorgun.', ''],
  ['warum', 'neden', 'va-RUM', 'Warum weinst du?', 'Neden ağlıyorsun?', ''],
  ['vor', 'önünde; önce', 'FOOR', 'Ich warte vor dem Haus.', 'Evin önünde bekliyorum.', ''],
  ['los', 'haydi; (ne) oldu', 'LOOS', 'Was ist los?', 'Ne oldu?', ''],
  ['wieder', 'yine, tekrar', 'Vİİ-dır', 'Er ist wieder da.', 'O yine burada.', ''],
  ['sagen', 'söylemek', 'ZAA-gen', 'Was sagst du?', 'Ne diyorsun?', ''],
  ['machen', 'yapmak', 'MA-hen', 'Was machst du heute?', 'Bugün ne yapıyorsun?', ''],
  ['danke', 'teşekkürler', 'DAN-ke', 'Danke für das Essen!', 'Yemek için teşekkürler!', ''],
  ['sehr', 'çok', 'ZEER', 'Das ist sehr gut.', 'Bu çok iyi.', ''],
  ['denn', 'çünkü; ki (soruda)', 'DEN', 'Was machst du denn?', 'Ne yapıyorsun ki?', ''],
  ['der Mann', 'adam; koca', 'deer MAN', 'Der Mann ist groß.', 'Adam uzun boylu.', '👨'],
  ['tun', 'yapmak, etmek', 'TUUN', 'Was kann ich tun?', 'Ne yapabilirim?', ''],
  ['sehen', 'görmek', 'ZEE-en', 'Ich sehe dich.', 'Seni görüyorum.', ''],
  ['vielleicht', 'belki', 'fii-LAYHT', 'Vielleicht komme ich morgen.', 'Belki yarın gelirim.', ''],
  ['wer', 'kim', 'VEER', 'Wer ist das?', 'Bu kim?', ''],
  ['dieser', 'bu', 'Dİİ-zır', 'Dieser Film ist gut.', 'Bu film iyi.', ''],
  ['kommen', 'gelmek', 'KO-men', 'Kommst du heute?', 'Bugün geliyor musun?', ''],
  ['über', 'üzerinde; hakkında', 'ÜÜ-bır', 'Wir reden über das Wetter.', 'Hava hakkında konuşuyoruz.', ''],
  ['geben', 'vermek', 'GEE-ben', 'Gib mir das Buch!', 'Kitabı bana ver!', ''],
  ['dein', 'senin', 'DAYN', 'Ist das dein Auto?', 'Bu senin araban mı?', ''],
  ['sollen', '-meli (başkası istiyor)', 'ZO-len', 'Was soll ich tun?', 'Ne yapmalıyım?', ''],
  ['nie', 'asla, hiç', 'Nİİ', 'Ich rauche nie.', 'Asla sigara içmem.', ''],
  ['wirklich', 'gerçekten', 'VİRK-lih', 'Das ist wirklich schön.', 'Bu gerçekten güzel.', ''],
  ['viel', 'çok', 'FİİL', 'Ich habe viel Arbeit.', 'Çok işim var.', ''],
  ['weg', 'gitmiş, uzakta', 'VEK', 'Mein Schlüssel ist weg.', 'Anahtarım kayıp.', ''],
  ['am', '-de (an dem)', 'AM', 'Wir treffen uns am Montag.', 'Pazartesi buluşuyoruz.', ''],
  ['einfach', 'kolay; basitçe', 'AYN-fah', 'Das ist ganz einfach.', 'Bu çok kolay.', ''],
  ['das Leben', 'hayat', 'das LEE-ben', 'Das Leben ist schön.', 'Hayat güzel.', ''],
  ['die Zeit', 'zaman', 'dii TSAYT', 'Hast du Zeit?', 'Vaktin var mı?', '⏰'],
  ['weil', 'çünkü', 'VAYL', 'Ich esse, weil ich Hunger habe.', 'Yiyorum çünkü açım.', ''],
  ['heute', 'bugün', 'HOY-te', 'Heute ist Montag.', 'Bugün pazartesi.', ''],
  ['ganz', 'tamamen; bütün', 'GANTS', 'Das ist ganz neu.', 'Bu tamamen yeni.', ''],
  ['sicher', 'emin; güvenli', 'Zİ-hır', 'Bist du sicher?', 'Emin misin?', ''],
  ['die Frau', 'kadın; eş', 'dii FRAU', 'Die Frau liest ein Buch.', 'Kadın bir kitap okuyor.', '👩'],
  ['nun', 'şimdi; eh', 'NUUN', 'Was machen wir nun?', 'Şimdi ne yapıyoruz?', ''],
  ['bis', '-e kadar', 'BİS', 'Bis morgen!', 'Yarın görüşürüz!', ''],
  ['leid', 'üzgün (tut mir leid)', 'LAYT', 'Es tut mir leid.', 'Özür dilerim.', ''],
  ['zurück', 'geri', 'tsu-RÜK', 'Ich bin gleich zurück.', 'Hemen dönerim.', ''],
  ['lassen', 'bırakmak; izin vermek', 'LA-sen', 'Lass mich in Ruhe!', 'Beni rahat bırak!', ''],
  ['hallo', 'merhaba', 'ha-LOO', "Hallo, wie geht's?", 'Merhaba, nasılsın?', ''],
  ['der Gott', 'tanrı', 'deer GOT', 'Gott sei Dank!', 'Çok şükür!', ''],
  ['sein, seine', 'onun (erkek)', 'ZAYN, ZAY-ne', 'Das ist seine Katze.', 'Bu onun kedisi.', ''],
  ['zwei', 'iki', 'TSVAY', 'Ich habe zwei Kinder.', 'İki çocuğum var.', ''],
  ['genau', 'tam; aynen', 'ge-NAU', 'Genau, das stimmt.', 'Aynen, bu doğru.', ''],
  ['klar', 'açık; tabii', 'KLAAR', 'Alles klar!', 'Tamamdır!', ''],
  ['morgen', 'yarın', 'MOR-gen', 'Bis morgen!', 'Yarın görüşürüz!', ''],
  ['die Leute', 'insanlar', 'dii LOY-te', 'Die Leute sind nett.', 'İnsanlar nazik.', ''],
  ['der Vater', 'baba', 'deer FAA-tır', 'Mein Vater kocht gern.', 'Babam yemek yapmayı sever.', '👨'],
  ['schön', 'güzel', 'ŞÖÖN', 'Das Wetter ist schön.', 'Hava güzel.', ''],
  ['glauben', 'inanmak; sanmak', 'GLAU-ben', 'Ich glaube dir.', 'Sana inanıyorum.', ''],
  ['ab', '-den itibaren', 'AP', 'Ab Montag arbeite ich.', 'Pazartesiden itibaren çalışıyorum.', ''],
  ['gerade', 'şu an; düz', 'ge-RAA-de', 'Ich esse gerade.', 'Şu an yemek yiyorum.', ''],
  ['der Tag', 'gün', 'deer TAAK', 'Guten Tag!', 'İyi günler!', ''],
  ['reden', 'konuşmak', 'REE-den', 'Wir müssen reden.', 'Konuşmamız lazım.', ''],
  ['wohl', 'herhalde; iyi', 'VOOL', 'Er ist wohl krank.', 'Herhalde hasta.', ''],
  ['die Liebe', 'aşk, sevgi', 'dii Lİİ-be', 'Liebe ist wichtig.', 'Sevgi önemlidir.', '❤️'],
  ['unser', 'bizim', 'UN-zır', 'Das ist unser Haus.', 'Bu bizim evimiz.', ''],
  ['jemand', 'biri', 'YEE-mant', 'Ist da jemand?', 'Orada biri var mı?', ''],
  ['das Geld', 'para', 'das GELT', 'Ich habe kein Geld.', 'Hiç param yok.', '💰'],
  ['durch', 'içinden; sayesinde', 'DURH', 'Wir gehen durch den Park.', 'Parkın içinden geçiyoruz.', ''],
  ['ob', '-ip -mediği', 'OP', 'Ich weiß nicht, ob er kommt.', 'Gelip gelmeyeceğini bilmiyorum.', ''],
  ['die Mutter', 'anne', 'dii MU-tır', 'Meine Mutter ist Lehrerin.', 'Annem öğretmen.', '👩'],
  ['raus', 'dışarı', 'RAUS', 'Geh raus!', 'Dışarı çık!', ''],
  ['paar', 'birkaç (ein paar)', 'PAAR', 'Ich habe ein paar Fragen.', 'Birkaç sorum var.', ''],
  ['passieren', 'olmak, meydana gelmek', 'pa-Sİİ-ren', 'Was ist passiert?', 'Ne oldu?', ''],
  ['denken', 'düşünmek', 'DEN-ken', 'Ich denke an dich.', 'Seni düşünüyorum.', ''],
  ['wieso', 'neden', 'vii-ZOO', 'Wieso bist du hier?', 'Neden buradasın?', ''],
  ['selbst', 'kendisi; bile', 'ZELPST', 'Ich mache das selbst.', 'Bunu kendim yaparım.', ''],
  ['gehören', 'ait olmak', 'ge-HÖÖ-ren', 'Das Buch gehört mir.', 'Kitap bana ait.', ''],
  ['mögen', 'sevmek; istemek (möchte)', 'MÖÖ-gen', 'Ich möchte einen Kaffee.', 'Bir kahve istiyorum.', ''],
  ['ohne', '-sız, -siz', 'OO-ne', 'Kaffee ohne Zucker, bitte.', 'Şekersiz kahve, lütfen.', ''],
  ['hören', 'duymak; dinlemek', 'HÖÖ-ren', 'Ich höre Musik.', 'Müzik dinliyorum.', ''],
  ['her', 'buraya (bana doğru)', 'HEER', 'Komm her!', 'Buraya gel!', ''],
  ['andere', 'diğer, başka', 'AN-de-re', 'Ich möchte ein anderes Zimmer.', 'Başka bir oda istiyorum.', ''],
  ['helfen', 'yardım etmek', 'HEL-fen', 'Kannst du mir helfen?', 'Bana yardım edebilir misin?', ''],
  ['die Nacht', 'gece', 'dii NAHT', 'Gute Nacht!', 'İyi geceler!', '🌙'],
  ['finden', 'bulmak', 'FİN-den', 'Ich finde meinen Schlüssel nicht.', 'Anahtarımı bulamıyorum.', ''],
  ['lang', 'uzun', 'LANG', 'Der Weg ist lang.', 'Yol uzun.', ''],
  ['natürlich', 'tabii ki; doğal', 'na-TÜÜR-lih', 'Natürlich helfe ich dir.', 'Tabii ki sana yardım ederim.', ''],
  ['gar', 'hiç (gar nicht)', 'GAAR', 'Das ist gar nicht schwer.', 'Bu hiç zor değil.', ''],
  ['dort', 'orada', 'DORT', 'Dort ist die Schule.', 'Okul orada.', ''],
  ['weiter', 'devam; daha ileri', 'VAY-tır', 'Mach weiter!', 'Devam et!', ''],
  ['seit', '-den beri', 'ZAYT', 'Ich wohne seit zwei Jahren hier.', 'İki yıldır burada oturuyorum.', ''],
  ['gleich', 'hemen; aynı', 'GLAYH', 'Ich komme gleich.', 'Hemen geliyorum.', ''],
  ['recht', 'haklı; doğru', 'REHT', 'Du hast recht.', 'Haklısın.', ''],
  ['richtig', 'doğru', 'RİH-tih', 'Die Antwort ist richtig.', 'Cevap doğru.', ''],
  ['die Ordnung', 'düzen (in Ordnung: tamam)', 'dii ORT-nung', 'Alles in Ordnung?', 'Her şey yolunda mı?', ''],
  ['davon', 'ondan; bundan', 'da-FON', 'Ich möchte mehr davon.', 'Bundan daha fazla istiyorum.', ''],
  ['dafür', 'bunun için', 'da-FÜÜR', 'Danke dafür!', 'Bunun için teşekkürler!', ''],
  ['wegen', 'yüzünden, -den dolayı', 'VEE-gen', 'Wegen des Regens bleibe ich hier.', 'Yağmur yüzünden burada kalıyorum.', ''],
  ['das Haus', 'ev', 'das HAUS', 'Das Haus ist groß.', 'Ev büyük.', '🏠'],
  ['das Mädchen', 'kız', 'das MEET-hen', 'Das Mädchen spielt.', 'Kız oynuyor.', '👧'],
  ['hin', 'oraya', 'HİN', 'Wo gehst du hin?', 'Nereye gidiyorsun?', ''],
  ['der Abend', 'akşam', 'deer AA-bent', 'Guten Abend!', 'İyi akşamlar!', '🌆'],
  ['drei', 'üç', 'DRAY', 'Ich habe drei Katzen.', 'Üç kedim var.', ''],
  ['der Freund', 'arkadaş; erkek arkadaş', 'deer FROYNT', 'Er ist mein Freund.', 'O benim arkadaşım.', ''],
  ['warten', 'beklemek', 'VAR-ten', 'Ich warte auf den Bus.', 'Otobüsü bekliyorum.', ''],
  ['der Mensch', 'insan', 'deer MENŞ', 'Er ist ein guter Mensch.', 'O iyi bir insan.', '🧑'],
  ['essen', 'yemek yemek', 'E-sen', 'Wir essen um sieben.', 'Yedide yemek yiyoruz.', ''],
  ['die Angst', 'korku', 'dii ANGST', 'Ich habe Angst.', 'Korkuyorum.', ''],
  ['bleiben', 'kalmak', 'BLAY-ben', 'Ich bleibe zu Hause.', 'Evde kalıyorum.', ''],
  ['zusammen', 'birlikte', 'tsu-ZA-men', 'Wir essen zusammen.', 'Birlikte yemek yiyoruz.', ''],
  ['die Welt', 'dünya', 'dii VELT', 'Die Welt ist groß.', 'Dünya büyük.', '🌍'],
  ['unter', 'altında', 'UN-tır', 'Die Katze ist unter dem Tisch.', 'Kedi masanın altında.', ''],
  ['schnell', 'hızlı', 'ŞNEL', 'Das Auto ist schnell.', 'Araba hızlı.', ''],
  ['tot', 'ölü', 'TOOT', 'Die Blume ist tot.', 'Çiçek ölmüş.', ''],
  ['dürfen', 'izinli olmak, -ebilmek', 'DÜR-fen', 'Darf ich reinkommen?', 'İçeri girebilir miyim?', ''],
  ['erst', 'ilk önce; ancak', 'EERST', 'Ich komme erst morgen.', 'Ancak yarın geliyorum.', ''],
  ['rein', 'içeri; temiz', 'RAYN', 'Komm rein!', 'İçeri gel!', ''],
  ['stimmen', 'doğru olmak', 'ŞTİ-men', 'Das stimmt.', 'Bu doğru.', ''],
  ['nehmen', 'almak', 'NEE-men', 'Ich nehme den Bus.', 'Otobüse biniyorum.', ''],
  ['das Kind', 'çocuk', 'das KİNT', 'Das Kind schläft.', 'Çocuk uyuyor.', '🧒'],
  ['bringen', 'getirmek', 'BRİN-gen', 'Bring mir bitte Wasser.', 'Bana su getir lütfen.', ''],
  ['genug', 'yeterli', 'ge-NUUK', 'Ich habe genug gegessen.', 'Yeterince yedim.', ''],
  ['brauchen', 'ihtiyaç duymak', 'BRAU-hen', 'Ich brauche Hilfe.', 'Yardıma ihtiyacım var.', ''],
  ['gegen', '-e karşı', 'GEE-gen', 'Ich bin gegen den Plan.', 'Plana karşıyım.', ''],
  ['der Moment', 'an', 'deer mo-MENT', 'Einen Moment, bitte.', 'Bir dakika, lütfen.', ''],
  ['der Junge', 'oğlan', 'deer YUN-ge', 'Der Junge spielt Fußball.', 'Oğlan futbol oynuyor.', '👦'],
  ['stehen', 'ayakta durmak', 'ŞTEE-en', 'Er steht an der Tür.', 'O kapıda duruyor.', ''],
  ['sonst', 'yoksa; başka', 'ZONST', 'Beeil dich, sonst kommst du zu spät.', 'Acele et, yoksa geç kalırsın.', ''],
  ['die Musik', 'müzik', 'dii mu-ZİİK', 'Ich höre gern Musik.', 'Müzik dinlemeyi severim.', '🎵'],
  ['die Arbeit', 'iş', 'dii AR-bayt', 'Ich gehe zur Arbeit.', 'İşe gidiyorum.', ''],
  ['fragen', 'sormak', 'FRAA-gen', 'Darf ich etwas fragen?', 'Bir şey sorabilir miyim?', ''],
  ['der Herr', 'bay, beyefendi', 'deer HER', 'Guten Tag, Herr Müller!', 'İyi günler, Bay Müller!', ''],
  ['dabei', 'yanında; bu arada', 'da-BAY', 'Hast du Geld dabei?', 'Yanında para var mı?', ''],
  ['heißen', 'adı olmak', 'HAY-sen', 'Ich heiße Ahmet.', 'Adım Ahmet.', ''],
  ['die Familie', 'aile', 'dii fa-Mİİ-li-e', 'Meine Familie ist groß.', 'Ailem kalabalık.', '👪'],
  ['niemand', 'hiç kimse', 'Nİİ-mant', 'Niemand ist zu Hause.', 'Evde kimse yok.', ''],
  ['sofort', 'hemen', 'zo-FORT', 'Komm sofort!', 'Hemen gel!', ''],
  ['bevor', '-den önce', 'be-FOOR', 'Ich esse, bevor ich gehe.', 'Gitmeden önce yemek yiyorum.', ''],
  ['das Jahr', 'yıl', 'das YAAR', 'Das Jahr ist fast vorbei.', 'Yıl neredeyse bitti.', ''],
  ['einmal', 'bir kere', 'AYN-maal', 'Ich war einmal in Wien.', "Bir kere Viyana'daydım.", ''],
  ['das Problem', 'sorun', 'das pro-BLEEM', 'Kein Problem!', 'Sorun değil!', ''],
  ['der Sohn', 'oğul', 'deer ZOON', 'Mein Sohn ist fünf.', 'Oğlum beş yaşında.', '👦'],
  ['wann', 'ne zaman', 'VAN', 'Wann kommst du?', 'Ne zaman geliyorsun?', ''],
  ['fertig', 'hazır; bitmiş', 'FER-tih', 'Ich bin fertig.', 'Hazırım.', ''],
  ['halten', 'tutmak; durmak', 'HAL-ten', 'Der Bus hält hier.', 'Otobüs burada duruyor.', ''],
  ['allein', 'yalnız', 'a-LAYN', 'Ich wohne allein.', 'Yalnız yaşıyorum.', ''],
  ['sprechen', 'konuşmak', 'ŞPRE-hen', 'Sprichst du Deutsch?', 'Almanca konuşuyor musun?', ''],
  ['beide', 'ikisi de', 'BAY-de', 'Beide sind nett.', 'İkisi de nazik.', ''],
  ['die Sache', 'şey, mesele', 'dii ZA-he', 'Das ist eine gute Sache.', 'Bu iyi bir şey.', ''],
  ['die Hilfe', 'yardım', 'dii HİL-fe', 'Danke für die Hilfe!', 'Yardım için teşekkürler!', ''],
  ['jeder', 'her, herkes', 'YEE-dır', 'Jeder kennt ihn.', 'Herkes onu tanır.', ''],
  ['darüber', 'bunun hakkında', 'da-RÜÜ-bır', 'Lass uns darüber reden.', 'Bunun hakkında konuşalım.', ''],
  ['verstehen', 'anlamak', 'fer-ŞTEE-en', 'Ich verstehe das nicht.', 'Bunu anlamıyorum.', ''],
  ['wahr', 'gerçek, doğru', 'VAAR', 'Das ist nicht wahr!', 'Bu doğru değil!', ''],
  ['dazu', 'buna; ayrıca', 'da-TSUU', 'Was sagst du dazu?', 'Buna ne dersin?', ''],
  ['der Bruder', 'erkek kardeş', 'deer BRUU-dır', 'Mein Bruder ist Arzt.', 'Erkek kardeşim doktor.', '👦'],
  ['daran', 'buna, bunu (an)', 'da-RAN', 'Denk daran!', 'Bunu unutma!', ''],
  ['gern', 'seve seve', 'GERN', 'Ich lese gern.', 'Okumayı severim.', ''],
  ['der Fall', 'durum; dava', 'deer FAL', 'Auf jeden Fall!', 'Her hâlükârda!', ''],
  ['egal', 'fark etmez', 'e-GAAL', 'Das ist mir egal.', 'Bana fark etmez.', ''],
  ['kennen', 'tanımak, bilmek', 'KE-nen', 'Kennst du ihn?', 'Onu tanıyor musun?', ''],
  ['vergessen', 'unutmak', 'fer-GE-sen', 'Ich habe es vergessen.', 'Onu unuttum.', ''],
  ['die Frage', 'soru', 'dii FRAA-ge', 'Ich habe eine Frage.', 'Bir sorum var.', '❓'],
  ['echt', 'gerçek; gerçekten', 'EHT', 'Das ist echt gut.', 'Bu gerçekten iyi.', ''],
  ['eigentlich', 'aslında', 'AY-gent-lih', 'Eigentlich bin ich müde.', 'Aslında yorgunum.', ''],
  ['die Uhr', 'saat', 'dii UUR', 'Es ist drei Uhr.', 'Saat üç.', '⌚'],
  ['die Stadt', 'şehir', 'dii ŞTAT', 'Die Stadt ist schön.', 'Şehir güzel.', '🏙️'],
  ['das Baby', 'bebek', 'das BEE-bi', 'Das Baby schläft.', 'Bebek uyuyor.', '👶'],
  ['fahren', '(araçla) gitmek; sürmek', 'FAA-ren', 'Ich fahre mit dem Bus.', 'Otobüsle gidiyorum.', ''],
  ['der Name', 'isim', 'deer NAA-me', 'Wie ist Ihr Name?', 'Adınız nedir?', ''],
  ['bekommen', 'almak, elde etmek', 'be-KO-men', 'Ich bekomme einen Brief.', 'Bir mektup alıyorum.', ''],
  ['der Kopf', 'baş, kafa', 'deer KOPF', 'Mein Kopf tut weh.', 'Başım ağrıyor.', ''],
  ['klein', 'küçük', 'KLAYN', 'Die Wohnung ist klein.', 'Daire küçük.', ''],
  ['spät', 'geç', 'ŞPEET', 'Es ist schon spät.', 'Saat zaten geç.', ''],
  ['das Glück', 'şans; mutluluk', 'das GLÜK', 'Viel Glück!', 'Bol şans!', '🍀'],
  ['letzte', 'son', 'LETS-te', 'Das ist die letzte Frage.', 'Bu son soru.', ''],
  ['darauf', 'onun üstüne; buna', 'da-RAUF', 'Ich freue mich darauf.', 'Onu dört gözle bekliyorum.', ''],
  ['das Ende', 'son', 'das EN-de', 'Das Ende ist gut.', 'Sonu iyi.', ''],
  ['bald', 'yakında', 'BALT', 'Bis bald!', 'Görüşürüz!', ''],
  ['töten', 'öldürmek', 'TÖÖ-ten', 'Man darf nicht töten.', 'Öldürmek yasaktır.', ''],
  ['das Ding', 'şey', 'das DİNG', 'Was ist das für ein Ding?', 'Bu ne biçim bir şey?', ''],
  ['meinen', 'kastetmek; düşünmek', 'MAY-nen', 'Was meinst du?', 'Ne demek istiyorsun?', ''],
  ['toll', 'harika', 'TOL', 'Das ist toll!', 'Bu harika!', ''],
  ['eins', 'bir (sayı)', 'AYNS', 'Eins, zwei, drei!', 'Bir, iki, üç!', ''],
  ['die Minute', 'dakika', 'dii mi-NUU-te', 'Warte eine Minute!', 'Bir dakika bekle!', ''],
  ['bereit', 'hazır', 'be-RAYT', 'Bist du bereit?', 'Hazır mısın?', ''],
  ['weit', 'uzak; geniş', 'VAYT', 'Ist es weit?', 'Uzak mı?', ''],
  ['die Ahnung', 'fikir, sezgi', 'dii AA-nung', 'Ich habe keine Ahnung.', 'Hiçbir fikrim yok.', ''],
  ['bisschen', 'biraz (ein bisschen)', 'BİS-hen', 'Ich spreche ein bisschen Deutsch.', 'Biraz Almanca konuşuyorum.', ''],
  ['die Tür', 'kapı', 'dii TÜÜR', 'Mach die Tür zu!', 'Kapıyı kapat!', '🚪'],
  ['das Auto', 'araba', 'das AU-to', 'Mein Auto ist rot.', 'Arabam kırmızı.', '🚗'],
  ['das Auge', 'göz', 'das AU-ge', 'Sie hat blaue Augen.', 'Onun mavi gözleri var.', '👁️'],
  ['die Polizei', 'polis', 'dii po-li-TSAY', 'Ruf die Polizei!', 'Polisi ara!', '🚓'],
  ['sterben', 'ölmek', 'ŞTER-ben', 'Die Pflanze stirbt.', 'Bitki ölüyor.', ''],
  ['draußen', 'dışarıda', 'DRAU-sen', 'Die Kinder spielen draußen.', 'Çocuklar dışarıda oynuyor.', ''],
  ['fast', 'neredeyse', 'FAST', 'Ich bin fast fertig.', 'Neredeyse bitirdim.', ''],
  ['runter', 'aşağı', 'RUN-tır', 'Komm runter!', 'Aşağı gel!', ''],
  ['vorbei', 'geçmiş, bitmiş', 'foor-BAY', 'Der Sommer ist vorbei.', 'Yaz bitti.', ''],
  ['treffen', 'buluşmak', 'TRE-fen', 'Wir treffen uns im Café.', 'Kafede buluşuyoruz.', ''],
  ['arbeiten', 'çalışmak', 'AR-bay-ten', 'Ich arbeite in einem Büro.', 'Bir ofiste çalışıyorum.', ''],
  ['verrückt', 'deli', 'fer-RÜKT', 'Bist du verrückt?', 'Deli misin?', ''],
  ['neu', 'yeni', 'NOY', 'Mein Handy ist neu.', 'Telefonum yeni.', ''],
  ['hinter', 'arkasında', 'HİN-tır', 'Der Garten ist hinter dem Haus.', 'Bahçe evin arkasında.', ''],
  ['die Sorge', 'endişe', 'dii ZOR-ge', 'Mach dir keine Sorgen!', 'Endişelenme!', ''],
  ['einzig', 'tek, biricik', 'AYN-tsih', 'Du bist mein einziger Freund.', 'Sen benim tek arkadaşımsın.', ''],
  ['darum', 'bu yüzden', 'da-RUM', 'Darum bin ich hier.', 'Bu yüzden buradayım.', ''],
  ['die Tochter', 'kız evlat', 'dii TOH-tır', 'Meine Tochter ist zehn.', 'Kızım on yaşında.', '👧'],
  ['die Idee', 'fikir', 'dii i-DEE', 'Das ist eine gute Idee!', 'Bu iyi bir fikir!', '💡'],
  ['die Schwester', 'kız kardeş', 'dii ŞVES-tır', 'Meine Schwester wohnt in Köln.', "Kız kardeşim Köln'de oturuyor.", '👧'],
  ['ruhig', 'sakin, sessiz', 'RUU-ih', 'Hier ist es ruhig.', 'Burası sakin.', ''],
  ['ziemlich', 'oldukça', 'TSİİM-lih', 'Es ist ziemlich kalt.', 'Hava oldukça soğuk.', ''],
  ['kurz', 'kısa', 'KURTS', 'Der Film ist kurz.', 'Film kısa.', ''],
  ['der Kerl', 'herif, adam', 'deer KERL', 'Er ist ein netter Kerl.', 'O hoş bir adam.', ''],
  ['liegen', 'yatmak; bulunmak', 'Lİİ-gen', 'Das Buch liegt auf dem Tisch.', 'Kitap masanın üstünde duruyor.', ''],
  ['suchen', 'aramak', 'ZUU-hen', 'Ich suche meine Brille.', 'Gözlüğümü arıyorum.', ''],
  ['je', 'hiç; her biri', 'YEE', 'Warst du je in Rom?', "Hiç Roma'da bulundun mu?", ''],
  ['woher', 'nereden', 'voo-HEER', 'Woher kommst du?', 'Nerelisin?', ''],
  ['der Job', 'iş', 'deer COP', 'Ich habe einen neuen Job.', 'Yeni bir işim var.', ''],
  ['überhaupt', 'hiç; zaten', 'üü-bır-HAUPT', 'Das ist überhaupt nicht schlimm.', 'Bu hiç de kötü değil.', ''],
  ['der Teufel', 'şeytan', 'deer TOY-fel', 'Er ist ein armer Teufel.', 'O zavallı biri.', '😈'],
  ['verlieren', 'kaybetmek', 'fer-Lİİ-ren', 'Ich verliere oft meine Schlüssel.', 'Anahtarlarımı sık kaybederim.', ''],
  ['groß', 'büyük; uzun boylu', 'GROOS', 'Das Zimmer ist groß.', 'Oda büyük.', ''],
  ['die Hand', 'el', 'dii HANT', 'Gib mir deine Hand!', 'Bana elini ver!', '✋'],
  ['der Grund', 'sebep', 'deer GRUNT', 'Was ist der Grund?', 'Sebebi ne?', ''],
  ['die Mama', 'anne (anneciğim)', 'dii MA-ma', 'Mama, ich habe Hunger!', 'Anne, acıktım!', ''],
  ['die Ruhe', 'sessizlik, huzur', 'dii RUU-e', 'Ich brauche Ruhe.', 'Huzura ihtiyacım var.', ''],
  ['der Tod', 'ölüm', 'deer TOOT', 'Der Tod ist traurig.', 'Ölüm üzücüdür.', ''],
  ['die Stunde', 'saat (süre)', 'dii ŞTUN-de', 'Ich warte seit einer Stunde.', 'Bir saattir bekliyorum.', ''],
  ['hoffen', 'ummak', 'HO-fen', 'Ich hoffe, du kommst.', 'Umarım gelirsin.', ''],
  ['oben', 'yukarıda', 'OO-ben', 'Mein Zimmer ist oben.', 'Odam yukarıda.', ''],
  ['gestern', 'dün', 'GES-tırn', 'Gestern war ich krank.', 'Dün hastaydım.', ''],
  ['versuchen', 'denemek', 'fer-ZUU-hen', 'Ich versuche es noch einmal.', 'Bir kez daha deniyorum.', ''],
  ['die Art', 'tür; tarz', 'dii AART', 'Das ist eine Art Kuchen.', 'Bu bir tür kek.', ''],
  ['der Schatz', 'hazine; sevgilim', 'deer ŞATS', 'Du bist mein Schatz.', 'Sen benim bir tanemsin.', '💎'],
  ['endlich', 'nihayet', 'ENT-lih', 'Endlich bist du da!', 'Nihayet geldin!', ''],
  ['etwa', 'yaklaşık', 'ET-va', 'Es dauert etwa eine Stunde.', 'Yaklaşık bir saat sürüyor.', ''],
  ['erzählen', 'anlatmak', 'er-TSEE-len', 'Erzähl mir eine Geschichte!', 'Bana bir hikâye anlat!', ''],
  ['laufen', 'koşmak; yürümek', 'LAU-fen', 'Ich laufe jeden Morgen.', 'Her sabah koşuyorum.', ''],
  ['schwer', 'ağır; zor', 'ŞVEER', 'Die Tasche ist schwer.', 'Çanta ağır.', ''],
  ['anders', 'farklı', 'AN-dırs', 'Heute ist alles anders.', 'Bugün her şey farklı.', ''],
  ['fünf', 'beş', 'FÜNF', 'Ich habe fünf Euro.', 'Beş eurom var.', ''],
  ['das Wasser', 'su', 'das VA-sır', 'Ich trinke viel Wasser.', 'Çok su içiyorum.', '💧'],
  ['erste', 'birinci, ilk', 'EERS-te', 'Das ist mein erster Tag.', 'Bu benim ilk günüm.', ''],
  ['die Geschichte', 'hikâye; tarih', 'dii ge-ŞİH-te', 'Die Geschichte ist spannend.', 'Hikâye heyecanlı.', ''],
  ['wenig', 'az', 'VEE-nih', 'Ich habe wenig Zeit.', 'Az vaktim var.', ''],
  ['holen', 'getirmek, almak', 'HOO-len', 'Ich hole Brot.', 'Ekmek alıyorum.', ''],
  ['bedeuten', 'anlamına gelmek', 'be-DOY-ten', 'Was bedeutet das?', 'Bu ne demek?', ''],
  ['nett', 'nazik, hoş', 'NET', 'Sie ist sehr nett.', 'O çok nazik.', ''],
  ['die Wahrheit', 'gerçek, doğruluk', 'dii VAAR-hayt', 'Sag mir die Wahrheit!', 'Bana doğruyu söyle!', ''],
  ['die Woche', 'hafta', 'dii VO-he', 'Die Woche war lang.', 'Hafta uzundu.', '📅'],
  ['deshalb', 'bu yüzden', 'DES-halp', 'Ich bin krank, deshalb bleibe ich hier.', 'Hastayım, bu yüzden burada kalıyorum.', ''],
  ['welcher', 'hangi', 'VEL-hır', 'Welches Buch liest du?', 'Hangi kitabı okuyorsun?', ''],
  ['bestimmt', 'kesinlikle; belirli', 'be-ŞTİMT', 'Er kommt bestimmt.', 'O kesin gelir.', ''],
  ['hoch', 'yüksek', 'HOOH', 'Der Berg ist hoch.', 'Dağ yüksek.', ''],
  ['das Alter', 'yaş', 'das AL-tır', 'Das Alter ist egal.', 'Yaş önemli değil.', ''],
  ['schauen', 'bakmak', 'ŞAU-en', 'Schau mal!', 'Bir bak!', ''],
  ['das Land', 'ülke; kırsal', 'das LANT', 'Deutschland ist ein schönes Land.', 'Almanya güzel bir ülke.', ''],
  ['das Zimmer', 'oda', 'das TSİ-mır', 'Mein Zimmer ist klein.', 'Odam küçük.', '🛏️'],
  ['der Wagen', 'araba', 'deer VAA-gen', 'Der Wagen ist neu.', 'Araba yeni.', '🚗'],
  ['vier', 'dört', 'FİİR', 'Wir sind vier Personen.', 'Dört kişiyiz.', ''],
  ['gefallen', 'hoşa gitmek', 'ge-FA-len', 'Das Kleid gefällt mir.', 'Elbise hoşuma gidiyor.', ''],
  ['der Spaß', 'eğlence', 'deer ŞPAAS', 'Viel Spaß!', 'İyi eğlenceler!', ''],
  ['niemals', 'asla', 'Nİİ-maals', 'Ich lüge niemals.', 'Asla yalan söylemem.', ''],
  ['die Schuld', 'suç; borç', 'dii ŞULT', 'Das ist nicht deine Schuld.', 'Bu senin suçun değil.', ''],
  ['verlassen', 'terk etmek, ayrılmak', 'fer-LA-sen', 'Er verlässt das Haus.', 'O evden çıkıyor.', ''],
  ['zeigen', 'göstermek', 'TSAY-gen', 'Zeig mir das Foto!', 'Bana fotoğrafı göster!', ''],
  ['ernst', 'ciddi', 'ERNST', 'Die Lage ist ernst.', 'Durum ciddi.', ''],
  ['der Ort', 'yer', 'deer ORT', 'Das ist ein schöner Ort.', 'Bu güzel bir yer.', ''],
  ['manchmal', 'bazen', 'MANH-maal', 'Manchmal koche ich.', 'Bazen yemek pişiririm.', ''],
  ['die Seite', 'sayfa; taraf', 'dii ZAY-te', 'Lies Seite zehn!', 'Onuncu sayfayı oku!', ''],
  ['zwischen', 'arasında', 'TSVİ-şen', 'Das Café ist zwischen Bank und Post.', 'Kafe banka ile postane arasında.', ''],
  ['eben', 'az önce; işte', 'EE-ben', 'Er war eben hier.', 'Az önce buradaydı.', ''],
  ['während', 'sırasında; iken', 'VEE-rent', 'Während des Essens liest er.', 'Yemek sırasında okuyor.', ''],
  ['das Spiel', 'oyun; maç', 'das ŞPİİL', 'Das Spiel beginnt um acht.', 'Maç sekizde başlıyor.', '🎲'],
  ['die Chance', 'şans, fırsat', 'dii ŞAN-se', 'Das ist deine Chance!', 'Bu senin fırsatın!', ''],
  ['die Freundin', 'kız arkadaş', 'dii FROYN-din', 'Das ist meine Freundin Lisa.', 'Bu arkadaşım Lisa.', ''],
  ['der Krieg', 'savaş', 'deer KRİİK', 'Der Krieg ist vorbei.', 'Savaş bitti.', ''],
  ['entschuldigen', 'affetmek; özür dilemek', 'ent-ŞUL-di-gen', 'Entschuldigen Sie bitte!', 'Affedersiniz!', ''],
  ['wichtig', 'önemli', 'VİH-tih', 'Das ist sehr wichtig.', 'Bu çok önemli.', ''],
  ['das Bett', 'yatak', 'das BET', 'Ich gehe ins Bett.', 'Yatağa gidiyorum.', '🛏️'],
  ['schlecht', 'kötü', 'ŞLEHT', 'Das Wetter ist schlecht.', 'Hava kötü.', ''],
  ['die Schule', 'okul', 'dii ŞUU-le', 'Die Kinder gehen zur Schule.', 'Çocuklar okula gidiyor.', '🏫'],
  ['die Entschuldigung', 'özür', 'dii ent-ŞUL-di-gung', 'Entschuldigung, wo ist die Bank?', 'Affedersiniz, banka nerede?', ''],
  ['das Wort', 'kelime', 'das VORT', 'Ich kenne das Wort nicht.', 'Bu kelimeyi bilmiyorum.', ''],
  ['der Typ', 'tip, herif', 'deer TÜÜP', 'Er ist ein komischer Typ.', 'O tuhaf bir tip.', ''],
  ['schlafen', 'uyumak', 'ŞLAA-fen', 'Ich schlafe acht Stunden.', 'Sekiz saat uyuyorum.', ''],
  ['euer', 'sizin', 'OY-ır', 'Ist das euer Hund?', 'Bu sizin köpeğiniz mi?', ''],
  ['das Gesicht', 'yüz', 'das ge-ZİHT', 'Wasch dein Gesicht!', 'Yüzünü yıka!', '🙂'],
  ['falls', 'eğer, olur da', 'FALS', 'Ruf mich an, falls du Zeit hast.', 'Vaktin olursa beni ara.', ''],
  ['bloß', 'sadece; sakın', 'BLOOS', 'Das ist bloß ein Spiel.', 'Bu sadece bir oyun.', ''],
  ['unten', 'aşağıda', 'UN-ten', 'Die Küche ist unten.', 'Mutfak aşağıda.', ''],
  ['der Teil', 'parça, kısım', 'deer TAYL', 'Das ist der erste Teil.', 'Bu birinci kısım.', ''],
  ['stellen', 'koymak (dik)', 'ŞTE-len', 'Stell die Flasche auf den Tisch!', 'Şişeyi masaya koy!', ''],
  ['oft', 'sık sık', 'OFT', 'Ich gehe oft spazieren.', 'Sık sık yürüyüşe çıkarım.', ''],
  ['trinken', 'içmek', 'TRİN-ken', 'Ich trinke Tee.', 'Çay içiyorum.', ''],
  ['einige', 'birkaç, bazı', 'AY-ni-ge', 'Einige Leute warten.', 'Birkaç kişi bekliyor.', ''],
  ['kriegen', 'almak (günlük dil)', 'KRİİ-gen', 'Ich kriege ein Eis.', 'Bir dondurma alıyorum.', ''],
  ['das Blut', 'kan', 'das BLUUT', 'Das Blut ist rot.', 'Kan kırmızıdır.', '🩸'],
  ['ehrlich', 'dürüst', 'EER-lih', 'Sei ehrlich!', 'Dürüst ol!', ''],
  ['die Eltern', 'anne baba', 'dii EL-tırn', 'Meine Eltern wohnen in Izmir.', "Annemle babam İzmir'de oturuyor.", ''],
  ['scheinen', 'görünmek; parlamak', 'ŞAY-nen', 'Die Sonne scheint.', 'Güneş parlıyor.', ''],
  ['das Herz', 'kalp', 'das HERTS', 'Mein Herz schlägt schnell.', 'Kalbim hızlı atıyor.', '❤️'],
  ['glücklich', 'mutlu', 'GLÜK-lih', 'Ich bin sehr glücklich.', 'Çok mutluyum.', ''],
  ['alt', 'yaşlı; eski', 'ALT', 'Wie alt bist du?', 'Kaç yaşındasın?', ''],
  ['auf Wiedersehen', 'hoşça kalın', 'auf Vİİ-dır-zee-en', 'Auf Wiedersehen, Frau Schmidt!', 'Hoşça kalın, Bayan Schmidt!', ''],
  ['frei', 'serbest; boş', 'FRAY', 'Ist der Platz frei?', 'Bu yer boş mu?', ''],
  ['möglich', 'mümkün', 'MÖÖK-lih', 'Ist das möglich?', 'Bu mümkün mü?', ''],
  ['irgendwie', 'bir şekilde', 'İR-gent-vii', 'Irgendwie schaffen wir das.', 'Bir şekilde bunu başarırız.', ''],
  ['reichen', 'yetmek; uzatmak', 'RAY-hen', 'Das reicht!', 'Bu kadar yeter!', ''],
  ['fest', 'sıkı; sabit', 'FEST', 'Halt dich fest!', 'Sıkı tutun!', ''],
  ['die Waffe', 'silah', 'dii VA-fe', 'Die Polizei hat eine Waffe.', 'Polisin bir silahı var.', ''],
  ['kaum', 'neredeyse hiç', 'KAUM', 'Ich habe kaum geschlafen.', 'Neredeyse hiç uyumadım.', ''],
  ['irgendwas', 'herhangi bir şey', 'İR-gent-vas', 'Sag doch irgendwas!', 'Bir şey söylesene!', ''],
  ['klingen', 'kulağa gelmek', 'KLİN-gen', 'Das klingt gut.', 'Kulağa hoş geliyor.', ''],
  ['der Platz', 'yer; meydan', 'deer PLATS', 'Nimm Platz, bitte.', 'Buyur otur.', ''],
  ['der Papa', 'baba (babacığım)', 'deer PA-pa', 'Papa, komm spielen!', 'Baba, gel oynayalım!', ''],
  ['falsch', 'yanlış', 'FALŞ', 'Die Antwort ist falsch.', 'Cevap yanlış.', ''],
  ['sondern', 'aksine, bilakis', 'ZON-dırn', 'Nicht heute, sondern morgen.', 'Bugün değil, yarın.', ''],
  ['die Nummer', 'numara', 'dii NU-mır', 'Wie ist deine Nummer?', 'Numaran ne?', ''],
  ['früh', 'erken', 'FRÜÜ', 'Ich stehe früh auf.', 'Erken kalkarım.', ''],
  ['jung', 'genç', 'YUNG', 'Er ist noch jung.', 'O daha genç.', ''],
  ['wohin', 'nereye', 'voo-HİN', 'Wohin gehst du?', 'Nereye gidiyorsun?', ''],
  ['außer', '-den başka, hariç', 'AU-sır', 'Alle außer mir sind da.', 'Benden başka herkes burada.', ''],
  ['setzen', 'oturtmak (sich: oturmak)', 'ZET-sen', 'Setz dich, bitte!', 'Otur lütfen!', ''],
  ['zuerst', 'önce', 'tsu-EERST', 'Zuerst trinke ich Kaffee.', 'Önce kahve içiyorum.', ''],
  ['wahrscheinlich', 'muhtemelen', 'vaar-ŞAYN-lih', 'Er kommt wahrscheinlich später.', 'Muhtemelen daha sonra gelir.', ''],
  ['das Telefon', 'telefon', 'das te-le-FOON', 'Das Telefon klingelt.', 'Telefon çalıyor.', '☎️'],
  ['willkommen', 'hoş geldin', 'vil-KO-men', 'Willkommen in Berlin!', "Berlin'e hoş geldin!", ''],
  ['der Plan', 'plan', 'deer PLAAN', 'Ich habe einen Plan.', 'Bir planım var.', ''],
  ['retten', 'kurtarmak', 'RE-ten', 'Der Arzt rettet das Kind.', 'Doktor çocuğu kurtarıyor.', ''],
  ['hierher', 'buraya', 'HİİR-heer', 'Komm hierher!', 'Buraya gel!', ''],
  ['der Fehler', 'hata', 'deer FEE-lır', 'Das war ein Fehler.', 'Bu bir hataydı.', ''],
  ['der Dollar', 'dolar', 'deer DO-lar', 'Das kostet zehn Dollar.', 'Bu on dolar.', '💵'],
  ['zehn', 'on', 'TSEEN', 'Ich bin zehn Minuten zu spät.', 'On dakika geç kaldım.', ''],
  ['passen', 'uymak; olmak', 'PA-sen', 'Die Hose passt mir.', 'Pantolon bana oluyor.', ''],
  ['nächste', 'sonraki, en yakın', 'NEEHS-te', 'Wir sehen uns nächste Woche.', 'Haftaya görüşürüz.', ''],
  ['die Menge', 'miktar; kalabalık', 'dii MEN-ge', 'Ich habe eine Menge Arbeit.', 'Bir sürü işim var.', ''],
  ['langsam', 'yavaş', 'LANG-zaam', 'Sprich bitte langsam.', 'Lütfen yavaş konuş.', ''],
  ['bereits', 'zaten', 'be-RAYTS', 'Er ist bereits weg.', 'O zaten gitti.', ''],
  ['sechs', 'altı', 'ZEKS', 'Es ist sechs Uhr.', 'Saat altı.', ''],
  ['lieben', 'sevmek', 'Lİİ-ben', 'Ich liebe dich.', 'Seni seviyorum.', ''],
  ['das Büro', 'ofis, büro', 'das bü-ROO', 'Ich bin im Büro.', 'Ofisteyim.', '🏢'],
  ['rufen', 'çağırmak, seslenmek', 'RUU-fen', 'Ruf ein Taxi!', 'Bir taksi çağır!', ''],
  ['schaffen', 'başarmak', 'ŞA-fen', 'Du schaffst das!', 'Sen bunu başarırsın!', ''],
  ['leider', 'maalesef', 'LAY-dır', 'Leider habe ich keine Zeit.', 'Maalesef vaktim yok.', ''],
  ['die Hölle', 'cehennem', 'dii HÖ-le', 'Das war die Hölle.', 'Bu cehennem gibiydi.', ''],
  ['trotzdem', 'yine de', 'TROTS-deem', 'Es regnet, trotzdem gehe ich.', 'Yağmur yağıyor, yine de gidiyorum.', ''],
  ['der Doktor', 'doktor', 'deer DOK-tor', 'Der Doktor ist nett.', 'Doktor nazik.', '🩺'],
  ['voll', 'dolu', 'FOL', 'Der Bus ist voll.', 'Otobüs dolu.', ''],
  ['der Film', 'film', 'deer FİLM', 'Der Film ist lustig.', 'Film komik.', '🎬'],
  ['überall', 'her yerde', 'üü-bır-AL', 'Überall ist Schnee.', 'Her yer kar.', ''],
  ['der Hund', 'köpek', 'deer HUNT', 'Der Hund bellt.', 'Köpek havlıyor.', '🐕'],
  ['direkt', 'doğrudan', 'di-REKT', 'Der Bus fährt direkt zum Bahnhof.', 'Otobüs doğrudan istasyona gidiyor.', ''],
  ['das Schiff', 'gemi', 'das ŞİF', 'Das Schiff ist groß.', 'Gemi büyük.', '🚢'],
  ['der König', 'kral', 'deer KÖÖ-nih', 'Der König wohnt im Schloss.', 'Kral şatoda yaşıyor.', '👑'],
  ['danach', 'ondan sonra', 'da-NAAH', 'Danach gehen wir nach Hause.', 'Ondan sonra eve gidiyoruz.', ''],
  ['funktionieren', 'çalışmak (makine)', 'funk-tsyo-Nİİ-ren', 'Das Handy funktioniert nicht.', 'Telefon çalışmıyor.', ''],
  ['lernen', 'öğrenmek', 'LER-nen', 'Ich lerne Deutsch.', 'Almanca öğreniyorum.', ''],
  ['deswegen', 'bu yüzden', 'DES-vee-gen', 'Deswegen bin ich müde.', 'Bu yüzden yorgunum.', ''],
  ['nennen', 'adlandırmak', 'NE-nen', 'Nenn mich Tom.', 'Bana Tom de.', ''],
  ['das Feuer', 'ateş; yangın', 'das FOY-ır', 'Das Feuer ist heiß.', 'Ateş sıcak.', '🔥'],
  ['erinnern', 'hatırlatmak (sich: hatırlamak)', 'er-İ-nırn', 'Ich erinnere mich an dich.', 'Seni hatırlıyorum.', ''],
  ['völlig', 'tamamen', 'FÖ-lih', 'Ich bin völlig müde.', 'Tamamen yorgunum.', ''],
  ['die Stelle', 'yer; iş yeri', 'dii ŞTE-le', 'An deiner Stelle würde ich gehen.', 'Senin yerinde olsam giderdim.', ''],
  ['der Kumpel', 'kanka, dost', 'deer KUM-pel', 'Er ist mein bester Kumpel.', 'O benim en iyi kankam.', ''],
  ['der Kaffee', 'kahve', 'deer KA-fee', 'Ich trinke gern Kaffee.', 'Kahve içmeyi severim.', '☕'],
  ['die Luft', 'hava (solunan)', 'dii LUFT', 'Die Luft ist frisch.', 'Hava temiz.', ''],
  ['ziehen', 'çekmek; taşınmak', 'TSİİ-en', 'Wir ziehen nach Hamburg.', "Hamburg'a taşınıyoruz.", ''],
  ['verschwinden', 'kaybolmak', 'fer-ŞVİN-den', 'Die Katze ist verschwunden.', 'Kedi kayboldu.', ''],
  ['aufhören', 'bırakmak, durmak', 'AUF-höö-ren', 'Hör auf damit!', 'Kes şunu!', ''],
  ['eigen', 'kendi', 'AY-gen', 'Ich habe ein eigenes Zimmer.', 'Kendi odam var.', ''],
  ['zwar', 'gerçi', 'TSVAAR', 'Es ist zwar kalt, aber schön.', 'Gerçi soğuk ama güzel.', ''],
  ['das Buch', 'kitap', 'das BUUH', 'Ich lese ein Buch.', 'Bir kitap okuyorum.', '📖'],
  ['krank', 'hasta', 'KRANK', 'Ich bin krank.', 'Hastayım.', ''],
  ['fühlen', 'hissetmek', 'FÜÜ-len', 'Ich fühle mich gut.', 'Kendimi iyi hissediyorum.', ''],
  ['der Wert', 'değer', 'deer VEERT', 'Das hat keinen Wert.', 'Bunun bir değeri yok.', ''],
  ['der Arzt', 'doktor, hekim', 'deer AARTST', 'Ich gehe zum Arzt.', 'Doktora gidiyorum.', '🧑‍⚕️'],
  ['froh', 'memnun', 'FROO', 'Ich bin froh, dass du da bist.', 'Burada olduğuna memnunum.', ''],
  ['die Straße', 'cadde, sokak', 'dii ŞTRAA-se', 'Die Straße ist lang.', 'Cadde uzun.', '🛣️'],
  ['heiraten', 'evlenmek', 'HAY-raa-ten', 'Wir heiraten im Mai.', 'Mayısta evleniyoruz.', ''],
  ['super', 'süper', 'ZUU-pır', 'Das ist super!', 'Bu süper!', ''],
  ['der Onkel', 'amca, dayı', 'deer ON-kel', 'Mein Onkel wohnt in Bonn.', "Amcam Bonn'da oturuyor.", ''],
  ['total', 'tamamen', 'to-TAAL', 'Ich bin total müde.', 'Tamamen yorgunum.', ''],
  ['die Party', 'parti', 'dii PAAR-ti', 'Die Party ist toll.', 'Parti harika.', '🎉'],
  ['erklären', 'açıklamak', 'er-KLEE-ren', 'Kannst du das erklären?', 'Bunu açıklayabilir misin?', ''],
  ['die Wahl', 'seçim', 'dii VAAL', 'Ich habe keine Wahl.', 'Başka seçeneğim yok.', ''],
  ['vertrauen', 'güvenmek', 'fer-TRAU-en', 'Ich vertraue dir.', 'Sana güveniyorum.', ''],
  ['damals', 'o zamanlar', 'DAA-maals', 'Damals war ich jung.', 'O zamanlar gençtim.', ''],
  ['leicht', 'kolay; hafif', 'LAYHT', 'Die Tasche ist leicht.', 'Çanta hafif.', ''],
  ['nachdem', '-dikten sonra', 'naah-DEEM', 'Nachdem ich gegessen habe, schlafe ich.', 'Yemek yedikten sonra uyuyorum.', ''],
  ['das Gefühl', 'his, duygu', 'das ge-FÜÜL', 'Ich habe ein gutes Gefühl.', 'İçimde iyi bir his var.', ''],
  ['kaufen', 'satın almak', 'KAU-fen', 'Ich kaufe Brot.', 'Ekmek alıyorum.', ''],
  ['interessieren', 'ilgilendirmek', 'in-te-re-Sİİ-ren', 'Ich interessiere mich für Musik.', 'Müzikle ilgileniyorum.', ''],
  ['irgendwo', 'bir yerde', 'İR-gent-voo', 'Mein Handy ist irgendwo hier.', 'Telefonum burada bir yerde.', ''],
  ['das Stück', 'parça', 'das ŞTÜK', 'Ein Stück Kuchen, bitte.', 'Bir dilim kek, lütfen.', '🍰'],
  ['genauso', 'aynı şekilde', 'ge-NAU-zoo', 'Ich denke genauso.', 'Ben de aynı şekilde düşünüyorum.', ''],
  ['die Zukunft', 'gelecek', 'dii TSUU-kunft', 'Die Zukunft ist hell.', 'Gelecek parlak.', ''],
  ['cool', 'havalı', 'KUUL', 'Das ist cool!', 'Bu havalı!', ''],
  ['das Licht', 'ışık', 'das LİHT', 'Mach das Licht an!', 'Işığı aç!', '💡'],
  ['der Himmel', 'gökyüzü; cennet', 'deer Hİ-mel', 'Der Himmel ist blau.', 'Gökyüzü mavi.', '🌌'],
  ['die Nachricht', 'mesaj; haber', 'dii NAAH-riht', 'Ich schreibe dir eine Nachricht.', 'Sana bir mesaj yazıyorum.', ''],
  ['drüben', 'karşıda', 'DRÜÜ-ben', 'Das Café ist da drüben.', 'Kafe şurada karşıda.', ''],
  ['kümmern', 'ilgilenmek (sich)', 'KÜ-mırn', 'Ich kümmere mich um das Kind.', 'Çocukla ben ilgileniyorum.', ''],
  ['laut', 'yüksek sesli', 'LAUT', 'Die Musik ist zu laut.', 'Müzik çok yüksek.', ''],
  ['anrufen', 'telefon etmek', 'AN-ruu-fen', 'Ich rufe dich morgen an.', 'Seni yarın ararım.', ''],
  ['sitzen', 'oturmak', 'ZİT-sen', 'Ich sitze im Garten.', 'Bahçede oturuyorum.', ''],
  ['die Erde', 'dünya; toprak', 'dii EER-de', 'Die Erde ist rund.', 'Dünya yuvarlaktır.', '🌍'],
  ['der Schlüssel', 'anahtar', 'deer ŞLÜ-sel', 'Wo ist mein Schlüssel?', 'Anahtarım nerede?', '🔑'],
  ['der Rest', 'kalan', 'deer REST', 'Den Rest esse ich morgen.', 'Kalanını yarın yerim.', ''],
  ['eher', 'daha çok; daha erken', 'EE-ır', 'Ich trinke eher Tee.', 'Daha çok çay içerim.', ''],
  ['das Gefängnis', 'hapishane', 'das ge-FENG-nis', 'Er sitzt im Gefängnis.', 'O hapiste.', ''],
  ['das Opfer', 'kurban', 'das OP-fır', 'Das Opfer ist im Krankenhaus.', 'Kurban hastanede.', ''],
  ['der Körper', 'vücut', 'deer KÖR-pır', 'Sport ist gut für den Körper.', 'Spor vücut için iyidir.', ''],
  ['solch', 'böyle', 'ZOLH', 'Solche Schuhe mag ich.', 'Böyle ayakkabıları severim.', ''],
  ['schreiben', 'yazmak', 'ŞRAY-ben', 'Ich schreibe einen Brief.', 'Bir mektup yazıyorum.', ''],
  ['böse', 'kötü; kızgın', 'BÖÖ-ze', 'Bist du mir böse?', 'Bana kızgın mısın?', ''],
  ['vorstellen', 'tanıştırmak; hayal etmek', 'FOOR-şte-len', 'Darf ich mich vorstellen?', 'Kendimi tanıtabilir miyim?', ''],
  ['wovon', 'neden, ne hakkında', 'voo-FON', 'Wovon sprichst du?', 'Neden bahsediyorsun?', ''],
  ['sobald', '-er -mez', 'zo-BALT', 'Ich rufe an, sobald ich da bin.', 'Varır varmaz ararım.', ''],
  ['nochmal', 'bir daha', 'NOH-maal', 'Sag das nochmal!', 'Bunu bir daha söyle!', ''],
  ['die Wohnung', 'daire, ev', 'dii VOO-nung', 'Die Wohnung hat drei Zimmer.', 'Dairenin üç odası var.', '🏠'],
  ['weh', 'acı (wehtun: ağrımak)', 'VEE', 'Mein Bauch tut weh.', 'Karnım ağrıyor.', ''],
  ['das Krankenhaus', 'hastane', 'das KRAN-ken-haus', 'Sie liegt im Krankenhaus.', 'O hastanede yatıyor.', '🏥'],
  ['die Million', 'milyon', 'dii mi-LYOON', 'Die Stadt hat eine Million Menschen.', 'Şehrin bir milyon nüfusu var.', ''],
  ['die Klasse', 'sınıf; harika', 'dii KLA-se', 'Meine Klasse ist nett.', 'Sınıfım hoş.', ''],
  ['hart', 'sert; zor', 'HART', 'Das Brot ist hart.', 'Ekmek sert.', ''],
  ['der Sinn', 'anlam', 'deer ZİN', 'Das macht keinen Sinn.', 'Bunun anlamı yok.', ''],
  ['außerdem', 'ayrıca', 'AU-sır-deem', 'Außerdem ist es kalt.', 'Ayrıca hava soğuk.', ''],
  ['verletzen', 'yaralamak', 'fer-LET-sen', 'Er hat sich verletzt.', 'O yaralandı.', ''],
  ['ändern', 'değiştirmek', 'EN-dırn', 'Ich ändere meinen Plan.', 'Planımı değiştiriyorum.', ''],
  ['erfahren', 'öğrenmek, haber almak', 'er-FAA-ren', 'Wie hast du das erfahren?', 'Bunu nasıl öğrendin?', ''],
  ['tragen', 'taşımak; giymek', 'TRAA-gen', 'Sie trägt ein rotes Kleid.', 'O kırmızı bir elbise giyiyor.', ''],
  ['wenigstens', 'en azından', 'VEE-nihs-tens', 'Wenigstens regnet es nicht.', 'En azından yağmur yağmıyor.', ''],
  ['vorsichtig', 'dikkatli', 'FOOR-zih-tih', 'Sei vorsichtig!', 'Dikkatli ol!', ''],
  ['stolz', 'gururlu', 'ŞTOLTS', 'Ich bin stolz auf dich.', 'Seninle gurur duyuyorum.', ''],
  ['stark', 'güçlü', 'ŞTARK', 'Er ist sehr stark.', 'O çok güçlü.', ''],
  ['fallen', 'düşmek', 'FA-len', 'Das Glas fällt auf den Boden.', 'Bardak yere düşüyor.', ''],
  ['besonders', 'özellikle', 'be-ZON-dırs', 'Ich mag besonders Äpfel.', 'Özellikle elmayı severim.', ''],
  ['schicken', 'göndermek', 'Şİ-ken', 'Ich schicke dir ein Foto.', 'Sana bir fotoğraf gönderiyorum.', ''],
  ['die Person', 'kişi', 'dii per-ZOON', 'Der Tisch ist für vier Personen.', 'Masa dört kişilik.', ''],
  ['schätzen', 'tahmin etmek; takdir etmek', 'ŞET-sen', 'Ich schätze, er ist dreißig.', 'Sanırım o otuz yaşında.', ''],
  ['solange', '-dığı sürece', 'zo-LAN-ge', 'Bleib, solange du willst.', 'İstediğin kadar kal.', ''],
  ['großartig', 'muhteşem', 'GROOS-aar-tih', 'Das Essen ist großartig.', 'Yemek muhteşem.', ''],
  ['lachen', 'gülmek', 'LA-hen', 'Wir lachen viel.', 'Çok gülüyoruz.', ''],
  ['erwarten', 'beklemek (ummak)', 'er-VAR-ten', 'Ich erwarte einen Anruf.', 'Bir telefon bekliyorum.', ''],
  ['der Boden', 'zemin, yer', 'deer BOO-den', 'Die Tasche liegt auf dem Boden.', 'Çanta yerde duruyor.', ''],
  ['der Boss', 'patron', 'deer BOS', 'Der Boss ist heute nicht da.', 'Patron bugün burada değil.', ''],
  ['die Stimme', 'ses', 'dii ŞTİ-me', 'Sie hat eine schöne Stimme.', 'Onun güzel bir sesi var.', ''],
  ['still', 'sessiz', 'ŞTİL', 'Sei still!', 'Sessiz ol!', ''],
  ['die Sicherheit', 'güvenlik', 'dii Zİ-hır-hayt', 'Sicherheit ist wichtig.', 'Güvenlik önemlidir.', ''],
  ['der Mund', 'ağız', 'deer MUNT', 'Mach den Mund auf!', 'Ağzını aç!', '👄'],
  ['kämpfen', 'savaşmak, mücadele etmek', 'KEMP-fen', 'Wir kämpfen für unsere Rechte.', 'Haklarımız için mücadele ediyoruz.', ''],
  ['das Zeug', 'şey(ler), eşya', 'das TSOYK', 'Nimm dein Zeug mit!', 'Eşyalarını al!', ''],
  ['lustig', 'komik, eğlenceli', 'LUS-tih', 'Der Film ist lustig.', 'Film komik.', ''],
  ['umbringen', 'öldürmek', 'UM-brin-gen', 'Der Stress bringt mich um!', 'Stres beni öldürüyor!', ''],
  ['hassen', 'nefret etmek', 'HA-sen', 'Ich hasse Regen.', 'Yağmurdan nefret ediyorum.', ''],
  ['schlimm', 'kötü, fena', 'ŞLİM', 'Das ist nicht so schlimm.', 'O kadar da kötü değil.', ''],
  ['unglaublich', 'inanılmaz', 'un-GLAUP-lih', 'Das ist unglaublich!', 'Bu inanılmaz!', ''],
  ['der Laden', 'dükkân', 'deer LAA-den', 'Der Laden ist geschlossen.', 'Dükkân kapalı.', '🏪'],
  ['führen', 'yönetmek; götürmek', 'FÜÜ-ren', 'Der Weg führt zum See.', 'Yol göle çıkıyor.', ''],
  ['die Meinung', 'fikir, görüş', 'dii MAY-nung', 'Was ist deine Meinung?', 'Senin fikrin ne?', ''],
  ['lesen', 'okumak', 'LEE-zen', 'Ich lese die Zeitung.', 'Gazete okuyorum.', ''],
  ['der Mörder', 'katil', 'deer MÖR-dır', 'Die Polizei sucht den Mörder.', 'Polis katili arıyor.', ''],
  ['geschehen', 'olmak, meydana gelmek', 'ge-ŞEE-en', 'Was ist geschehen?', 'Ne oldu?', ''],
  ['das Geschäft', 'dükkân; iş', 'das ge-ŞEFT', 'Das Geschäft öffnet um neun.', 'Dükkân dokuzda açılıyor.', '🏬'],
  ['die Verzeihung', 'özür, af', 'dii fer-TSAY-ung', 'Verzeihung, ist hier frei?', 'Pardon, burası boş mu?', ''],
  ['fliegen', 'uçmak', 'FLİİ-gen', 'Wir fliegen nach Istanbul.', "İstanbul'a uçuyoruz.", ''],
  ['das Team', 'takım, ekip', 'das TİİM', 'Unser Team ist stark.', 'Takımımız güçlü.', ''],
  ['vorher', 'önceden', 'FOOR-heer', 'Ruf mich vorher an!', 'Önceden beni ara!', ''],
  ['der Schluss', 'son', 'deer ŞLUS', 'Schluss für heute!', 'Bugünlük bu kadar!', ''],
  ['verdienen', 'kazanmak; hak etmek', 'fer-Dİİ-nen', 'Er verdient viel Geld.', 'O çok para kazanıyor.', ''],
  ['perfekt', 'mükemmel', 'per-FEKT', 'Dein Deutsch ist perfekt.', 'Almancan mükemmel.', ''],
  ['versprechen', 'söz vermek', 'fer-ŞPRE-hen', 'Ich verspreche es dir.', 'Sana söz veriyorum.', ''],
  ['das Handy', 'cep telefonu', 'das HEN-di', 'Mein Handy ist kaputt.', 'Telefonum bozuk.', '📱'],
  ['hinten', 'arkada', 'HİN-ten', 'Der Garten ist hinten.', 'Bahçe arkada.', ''],
  ['der Monat', 'ay (takvim)', 'deer MOO-nat', 'Der Monat hat dreißig Tage.', 'Ay otuz gün çekiyor.', ''],
  ['acht', 'sekiz', 'AHT', 'Es ist acht Uhr.', 'Saat sekiz.', ''],
  ['nötig', 'gerekli', 'NÖÖ-tih', 'Das ist nicht nötig.', 'Buna gerek yok.', ''],
  ['der Mord', 'cinayet', 'deer MORT', 'Die Polizei untersucht den Mord.', 'Polis cinayeti araştırıyor.', ''],
  ['heraus', 'dışarı', 'he-RAUS', 'Komm heraus!', 'Dışarı çık!', ''],
  ['unmöglich', 'imkânsız', 'UN-möök-lih', 'Das ist unmöglich!', 'Bu imkânsız!', ''],
  ['der Liebling', 'sevgili, favori', 'deer LİİP-ling', 'Du bist mein Liebling.', 'Sen benim sevgilimsin.', ''],
  ['tatsächlich', 'gerçekten', 'TAAT-zeh-lih', 'Er ist tatsächlich gekommen.', 'O gerçekten geldi.', ''],
  ['folgen', 'takip etmek', 'FOL-gen', 'Folgen Sie mir, bitte!', 'Beni takip edin, lütfen!', ''],
  ['bitten', 'rica etmek', 'Bİ-ten', 'Ich bitte dich um Hilfe.', 'Senden yardım rica ediyorum.', ''],
  ['behalten', 'saklamak, tutmak', 'be-HAL-ten', 'Du kannst das Buch behalten.', 'Kitabı sende kalabilir.', ''],
  ['die Nähe', 'yakınlık', 'dii NEE-e', 'Wohnst du in der Nähe?', 'Yakında mı oturuyorsun?', ''],
  ['plötzlich', 'aniden', 'PLÖTS-lih', 'Plötzlich regnet es.', 'Aniden yağmur yağıyor.', ''],
  ['der Tisch', 'masa', 'deer TİŞ', 'Das Essen steht auf dem Tisch.', 'Yemek masada.', '🍽️'],
  ['jemals', 'hiç (bir zaman)', 'YEE-maals', 'Warst du jemals in Paris?', "Hiç Paris'te bulundun mu?", ''],
  ['verkaufen', 'satmak', 'fer-KAU-fen', 'Er verkauft sein Auto.', 'O arabasını satıyor.', ''],
  ['gefährlich', 'tehlikeli', 'ge-FEER-lih', 'Das ist gefährlich!', 'Bu tehlikeli!', ''],
  ['anfangen', 'başlamak', 'AN-fan-gen', 'Wir fangen jetzt an.', 'Şimdi başlıyoruz.', ''],
  ['das Hotel', 'otel', 'das ho-TEL', 'Das Hotel ist in der Nähe.', 'Otel yakında.', '🏨'],
  ['der Meister', 'usta; şampiyon', 'deer MAYS-tır', 'Er ist ein Meister im Kochen.', 'O yemekte usta.', ''],
  ['der Kampf', 'kavga; mücadele', 'deer KAMPF', 'Der Kampf ist vorbei.', 'Kavga bitti.', ''],
  ['die Antwort', 'cevap', 'dii ANT-vort', 'Ich warte auf deine Antwort.', 'Cevabını bekliyorum.', ''],
  ['obwohl', '-e rağmen', 'op-VOOL', 'Ich gehe, obwohl es regnet.', 'Yağmur yağmasına rağmen gidiyorum.', ''],
  ['sieben', 'yedi', 'Zİİ-ben', 'Die Woche hat sieben Tage.', 'Haftada yedi gün var.', ''],
  ['komisch', 'tuhaf; komik', 'KOO-miş', 'Das ist komisch.', 'Bu tuhaf.', ''],
  ['gewinnen', 'kazanmak', 'ge-Vİ-nen', 'Wir gewinnen das Spiel.', 'Maçı kazanıyoruz.', ''],
  ['bezahlen', 'ödemek', 'be-TSAA-len', 'Ich möchte bezahlen, bitte.', 'Ödemek istiyorum, lütfen.', ''],
  ['unterwegs', 'yolda', 'un-tır-VEEKS', 'Ich bin schon unterwegs.', 'Zaten yoldayım.', ''],
  ['dumm', 'aptal', 'DUM', 'Das war eine dumme Idee.', 'Bu aptalca bir fikirdi.', ''],
  ['der Ärger', 'dert, bela; öfke', 'deer ER-gır', 'Ich habe Ärger mit dem Chef.', 'Patronla başım dertte.', ''],
  ['das Bild', 'resim', 'das BİLT', 'Das Bild ist schön.', 'Resim güzel.', '🖼️'],
  ['dagegen', 'buna karşı', 'da-GEE-gen', 'Hast du etwas dagegen?', 'Buna bir itirazın var mı?', ''],
  ['die Leiche', 'ceset', 'dii LAY-he', 'Die Polizei findet eine Leiche.', 'Polis bir ceset buluyor.', ''],
  ['verheiratet', 'evli', 'fer-HAY-raa-tet', 'Ich bin verheiratet.', 'Evliyim.', ''],
  ['der Traum', 'rüya; hayal', 'deer TRAUM', 'Das ist mein Traum.', 'Bu benim hayalim.', ''],
  ['die Entscheidung', 'karar', 'dii ent-ŞAY-dung', 'Das ist deine Entscheidung.', 'Bu senin kararın.', ''],
  ['die Regel', 'kural', 'dii REE-gel', 'Das ist die Regel.', 'Kural bu.', ''],
  ['das Fenster', 'pencere', 'das FENS-tır', 'Mach das Fenster auf!', 'Pencereyi aç!', '🪟'],
  ['fangen', 'yakalamak', 'FAN-gen', 'Die Katze fängt eine Maus.', 'Kedi bir fare yakalıyor.', ''],
  ['fort', 'gitmiş, uzak', 'FORT', 'Er ist schon fort.', 'O çoktan gitti.', ''],
  ['ständig', 'sürekli', 'ŞTEN-dih', 'Er redet ständig.', 'O sürekli konuşuyor.', ''],
  ['die Gefahr', 'tehlike', 'dii ge-FAAR', 'Hier ist Gefahr!', 'Burada tehlike var!', ''],
  ['absolut', 'kesinlikle', 'ap-zo-LUUT', 'Das ist absolut richtig.', 'Bu kesinlikle doğru.', ''],
  ['der Augenblick', 'an', 'deer AU-gen-blik', 'Einen Augenblick, bitte!', 'Bir saniye, lütfen!', ''],
  ['der Bescheid', 'haber (Bescheid sagen)', 'deer be-ŞAYT', 'Sag mir Bescheid!', 'Bana haber ver!', ''],
  ['der Gedanke', 'düşünce', 'deer ge-DAN-ke', 'Das ist ein guter Gedanke.', 'Bu iyi bir düşünce.', ''],
  ['das Ziel', 'hedef', 'das TSİİL', 'Mein Ziel ist klar.', 'Hedefim belli.', '🎯'],
  ['benutzen', 'kullanmak', 'be-NUT-sen', 'Darf ich dein Handy benutzen?', 'Telefonunu kullanabilir miyim?', ''],
  ['die Bewegung', 'hareket', 'dii be-VEE-gung', 'Bewegung ist gesund.', 'Hareket sağlıklıdır.', ''],
  ['wünschen', 'dilemek', 'VÜN-şen', 'Ich wünsche dir alles Gute!', 'Sana her şeyin iyisini dilerim!', ''],
  ['zahlen', 'ödemek', 'TSAA-len', 'Zahlen, bitte!', 'Hesap, lütfen!', ''],
  ['der Anfang', 'başlangıç', 'deer AN-fang', 'Das ist erst der Anfang.', 'Bu daha başlangıç.', ''],
  ['legen', 'koymak (yatay)', 'LEE-gen', 'Leg das Buch auf den Tisch!', 'Kitabı masaya koy!', ''],
  ['der Anwalt', 'avukat', 'deer AN-valt', 'Ich brauche einen Anwalt.', 'Bir avukata ihtiyacım var.', ''],
  ['offen', 'açık', 'O-fen', 'Die Tür ist offen.', 'Kapı açık.', ''],
  ['arm', 'fakir', 'ARM', 'Die Familie ist arm.', 'Aile fakir.', ''],
  ['das Bier', 'bira', 'das BİİR', 'Ein Bier, bitte!', 'Bir bira, lütfen!', '🍺'],
  ['der Partner', 'ortak; partner', 'deer PART-nır', 'Er ist mein Partner.', 'O benim ortağım.', ''],
  ['der Finger', 'parmak', 'deer FİN-gır', 'Mein Finger tut weh.', 'Parmağım acıyor.', '☝️'],
  ['die Ehe', 'evlilik', 'dii EE-e', 'Ihre Ehe ist glücklich.', 'Evlilikleri mutlu.', ''],
  ['die Rolle', 'rol', 'dii RO-le', 'Das spielt keine Rolle.', 'Bunun önemi yok.', ''],
  ['die Hochzeit', 'düğün', 'dii HOH-tsayt', 'Die Hochzeit ist im Juni.', 'Düğün haziranda.', '💒'],
  ['wach', 'uyanık', 'VAH', 'Bist du schon wach?', 'Uyandın mı?', ''],
  ['wozu', 'ne için', 'voo-TSUU', 'Wozu brauchst du das?', 'Bunu ne için istiyorsun?', ''],
  ['der Arm', 'kol', 'deer ARM', 'Mein Arm tut weh.', 'Kolum ağrıyor.', '💪'],
  ['der Chef', 'şef, patron', 'deer ŞEF', 'Mein Chef ist nett.', 'Patronum nazik.', ''],
  ['die Information', 'bilgi', 'dii in-for-ma-TSYOON', 'Ich brauche mehr Informationen.', 'Daha fazla bilgiye ihtiyacım var.', ''],
  ['erledigen', 'halletmek', 'er-LEE-di-gen', 'Ich erledige das heute.', 'Bunu bugün hallederim.', ''],
  ['hoffentlich', 'umarım', 'HO-fent-lih', 'Hoffentlich regnet es nicht.', 'Umarım yağmur yağmaz.', ''],
  ['tanzen', 'dans etmek', 'TAN-tsen', 'Wir tanzen die ganze Nacht.', 'Bütün gece dans ediyoruz.', ''],
  ['ansehen', 'bakmak, izlemek', 'AN-zee-en', 'Sieh dir das an!', 'Şuna bir bak!', ''],
  ['zuhause', 'evde', 'tsu-HAU-ze', 'Ich bin zuhause.', 'Evdeyim.', ''],
  ['wunderbar', 'harika', 'VUN-dır-baar', 'Das Wetter ist wunderbar.', 'Hava harika.', ''],
  ['die Reise', 'yolculuk', 'dii RAY-ze', 'Gute Reise!', 'İyi yolculuklar!', '🧳'],
  ['die Dame', 'hanımefendi', 'dii DAA-me', 'Meine Damen und Herren!', 'Bayanlar ve baylar!', ''],
  ['irgendwann', 'bir gün, bir ara', 'İR-gent-van', 'Irgendwann fahre ich nach Wien.', "Bir gün Viyana'ya gideceğim.", ''],
  ['stecken', 'sokmak; bulunmak', 'ŞTE-ken', 'Der Schlüssel steckt in der Tür.', 'Anahtar kapıda takılı.', ''],
  ['jedenfalls', 'her hâlükârda', 'YEE-den-fals', 'Ich komme jedenfalls.', 'Her hâlükârda geliyorum.', ''],
  ['schreien', 'bağırmak', 'ŞRAY-en', 'Warum schreist du?', 'Neden bağırıyorsun?', ''],
  ['rüber', 'karşıya', 'RÜÜ-bır', 'Komm rüber!', 'Buraya gel!', ''],
  ['tschüss', 'hoşça kal', 'ÇÜS', 'Tschüss, bis morgen!', 'Hoşça kal, yarın görüşürüz!', ''],
  ['der Raum', 'oda; alan', 'deer RAUM', 'Der Raum ist hell.', 'Oda aydınlık.', ''],
  ['heiß', 'sıcak', 'HAYS', 'Der Tee ist heiß.', 'Çay sıcak.', ''],
  ['das Foto', 'fotoğraf', 'das FOO-to', 'Mach ein Foto!', 'Bir fotoğraf çek!', '📷'],
  ['kalt', 'soğuk', 'KALT', 'Heute ist es kalt.', 'Bugün hava soğuk.', ''],
  ['irgendetwas', 'herhangi bir şey', 'İR-gent-et-vas', 'Möchtest du irgendetwas trinken?', 'Bir şey içmek ister misin?', ''],
  ['die Weile', 'bir süre', 'dii VAY-le', 'Das dauert eine Weile.', 'Bu biraz sürer.', ''],
  ['bisher', 'şimdiye kadar', 'bis-HEER', 'Bisher ist alles gut.', 'Şimdiye kadar her şey iyi.', ''],
  ['unbedingt', 'mutlaka', 'UN-be-dinkt', 'Du musst unbedingt kommen!', 'Mutlaka gelmelisin!', ''],
  ['der Zug', 'tren', 'deer TSUUK', 'Der Zug kommt pünktlich.', 'Tren zamanında geliyor.', '🚆'],
  ['die Sekunde', 'saniye', 'dii ze-KUN-de', 'Warte eine Sekunde!', 'Bir saniye bekle!', ''],
  ['wofür', 'ne için', 'voo-FÜÜR', 'Wofür ist das?', 'Bu ne için?', ''],
  ['der Beweis', 'kanıt', 'deer be-VAYS', 'Wo ist der Beweis?', 'Kanıt nerede?', ''],
  ['die Seele', 'ruh', 'dii ZEE-le', 'Musik ist gut für die Seele.', 'Müzik ruha iyi gelir.', ''],
  ['schießen', 'ateş etmek; şut atmak', 'Şİİ-sen', 'Er schießt ein Tor.', 'O bir gol atıyor.', ''],
  ['müde', 'yorgun', 'MÜÜ-de', 'Ich bin sehr müde.', 'Çok yorgunum.', ''],
  ['dauern', 'sürmek', 'DAU-ırn', 'Wie lange dauert das?', 'Bu ne kadar sürer?', ''],
  ['der Brief', 'mektup', 'deer BRİİF', 'Ich schreibe einen Brief.', 'Bir mektup yazıyorum.', '✉️'],
  ['bekannt', 'tanınmış, bilinen', 'be-KANT', 'Er ist sehr bekannt.', 'O çok tanınıyor.', ''],
  ['der Unfall', 'kaza', 'deer UN-fal', 'Es gab einen Unfall.', 'Bir kaza oldu.', ''],
  ['dahin', 'oraya', 'da-HİN', 'Wie komme ich dahin?', 'Oraya nasıl giderim?', ''],
  ['die Kontrolle', 'kontrol', 'dii kon-TRO-le', 'Alles unter Kontrolle.', 'Her şey kontrol altında.', ''],
  ['das Beispiel', 'örnek', 'das BAY-şpiil', 'Gib mir ein Beispiel!', 'Bana bir örnek ver!', ''],
  ['dasselbe', 'aynı şey', 'das-ZEL-be', 'Ich nehme dasselbe.', 'Ben de aynısını alıyorum.', ''],
  ['schlagen', 'vurmak', 'ŞLAA-gen', 'Man darf Kinder nicht schlagen.', 'Çocuklara vurulmaz.', ''],
  ['wütend', 'öfkeli', 'VÜÜ-tent', 'Warum bist du so wütend?', 'Neden bu kadar öfkelisin?', ''],
  ['die Weise', 'şekil, tarz', 'dii VAY-ze', 'Auf diese Weise geht es.', 'Bu şekilde oluyor.', ''],
  ['darin', 'onun içinde', 'da-RİN', 'Was ist darin?', 'İçinde ne var?', ''],
  ['die Vorsicht', 'dikkat', 'dii FOOR-ziht', 'Vorsicht, die Treppe!', 'Dikkat, merdiven!', '⚠️'],
  ['zumindest', 'en azından', 'tsu-MİN-dest', 'Zumindest ist es warm.', 'En azından hava sıcak.', ''],
  ['vermissen', 'özlemek', 'fer-Mİ-sen', 'Ich vermisse dich.', 'Seni özlüyorum.', ''],
  ['hübsch', 'güzel, hoş', 'HÜPŞ', 'Das Kleid ist hübsch.', 'Elbise hoş.', ''],
  ['die Verbindung', 'bağlantı', 'dii fer-BİN-dung', 'Die Verbindung ist schlecht.', 'Bağlantı kötü.', ''],
  ['tief', 'derin', 'TİİF', 'Das Wasser ist tief.', 'Su derin.', ''],
  ['die Richtung', 'yön', 'dii RİH-tung', 'In welche Richtung gehen wir?', 'Hangi yöne gidiyoruz?', '🧭'],
  ['die Lage', 'durum; konum', 'dii LAA-ge', 'Die Lage ist ernst.', 'Durum ciddi.', ''],
  ['sowieso', 'zaten', 'zoo-vii-ZOO', 'Ich wollte sowieso gehen.', 'Zaten gitmek istiyordum.', ''],
  ['die Kraft', 'güç', 'dii KRAFT', 'Ich habe keine Kraft mehr.', 'Hiç gücüm kalmadı.', ''],
  ['normal', 'normal', 'nor-MAAL', 'Das ist ganz normal.', 'Bu tamamen normal.', ''],
  ['die Ehre', 'onur', 'dii EE-re', 'Es ist mir eine Ehre.', 'Bu benim için bir onur.', ''],
  ['das Geschenk', 'hediye', 'das ge-ŞENK', 'Das Geschenk ist für dich.', 'Hediye senin için.', '🎁'],
  ['die Bar', 'bar', 'dii BAAR', 'Wir treffen uns in der Bar.', 'Barda buluşuyoruz.', '🍸'],
  ['die Tasche', 'çanta; cep', 'dii TA-şe', 'Meine Tasche ist schwer.', 'Çantam ağır.', '👜'],
  ['stehlen', 'çalmak (hırsızlık)', 'ŞTEE-len', 'Jemand hat mein Fahrrad gestohlen.', 'Biri bisikletimi çaldı.', ''],
  ['der Hunger', 'açlık', 'deer HUN-gır', 'Ich habe Hunger.', 'Açım.', ''],
  ['lügen', 'yalan söylemek', 'LÜÜ-gen', 'Du lügst!', 'Yalan söylüyorsun!', ''],
  ['die Beziehung', 'ilişki', 'dii be-TSİİ-ung', 'Wir haben eine gute Beziehung.', 'İyi bir ilişkimiz var.', ''],
  ['der Preis', 'fiyat; ödül', 'deer PRAYS', 'Der Preis ist gut.', 'Fiyat iyi.', '🏷️'],
  ['der Witz', 'şaka, fıkra', 'deer VİTS', 'Erzähl mir einen Witz!', 'Bana bir fıkra anlat!', ''],
  ['die Liste', 'liste', 'dii LİS-te', 'Ich schreibe eine Liste.', 'Bir liste yazıyorum.', '📝'],
  ['der Geist', 'ruh; hayalet', 'deer GAYST', 'Im Haus wohnt ein Geist.', 'Evde bir hayalet yaşıyor.', '👻'],
  ['neben', 'yanında', 'NEE-ben', 'Setz dich neben mich!', 'Yanıma otur!', ''],
  ['die Firma', 'şirket', 'dii FİR-ma', 'Die Firma ist groß.', 'Şirket büyük.', ''],
  ['süß', 'tatlı', 'ZÜÜS', 'Der Kuchen ist süß.', 'Kek tatlı.', ''],
  ['der Rücken', 'sırt', 'deer RÜ-ken', 'Mein Rücken tut weh.', 'Sırtım ağrıyor.', ''],
  ['schrecklich', 'korkunç', 'ŞREK-lih', 'Das Wetter ist schrecklich.', 'Hava korkunç.', ''],
  ['verliebt', 'âşık', 'fer-LİİPT', 'Ich bin verliebt.', 'Âşığım.', ''],
  ['öffnen', 'açmak', 'ÖF-nen', 'Öffne bitte die Tür!', 'Kapıyı açar mısın lütfen!', ''],
  ['das Boot', 'tekne', 'das BOOT', 'Wir fahren mit dem Boot.', 'Tekneyle gidiyoruz.', '⛵'],
  ['seltsam', 'garip', 'ZELT-zaam', 'Das ist seltsam.', 'Bu garip.', ''],
  ['verstecken', 'saklamak', 'fer-ŞTE-ken', 'Das Kind versteckt sich.', 'Çocuk saklanıyor.', ''],
  ['fürchten', 'korkmak', 'FÜRH-ten', 'Ich fürchte mich vor Hunden.', 'Köpeklerden korkarım.', ''],
  ['erwischen', 'yakalamak', 'er-Vİ-şen', 'Ich habe den Bus erwischt.', 'Otobüse yetiştim.', ''],
  ['die Tante', 'teyze, hala', 'dii TAN-te', 'Meine Tante backt Kuchen.', 'Teyzem kek yapıyor.', ''],
  ['das Pferd', 'at', 'das PFEERT', 'Das Pferd ist schnell.', 'At hızlı.', '🐎'],
  ['das Wunder', 'mucize', 'das VUN-dır', 'Das ist ein Wunder!', 'Bu bir mucize!', ''],
  ['sauer', 'ekşi; kızgın', 'ZAU-ır', 'Die Zitrone ist sauer.', 'Limon ekşi.', ''],
  ['vermutlich', 'muhtemelen', 'fer-MUUT-lih', 'Er ist vermutlich krank.', 'Muhtemelen hasta.', ''],
  ['nah', 'yakın', 'NAA', 'Der Bahnhof ist nah.', 'İstasyon yakın.', ''],
  ['aussehen', 'görünmek', 'AUS-zee-en', 'Du siehst gut aus.', 'İyi görünüyorsun.', ''],
  ['links', 'solda, sola', 'LİNKS', 'Gehen Sie nach links!', 'Sola gidin!', '⬅️'],
  ['beschützen', 'korumak', 'be-ŞÜT-sen', 'Der Hund beschützt das Haus.', 'Köpek evi koruyor.', ''],
  ['geboren', 'doğmuş', 'ge-BOO-ren', 'Ich bin in Ankara geboren.', "Ankara'da doğdum.", ''],
  ['erreichen', 'ulaşmak, yetişmek', 'er-RAY-hen', 'Ich erreiche den Zug.', 'Trene yetişiyorum.', ''],
  ['der Punkt', 'nokta', 'deer PUNKT', 'Das ist ein wichtiger Punkt.', 'Bu önemli bir nokta.', ''],
  ['die Kirche', 'kilise', 'dii KİR-he', 'Die Kirche ist alt.', 'Kilise eski.', '⛪'],
  ['verraten', 'ele vermek; söylemek', 'fer-RAA-ten', 'Verrat es niemandem!', 'Kimseye söyleme!', ''],
  ['selber', 'kendisi', 'ZEL-bır', 'Das mache ich selber.', 'Onu kendim yaparım.', ''],
  ['der Befehl', 'emir', 'deer be-FEEL', 'Das ist ein Befehl!', 'Bu bir emir!', ''],
  ['der Geburtstag', 'doğum günü', 'deer ge-BUURTS-taak', 'Alles Gute zum Geburtstag!', 'Doğum günün kutlu olsun!', '🎂'],
  ['die Haut', 'cilt, deri', 'dii HAUT', 'Die Sonne ist schlecht für die Haut.', 'Güneş cilde kötü gelir.', ''],
  ['wetten', 'bahse girmek', 'VE-ten', 'Ich wette, er kommt nicht.', 'Bahse girerim gelmez.', ''],
  ['reich', 'zengin', 'RAYH', 'Er ist sehr reich.', 'O çok zengin.', ''],
  ['schwören', 'yemin etmek', 'ŞVÖÖ-ren', 'Ich schwöre, das ist wahr!', 'Yemin ederim, bu doğru!', ''],
  ['traurig', 'üzgün', 'TRAU-rih', 'Warum bist du traurig?', 'Neden üzgünsün?', ''],
  ['der Anruf', 'telefon çağrısı', 'deer AN-ruuf', 'Danke für den Anruf!', 'Aradığın için teşekkürler!', ''],
  ['der Frieden', 'barış', 'deer FRİİ-den', 'Wir wollen Frieden.', 'Barış istiyoruz.', '🕊️'],
  ['die Karte', 'kart; harita; bilet', 'dii KAR-te', 'Hast du eine Karte von Berlin?', 'Berlin haritan var mı?', '🗺️'],
  ['diesmal', 'bu sefer', 'DİİS-maal', 'Diesmal zahle ich.', 'Bu sefer ben ödüyorum.', ''],
  ['schade', 'yazık', 'ŞAA-de', 'Das ist schade!', 'Ne yazık!', ''],
  ['persönlich', 'kişisel; bizzat', 'per-ZÖÖN-lih', 'Ich kenne ihn persönlich.', 'Onu bizzat tanıyorum.', ''],
  ['die Sonne', 'güneş', 'dii ZO-ne', 'Die Sonne scheint.', 'Güneş parlıyor.', '☀️'],
  ['lieb', 'sevimli, tatlı', 'LİİP', 'Das ist lieb von dir.', 'Bu çok tatlı.', ''],
  ['nämlich', 'çünkü, yani', 'NEEM-lih', 'Ich bleibe hier, ich bin nämlich krank.', 'Burada kalıyorum, çünkü hastayım.', ''],
  ['der Professor', 'profesör', 'deer pro-FE-sor', 'Der Professor ist streng.', 'Profesör sert.', ''],
  ['das Gericht', 'mahkeme; yemek', 'das ge-RİHT', 'Das Gericht ist lecker.', 'Yemek lezzetli.', ''],
  ['die Nase', 'burun', 'dii NAA-ze', 'Meine Nase ist kalt.', 'Burnum soğuk.', '👃'],
  ['ewig', 'sonsuz, ebedi', 'EE-vih', 'Ich warte ewig auf dich.', 'Seni sonsuza kadar beklerim.', ''],
  ['singen', 'şarkı söylemek', 'ZİN-gen', 'Sie singt sehr schön.', 'O çok güzel şarkı söylüyor.', ''],
  ['die Bank', 'banka; bank', 'dii BANK', 'Die Bank ist geschlossen.', 'Banka kapalı.', '🏦'],
  ['beschäftigt', 'meşgul', 'be-ŞEF-tihkt', 'Ich bin gerade beschäftigt.', 'Şu an meşgulüm.', ''],
  ['der Computer', 'bilgisayar', 'deer kom-PYUU-tır', 'Mein Computer ist langsam.', 'Bilgisayarım yavaş.', '💻'],
  ['Weihnachten', 'Noel', 'VAY-nah-ten', 'Frohe Weihnachten!', 'Mutlu Noeller!', '🎄'],
  ['offensichtlich', 'belli ki', 'O-fen-ziht-lih', 'Er ist offensichtlich müde.', 'Belli ki yorgun.', ''],
  ['der Fuß', 'ayak', 'deer FUUS', 'Ich gehe zu Fuß.', 'Yürüyerek gidiyorum.', '🦶'],
  ['die Show', 'gösteri', 'dii ŞOO', 'Die Show beginnt um acht.', 'Gösteri sekizde başlıyor.', ''],
  ['die Überraschung', 'sürpriz', 'dii üü-bır-RA-şung', 'Was für eine Überraschung!', 'Ne sürpriz!', ''],
  ['das Geheimnis', 'sır', 'das ge-HAYM-nis', 'Das ist ein Geheimnis.', 'Bu bir sır.', '🤫'],
  ['der Kontakt', 'temas, iletişim', 'deer kon-TAKT', 'Wir bleiben in Kontakt.', 'İletişimde kalalım.', ''],
  ['das Gold', 'altın', 'das GOLT', 'Der Ring ist aus Gold.', 'Yüzük altından.', '🥇'],
  ['die Droge', 'uyuşturucu', 'dii DROO-ge', 'Drogen sind gefährlich.', 'Uyuşturucular tehlikelidir.', ''],
  ['die Regierung', 'hükümet', 'dii re-Gİİ-rung', 'Die Regierung ist neu.', 'Hükümet yeni.', ''],
  ['der Wein', 'şarap', 'deer VAYN', 'Ein Glas Wein, bitte.', 'Bir kadeh şarap, lütfen.', '🍷'],
  ['ermorden', 'öldürmek (cinayet)', 'er-MOR-den', 'Der König wurde ermordet.', 'Kral öldürüldü.', ''],
  ['entfernt', 'uzak', 'ent-FERNT', 'Das Dorf ist weit entfernt.', 'Köy çok uzak.', ''],
  ['manch', 'bazı', 'MANH', 'Manche Leute mögen keinen Kaffee.', 'Bazı insanlar kahve sevmez.', ''],
  ['die Lust', 'istek, heves', 'dii LUST', 'Ich habe Lust auf Pizza.', 'Canım pizza istiyor.', ''],
  ['wunderschön', 'çok güzel', 'VUN-dır-şöön', 'Der See ist wunderschön.', 'Göl çok güzel.', ''],
  ['witzig', 'esprili, komik', 'VİT-sih', 'Du bist witzig.', 'Sen esprilisin.', ''],
  ['zerstören', 'yok etmek', 'tser-ŞTÖÖ-ren', 'Der Sturm zerstört das Haus.', 'Fırtına evi yıkıyor.', ''],
  ['übrigens', 'bu arada', 'ÜÜ-bri-gens', 'Übrigens, ich heiße Tom.', 'Bu arada, benim adım Tom.', ''],
  ['der Wille', 'irade, istek', 'deer Vİ-le', 'Wo ein Wille ist, ist ein Weg.', 'İsteyen yol bulur.', ''],
  ['das Heim', 'yuva, ev', 'das HAYM', 'Das ist unser Heim.', 'Burası bizim yuvamız.', ''],
  ['der Blick', 'bakış; manzara', 'deer BLİK', 'Der Blick ist toll.', 'Manzara harika.', ''],
  ['der Besuch', 'ziyaret', 'deer be-ZUUH', 'Wir haben Besuch.', 'Misafirimiz var.', ''],
  ['das Haar', 'saç', 'das HAAR', 'Sie hat lange Haare.', 'Onun uzun saçları var.', '💇'],
  ['antworten', 'cevap vermek', 'ANT-vor-ten', 'Bitte antworte mir!', 'Lütfen bana cevap ver!', ''],
  ['der Präsident', 'başkan', 'deer pre-zi-DENT', 'Der Präsident spricht heute.', 'Başkan bugün konuşuyor.', ''],
  ['die Hoffnung', 'umut', 'dii HOF-nung', 'Es gibt noch Hoffnung.', 'Hâlâ umut var.', ''],
  ['rechts', 'sağda, sağa', 'REHTS', 'Die Bank ist rechts.', 'Banka sağda.', '➡️'],
  ['interessant', 'ilginç', 'in-te-re-SANT', 'Das Buch ist interessant.', 'Kitap ilginç.', ''],
  ['entscheiden', 'karar vermek', 'ent-ŞAY-den', 'Du musst dich entscheiden.', 'Karar vermelisin.', ''],
  ['miteinander', 'birbiriyle', 'mit-ay-NAN-dır', 'Wir reden miteinander.', 'Birbirimizle konuşuyoruz.', ''],
  ['indem', '-arak', 'in-DEEM', 'Ich lerne, indem ich lese.', 'Okuyarak öğreniyorum.', ''],
  ['wohnen', 'oturmak, ikamet etmek', 'VOO-nen', 'Wo wohnst du?', 'Nerede oturuyorsun?', ''],
  ['weder', 'ne... ne', 'VEE-dır', 'Ich trinke weder Tee noch Kaffee.', 'Ne çay ne kahve içerim.', ''],
  ['die Möglichkeit', 'imkân', 'dii MÖÖK-lih-kayt', 'Es gibt eine Möglichkeit.', 'Bir imkân var.', ''],
  ['kaputt', 'bozuk', 'ka-PUT', 'Die Waschmaschine ist kaputt.', 'Çamaşır makinesi bozuk.', ''],
  ['das Flugzeug', 'uçak', 'das FLUUK-tsoyk', 'Das Flugzeug landet.', 'Uçak iniyor.', '✈️'],
  ['die Vergangenheit', 'geçmiş', 'dii fer-GAN-gen-hayt', 'Das ist Vergangenheit.', 'Bu geçmişte kaldı.', ''],
  ['zweite', 'ikinci', 'TSVAY-te', 'Das ist mein zweites Auto.', 'Bu benim ikinci arabam.', ''],
  ['der Tee', 'çay', 'deer TEE', 'Möchtest du Tee?', 'Çay ister misin?', '🍵'],
  ['entweder', 'ya... ya da', 'ent-VEE-dır', 'Entweder heute oder morgen.', 'Ya bugün ya da yarın.', ''],
  ['aufhalten', 'durdurmak', 'AUF-hal-ten', 'Niemand kann mich aufhalten.', 'Kimse beni durduramaz.', ''],
  ['überrascht', 'şaşırmış', 'üü-bır-RAŞT', 'Ich bin überrascht.', 'Şaşırdım.', ''],
  ['sauber', 'temiz', 'ZAU-bır', 'Die Küche ist sauber.', 'Mutfak temiz.', ''],
  ['der Schlag', 'darbe, vuruş', 'deer ŞLAAK', 'Das war ein harter Schlag.', 'Bu ağır bir darbeydi.', ''],
  ['nervös', 'gergin', 'ner-VÖÖS', 'Ich bin nervös.', 'Gerginim.', ''],
  ['die Gesellschaft', 'toplum; şirket', 'dii ge-ZEL-şaft', 'Die Gesellschaft ändert sich.', 'Toplum değişiyor.', ''],
  ['schuldig', 'suçlu; borçlu', 'ŞUL-dih', 'Er ist nicht schuldig.', 'O suçlu değil.', ''],
  ['der Hals', 'boyun; boğaz', 'deer HALS', 'Mein Hals tut weh.', 'Boğazım ağrıyor.', ''],
  ['schützen', 'korumak', 'ŞÜT-sen', 'Die Jacke schützt vor Regen.', 'Ceket yağmurdan korur.', ''],
  ['besuchen', 'ziyaret etmek', 'be-ZUU-hen', 'Ich besuche meine Oma.', 'Büyükannemi ziyaret ediyorum.', ''],
  ['überleben', 'hayatta kalmak', 'üü-bır-LEE-ben', 'Er hat den Unfall überlebt.', 'Kazadan sağ kurtuldu.', ''],
  ['erhalten', 'almak, elde etmek', 'er-HAL-ten', 'Ich habe deinen Brief erhalten.', 'Mektubunu aldım.', ''],
  ['teilen', 'paylaşmak', 'TAY-len', 'Wir teilen die Pizza.', 'Pizzayı paylaşıyoruz.', ''],
  ['das Gebäude', 'bina', 'das ge-BOY-de', 'Das Gebäude ist sehr hoch.', 'Bina çok yüksek.', '🏢'],
  ['das Schicksal', 'kader', 'das ŞİK-zaal', 'Das ist Schicksal.', 'Bu kader.', ''],
  ['das Zeichen', 'işaret', 'das TSAY-hen', 'Das ist ein gutes Zeichen.', 'Bu iyiye işaret.', ''],
  ['der Richter', 'hâkim', 'deer RİH-tır', 'Der Richter ist fair.', 'Hâkim adil.', ''],
  ['besorgt', 'endişeli', 'be-ZORKT', 'Ich bin besorgt.', 'Endişeliyim.', ''],
  ['die Küche', 'mutfak', 'dii KÜ-he', 'Mama ist in der Küche.', 'Annem mutfakta.', '🍳'],
  ['das Vergnügen', 'zevk', 'das fer-GNÜÜ-gen', 'Es ist mir ein Vergnügen.', 'Benim için bir zevk.', ''],
  ['das Volk', 'halk, millet', 'das FOLK', 'Das Volk will Frieden.', 'Halk barış istiyor.', ''],
  ['herausfinden', 'ortaya çıkarmak', 'he-RAUS-fin-den', 'Ich finde es heraus.', 'Bunu öğreneceğim.', ''],
  ['die Königin', 'kraliçe', 'dii KÖÖ-ni-gin', 'Die Königin ist alt.', 'Kraliçe yaşlı.', '👸'],
  ['der Soldat', 'asker', 'deer zol-DAAT', 'Der Soldat ist jung.', 'Asker genç.', '💂'],
  ['feiern', 'kutlamak', 'FAY-ırn', 'Wir feiern heute.', 'Bugün kutluyoruz.', ''],
  ['die Situation', 'durum', 'dii zi-tu-a-TSYOON', 'Die Situation ist schwierig.', 'Durum zor.', ''],
  ['allerdings', 'ancak; tabii', 'A-lır-dings', 'Das ist allerdings teuer.', 'Ancak bu pahalı.', ''],
  ['soweit', '-dığı kadarıyla', 'zo-VAYT', 'Soweit ich weiß, ist er da.', 'Bildiğim kadarıyla orada.', ''],
  ['der Rat', 'tavsiye', 'deer RAAT', 'Ich brauche deinen Rat.', 'Tavsiyene ihtiyacım var.', ''],
  ['worauf', 'neye', 'voo-RAUF', 'Worauf wartest du?', 'Neyi bekliyorsun?', ''],
  ['die Kamera', 'kamera', 'dii KA-me-ra', 'Die Kamera ist neu.', 'Kamera yeni.', '📹'],
  ['die Achtung', 'dikkat; saygı', 'dii AH-tung', 'Achtung, der Zug kommt!', 'Dikkat, tren geliyor!', ''],
  ['der Schuh', 'ayakkabı', 'deer ŞUU', 'Die Schuhe sind neu.', 'Ayakkabılar yeni.', '👟'],
  ['der Glückwunsch', 'tebrik', 'deer GLÜK-vunş', 'Herzlichen Glückwunsch!', 'Tebrikler!', ''],
  ['statt', 'yerine', 'ŞTAT', 'Ich nehme Tee statt Kaffee.', 'Kahve yerine çay alıyorum.', ''],
  ['übernehmen', 'üstlenmek', 'üü-bır-NEE-men', 'Ich übernehme das.', 'Bunu ben üstleniyorum.', ''],
  ['die Gegend', 'bölge, çevre', 'dii GEE-gent', 'Die Gegend ist ruhig.', 'Bölge sakin.', ''],
  ['der Wald', 'orman', 'deer VALT', 'Wir gehen im Wald spazieren.', 'Ormanda yürüyüş yapıyoruz.', '🌲'],
  ['erkennen', 'tanımak, fark etmek', 'er-KE-nen', 'Ich erkenne dich nicht.', 'Seni tanıyamıyorum.', ''],
  ['das Glas', 'bardak; cam', 'das GLAAS', 'Ein Glas Wasser, bitte.', 'Bir bardak su, lütfen.', '🥛'],
  ['verantwortlich', 'sorumlu', 'fer-ANT-vort-lih', 'Wer ist verantwortlich?', 'Kim sorumlu?', ''],
  ['herein', 'içeri', 'he-RAYN', 'Herein, bitte!', 'Buyrun, girin!', ''],
  ['das Kleid', 'elbise', 'das KLAYT', 'Das Kleid ist blau.', 'Elbise mavi.', '👗'],
  ['das Gesetz', 'kanun', 'das ge-ZETS', 'Das ist gegen das Gesetz.', 'Bu kanuna aykırı.', ''],
  ['das Abendessen', 'akşam yemeği', 'das AA-bent-e-sen', 'Das Abendessen ist fertig.', 'Akşam yemeği hazır.', '🍲'],
  ['gemeinsam', 'birlikte, ortak', 'ge-MAYN-zaam', 'Wir kochen gemeinsam.', 'Birlikte yemek yapıyoruz.', ''],
  ['der Schritt', 'adım', 'deer ŞRİT', 'Das ist der erste Schritt.', 'Bu ilk adım.', ''],
  ['gucken', 'bakmak', 'GU-ken', 'Guck mal!', 'Bak hele!', ''],
  ['beginnen', 'başlamak', 'be-Gİ-nen', 'Der Kurs beginnt heute.', 'Kurs bugün başlıyor.', ''],
  ['ungefähr', 'yaklaşık', 'UN-ge-feer', 'Ich bin ungefähr dreißig.', 'Yaklaşık otuz yaşındayım.', ''],
  ['die Aufgabe', 'görev; ödev', 'dii AUF-gaa-be', 'Das ist deine Aufgabe.', 'Bu senin görevin.', ''],
  ['neun', 'dokuz', 'NOYN', 'Der Kurs beginnt um neun.', 'Kurs dokuzda başlıyor.', ''],
  ['furchtbar', 'berbat', 'FURHT-baar', 'Das Essen ist furchtbar.', 'Yemek berbat.', ''],
  ['drinnen', 'içeride', 'DRİ-nen', 'Die Kinder spielen drinnen.', 'Çocuklar içeride oynuyor.', ''],
  ['zuvor', 'daha önce', 'tsu-FOOR', 'Ich war nie zuvor hier.', 'Daha önce hiç burada bulunmadım.', ''],
  ['freuen', 'sevinmek (sich)', 'FROY-en', 'Ich freue mich sehr!', 'Çok seviniyorum!', ''],
  ['übrig', 'artan, kalan', 'ÜÜ-brih', 'Ist noch Kuchen übrig?', 'Hiç kek kaldı mı?', ''],
  ['die Spur', 'iz', 'dii ŞPUUR', 'Es gibt keine Spur.', 'Hiçbir iz yok.', ''],
  ['melden', 'bildirmek', 'MEL-den', 'Ich melde mich morgen.', 'Yarın sana haber veririm.', ''],
  ['werfen', 'atmak, fırlatmak', 'VER-fen', 'Wirf den Ball!', 'Topu at!', ''],
  ['hängen', 'asılı olmak; asmak', 'HEN-gen', 'Das Bild hängt an der Wand.', 'Resim duvarda asılı.', ''],
  ['die Freude', 'sevinç', 'dii FROY-de', 'Das macht mir Freude.', 'Bu beni sevindiriyor.', ''],
  ['der Ehemann', 'koca, eş', 'deer EE-e-man', 'Ihr Ehemann ist Koch.', 'Kocası aşçı.', ''],
  ['erschießen', 'vurarak öldürmek', 'er-Şİİ-sen', 'Der Jäger erschießt den Wolf.', 'Avcı kurdu vuruyor.', ''],
  ['verzeihen', 'affetmek', 'fer-TSAY-en', 'Bitte verzeih mir!', 'Lütfen beni affet!', ''],
  ['das Schwein', 'domuz', 'das ŞVAYN', 'Das Schwein ist rosa.', 'Domuz pembe.', '🐖'],
  ['das Monster', 'canavar', 'das MONS-tır', 'Das Kind hat Angst vor Monstern.', 'Çocuk canavarlardan korkuyor.', '👹'],
  ['die Mission', 'görev', 'dii mi-SYOON', 'Die Mission ist gefährlich.', 'Görev tehlikeli.', ''],
  ['vorne', 'önde', 'FOR-ne', 'Ich sitze vorne.', 'Önde oturuyorum.', ''],
  ['stopp', 'dur', 'ŞTOP', 'Stopp! Nicht weiter!', 'Dur! Daha ileri gitme!', ''],
  ['übel', 'kötü; midesi bulanık', 'ÜÜ-bel', 'Mir ist übel.', 'Midem bulanıyor.', ''],
  ['die Adresse', 'adres', 'dii a-DRE-se', 'Wie ist deine Adresse?', 'Adresin ne?', ''],
  ['der Unsinn', 'saçmalık', 'deer UN-zin', 'Das ist Unsinn!', 'Bu saçmalık!', ''],
  ['das Messer', 'bıçak', 'das ME-sır', 'Das Messer ist scharf.', 'Bıçak keskin.', '🔪'],
  ['gesund', 'sağlıklı', 'ge-ZUNT', 'Obst ist gesund.', 'Meyve sağlıklıdır.', ''],
  ['der Respekt', 'saygı', 'deer res-PEKT', 'Ich habe Respekt vor dir.', 'Sana saygım var.', ''],
  ['leisten', 'başarmak (sich: kendine almak)', 'LAYS-ten', 'Ich kann mir das nicht leisten.', 'Buna gücüm yetmez.', ''],
  ['davor', 'ondan önce; önünde', 'da-FOOR', 'Ich habe Angst davor.', 'Bundan korkuyorum.', ''],
  ['der Ball', 'top', 'deer BAL', 'Der Hund spielt mit dem Ball.', 'Köpek topla oynuyor.', '⚽'],
  ['mitnehmen', 'yanına almak', 'MİT-nee-men', 'Nimm einen Schirm mit!', 'Yanına bir şemsiye al!', ''],
  ['die Schwierigkeit', 'zorluk', 'dii ŞVİİ-rih-kayt', 'Wir haben Schwierigkeiten.', 'Zorluklarımız var.', ''],
  ['die Hälfte', 'yarı', 'dii HELF-te', 'Ich esse die Hälfte.', 'Yarısını yiyorum.', ''],
  ['der Planet', 'gezegen', 'deer pla-NEET', 'Die Erde ist ein Planet.', 'Dünya bir gezegendir.', '🪐'],
  ['schwanger', 'hamile', 'ŞVAN-gır', 'Meine Frau ist schwanger.', 'Karım hamile.', ''],
  ['die Gruppe', 'grup', 'dii GRU-pe', 'Wir lernen in einer Gruppe.', 'Grup hâlinde öğreniyoruz.', ''],
  ['verhaften', 'tutuklamak', 'fer-HAF-ten', 'Die Polizei verhaftet den Dieb.', 'Polis hırsızı tutukluyor.', ''],
  ['irgendein', 'herhangi bir', 'İR-gent-ayn', 'Gib mir irgendein Buch!', 'Bana herhangi bir kitap ver!', ''],
  ['drehen', 'döndürmek, çevirmek', 'DREE-en', 'Dreh dich um!', 'Arkanı dön!', ''],
  ['das Eis', 'dondurma; buz', 'das AYS', 'Ich esse ein Eis.', 'Bir dondurma yiyorum.', '🍦'],
  ['danken', 'teşekkür etmek', 'DAN-ken', 'Ich danke dir.', 'Sana teşekkür ederim.', ''],
  ['der Erfolg', 'başarı', 'deer er-FOLK', 'Viel Erfolg!', 'Başarılar!', ''],
  ['zufrieden', 'memnun', 'tsu-FRİİ-den', 'Ich bin zufrieden.', 'Memnunum.', ''],
  ['schließen', 'kapatmak', 'ŞLİİ-sen', 'Schließ bitte die Tür!', 'Lütfen kapıyı kapat!', ''],
  ['besorgen', 'temin etmek', 'be-ZOR-gen', 'Ich besorge die Tickets.', 'Biletleri ben alırım.', ''],
  ['das Wochenende', 'hafta sonu', 'das VO-hen-en-de', 'Schönes Wochenende!', 'İyi hafta sonları!', ''],
  ['worüber', 'ne hakkında', 'voo-RÜÜ-bır', 'Worüber sprichst du?', 'Ne hakkında konuşuyorsun?', ''],
  ['das Bein', 'bacak', 'das BAYN', 'Mein Bein tut weh.', 'Bacağım ağrıyor.', '🦵'],
  ['das Verbrechen', 'suç', 'das fer-BRE-hen', 'Das ist ein Verbrechen.', 'Bu bir suç.', ''],
  ['der Bericht', 'rapor', 'deer be-RİHT', 'Der Bericht ist fertig.', 'Rapor hazır.', ''],
  ['nachts', 'geceleyin', 'NAHTS', 'Nachts ist es ruhig.', 'Geceleri ortalık sakin.', ''],
  ['die Prinzessin', 'prenses', 'dii prin-TSE-sin', 'Die Prinzessin wohnt im Schloss.', 'Prenses şatoda yaşıyor.', '👸'],
  ['der Schmerz', 'acı, ağrı', 'deer ŞMERTS', 'Ich habe Schmerzen.', 'Ağrım var.', ''],
  ['klingeln', 'çalmak (zil)', 'KLİN-geln', 'Das Telefon klingelt.', 'Telefon çalıyor.', ''],
  ['die Position', 'pozisyon', 'dii po-zi-TSYOON', 'Das ist eine gute Position.', 'Bu iyi bir pozisyon.', ''],
  ['fernsehen', 'televizyon izlemek', 'FERN-zee-en', 'Wir sehen abends fern.', 'Akşamları televizyon izliyoruz.', ''],
  ['schließlich', 'sonunda', 'ŞLİİS-lih', 'Schließlich hat er ja gesagt.', 'Sonunda evet dedi.', ''],
  ['gefangen', 'esir, tutsak', 'ge-FAN-gen', 'Der Vogel ist gefangen.', 'Kuş yakalandı.', ''],
  ['schwierig', 'zor', 'ŞVİİ-rih', 'Deutsch ist nicht so schwierig.', 'Almanca o kadar zor değil.', ''],
  ['das Angebot', 'teklif; indirim', 'das AN-ge-boot', 'Das ist ein gutes Angebot.', 'Bu iyi bir teklif.', ''],
  ['der Ring', 'yüzük', 'deer RİNG', 'Der Ring ist schön.', 'Yüzük güzel.', '💍'],
  ['rennen', 'koşmak', 'RE-nen', 'Die Kinder rennen im Park.', 'Çocuklar parkta koşuyor.', ''],
  ['das Lied', 'şarkı', 'das LİİT', 'Das Lied ist schön.', 'Şarkı güzel.', '🎶'],
  ['das Ei', 'yumurta', 'das AY', 'Ich esse ein Ei.', 'Bir yumurta yiyorum.', '🥚'],
  ['fantastisch', 'harika', 'fan-TAS-tiş', 'Das Konzert war fantastisch.', 'Konser harikaydı.', ''],
  ['die Insel', 'ada', 'dii İN-zel', 'Die Insel ist klein.', 'Ada küçük.', '🏝️'],
  ['daher', 'bu yüzden', 'DAA-heer', 'Ich bin krank, daher bleibe ich hier.', 'Hastayım, bu yüzden burada kalıyorum.', ''],
  ['zufällig', 'tesadüfen', 'TSUU-fe-lih', 'Ich habe ihn zufällig getroffen.', 'Onunla tesadüfen karşılaştım.', ''],
  ['das Dorf', 'köy', 'das DORF', 'Das Dorf ist klein.', 'Köy küçük.', '🏘️'],
  ['bewegen', 'hareket ettirmek', 'be-VEE-gen', 'Beweg dich nicht!', 'Kıpırdama!', ''],
  ['der Feind', 'düşman', 'deer FAYNT', 'Er ist nicht dein Feind.', 'O senin düşmanın değil.', ''],
  ['einverstanden', 'razı, anlaştık', 'AYN-fer-ştan-den', 'Einverstanden!', 'Anlaştık!', ''],
  ['bauen', 'inşa etmek', 'BAU-en', 'Wir bauen ein Haus.', 'Bir ev yapıyoruz.', ''],
  ['halb', 'yarım', 'HALP', 'Es ist halb acht.', 'Saat yedi buçuk.', ''],
  ['verpassen', 'kaçırmak', 'fer-PA-sen', 'Ich habe den Bus verpasst.', 'Otobüsü kaçırdım.', ''],
  ['leise', 'sessiz, alçak sesle', 'LAY-ze', 'Sprich bitte leise!', 'Lütfen alçak sesle konuş!', ''],
  ['das Unternehmen', 'şirket', 'das un-tır-NEE-men', 'Das Unternehmen ist groß.', 'Şirket büyük.', ''],
  ['kosten', 'tutmak (fiyat)', 'KOS-ten', 'Was kostet das?', 'Bu ne kadar?', ''],
  ['das Tier', 'hayvan', 'das TİİR', 'Ich mag Tiere.', 'Hayvanları severim.', '🐾'],
  ['die Freiheit', 'özgürlük', 'dii FRAY-hayt', 'Freiheit ist wichtig.', 'Özgürlük önemlidir.', ''],
  ['unterhalten', 'sohbet etmek (sich)', 'un-tır-HAL-ten', 'Wir unterhalten uns gern.', 'Sohbet etmeyi severiz.', ''],
  ['einladen', 'davet etmek', 'AYN-laa-den', 'Ich lade dich ein.', 'Seni davet ediyorum.', ''],
  ['der Schaden', 'hasar, zarar', 'deer ŞAA-den', 'Der Schaden ist groß.', 'Hasar büyük.', ''],
  ['beenden', 'bitirmek', 'be-EN-den', 'Ich beende die Arbeit.', 'İşi bitiriyorum.', ''],
  ['lächerlich', 'gülünç', 'LE-hır-lih', 'Das ist lächerlich!', 'Bu gülünç!', ''],
  ['der Park', 'park', 'deer PARK', 'Wir gehen in den Park.', 'Parka gidiyoruz.', '🌳'],
  ['die Energie', 'enerji', 'dii e-ner-Gİİ', 'Ich habe keine Energie.', 'Hiç enerjim yok.', ''],
  ['das Fleisch', 'et', 'das FLAYŞ', 'Ich esse kein Fleisch.', 'Et yemem.', '🥩'],
  ['bestehen', 'geçmek (sınav); oluşmak', 'be-ŞTEE-en', 'Ich habe die Prüfung bestanden.', 'Sınavı geçtim.', ''],
  ['die Zeitung', 'gazete', 'dii TSAY-tung', 'Ich lese die Zeitung.', 'Gazete okuyorum.', '📰'],
  ['betrunken', 'sarhoş', 'be-TRUN-ken', 'Er ist betrunken.', 'O sarhoş.', ''],
  ['der Patient', 'hasta', 'deer pa-TSYENT', 'Der Patient wartet.', 'Hasta bekliyor.', ''],
  ['das Gespräch', 'konuşma, sohbet', 'das ge-ŞPREEH', 'Das war ein gutes Gespräch.', 'İyi bir sohbetti.', ''],
  ['leiden', 'acı çekmek', 'LAY-den', 'Er leidet sehr.', 'O çok acı çekiyor.', ''],
  ['das Taxi', 'taksi', 'das TAK-si', 'Ich nehme ein Taxi.', 'Taksiye biniyorum.', '🚕'],
  ['der See', 'göl', 'deer ZEE', 'Wir schwimmen im See.', 'Gölde yüzüyoruz.', '🏞️'],
  ['der Unterschied', 'fark', 'deer UN-tır-şiit', 'Wo ist der Unterschied?', 'Fark nerede?', ''],
  ['der Wind', 'rüzgâr', 'deer VİNT', 'Der Wind ist stark.', 'Rüzgâr kuvvetli.', '🌬️'],
  ['die Wand', 'duvar', 'dii VANT', 'Die Wand ist weiß.', 'Duvar beyaz.', '🧱'],
  ['der Bus', 'otobüs', 'deer BUS', 'Der Bus kommt gleich.', 'Otobüs birazdan geliyor.', '🚌'],
  ['der Angriff', 'saldırı', 'deer AN-grif', 'Der Angriff kam plötzlich.', 'Saldırı aniden geldi.', ''],
  ['das Loch', 'delik', 'das LOH', 'Die Socke hat ein Loch.', 'Çorabın deliği var.', '🕳️'],
  ['das Interesse', 'ilgi', 'das in-te-RE-se', 'Ich habe kein Interesse.', 'İlgilenmiyorum.', ''],
  ['treten', 'tekmelemek; basmak', 'TREE-ten', 'Tritt nicht auf die Blumen!', 'Çiçeklere basma!', ''],
  ['der Polizist', 'polis memuru', 'deer po-li-TSİST', 'Der Polizist hilft mir.', 'Polis bana yardım ediyor.', '👮'],
  ['die Blume', 'çiçek', 'dii BLUU-me', 'Die Blume riecht gut.', 'Çiçek güzel kokuyor.', '🌸'],
  ['die Neuigkeit', 'haber, yenilik', 'dii NOY-ih-kayt', 'Ich habe eine Neuigkeit.', 'Bir haberim var.', ''],
  ['die Flasche', 'şişe', 'dii FLA-şe', 'Eine Flasche Wasser, bitte.', 'Bir şişe su, lütfen.', '🍾'],
  ['der Schuss', 'atış; el silah sesi', 'deer ŞUS', 'Ich höre einen Schuss.', 'Bir silah sesi duyuyorum.', ''],
  ['das Meer', 'deniz', 'das MEER', 'Wir fahren ans Meer.', 'Denize gidiyoruz.', '🌊'],
  ['die Maschine', 'makine', 'dii ma-Şİİ-ne', 'Die Maschine ist laut.', 'Makine gürültülü.', '⚙️'],
  ['verbringen', 'geçirmek (zaman)', 'fer-BRİN-gen', 'Wir verbringen den Urlaub in Spanien.', "Tatili İspanya'da geçiriyoruz.", ''],
  ['blöd', 'aptal, saçma', 'BLÖÖT', 'Das ist eine blöde Idee.', 'Bu saçma bir fikir.', ''],
  ['das Frühstück', 'kahvaltı', 'das FRÜÜ-ştük', 'Das Frühstück ist fertig.', 'Kahvaltı hazır.', '🥐'],
  ['der Meter', 'metre', 'deer MEE-tır', 'Das Haus ist zehn Meter hoch.', 'Ev on metre yüksekliğinde.', '📏'],
  ['aufpassen', 'dikkat etmek', 'AUF-pa-sen', 'Pass auf!', 'Dikkat et!', ''],
  ['der Engel', 'melek', 'deer EN-gel', 'Du bist ein Engel.', 'Sen bir meleksin.', '👼'],
  ['offenbar', 'görünüşe göre', 'O-fen-baar', 'Er ist offenbar krank.', 'Görünüşe göre hasta.', ''],
  ['die Gelegenheit', 'fırsat', 'dii ge-LEE-gen-hayt', 'Das ist eine gute Gelegenheit.', 'Bu iyi bir fırsat.', ''],
  ['die Lüge', 'yalan', 'dii LÜÜ-ge', 'Das ist eine Lüge!', 'Bu bir yalan!', ''],
  ['das Ohr', 'kulak', 'das OOR', 'Mein Ohr tut weh.', 'Kulağım ağrıyor.', '👂'],
  ['beeilen', 'acele etmek (sich)', 'be-AY-len', 'Beeil dich!', 'Acele et!', ''],
  ['brechen', 'kırmak', 'BRE-hen', 'Er hat sich das Bein gebrochen.', 'Bacağını kırdı.', ''],
  ['der Zeitpunkt', 'an, zaman noktası', 'deer TSAYT-punkt', 'Jetzt ist ein guter Zeitpunkt.', 'Şimdi iyi bir zaman.', ''],
  ['die Ecke', 'köşe', 'dii E-ke', 'Das Café ist an der Ecke.', 'Kafe köşede.', ''],
  ['die Brücke', 'köprü', 'dii BRÜ-ke', 'Die Brücke ist alt.', 'Köprü eski.', '🌉'],
  ['der Druck', 'basınç; baskı', 'deer DRUK', 'Ich stehe unter Druck.', 'Baskı altındayım.', ''],
  ['mitbringen', 'yanında getirmek', 'MİT-brin-gen', 'Bring bitte Brot mit!', 'Lütfen ekmek getir!', ''],
  ['der Haufen', 'yığın', 'deer HAU-fen', 'Ich habe einen Haufen Arbeit.', 'Bir yığın işim var.', ''],
  ['die Oma', 'büyükanne, nine', 'dii OO-ma', 'Meine Oma backt Kuchen.', 'Ninem kek yapıyor.', '👵'],
  ['der Auftrag', 'görev; sipariş', 'deer AUF-traak', 'Ich habe einen Auftrag.', 'Bir görevim var.', ''],
  ['leer', 'boş', 'LEER', 'Das Glas ist leer.', 'Bardak boş.', ''],
  ['entkommen', 'kaçmak, kurtulmak', 'ent-KO-men', 'Der Dieb ist entkommen.', 'Hırsız kaçtı.', ''],
  ['weiß', 'beyaz', 'VAYS', 'Der Schnee ist weiß.', 'Kar beyazdır.', ''],
  ['die Lösung', 'çözüm', 'dii LÖÖ-zung', 'Wir finden eine Lösung.', 'Bir çözüm buluruz.', ''],
  ['die Pause', 'mola', 'dii PAU-ze', 'Machen wir eine Pause!', 'Mola verelim!', ''],
  ['der Keller', 'bodrum', 'deer KE-lır', 'Der Wein ist im Keller.', 'Şarap bodrumda.', ''],
  ['weinen', 'ağlamak', 'VAY-nen', 'Das Baby weint.', 'Bebek ağlıyor.', ''],
  ['nutzen', 'kullanmak, yararlanmak', 'NUT-sen', 'Nutze deine Zeit!', 'Vaktini iyi kullan!', ''],
  ['die Verantwortung', 'sorumluluk', 'dii fer-ANT-vor-tung', 'Ich übernehme die Verantwortung.', 'Sorumluluğu üstleniyorum.', ''],
  ['das Schloss', 'şato; kilit', 'das ŞLOS', 'Das Schloss ist alt.', 'Şato eski.', '🏰'],
  ['der Hut', 'şapka', 'deer HUUT', 'Er trägt einen Hut.', 'O şapka takıyor.', '🎩'],
  ['lächeln', 'gülümsemek', 'LE-heln', 'Sie lächelt immer.', 'O hep gülümsüyor.', ''],
  ['mitkommen', 'birlikte gelmek', 'MİT-ko-men', 'Kommst du mit?', 'Sen de geliyor musun?', ''],
  ['vorhin', 'az önce', 'foor-HİN', 'Er war vorhin hier.', 'Az önce buradaydı.', ''],
  ['die Fahrt', 'yolculuk', 'dii FAART', 'Die Fahrt dauert zwei Stunden.', 'Yolculuk iki saat sürüyor.', ''],
  ['ernsthaft', 'ciddi olarak', 'ERNST-haft', 'Meinst du das ernsthaft?', 'Bunu ciddi mi söylüyorsun?', ''],
  ['die Bombe', 'bomba', 'dii BOM-be', 'Die Bombe ist gefährlich.', 'Bomba tehlikeli.', '💣'],
  ['die Operation', 'ameliyat; operasyon', 'dii o-pe-ra-TSYOON', 'Die Operation war gut.', 'Ameliyat iyi geçti.', ''],
  ['das Dach', 'çatı', 'das DAH', 'Die Katze sitzt auf dem Dach.', 'Kedi çatıda oturuyor.', ''],
  ['die Folge', 'sonuç; bölüm', 'dii FOL-ge', 'Ich sehe die neue Folge.', 'Yeni bölümü izliyorum.', ''],
  ['dankbar', 'minnettar', 'DANK-baar', 'Ich bin dir sehr dankbar.', 'Sana çok minnettarım.', ''],
  ['das Gehirn', 'beyin', 'das ge-HİRN', 'Das Gehirn braucht Schlaf.', 'Beynin uykuya ihtiyacı var.', '🧠'],
  ['der Mut', 'cesaret', 'deer MUUT', 'Du hast viel Mut.', 'Çok cesaretlisin.', ''],
  ['heilig', 'kutsal', 'HAY-lih', 'Der Ort ist heilig.', 'Bu yer kutsal.', ''],
  ['das System', 'sistem', 'das züs-TEEM', 'Das System ist neu.', 'Sistem yeni.', ''],
  ['der Wahnsinn', 'çılgınlık', 'deer VAAN-zin', 'Das ist Wahnsinn!', 'Bu çılgınlık!', ''],
  ['das Thema', 'konu', 'das TEE-ma', 'Das ist ein wichtiges Thema.', 'Bu önemli bir konu.', ''],
  ['der Urlaub', 'tatil', 'deer UUR-laup', 'Wir machen Urlaub am Meer.', 'Deniz kenarında tatil yapıyoruz.', '🏖️'],
  ['steigen', 'çıkmak, binmek', 'ŞTAY-gen', 'Steig ins Auto!', 'Arabaya bin!', ''],
  ['vorwärts', 'ileri', 'FOOR-verts', 'Geh vorwärts!', 'İleri git!', ''],
  ['überprüfen', 'kontrol etmek', 'üü-bır-PRÜÜ-fen', 'Ich überprüfe die Daten.', 'Verileri kontrol ediyorum.', ''],
  ['der Baum', 'ağaç', 'deer BAUM', 'Der Baum ist hoch.', 'Ağaç yüksek.', '🌳'],
  ['anscheinend', 'görünüşe göre', 'AN-şay-nent', 'Anscheinend ist er weg.', 'Görünüşe göre gitmiş.', ''],
  ['der Lehrer', 'öğretmen', 'deer LEE-rır', 'Der Lehrer erklärt die Regel.', 'Öğretmen kuralı açıklıyor.', '🧑‍🏫'],
  ['der Nachmittag', 'öğleden sonra', 'deer NAAH-mi-taak', 'Am Nachmittag gehe ich schwimmen.', 'Öğleden sonra yüzmeye gidiyorum.', ''],
  ['das Risiko', 'risk', 'das Rİİ-zi-ko', 'Das Risiko ist groß.', 'Risk büyük.', ''],
  ['der Held', 'kahraman', 'deer HELT', 'Du bist mein Held.', 'Sen benim kahramanımsın.', '🦸'],
  ['prima', 'harika', 'PRİİ-ma', 'Das ist prima!', 'Bu harika!', ''],
  ['die Gewalt', 'şiddet', 'dii ge-VALT', 'Gewalt ist keine Lösung.', 'Şiddet çözüm değildir.', ''],
  ['nachdenken', 'düşünmek (üzerine)', 'NAAH-den-ken', 'Ich denke darüber nach.', 'Bunun üzerine düşünüyorum.', ''],
  ['das Tor', 'kapı (büyük); gol', 'das TOOR', 'Er schießt ein Tor.', 'O bir gol atıyor.', '🥅'],
  ['die Erfahrung', 'tecrübe', 'dii er-FAA-rung', 'Ich habe viel Erfahrung.', 'Çok tecrübem var.', ''],
  ['jagen', 'avlamak, kovalamak', 'YAA-gen', 'Die Katze jagt die Maus.', 'Kedi fareyi kovalıyor.', ''],
  ['die Katze', 'kedi', 'dii KAT-se', 'Die Katze schläft.', 'Kedi uyuyor.', '🐈'],
  ['die Runde', 'tur', 'dii RUN-de', 'Ich laufe eine Runde.', 'Bir tur koşuyorum.', ''],
  ['deutsch', 'Alman; Almanca', 'DOYÇ', 'Ich lerne Deutsch.', 'Almanca öğreniyorum.', ''],
  ['dringend', 'acil', 'DRİN-gent', 'Es ist dringend!', 'Acil!', ''],
  ['der Großvater', 'büyükbaba, dede', 'deer GROOS-faa-tır', 'Mein Großvater ist achtzig.', 'Dedem seksen yaşında.', '👴'],
  ['der Sommer', 'yaz', 'deer ZO-mır', 'Im Sommer ist es heiß.', 'Yazın hava sıcaktır.', ''],
  ['hinterlassen', 'bırakmak (geride)', 'hin-tır-LA-sen', 'Er hat eine Nachricht hinterlassen.', 'O bir mesaj bıraktı.', ''],
  ['das Gewissen', 'vicdan', 'das ge-Vİ-sen', 'Ich habe ein schlechtes Gewissen.', 'Vicdanım rahat değil.', ''],
  ['der Kunde', 'müşteri', 'deer KUN-de', 'Der Kunde ist König.', 'Müşteri her zaman haklıdır.', ''],
  ['der Zeuge', 'tanık', 'deer TSOY-ge', 'Der Zeuge sagt die Wahrheit.', 'Tanık doğruyu söylüyor.', ''],
  ['planen', 'planlamak', 'PLAA-nen', 'Wir planen eine Reise.', 'Bir yolculuk planlıyoruz.', ''],
  ['stören', 'rahatsız etmek', 'ŞTÖÖ-ren', 'Störe ich?', 'Rahatsız ediyor muyum?', ''],
  ['der Stein', 'taş', 'deer ŞTAYN', 'Der Stein ist schwer.', 'Taş ağır.', '🪨'],
  ['atmen', 'nefes almak', 'AAT-men', 'Atme tief ein!', 'Derin nefes al!', ''],
  ['die Hose', 'pantolon', 'dii HOO-ze', 'Die Hose ist zu lang.', 'Pantolon çok uzun.', '👖'],
  ['das Restaurant', 'restoran', 'das res-to-RAN', 'Wir essen im Restaurant.', 'Restoranda yemek yiyoruz.', '🍴'],
  ['die Natur', 'doğa', 'dii na-TUUR', 'Ich liebe die Natur.', 'Doğayı seviyorum.', '🌿'],
  ['der Streit', 'kavga, tartışma', 'deer ŞTRAYT', 'Wir haben Streit.', 'Kavgalıyız.', ''],
  ['küssen', 'öpmek', 'KÜ-sen', 'Er küsst seine Frau.', 'O karısını öpüyor.', ''],
  ['längst', 'çoktan', 'LENGST', 'Das weiß ich längst.', 'Bunu çoktan biliyorum.', ''],
  ['erlauben', 'izin vermek', 'er-LAU-ben', 'Das ist nicht erlaubt.', 'Buna izin yok.', ''],
  ['schmecken', 'tadı olmak', 'ŞME-ken', 'Das schmeckt gut!', 'Bunun tadı güzel!', ''],
  ['die Kugel', 'top; kurşun', 'dii KUU-gel', 'Zwei Kugeln Eis, bitte.', 'İki top dondurma, lütfen.', ''],
  ['normalerweise', 'normalde', 'nor-MAA-lır-vay-ze', 'Normalerweise stehe ich um sieben auf.', 'Normalde yedide kalkarım.', ''],
  ['schwarz', 'siyah', 'ŞVARTS', 'Die Katze ist schwarz.', 'Kedi siyah.', '']
];
