// En sık 1000 Fransızca kelime (lemma), sıklık sırasıyla.
// Kaynak: FrequencyWords (Hermit Dave), OpenSubtitles 2018 — https://github.com/hermitdave/FrequencyWords — CC BY-SA 4.0.
// Bu liste o kaynaktan türetilmiştir (lemmatize edildi, Türkçe anlam/okunuş/örnek eklendi) ve CC BY-SA 4.0 lisansıyla paylaşılır.
// Biçim: [kelime, Türkçesi, okunuş, örnek cümle, örneğin Türkçesi, emoji]
window.FREQ = window.FREQ || {};
window.FREQ.fr = [
  ['de', '-den, -in (edat)', 'DÖ', "C'est le chien de Marie.", "Bu Marie'nin köpeği.", ''],
  ['je', 'ben', 'JÖ', 'Je suis turc.', "Ben Türk'üm.", ''],
  ['être', 'olmak', 'ETR', "Je suis content d'être ici.", 'Burada olduğuma memnunum.', ''],
  ['pas', 'değil (ne … pas)', 'PA', 'Je ne sais pas.', 'Bilmiyorum.', ''],
  ['le', 'belirli tanımlık (la, les)', 'LÖ', 'Le café est chaud.', 'Kahve sıcak.', ''],
  ['que', 'ki; ne', 'KÖ', 'Je pense que tu as raison.', 'Bence haklısın.', ''],
  ['vous', 'siz', 'VU', 'Vous parlez français ?', 'Fransızca konuşuyor musunuz?', ''],
  ['tu', 'sen', 'TÜ', 'Tu es où ?', 'Neredesin?', ''],
  ['un', 'bir (une: dişil)', 'ÖÑ', "J'ai un frère.", 'Bir erkek kardeşim var.', ''],
  ['ce', 'bu, şu', 'SÖ', 'Ce livre est bon.', 'Bu kitap iyi.', ''],
  ['à', '-e, -de (edat)', 'A', 'Je vais à Paris.', "Paris'e gidiyorum.", ''],
  ['et', 've', 'E', 'Toi et moi.', 'Sen ve ben.', ''],
  ['il', 'o (eril)', 'İL', 'Il est grand.', 'O uzun boylu.', ''],
  ['avoir', 'sahip olmak', 'a-VUAR', "J'ai deux enfants.", 'İki çocuğum var.', ''],
  ['ne', 'olumsuzluk (ne … pas)', 'NÖ', 'Je ne comprends pas.', 'Anlamıyorum.', ''],
  ['en', '-de, ile; ondan', 'AÑ', "J'habite en France.", "Fransa'da yaşıyorum.", ''],
  ['on', 'biz, insanlar (genel özne)', 'OÑ', 'On y va ?', 'Gidelim mi?', ''],
  ['ça', 'bu, şu (günlük dil)', 'SA', 'Ça va bien.', 'İyi gidiyor.', ''],
  ['qui', 'kim; ki (-en)', 'Kİ', 'Qui est là ?', 'Orada kim var?', ''],
  ['pour', 'için', 'PUR', "C'est pour toi.", 'Bu senin için.', ''],
  ['mais', 'ama', 'ME', "Il est tard, mais j'ai faim.", 'Geç oldu ama açım.', ''],
  ['dans', 'içinde, -de', 'DAÑ', 'Le chat est dans la maison.', 'Kedi evin içinde.', ''],
  ['nous', 'biz', 'NU', 'Nous sommes amis.', 'Biz arkadaşız.', ''],
  ['elle', 'o (dişil)', 'EL', 'Elle est médecin.', 'O doktor.', ''],
  ['me', 'beni, bana', 'MÖ', 'Tu me comprends ?', 'Beni anlıyor musun?', ''],
  ['bien', 'iyi, güzelce', 'BYEÑ', 'Je vais bien.', 'İyiyim.', ''],
  ['si', 'eğer; öyle, çok', 'Sİ', 'Si tu veux, on part.', 'İstersen gidelim.', ''],
  ['y', 'orada, oraya', 'İ', "J'y vais demain.", 'Yarın oraya gidiyorum.', ''],
  ['non', 'hayır', 'NOÑ', 'Non, merci.', 'Hayır, teşekkürler.', ''],
  ['te', 'seni, sana', 'TÖ', 'Je te vois.', 'Seni görüyorum.', ''],
  ['avec', 'ile, birlikte', 'a-VEK', 'Je viens avec toi.', 'Seninle geliyorum.', ''],
  ['tout', 'her şey; bütün', 'TU', 'Tout va bien.', 'Her şey yolunda.', ''],
  ['plus', 'daha; artık (ne … plus)', 'PLÜ', "Je n'ai plus faim.", 'Artık aç değilim.', ''],
  ['mon', 'benim (ma, mes)', 'MOÑ', 'Mon père est là.', 'Babam burada.', ''],
  ['faire', 'yapmak', 'FER', "Qu'est-ce que tu fais ?", 'Ne yapıyorsun?', ''],
  ['moi', 'ben, beni (vurgulu)', 'MUA', "C'est moi.", 'Benim.', ''],
  ['se', 'kendini (dönüşlü)', 'SÖ', 'Il se lève tôt.', 'Erken kalkar.', ''],
  ['oui', 'evet', 'Uİ', 'Oui, bien sûr.', 'Evet, tabii ki.', ''],
  ['aller', 'gitmek', 'a-LE', 'Je vais au marché.', 'Pazara gidiyorum.', ''],
  ['sur', 'üstünde', 'SÜR', 'Le livre est sur la table.', 'Kitap masanın üstünde.', ''],
  ['quoi', 'ne', 'KUA', 'Tu fais quoi ?', 'Ne yapıyorsun?', ''],
  ['comme', 'gibi; olarak', 'KOM', 'Il parle comme son père.', 'Babası gibi konuşuyor.', ''],
  ['savoir', 'bilmek', 'sa-VUAR', 'Je sais nager.', 'Yüzmeyi biliyorum.', ''],
  ['vouloir', 'istemek', 'vu-LUAR', 'Je veux un café.', 'Bir kahve istiyorum.', ''],
  ['ici', 'burada, buraya', 'i-Sİ', 'Viens ici !', 'Buraya gel!', ''],
  ['toi', 'sen, seni (vurgulu)', 'TUA', 'Et toi ?', 'Ya sen?', ''],
  ['dire', 'söylemek, demek', 'DİR', "Qu'est-ce que tu dis ?", 'Ne diyorsun?', ''],
  ['lui', 'ona; o (vurgulu eril)', 'LÜİ', 'Je lui parle.', 'Onunla konuşuyorum.', ''],
  ['votre', 'sizin (vos)', 'VOTR', "Votre nom, s'il vous plaît ?", 'Adınız, lütfen?', ''],
  ['pourquoi', 'neden', 'pur-KUA', 'Pourquoi tu pleures ?', 'Neden ağlıyorsun?', ''],
  ['où', 'nerede, nereye', 'U', 'Où est la gare ?', 'Gar nerede?', ''],
  ['là', 'orada; burada', 'LA', 'Je suis là.', 'Buradayım.', ''],
  ['rien', 'hiçbir şey', 'RYEÑ', 'Je ne vois rien.', 'Hiçbir şey görmüyorum.', ''],
  ['quand', 'ne zaman; -dığında', 'KAÑ', 'Tu arrives quand ?', 'Ne zaman geliyorsun?', ''],
  ['pouvoir', '-ebilmek', 'pu-VUAR', 'Je peux entrer ?', 'Girebilir miyim?', ''],
  ['son', 'onun (sa, ses)', 'SOÑ', 'Son frère est gentil.', 'Onun kardeşi nazik.', ''],
  ['alors', 'o zaman, öyleyse', 'a-LOR', 'Alors, on mange ?', 'O zaman yiyelim mi?', ''],
  ['ton', 'senin (ta, tes)', 'TOÑ', "C'est ton sac ?", 'Bu senin çantan mı?', ''],
  ['comment', 'nasıl', 'ko-MAÑ', "Comment tu t'appelles ?", 'Adın ne?', ''],
  ['par', 'tarafından; -den', 'PAR', 'Je passe par Lyon.', "Lyon'dan geçiyorum.", ''],
  ['ou', 'veya, ya da', 'U', 'Thé ou café ?', 'Çay mı, kahve mi?', ''],
  ['la chose', 'şey', 'la ŞOZ', "C'est une bonne chose.", 'Bu iyi bir şey.', ''],
  ['bon', 'iyi; lezzetli', 'BOÑ', 'Ce gâteau est bon.', 'Bu pasta lezzetli.', ''],
  ['merci', 'teşekkürler', 'mer-Sİ', 'Merci beaucoup !', 'Çok teşekkürler!', ''],
  ['juste', 'sadece; adil', 'JÜST', 'Juste un peu.', 'Sadece biraz.', ''],
  ['très', 'çok', 'TRE', 'Il fait très chaud.', 'Hava çok sıcak.', ''],
  ['jamais', 'asla, hiç', 'ja-ME', "Je ne bois jamais d'alcool.", 'Asla alkol içmem.', ''],
  ['aussi', 'de, da; ayrıca', 'o-Sİ', 'Moi aussi.', 'Ben de.', ''],
  ['vraiment', 'gerçekten', 'vre-MAÑ', "C'est vraiment beau.", 'Gerçekten güzel.', ''],
  ['voir', 'görmek', 'VUAR', 'Je vois la mer.', 'Denizi görüyorum.', ''],
  ['même', 'aynı; bile', 'MEM', 'On a le même âge.', 'Aynı yaştayız.', ''],
  ['maintenant', 'şimdi', 'meñt-NAÑ', 'Je pars maintenant.', 'Şimdi çıkıyorum.', ''],
  ['deux', 'iki', 'DÖ', "J'ai deux chats.", 'İki kedim var.', ''],
  ['autre', 'başka, diğer', 'OTR', 'Un autre café ?', 'Bir kahve daha?', ''],
  ['peu', 'az (un peu: biraz)', 'PÖ', 'Je parle un peu français.', 'Biraz Fransızca konuşuyorum.', ''],
  ['le temps', 'zaman; hava', 'lö TAÑ', "Je n'ai pas le temps.", 'Vaktim yok.', ''],
  ['quelque', 'bazı, birkaç', 'KELK', "J'ai quelques amis ici.", 'Burada birkaç arkadaşım var.', ''],
  ['toujours', 'her zaman; hâlâ', 'tu-JUR', 'Il est toujours en retard.', 'Hep geç kalır.', ''],
  ['encore', 'yine; hâlâ', 'añ-KOR', 'Encore une fois !', 'Bir kez daha!', ''],
  ['notre', 'bizim (nos)', 'NOTR', 'Notre maison est petite.', 'Evimiz küçük.', ''],
  ['le besoin', 'ihtiyaç', 'lö bö-ZUEÑ', "J'ai besoin d'aide.", 'Yardıma ihtiyacım var.', ''],
  ["l'accord (m.)", "anlaşma (d'accord: tamam)", 'la-KOR', "D'accord, on y va.", 'Tamam, gidelim.', ''],
  ['falloir', 'gerekmek', 'fa-LUAR', 'Il faut partir.', 'Gitmek gerekiyor.', ''],
  ['devoir', 'zorunda olmak, -meli', 'dö-VUAR', 'Je dois travailler.', 'Çalışmam lazım.', ''],
  ['la vie', 'hayat', 'la Vİ', 'La vie est belle.', 'Hayat güzel.', ''],
  ['peut-être', 'belki', 'pö-TETR', 'Peut-être demain.', 'Belki yarın.', ''],
  ['la fois', 'kez, defa', 'la FUA', 'Je nage une fois par semaine.', 'Haftada bir kez yüzerim.', ''],
  ['donc', 'yani, bu yüzden', 'DOÑK', 'Je pense, donc je suis.', 'Düşünüyorum, öyleyse varım.', ''],
  ['sans', '-sız, olmadan', 'SAÑ', 'Un café sans sucre.', 'Şekersiz bir kahve.', ''],
  ['le monde', 'dünya; insanlar', 'lö MOÑD', 'Tout le monde est là.', 'Herkes burada.', '🌍'],
  ['parce que', 'çünkü', 'pars-KÖ', "Je mange parce que j'ai faim.", 'Aç olduğum için yiyorum.', ''],
  ['avant', 'önce', 'a-VAÑ', 'Lave-toi les mains avant.', 'Önce ellerini yıka.', ''],
  ['sûr', 'emin', 'SÜR', 'Tu es sûr ?', 'Emin misin?', ''],
  ['trop', 'fazla, çok', 'TRO', "C'est trop cher.", 'Bu çok pahalı.', ''],
  ["quelqu'un", 'biri', 'kel-KÖÑ', "Il y a quelqu'un ?", 'Kimse var mı?', ''],
  ['parler', 'konuşmak', 'par-LE', 'Tu parles anglais ?', 'İngilizce konuşuyor musun?', ''],
  ['personne', 'kimse; kişi', 'per-SON', "Il n'y a personne.", 'Kimse yok.', ''],
  ['le père', 'baba', 'lö PER', 'Mon père est grand.', 'Babam uzun boylu.', '👨'],
  ['croire', 'inanmak, sanmak', 'KRUAR', 'Je te crois.', 'Sana inanıyorum.', ''],
  ['après', 'sonra', 'a-PRE', 'On se voit après le travail.', 'İşten sonra görüşürüz.', ''],
  ['le dieu', 'tanrı', 'lö DYÖ', 'Mon Dieu !', 'Aman Tanrım!', ''],
  ['penser', 'düşünmek', 'pañ-SE', 'Je pense à toi.', 'Seni düşünüyorum.', ''],
  ['aimer', 'sevmek', 'e-ME', "J'aime le chocolat.", 'Çikolatayı severim.', ''],
  ['leur', 'onların; onlara', 'LÖR', "C'est leur maison.", 'Bu onların evi.', ''],
  ["l'homme (m.)", 'adam; insan', 'LOM', 'Cet homme est mon voisin.', 'Bu adam benim komşum.', '👨'],
  ['venir', 'gelmek', 'vö-NİR', 'Tu viens avec nous ?', 'Bizimle geliyor musun?', ''],
  ['vrai', 'doğru, gerçek', 'VRE', "C'est vrai ?", 'Doğru mu?', ''],
  ['la femme', 'kadın; eş', 'la FAM', 'Cette femme est ma sœur.', 'Bu kadın benim kız kardeşim.', '👩'],
  ["l'an (m.)", 'yıl, yaş', 'LAÑ', "J'ai trente ans.", 'Otuz yaşındayım.', ''],
  ['mal', 'kötü; ağrı', 'MAL', "J'ai mal à la tête.", 'Başım ağrıyor.', ''],
  ['chez', '-in evinde, -de', 'ŞE', 'Je suis chez moi.', 'Evdeyim.', ''],
  ['déjà', 'zaten, çoktan', 'de-JA', 'Il est déjà parti.', 'O çoktan gitti.', ''],
  ['depuis', '-den beri', 'dö-PÜİ', "J'habite ici depuis un an.", 'Bir yıldır burada yaşıyorum.', ''],
  ['beaucoup', 'çok', 'bo-KU', 'Merci beaucoup !', 'Çok teşekkürler!', ''],
  ['la mort', 'ölüm', 'la MOR', 'Il a peur de la mort.', 'Ölümden korkuyor.', ''],
  ['mieux', 'daha iyi', 'MYÖ', "Je vais mieux aujourd'hui.", 'Bugün daha iyiyim.', ''],
  ['la mère', 'anne', 'la MER', 'Ma mère est gentille.', 'Annem nazik.', '👩'],
  ['la fille', 'kız; kız evlat', 'la FİY', 'Ma fille a cinq ans.', 'Kızım beş yaşında.', '👧'],
  ['les gens (m.)', 'insanlar', 'le JAÑ', 'Les gens sont sympas ici.', 'Burada insanlar cana yakın.', ''],
  ['quel', 'hangi; ne (quelle)', 'KEL', 'Quel âge as-tu ?', 'Kaç yaşındasın?', ''],
  ['désolé', 'üzgün, pardon', 'de-zo-LE', 'Désolé, je suis en retard.', 'Pardon, geç kaldım.', ''],
  ['voilà', 'işte', 'vua-LA', 'Voilà ton café.', 'İşte kahven.', ''],
  ['petit', 'küçük', 'pö-Tİ', "J'ai un petit chien.", 'Küçük bir köpeğim var.', ''],
  ['la maison', 'ev', 'la me-ZOÑ', 'Je rentre à la maison.', 'Eve dönüyorum.', '🏠'],
  ['cela', 'bu, şu', 'sö-LA', 'Cela me plaît.', 'Bu hoşuma gidiyor.', ''],
  ['le soir', 'akşam', 'lö SUAR', 'À ce soir !', 'Bu akşam görüşürüz!', '🌆'],
  ['passer', 'geçmek; uğramak', 'pa-SE', 'Je passe chez toi demain.', 'Yarın sana uğrarım.', ''],
  ['prendre', 'almak', 'PRAÑDR', 'Je prends le bus.', 'Otobüse biniyorum.', ''],
  ['le jour', 'gün', 'lö JUR', 'Il fait beau ce jour-là.', 'O gün hava güzel.', ''],
  ['monsieur', 'bay, beyefendi', 'mö-SYÖ', 'Bonjour, monsieur.', 'Günaydın, beyefendi.', ''],
  ['le nom', 'ad, isim', 'lö NOÑ', 'Quel est ton nom ?', 'Adın ne?', ''],
  ['salut', 'selam', 'sa-LÜ', 'Salut, ça va ?', 'Selam, nasılsın?', ''],
  ["l'argent (m.)", 'para; gümüş', 'lar-JAÑ', "Je n'ai pas d'argent.", 'Param yok.', '💰'],
  ['bonjour', 'merhaba, günaydın', 'boñ-JUR', 'Bonjour, madame !', 'Günaydın, hanımefendi!', ''],
  ['la nuit', 'gece', 'la NÜİ', 'Bonne nuit !', 'İyi geceler!', '🌙'],
  ['la raison', 'sebep; akıl', 'la re-ZOÑ', 'Tu as raison.', 'Haklısın.', ''],
  ['moins', 'daha az', 'MUEÑ', 'Je mange moins de sucre.', 'Daha az şeker yiyorum.', ''],
  ['arriver', 'varmak; olmak', 'a-ri-VE', 'Le train arrive à midi.', 'Tren öğlen varıyor.', ''],
  ['la maman', 'anne (samimi)', 'la ma-MAÑ', "Maman, j'ai faim !", 'Anne, acıktım!', ''],
  ['rester', 'kalmak', 'res-TE', 'Je reste à la maison.', 'Evde kalıyorum.', ''],
  ['le moment', 'an; süre', 'lö mo-MAÑ', "Un moment, s'il vous plaît.", 'Bir dakika, lütfen.', ''],
  ['seul', 'yalnız; tek', 'SÖL', 'Je vis seul.', 'Yalnız yaşıyorum.', ''],
  ['aider', 'yardım etmek', 'e-DE', "Tu peux m'aider ?", 'Bana yardım edebilir misin?', ''],
  ["l'air (m.)", 'hava; görünüş', 'LER', "Tu as l'air fatigué.", 'Yorgun görünüyorsun.', ''],
  ['entre', 'arasında', 'AÑTR', 'Entre toi et moi.', 'Seninle benim aramda.', ''],
  ['le papa', 'baba (samimi)', 'lö pa-PA', 'Papa, viens voir !', 'Baba, gel bak!', ''],
  ['le problème', 'sorun', 'lö pro-BLEM', 'Pas de problème.', 'Sorun yok.', ''],
  ['la peur', 'korku', 'la PÖR', "J'ai peur du noir.", 'Karanlıktan korkarım.', ''],
  ['regarder', 'bakmak, izlemek', 'rö-gar-DE', 'Je regarde la télé.', 'Televizyon izliyorum.', ''],
  ['le gars', 'adam, oğlan (günlük)', 'lö GA', "C'est un gars sympa.", 'Hoş bir adam.', ''],
  ['trouver', 'bulmak', 'tru-VE', 'Je ne trouve pas mes clés.', 'Anahtarlarımı bulamıyorum.', ''],
  ['le fils', 'oğul', 'lö FİS', 'Mon fils a dix ans.', 'Oğlum on yaşında.', '👦'],
  ['attendre', 'beklemek', 'a-TAÑDR', 'Attends-moi ici.', 'Beni burada bekle.', ''],
  ['jusque', "-e kadar (jusqu'à)", 'JÜSK', "Je travaille jusqu'à six heures.", 'Saat altıya kadar çalışıyorum.', ''],
  ['trois', 'üç', 'TRUA', "J'ai trois sœurs.", 'Üç kız kardeşim var.', ''],
  ['assez', 'yeterince; oldukça', 'a-SE', "J'ai assez mangé.", 'Yeterince yedim.', ''],
  ['la famille', 'aile', 'la fa-MİY', 'Ma famille est grande.', 'Ailem kalabalık.', '👪'],
  ['plaire', 'hoşa gitmek', 'PLER', "S'il te plaît, aide-moi.", 'Lütfen bana yardım et.', ''],
  ['le travail', 'iş, çalışma', 'lö tra-VAY', 'Je vais au travail.', 'İşe gidiyorum.', ''],
  ['la tête', 'baş, kafa', 'la TET', "J'ai mal à la tête.", 'Başım ağrıyor.', ''],
  ['appeler', 'aramak, çağırmak', 'a-PLE', "Je t'appelle ce soir.", 'Seni bu akşam ararım.', ''],
  ['partir', 'gitmek, ayrılmak', 'par-TİR', 'Je pars demain.', 'Yarın gidiyorum.', ''],
  ['vite', 'hızlı, çabuk', 'VİT', 'Viens vite !', 'Çabuk gel!', ''],
  ['arrêter', 'durdurmak; bırakmak', 'a-re-TE', "Arrête, s'il te plaît !", 'Dur, lütfen!', ''],
  ['la voiture', 'araba', 'la vua-TÜR', 'Ma voiture est rouge.', 'Arabam kırmızı.', '🚗'],
  ["l'enfant (m./f.)", 'çocuk', 'lañ-FAÑ', "L'enfant dort.", 'Çocuk uyuyor.', '🧒'],
  ['tuer', 'öldürmek', 'tü-E', 'Ce travail me tue !', 'Bu iş beni öldürüyor!', ''],
  ['pendant', 'boyunca, sırasında', 'pañ-DAÑ', 'Je dors pendant le film.', 'Film sırasında uyuyorum.', ''],
  ["l'idée (f.)", 'fikir', 'li-DE', 'Bonne idée !', 'İyi fikir!', '💡'],
  ['la chance', 'şans', 'la ŞAÑS', 'Bonne chance !', 'İyi şanslar!', '🍀'],
  ['la part', 'pay, parça', 'la PAR', 'Une part de gâteau ?', 'Bir dilim pasta?', ''],
  ['grand', 'büyük; uzun', 'GRAÑ', 'Mon frère est grand.', 'Ağabeyim uzun boylu.', ''],
  ["aujourd'hui", 'bugün', 'o-jur-DÜİ', "Aujourd'hui, il fait beau.", 'Bugün hava güzel.', ''],
  ["l'ami (m.)", "arkadaş (l'amie: kadın)", 'la-Mİ', "C'est mon ami Paul.", 'Bu arkadaşım Paul.', ''],
  ['demain', 'yarın', 'dö-MEÑ', 'À demain !', 'Yarın görüşürüz!', ''],
  ['tard', 'geç', 'TAR', 'Il est tard.', 'Saat geç oldu.', ''],
  ['puis', 'sonra, ardından', 'PÜİ', 'Je mange, puis je dors.', 'Yemek yiyorum, sonra uyuyorum.', ''],
  ['le truc', 'şey, zımbırtı (günlük)', 'lö TRÜK', "C'est quoi, ce truc ?", 'Bu şey ne?', ''],
  ['tant', 'o kadar (çok)', 'TAÑ', "Je t'aime tant !", 'Seni o kadar seviyorum ki!', ''],
  ['connaître', 'tanımak, bilmek', 'ko-NETR', 'Tu connais Paris ?', "Paris'i biliyor musun?", ''],
  ['combien', 'kaç, ne kadar', 'koñ-BYEÑ', "C'est combien ?", 'Ne kadar?', ''],
  ['le mec', 'adam, herif (argo)', 'lö MEK', 'Ce mec est drôle.', 'Bu adam komik.', ''],
  ['sentir', 'hissetmek; koklamak', 'sañ-TİR', 'Je me sens bien.', 'Kendimi iyi hissediyorum.', ''],
  ['la porte', 'kapı', 'la PORT', "Ferme la porte, s'il te plaît.", 'Kapıyı kapat, lütfen.', '🚪'],
  ['sortir', 'çıkmak', 'sor-TİR', 'Je sors ce soir.', 'Bu akşam dışarı çıkıyorum.', ''],
  ['super', 'süper, harika', 'sü-PER', "C'est super !", 'Harika!', ''],
  ["l'heure (f.)", 'saat', 'LÖR', 'Quelle heure est-il ?', 'Saat kaç?', '🕐'],
  ['contre', 'karşı', 'KOÑTR', 'Je suis contre cette idée.', 'Bu fikre karşıyım.', ''],
  ['le coup', 'darbe, vuruş', 'lö KU', 'Un coup de téléphone.', 'Bir telefon görüşmesi.', ''],
  ['comprendre', 'anlamak', 'koñ-PRAÑDR', 'Je ne comprends pas.', 'Anlamıyorum.', ''],
  ['entendre', 'duymak', 'añ-TAÑDR', "Tu m'entends ?", 'Beni duyuyor musun?', ''],
  ['ensemble', 'birlikte', 'añ-SAÑBL', 'On mange ensemble ?', 'Birlikte yiyelim mi?', ''],
  ['nouveau', 'yeni (nouvelle)', 'nu-VO', "J'ai un nouveau vélo.", 'Yeni bir bisikletim var.', ''],
  ["l'amour (m.)", 'aşk, sevgi', 'la-MUR', "L'amour est beau.", 'Aşk güzeldir.', '❤️'],
  ['importer', 'önemli olmak; ithal etmek', 'eñ-por-TE', "N'importe quoi !", 'Saçmalık!', ''],
  ['le sang', 'kan', 'lö SAÑ', 'Il a du sang sur la main.', 'Elinde kan var.', '🩸'],
  ['le cas', 'durum, vaka', 'lö KA', "Dans ce cas, d'accord.", 'O durumda, tamam.', ''],
  ['sous', 'altında', 'SU', 'Le chat est sous la table.', 'Kedi masanın altında.', ''],
  ['finir', 'bitirmek', 'fi-NİR', "J'ai fini mon travail.", 'İşimi bitirdim.', ''],
  ['la question', 'soru', 'la kes-TYOÑ', "J'ai une question.", 'Bir sorum var.', '❓'],
  ['la partie', 'bölüm; oyun', 'la par-Tİ', 'On fait une partie de cartes ?', 'Bir el kâğıt oynayalım mı?', ''],
  ["l'histoire (f.)", 'hikâye; tarih', 'lis-TUAR', 'Raconte-moi une histoire.', 'Bana bir hikâye anlat.', ''],
  ["l'aide (f.)", 'yardım', 'LED', 'Merci pour ton aide.', 'Yardımın için teşekkürler.', ''],
  ['dernier', 'son; geçen', 'der-NYE', "C'est le dernier train.", 'Bu son tren.', ''],
  ['demander', 'sormak, istemek', 'dö-mañ-DE', 'Je demande mon chemin.', 'Yolu soruyorum.', ''],
  ['chercher', 'aramak', 'şer-ŞE', 'Je cherche mes lunettes.', 'Gözlüğümü arıyorum.', ''],
  ['le genre', 'tür; cinsiyet', 'lö JAÑR', 'Quel genre de musique ?', 'Ne tür müzik?', ''],
  ['seulement', 'sadece', 'söl-MAÑ', "J'ai seulement dix euros.", 'Sadece on avrom var.', ''],
  ['la police', 'polis', 'la po-LİS', 'Appelle la police !', 'Polisi ara!', '👮'],
  ['car', 'çünkü', 'KAR', 'Je reste, car il pleut.', 'Kalıyorum, çünkü yağmur yağıyor.', ''],
  ['le mois', 'ay (takvim)', 'lö MUA', 'Je pars le mois prochain.', 'Gelecek ay gidiyorum.', ''],
  ['le frère', 'erkek kardeş', 'lö FRER', 'Mon frère habite à Lyon.', "Kardeşim Lyon'da yaşıyor.", ''],
  ['laisser', 'bırakmak', 'le-SE', 'Laisse-moi tranquille !', 'Beni rahat bırak!', ''],
  ['aucun', 'hiçbir', 'o-KÖÑ', "Je n'ai aucune idée.", 'Hiçbir fikrim yok.', ''],
  ['mettre', 'koymak; giymek', 'METR', 'Je mets mon manteau.', 'Paltomu giyiyorum.', ''],
  ['eux', 'onlar (vurgulu eril)', 'Ö', 'Je joue avec eux.', 'Onlarla oynuyorum.', ''],
  ['chaque', 'her', 'ŞAK', 'Je cours chaque matin.', 'Her sabah koşuyorum.', ''],
  ['la ville', 'şehir', 'la VİL', "J'aime cette ville.", 'Bu şehri seviyorum.', '🏙️'],
  ['longtemps', 'uzun süre', 'loñ-TAÑ', "J'attends depuis longtemps.", 'Uzun zamandır bekliyorum.', ''],
  ['le bébé', 'bebek', 'lö be-BE', 'Le bébé dort.', 'Bebek uyuyor.', '👶'],
  ['la place', 'yer; meydan', 'la PLAS', 'Cette place est libre ?', 'Bu yer boş mu?', ''],
  ['revoir', 'tekrar görmek (au revoir)', 'rö-VUAR', 'Au revoir, à demain !', 'Hoşça kal, yarın görüşürüz!', ''],
  ['ni', 'ne … ne', 'Nİ', 'Ni oui ni non.', 'Ne evet ne hayır.', ''],
  ["l'attention (f.)", 'dikkat', 'la-tañ-SYOÑ', 'Attention, la route !', 'Dikkat, yol!', ''],
  ['donner', 'vermek', 'do-NE', 'Donne-moi ton numéro.', 'Bana numaranı ver.', ''],
  ["l'affaire (f.)", 'iş, mesele; dava', 'la-FER', "C'est une bonne affaire.", 'Bu iyi bir iş.', ''],
  ["l'endroit (m.)", 'yer', 'lañ-DRUA', "C'est un bel endroit.", 'Güzel bir yer.', ''],
  ['le corps', 'vücut', 'lö KOR', 'Le sport est bon pour le corps.', 'Spor vücuda iyi gelir.', ''],
  ['la façon', 'biçim, tarz', 'la fa-SOÑ', 'De toute façon, je viens.', 'Her durumda geliyorum.', ''],
  ['voici', 'işte (burada)', 'vua-Sİ', 'Voici mon ami.', 'İşte arkadaşım.', ''],
  ['le train', 'tren', 'lö TREÑ', 'Je prends le train.', 'Trene biniyorum.', '🚆'],
  ['dont', 'ki onun, -dığı', 'DOÑ', 'Le livre dont je parle.', 'Bahsettiğim kitap.', ''],
  ['écouter', 'dinlemek', 'e-ku-TE', "J'écoute de la musique.", 'Müzik dinliyorum.', ''],
  ["l'œil (m.)", 'göz (les yeux)', 'LÖY', 'Elle a les yeux bleus.', 'Onun gözleri mavi.', '👁️'],
  ['le type', 'tip; adam (günlük)', 'lö TİP', "C'est un type bien.", 'İyi bir adam.', ''],
  ['perdre', 'kaybetmek', 'PERDR', "J'ai perdu mon téléphone.", 'Telefonumu kaybettim.', ''],
  ['premier', 'ilk, birinci', 'prö-MYE', "C'est mon premier jour.", 'Bu benim ilk günüm.', ''],
  ['le côté', 'yan, taraf', 'lö ko-TE', 'Assieds-toi à côté de moi.', 'Yanıma otur.', ''],
  ['le point', 'nokta', 'lö PUEÑ', "C'est un bon point.", 'Bu iyi bir nokta.', ''],
  ['tellement', 'o kadar, öylesine', 'tel-MAÑ', 'Il est tellement gentil !', 'O kadar nazik ki!', ''],
  ['la main', 'el', 'la MEÑ', 'Lave-toi les mains.', 'Ellerini yıka.', '✋'],
  ['tenir', 'tutmak', 'tö-NİR', "Tiens, c'est pour toi.", 'Al, bu senin için.', ''],
  ['vieux', 'yaşlı, eski', 'VYÖ', "C'est un vieux livre.", 'Bu eski bir kitap.', ''],
  ['le matin', 'sabah', 'lö ma-TEÑ', 'Je bois du café le matin.', 'Sabahları kahve içerim.', '🌅'],
  ['pardon', 'pardon, affedersiniz', 'par-DOÑ', 'Pardon, où est la gare ?', 'Pardon, gar nerede?', ''],
  ['là-bas', 'orada', 'la-BA', 'Ma maison est là-bas.', 'Evim orada.', ''],
  ['la suite', 'devam; süit', 'la SÜİT', 'Tout de suite !', 'Hemen!', ''],
  ['vers', '-e doğru; sularında', 'VER', "J'arrive vers midi.", 'Öğlene doğru gelirim.', ''],
  ['la minute', 'dakika', 'la mi-NÜT', 'Attends une minute.', 'Bir dakika bekle.', ''],
  ['devant', 'önünde', 'dö-VAÑ', "Je t'attends devant l'école.", 'Seni okulun önünde bekliyorum.', ''],
  ['enfin', 'nihayet; yani', 'añ-FEÑ', 'Enfin, tu es là !', 'Nihayet geldin!', ''],
  ['la cause', 'sebep; dava', 'la KOZ', 'À cause de la pluie.', 'Yağmur yüzünden.', ''],
  ['la chambre', 'oda, yatak odası', 'la ŞAÑBR', 'Ma chambre est petite.', 'Odam küçük.', '🛏️'],
  ['le droit', 'hak; hukuk', 'lö DRUA', 'Tu as le droit de dire non.', 'Hayır demeye hakkın var.', ''],
  ["l'eau (f.)", 'su', 'LO', "Un verre d'eau, s'il vous plaît.", 'Bir bardak su, lütfen.', '💧'],
  ['le compte', 'hesap', 'lö KOÑT', "J'ai un compte en banque.", 'Banka hesabım var.', ''],
  ['la terre', 'dünya; toprak', 'la TER', 'La Terre est ronde.', 'Dünya yuvarlaktır.', '🌍'],
  ['beau', 'güzel, yakışıklı (belle)', 'BO', "Il fait beau aujourd'hui.", 'Bugün hava güzel.', ''],
  ['espérer', 'ummak', 'es-pe-RE', "J'espère que tu vas bien.", 'Umarım iyisindir.', ''],
  ['loin', 'uzak', 'LUEÑ', 'La gare est loin ?', 'Gar uzak mı?', ''],
  ['le mari', 'koca, eş', 'lö ma-Rİ', 'Mon mari est cuisinier.', 'Kocam aşçı.', ''],
  ['la fin', 'son, bitiş', 'la FEÑ', "C'est la fin du film.", 'Filmin sonu bu.', ''],
  ['gros', 'iri, şişman; büyük', 'GRO', "C'est un gros chien.", 'Bu iri bir köpek.', ''],
  ['le boulot', 'iş (günlük)', 'lö bu-LO', 'Je vais au boulot.', 'İşe gidiyorum.', ''],
  ['plutôt', 'daha çok, tercihen', 'plü-TO', 'Je préfère plutôt le thé.', 'Daha çok çayı tercih ederim.', ''],
  ['chéri', 'sevgilim, canım', 'şe-Rİ', 'Bonne nuit, chéri.', 'İyi geceler, canım.', ''],
  ['prêt', 'hazır', 'PRE', 'Tu es prêt ?', 'Hazır mısın?', ''],
  ['le bureau', 'ofis; masa', 'lö bü-RO', 'Je suis au bureau.', 'Ofisteyim.', '🏢'],
  ['mourir', 'ölmek', 'mu-RİR', 'Je meurs de faim !', 'Açlıktan ölüyorum!', ''],
  ['hier', 'dün', 'YER', "Hier, j'étais malade.", 'Dün hastaydım.', ''],
  ['possible', 'mümkün', 'po-SİBL', "C'est possible ?", 'Mümkün mü?', ''],
  ['jouer', 'oynamak; çalmak', 'ju-E', 'Les enfants jouent dehors.', 'Çocuklar dışarıda oynuyor.', ''],
  ['celui', 'o, şu (celle)', 'sö-LÜİ', 'Je veux celui-ci.', 'Bunu istiyorum.', ''],
  ['jeune', 'genç', 'JÖN', 'Elle est très jeune.', 'O çok genç.', ''],
  ['dehors', 'dışarıda', 'dö-OR', 'Il fait froid dehors.', 'Dışarısı soğuk.', ''],
  ['le docteur', 'doktor', 'lö dok-TÖR', 'Je vais chez le docteur.', 'Doktora gidiyorum.', '🩺'],
  ['la confiance', 'güven', 'la koñ-FYAÑS', "J'ai confiance en toi.", 'Sana güveniyorum.', ''],
  ["l'année (f.)", 'yıl', 'la-NE', 'Bonne année !', 'Mutlu yıllar!', ''],
  ['la vérité', 'gerçek, hakikat', 'la ve-ri-TE', 'Dis-moi la vérité.', 'Bana gerçeği söyle.', ''],
  ["l'école (f.)", 'okul', 'le-KOL', "Mon fils va à l'école.", 'Oğlum okula gidiyor.', '🏫'],
  ['le chef', 'şef, patron', 'lö ŞEF', 'Le chef est en réunion.', 'Şef toplantıda.', ''],
  ['le propos', 'söz (à propos: bu arada)', 'lö pro-PO', 'À propos, tu viens ?', 'Bu arada, geliyor musun?', ''],
  ['la semaine', 'hafta', 'la sö-MEN', 'À la semaine prochaine !', 'Haftaya görüşürüz!', ''],
  ['vivre', 'yaşamak', 'VİVR', 'Je vis à Istanbul.', "İstanbul'da yaşıyorum.", ''],
  ['le feu', 'ateş; trafik ışığı', 'lö FÖ', 'Le feu est rouge.', 'Işık kırmızı.', '🔥'],
  ['la journée', 'gün (gün boyu)', 'la jur-NE', 'Bonne journée !', 'İyi günler!', ''],
  ['madame', 'hanımefendi, bayan', 'ma-DAM', 'Merci, madame.', 'Teşekkürler, hanımefendi.', ''],
  ['le téléphone', 'telefon', 'lö te-le-FON', 'Mon téléphone sonne.', 'Telefonum çalıyor.', '📱'],
  ['près', 'yakın', 'PRE', "J'habite près d'ici.", 'Buraya yakın oturuyorum.', ''],
  ['meilleur', 'daha iyi; en iyi', 'me-YÖR', "C'est mon meilleur ami.", 'O benim en iyi arkadaşım.', ''],
  ['dessus', 'üstünde', 'dö-SÜ', 'Le prix est écrit dessus.', 'Fiyat üstünde yazılı.', ''],
  ['prier', 'dua etmek; rica etmek', 'pri-E', 'Je vous en prie.', 'Rica ederim.', ''],
  ["l'équipe (f.)", 'takım, ekip', 'le-KİP', 'Notre équipe a gagné.', 'Takımımız kazandı.', ''],
  ['manger', 'yemek yemek', 'mañ-JE', 'On mange à midi.', 'Öğlen yemek yiyoruz.', ''],
  ['dur', 'sert; zor', 'DÜR', "C'est dur, le français !", 'Fransızca zor!', ''],
  ['la guerre', 'savaş', 'la GER', 'La guerre est finie.', 'Savaş bitti.', ''],
  ['marcher', 'yürümek; çalışmak (alet)', 'mar-ŞE', 'Ça marche !', 'Tamamdır!', ''],
  ['la sécurité', 'güvenlik', 'la se-kü-ri-TE', 'Ta sécurité est importante.', 'Güvenliğin önemli.', ''],
  ['le garçon', 'oğlan, erkek çocuk', 'lö gar-SOÑ', 'Ce garçon est mon fils.', 'Bu oğlan benim oğlum.', '👦'],
  ['essayer', 'denemek', 'e-se-YE', 'Je peux essayer ?', 'Deneyebilir miyim?', ''],
  ['important', 'önemli', 'eñ-por-TAÑ', "C'est très important.", 'Bu çok önemli.', ''],
  ['exactement', 'tam olarak, aynen', 'eg-zak-tö-MAÑ', "C'est exactement ça.", 'Aynen öyle.', ''],
  ['fort', 'güçlü; yüksek sesle', 'FOR', 'Parle plus fort !', 'Daha yüksek sesle konuş!', ''],
  ['presque', 'neredeyse', 'PRESK', "J'ai presque fini.", 'Neredeyse bitirdim.', ''],
  ['plein', 'dolu', 'PLEÑ', 'Le verre est plein.', 'Bardak dolu.', ''],
  ['derrière', 'arkasında', 'de-RYER', 'Le jardin est derrière la maison.', 'Bahçe evin arkasında.', ''],
  ['le mariage', 'evlilik; düğün', 'lö ma-RYAJ', 'Le mariage est en juin.', 'Düğün haziranda.', '💍'],
  ['le parent', 'ebeveyn; akraba', 'lö pa-RAÑ', 'Mes parents habitent à Izmir.', "Annemle babam İzmir'de oturuyor.", ''],
  ['le capitaine', 'kaptan', 'lö ka-pi-TEN', 'Le capitaine est sur le bateau.', 'Kaptan gemide.', ''],
  ['fou', 'deli (folle)', 'FU', 'Tu es fou !', 'Sen delisin!', ''],
  ['tomber', 'düşmek', 'toñ-BE', 'Attention, tu vas tomber !', 'Dikkat, düşeceksin!', ''],
  ['la vue', 'görüş; manzara', 'la VÜ', 'Quelle belle vue !', 'Ne güzel manzara!', ''],
  ['souvenir', 'hatırlamak (se souvenir)', 'su-vö-NİR', 'Tu te souviens de moi ?', 'Beni hatırlıyor musun?', ''],
  ["l'envie (f.)", 'istek, arzu', 'lañ-Vİ', "J'ai envie d'une glace.", 'Canım dondurma istiyor.', ''],
  ['la fête', 'parti, bayram', 'la FET', 'On fait la fête ce soir.', 'Bu akşam parti yapıyoruz.', '🎉'],
  ['le jeu', 'oyun', 'lö JÖ', "C'est un jeu facile.", 'Bu kolay bir oyun.', '🎲'],
  ['génial', 'harika, dahiyane', 'je-NYAL', "C'est génial !", 'Bu harika!', ''],
  ['le pays', 'ülke', 'lö pe-İ', 'La France est un beau pays.', 'Fransa güzel bir ülke.', ''],
  ['garder', 'saklamak, tutmak', 'gar-DE', 'Garde la monnaie.', 'Üstü kalsın.', ''],
  ['le cours', 'ders', 'lö KUR', "J'ai un cours de français.", 'Fransızca dersim var.', ''],
  ['bientôt', 'yakında', 'byeñ-TO', 'À bientôt !', 'Görüşmek üzere!', ''],
  ['le numéro', 'numara', 'lö nü-me-RO', 'Quel est ton numéro ?', 'Numaran kaç?', ''],
  ['cinq', 'beş', 'SEÑK', "J'ai cinq euros.", 'Beş avrom var.', ''],
  ['parfait', 'mükemmel', 'par-FE', "C'est parfait, merci.", 'Mükemmel, teşekkürler.', ''],
  ['excuser', 'affetmek (excusez-moi)', 'eks-kü-ZE', 'Excusez-moi, madame.', 'Affedersiniz, hanımefendi.', ''],
  ['ainsi', 'böylece, böyle', 'eñ-Sİ', "C'est ainsi.", 'Böyle işte.', ''],
  ['le retour', 'dönüş', 'lö rö-TUR', 'Bon retour !', 'İyi dönüşler!', ''],
  ['sembler', 'görünmek, gibi gelmek', 'sañ-BLE', 'Il semble fatigué.', 'Yorgun görünüyor.', ''],
  ['autant', 'o kadar, aynı miktarda', 'o-TAÑ', 'Je travaille autant que toi.', 'Senin kadar çalışıyorum.', ''],
  ['la peine', 'zahmet; acı', 'la PEN', "Ce n'est pas la peine.", 'Zahmet etme, gerek yok.', ''],
  ['le plan', 'plan; harita', 'lö PLAÑ', "J'ai un plan.", 'Bir planım var.', '🗺️'],
  ["l'instant (m.)", 'an', 'leñs-TAÑ', "Un instant, s'il vous plaît.", 'Bir saniye, lütfen.', ''],
  ['la prison', 'hapishane', 'la pri-ZOÑ', 'Il est en prison.', 'O hapiste.', ''],
  ["l'arme (f.)", 'silah', 'LARM', "Il n'a pas d'arme.", 'Silahı yok.', ''],
  ['mauvais', 'kötü', 'mo-VE', "Il fait mauvais aujourd'hui.", 'Bugün hava kötü.', ''],
  ['le mot', 'kelime, söz', 'lö MO', 'Ce mot est difficile.', 'Bu kelime zor.', ''],
  ['travailler', 'çalışmak', 'tra-va-YE', 'Je travaille dans un bureau.', 'Bir ofiste çalışıyorum.', ''],
  ['quatre', 'dört', 'KATR', 'Nous sommes quatre.', 'Dört kişiyiz.', ''],
  ['rentrer', 'eve dönmek', 'rañ-TRE', 'Je rentre tard ce soir.', 'Bu akşam geç dönüyorum.', ''],
  ['le choix', 'seçim', 'lö ŞUA', 'Tu as le choix.', 'Seçim senin.', ''],
  ['parfois', 'bazen', 'par-FUA', 'Parfois, je cuisine.', 'Bazen yemek yaparım.', ''],
  ['le film', 'film', 'lö FİLM', 'On regarde un film ?', 'Film izleyelim mi?', '🎬'],
  ["d'abord", 'önce, ilk olarak', 'da-BOR', "D'abord, on mange.", 'Önce yemek yiyoruz.', ''],
  ['la faute', 'hata, kusur', 'la FOT', "Ce n'est pas ma faute.", 'Benim suçum değil.', ''],
  ['facile', 'kolay', 'fa-SİL', "C'est facile !", 'Kolay!', ''],
  ['bas', 'alçak; aşağı', 'BA', 'Parle plus bas.', 'Daha alçak sesle konuş.', ''],
  ['changer', 'değiştirmek', 'şañ-JE', 'Je change de train à Lyon.', "Lyon'da tren değiştiriyorum.", ''],
  ['le plaisir', 'zevk, keyif', 'lö ple-ZİR', 'Avec plaisir !', 'Memnuniyetle!', ''],
  ['heureux', 'mutlu', 'ö-RÖ', 'Je suis très heureux.', 'Çok mutluyum.', ''],
  ['entrer', 'girmek', 'añ-TRE', "Entrez, s'il vous plaît.", 'Girin, lütfen.', ''],
  ['propre', 'temiz; kendi', 'PROPR', 'La chambre est propre.', 'Oda temiz.', ''],
  ['le tour', 'tur; sıra', 'lö TUR', "C'est ton tour.", 'Sıra sende.', ''],
  ['ensuite', 'sonra', 'añ-SÜİT', 'Ensuite, on va au parc.', 'Sonra parka gidiyoruz.', ''],
  ["l'agent (m.)", 'ajan; memur', 'la-JAÑ', "L'agent de police est gentil.", 'Polis memuru nazik.', ''],
  ['le lit', 'yatak', 'lö Lİ', 'Je vais au lit.', 'Yatağa gidiyorum.', '🛏️'],
  ['adorer', 'bayılmak, çok sevmek', 'a-do-RE', "J'adore le fromage.", 'Peynire bayılırım.', ''],
  ['rendre', 'geri vermek', 'RAÑDR', 'Je te rends ton livre.', 'Kitabını geri veriyorum.', ''],
  ['la route', 'yol', 'la RUT', 'La route est longue.', 'Yol uzun.', '🛣️'],
  ['le lieu', 'yer, mekân', 'lö LYÖ', 'Le lieu est parfait.', 'Mekân mükemmel.', ''],
  ['commencer', 'başlamak', 'ko-mañ-SE', 'Le film commence à huit heures.', 'Film sekizde başlıyor.', ''],
  ['le service', 'hizmet; iyilik', 'lö ser-VİS', 'Tu peux me rendre un service ?', 'Bana bir iyilik yapabilir misin?', ''],
  ['drôle', 'komik; tuhaf', 'DROL', 'Ton ami est drôle.', 'Arkadaşın komik.', ''],
  ['difficile', 'zor', 'di-fi-SİL', "L'examen est difficile.", 'Sınav zor.', ''],
  ['pire', 'daha kötü', 'PİR', "C'est pire qu'hier.", 'Dünkünden daha kötü.', ''],
  ['le sujet', 'konu', 'lö sü-JE', 'Changeons de sujet.', 'Konuyu değiştirelim.', ''],
  ["l'état (m.)", 'durum; devlet', 'le-TA', 'La voiture est en bon état.', 'Araba iyi durumda.', ''],
  ['ceci', 'bu', 'sö-Sİ', 'Ceci est pour vous.', 'Bu sizin için.', ''],
  ['impossible', 'imkânsız', 'eñ-po-SİBL', "Rien n'est impossible.", 'Hiçbir şey imkânsız değildir.', ''],
  ['la sorte', 'tür, çeşit', 'la SORT', 'Quelle sorte de pain ?', 'Ne tür ekmek?', ''],
  ['le dollar', 'dolar', 'lö do-LAR', 'Ça coûte dix dollars.', 'On dolar tutuyor.', '💵'],
  ['bizarre', 'tuhaf, garip', 'bi-ZAR', "C'est bizarre.", 'Bu tuhaf.', ''],
  ['oublier', 'unutmak', 'u-bli-YE', "J'ai oublié ton nom.", 'Adını unuttum.', ''],
  ['tôt', 'erken', 'TO', 'Je me lève tôt.', 'Erken kalkarım.', ''],
  ['inquiet', 'endişeli (inquiète)', 'eñ-KYE', 'Ne sois pas inquiet.', 'Endişelenme.', ''],
  ['payer', 'ödemek', 'pe-YE', 'Je paie par carte.', 'Kartla ödüyorum.', ''],
  ['le cœur', 'kalp', 'lö KÖR', 'Il a un grand cœur.', 'Onun büyük bir kalbi var.', '❤️'],
  ['dès', '-den itibaren', 'DE', 'Dès demain, je commence.', 'Yarından itibaren başlıyorum.', ''],
  ['revenir', 'geri gelmek', 'röv-NİR', 'Je reviens tout de suite.', 'Hemen dönüyorum.', ''],
  ['le chien', 'köpek', 'lö ŞYEÑ', "Mon chien s'appelle Max.", 'Köpeğimin adı Max.', '🐕'],
  ['suffire', 'yetmek', 'sü-FİR', 'Ça suffit !', 'Yeter!', ''],
  ['le café', 'kahve; kafe', 'lö ka-FE', "Un café, s'il vous plaît.", 'Bir kahve, lütfen.', '☕'],
  ['calme', 'sakin', 'KALM', 'Reste calme.', 'Sakin ol.', ''],
  ['montrer', 'göstermek', 'moñ-TRE', 'Montre-moi ta photo.', 'Bana fotoğrafını göster.', ''],
  ['la photo', 'fotoğraf', 'la fo-TO', 'On prend une photo ?', 'Fotoğraf çekelim mi?', '📷'],
  ['fermer', 'kapatmak', 'fer-ME', 'Ferme la fenêtre.', 'Pencereyi kapat.', ''],
  ['sûrement', 'mutlaka, muhtemelen', 'sür-MAÑ', 'Il est sûrement à la maison.', 'Muhtemelen evdedir.', ''],
  ['le verre', 'bardak; cam', 'lö VER', 'Un verre de vin ?', 'Bir kadeh şarap?', '🥛'],
  ['le doute', 'şüphe', 'lö DUT', 'Sans doute.', 'Muhtemelen.', ''],
  ['la musique', 'müzik', 'la mü-ZİK', "J'aime la musique.", 'Müziği severim.', '🎵'],
  ['le courant', 'akım (au courant: haberdar)', 'lö ku-RAÑ', 'Tu es au courant ?', 'Haberin var mı?', ''],
  ['sauf', 'hariç', 'SOF', 'Tous sauf lui.', 'Onun dışında herkes.', ''],
  ['le moyen', 'yol, araç, çare', 'lö mua-YEÑ', "C'est le seul moyen.", 'Tek çare bu.', ''],
  ["l'avis (m.)", 'fikir, görüş', 'la-Vİ', "À mon avis, c'est bon.", 'Bence iyi.', ''],
  ['sauver', 'kurtarmak', 'so-VE', "Tu m'as sauvé !", 'Beni kurtardın!', ''],
  ["l'hôpital (m.)", 'hastane', 'lo-pi-TAL', "Il est à l'hôpital.", 'O hastanede.', '🏥'],
  ['le meurtre', 'cinayet', 'lö MÖRTR', "C'est un film sur un meurtre.", 'Bir cinayet hakkında film.', ''],
  ['sérieux', 'ciddi', 'se-RYÖ', 'Tu es sérieux ?', 'Ciddi misin?', ''],
  ['la seconde', 'saniye', 'la sö-GOÑD', "Une seconde, j'arrive !", 'Bir saniye, geliyorum!', ''],
  ["l'esprit (m.)", 'zihin, ruh', 'les-PRİ', "J'ai l'esprit libre.", 'Kafam rahat.', ''],
  ['le marché', 'pazar, piyasa', 'lö mar-ŞE', 'Je vais au marché.', 'Pazara gidiyorum.', ''],
  ['haut', 'yüksek; üst', 'O', 'Le mur est très haut.', 'Duvar çok yüksek.', ''],
  ['la salle', 'salon, oda', 'la SAL', 'La salle de bains est ici.', 'Banyo burada.', ''],
  ['malade', 'hasta', 'ma-LAD', "Je suis malade aujourd'hui.", 'Bugün hastayım.', ''],
  ['gentil', 'nazik, iyi', 'jañ-Tİ', 'Merci, tu es gentil.', 'Teşekkürler, çok naziksin.', ''],
  ['six', 'altı', 'SİS', 'Il est six heures.', 'Saat altı.', ''],
  ['simple', 'basit', 'SEÑPL', "C'est très simple.", 'Çok basit.', ''],
  ['apprendre', 'öğrenmek', 'a-PRAÑDR', "J'apprends le français.", 'Fransızca öğreniyorum.', ''],
  ['le seigneur', 'lord, efendi', 'lö se-NYÖR', 'Le seigneur vit au château.', 'Lord şatoda yaşıyor.', ''],
  ['le dîner', 'akşam yemeği', 'lö di-NE', 'Le dîner est prêt.', 'Akşam yemeği hazır.', '🍽️'],
  ['supposer', 'varsaymak', 'sü-po-ZE', 'Je suppose que oui.', 'Sanırım evet.', ''],
  ['le chemin', 'yol', 'lö şö-MEÑ', 'Je connais le chemin.', 'Yolu biliyorum.', ''],
  ['partout', 'her yerde', 'par-TU', 'Il y a du monde partout.', 'Her yerde insan var.', ''],
  ['le bras', 'kol', 'lö BRA', "J'ai mal au bras.", 'Kolum ağrıyor.', '💪'],
  ['prochain', 'gelecek, bir sonraki', 'pro-ŞEÑ', 'À la prochaine !', 'Bir dahaki sefere!', ''],
  ['le visage', 'yüz', 'lö vi-ZAJ', 'Elle a un joli visage.', 'Onun güzel bir yüzü var.', ''],
  ['la face', 'yüz; karşı', 'la FAS', 'La banque est en face.', 'Banka karşıda.', ''],
  ['la soirée', 'akşam; parti', 'la sua-RE', 'Bonne soirée !', 'İyi akşamlar!', ''],
  ['le roi', 'kral', 'lö RUA', 'Le roi est mort.', 'Kral öldü.', '👑'],
  ['surtout', 'özellikle', 'sür-TU', "J'aime surtout le chocolat.", 'Özellikle çikolatayı severim.', ''],
  ['le retard', 'gecikme', 'lö rö-TAR', 'Je suis en retard.', 'Geç kaldım.', ''],
  ['écrire', 'yazmak', 'e-KRİR', "J'écris une lettre.", 'Bir mektup yazıyorum.', ''],
  ['le livre', 'kitap', 'lö LİVR', 'Je lis un livre.', 'Bir kitap okuyorum.', '📖'],
  ['le rapport', 'rapor; ilişki', 'lö ra-POR', 'Quel est le rapport ?', 'Ne alakası var?', ''],
  ['le message', 'mesaj', 'lö me-SAJ', "J'ai reçu ton message.", 'Mesajını aldım.', ''],
  ['valoir', 'değmek, değerinde olmak', 'va-LUAR', 'Ça vaut la peine.', 'Buna değer.', ''],
  ['boire', 'içmek', 'BUAR', "Je bois de l'eau.", 'Su içiyorum.', ''],
  ['le président', 'başkan', 'lö pre-zi-DAÑ', 'Le président parle à la télé.', 'Başkan televizyonda konuşuyor.', ''],
  ['sinon', 'yoksa, aksi halde', 'si-NOÑ', 'Viens vite, sinon on part.', 'Çabuk gel, yoksa gidiyoruz.', ''],
  ["l'erreur (f.)", 'hata', 'le-RÖR', "C'est une erreur.", 'Bu bir hata.', ''],
  ['le rendez-vous', 'randevu, buluşma', 'lö rañ-de-VU', "J'ai rendez-vous chez le dentiste.", 'Dişçide randevum var.', ''],
  ['pauvre', 'fakir; zavallı', 'POVR', 'Pauvre chat !', 'Zavallı kedi!', ''],
  ['devenir', 'olmak, haline gelmek', 'döv-NİR', 'Je veux devenir médecin.', 'Doktor olmak istiyorum.', ''],
  ['rencontrer', 'tanışmak, karşılaşmak', 'rañ-koñ-TRE', 'Ravi de te rencontrer.', 'Tanıştığıma memnun oldum.', ''],
  ['occuper', 'meşgul etmek; ilgilenmek', 'o-kü-PE', "Je m'occupe des enfants.", 'Çocuklarla ben ilgileniyorum.', ''],
  ['souvent', 'sık sık', 'su-VAÑ', 'Je viens souvent ici.', 'Buraya sık gelirim.', ''],
  ['la pièce', 'oda; parça; madeni para', 'la PYES', "L'appartement a trois pièces.", 'Dairenin üç odası var.', ''],
  ['recevoir', 'almak (teslim)', 'rö-sö-VUAR', "J'ai reçu une lettre.", 'Bir mektup aldım.', ''],
  ['grave', 'ciddi, vahim', 'GRAV', "Ce n'est pas grave.", 'Önemli değil.', ''],
  ["l'intérieur (m.)", 'iç', 'leñ-te-RYÖR', "Il fait chaud à l'intérieur.", 'İçerisi sıcak.', ''],
  ["l'honneur (m.)", 'onur, şeref', 'lo-NÖR', "C'est un honneur.", 'Bu bir onur.', ''],
  ['dormir', 'uyumak', 'dor-MİR', 'Le bébé dort.', 'Bebek uyuyor.', ''],
  ['faux', 'yanlış; sahte', 'FO', "C'est faux !", 'Yanlış!', ''],
  ['le groupe', 'grup', 'lö GRUP', 'On voyage en groupe.', 'Grup halinde seyahat ediyoruz.', ''],
  ['le rêve', 'rüya; hayal', 'lö REV', 'Fais de beaux rêves.', 'Tatlı rüyalar.', ''],
  ['la carte', 'kart; harita; menü', 'la KART', "La carte, s'il vous plaît.", 'Menü, lütfen.', '🗺️'],
  ["l'appel (m.)", 'çağrı, arama', 'la-PEL', "J'attends ton appel.", 'Aramanı bekliyorum.', ''],
  ['manquer', 'eksik olmak; özlemek', 'mañ-KE', 'Tu me manques.', 'Seni özledim.', ''],
  ['envoyer', 'göndermek', 'añ-vua-YE', 'Envoie-moi un message.', 'Bana bir mesaj gönder.', ''],
  ['le début', 'başlangıç', 'lö de-BÜ', "C'est le début du film.", 'Filmin başı bu.', ''],
  ['bonsoir', 'iyi akşamlar', 'boñ-SUAR', 'Bonsoir, madame.', 'İyi akşamlar, hanımefendi.', ''],
  ['content', 'memnun', 'koñ-TAÑ', 'Je suis content de te voir.', 'Seni gördüğüme sevindim.', ''],
  ['le secret', 'sır', 'lö sö-KRE', "C'est un secret.", 'Bu bir sır.', '🤫'],
  ['cher', 'pahalı; sevgili', 'ŞER', "C'est trop cher.", 'Bu çok pahalı.', ''],
  ["l'effet (m.)", 'etki', 'le-FE', 'En effet, tu as raison.', 'Gerçekten, haklısın.', ''],
  ['le sac', 'çanta', 'lö SAK', 'Mon sac est lourd.', 'Çantam ağır.', '👜'],
  ['continuer', 'devam etmek', 'koñ-ti-nü-E', "Continue, c'est bien !", 'Devam et, güzel!', ''],
  ['acheter', 'satın almak', 'aş-TE', "J'achète du pain.", 'Ekmek alıyorum.', ''],
  ['la voix', 'ses', 'la VUA', 'Tu as une belle voix.', 'Güzel bir sesin var.', ''],
  ['certain', 'belli, emin; bazı', 'ser-TEÑ', "J'en suis certain.", 'Bundan eminim.', ''],
  ['Noël', 'Noel', 'no-EL', 'Joyeux Noël !', 'Mutlu Noeller!', '🎄'],
  ['gagner', 'kazanmak', 'ga-NYE', 'On a gagné !', 'Kazandık!', ''],
  ['la grâce', 'lütuf (grâce à: sayesinde)', 'la GRAS', "Grâce à toi, j'ai réussi.", 'Senin sayende başardım.', ''],
  ['le maître', 'usta; öğretmen; sahip', 'lö METR', 'Le chien suit son maître.', 'Köpek sahibini takip ediyor.', ''],
  ['le prix', 'fiyat; ödül', 'lö PRİ', 'Quel est le prix ?', 'Fiyatı ne?', '🏷️'],
  ['général', 'genel (en général: genelde)', 'je-ne-RAL', 'En général, je dors tôt.', 'Genelde erken yatarım.', ''],
  ["l'âge (m.)", 'yaş', 'LAJ', 'Quel âge as-tu ?', 'Kaç yaşındasın?', ''],
  ['long', 'uzun (longue)', 'LOÑ', 'Le film est long.', 'Film uzun.', ''],
  ['la rue', 'sokak', 'la RÜ', "J'habite dans cette rue.", 'Bu sokakta oturuyorum.', ''],
  ['tirer', 'çekmek; ateş etmek', 'ti-RE', 'Tire la porte.', 'Kapıyı çek.', ''],
  ['le cheveu', 'saç teli (les cheveux: saç)', 'lö şö-VÖ', 'Elle a les cheveux longs.', 'Onun saçları uzun.', '💇'],
  ['noir', 'siyah', 'NUAR', "J'ai un chat noir.", 'Siyah bir kedim var.', ''],
  ['promettre', 'söz vermek', 'pro-METR', 'Je te le promets.', 'Sana söz veriyorum.', ''],
  ['le patron', 'patron', 'lö pa-TROÑ', 'Mon patron est sympa.', 'Patronum iyi biri.', ''],
  ["l'avocat (m.)", 'avukat; avokado', 'la-vo-KA', 'Je veux parler à mon avocat.', 'Avukatımla konuşmak istiyorum.', ''],
  ['la force', 'güç, kuvvet', 'la FORS', 'Il a beaucoup de force.', 'Çok güçlü.', ''],
  ["l'accident (m.)", 'kaza', 'lak-si-DAÑ', 'Il a eu un accident.', 'Kaza geçirdi.', ''],
  ['dix', 'on', 'DİS', "J'ai dix euros.", 'On avrom var.', ''],
  ['probablement', 'muhtemelen', 'pro-ba-blö-MAÑ', 'Il va probablement pleuvoir.', 'Muhtemelen yağmur yağacak.', ''],
  ['le bout', 'uç; parça', 'lö BU', 'Au bout de la rue.', 'Sokağın sonunda.', ''],
  ["l'ordre (m.)", 'düzen; emir', 'LORDR', 'Tout est en ordre.', 'Her şey düzenli.', ''],
  ['détester', 'nefret etmek', 'de-tes-TE', 'Je déteste le froid.', 'Soğuktan nefret ederim.', ''],
  ['retrouver', 'yeniden bulmak; buluşmak', 'rö-tru-VE', 'On se retrouve au café ?', 'Kafede buluşalım mı?', ''],
  ['le million', 'milyon', 'lö mi-LYOÑ', 'Un million de personnes.', 'Bir milyon kişi.', ''],
  ['incroyable', 'inanılmaz', 'eñ-krua-YABL', "C'est incroyable !", 'İnanılmaz!', ''],
  ['le voyage', 'yolculuk, seyahat', 'lö vua-YAJ', 'Bon voyage !', 'İyi yolculuklar!', '🧳'],
  ['ailleurs', 'başka yerde', 'a-YÖR', 'Allons ailleurs.', 'Başka yere gidelim.', ''],
  ['ressembler', 'benzemek', 'rö-sañ-BLE', 'Tu ressembles à ta mère.', 'Annene benziyorsun.', ''],
  ['bienvenue', 'hoş geldiniz', 'byeñv-NÜ', 'Bienvenue en France !', "Fransa'ya hoş geldiniz!", ''],
  ['disparaître', 'kaybolmak', 'dis-pa-RETR', 'Mon chat a disparu.', 'Kedim kayboldu.', ''],
  ['protéger', 'korumak', 'pro-te-JE', 'Je vais te protéger.', 'Seni koruyacağım.', ''],
  ['utiliser', 'kullanmak', 'ü-ti-li-ZE', 'Je peux utiliser ton stylo ?', 'Kalemini kullanabilir miyim?', ''],
  ['la situation', 'durum', 'la si-tü-a-SYOÑ', 'La situation est grave.', 'Durum ciddi.', ''],
  ['simplement', 'basitçe, sadece', 'señ-plö-MAÑ', 'Dis-le simplement.', 'Basitçe söyle.', ''],
  ['la scène', 'sahne', 'la SEN', 'Le chanteur est sur scène.', 'Şarkıcı sahnede.', ''],
  ['la sœur', 'kız kardeş', 'la SÖR', 'Ma sœur est étudiante.', 'Kız kardeşim öğrenci.', '👧'],
  ["l'oncle (m.)", 'amca, dayı', 'LOÑKL', 'Mon oncle habite à Nice.', "Amcam Nice'te yaşıyor.", ''],
  ['la liste', 'liste', 'la LİST', 'Je fais une liste.', 'Bir liste yapıyorum.', '📝'],
  ['complètement', 'tamamen', 'koñ-plet-MAÑ', "J'ai complètement oublié !", 'Tamamen unuttum!', ''],
  ['le dos', 'sırt', 'lö DO', "J'ai mal au dos.", 'Sırtım ağrıyor.', ''],
  ["l'armée (f.)", 'ordu', 'lar-ME', "Mon frère est dans l'armée.", 'Kardeşim orduda.', ''],
  ['la paix', 'barış; huzur', 'la PE', 'Laisse-moi en paix.', 'Beni rahat bırak.', '🕊️'],
  ['battre', 'dövmek; yenmek', 'BATR', 'On va battre cette équipe.', 'Bu takımı yeneceğiz.', ''],
  ['le crime', 'suç', 'lö KRİM', "C'est un crime grave.", 'Bu ağır bir suç.', ''],
  ["l'anniversaire (m.)", 'doğum günü', 'la-ni-ver-SER', 'Joyeux anniversaire !', 'İyi ki doğdun!', '🎂'],
  ['réussir', 'başarmak', 're-ü-SİR', "J'ai réussi mon examen.", 'Sınavımı geçtim.', ''],
  ['agir', 'davranmak, harekete geçmek', 'a-JİR', "Il s'agit de ton avenir.", 'Söz konusu olan senin geleceğin.', ''],
  ['retourner', 'geri dönmek; çevirmek', 'rö-tur-NE', 'Je retourne en Turquie.', "Türkiye'ye dönüyorum.", ''],
  ['sale', 'kirli', 'SAL', 'Ta chemise est sale.', 'Gömleğin kirli.', ''],
  ['libre', 'özgür; boş', 'LİBR', 'Tu es libre ce soir ?', 'Bu akşam boş musun?', ''],
  ['bouger', 'kıpırdamak', 'bu-JE', 'Ne bouge pas !', 'Kıpırdama!', ''],
  ['le contrôle', 'kontrol', 'lö koñ-TROL', 'Tout est sous contrôle.', 'Her şey kontrol altında.', ''],
  ['rappeler', 'geri aramak; hatırlatmak', 'ra-PLE', 'Je te rappelle plus tard.', 'Seni sonra ararım.', ''],
  ["l'hôtel (m.)", 'otel', 'lo-TEL', "L'hôtel est près de la gare.", 'Otel garın yakınında.', '🏨'],
  ['idiot', 'aptal', 'i-DYO', 'Ne sois pas idiot.', 'Aptal olma.', ''],
  ['absolument', 'kesinlikle', 'ab-so-lü-MAÑ', 'Absolument, tu as raison.', 'Kesinlikle, haklısın.', ''],
  ['la victime', 'kurban', 'la vik-TİM', 'La victime va bien.', 'Kurbanın durumu iyi.', ''],
  ["l'impression (f.)", 'izlenim', 'leñ-pre-SYOÑ', "J'ai l'impression qu'il pleut.", 'Bana yağmur yağıyor gibi geliyor.', ''],
  ['décider', 'karar vermek', 'de-si-DE', "J'ai décidé de partir.", 'Gitmeye karar verdim.', ''],
  ['sympa', 'cana yakın, hoş', 'señ-PA', 'Ton frère est sympa.', 'Kardeşin cana yakın.', ''],
  ["l'avion (m.)", 'uçak', 'la-VYOÑ', "Je prends l'avion demain.", 'Yarın uçağa biniyorum.', '✈️'],
  ["l'habitude (f.)", 'alışkanlık', 'la-bi-TÜD', "D'habitude, je marche.", 'Genelde yürürüm.', ''],
  ['la table', 'masa', 'la TABL', 'Le dîner est sur la table.', 'Akşam yemeği masada.', ''],
  ['rouge', 'kırmızı', 'RUJ', "J'aime le vin rouge.", 'Kırmızı şarabı severim.', ''],
  ['le système', 'sistem', 'lö sis-TEM', 'Le système ne marche pas.', 'Sistem çalışmıyor.', ''],
  ['le médecin', 'doktor, hekim', 'lö med-SEÑ', 'Je dois voir un médecin.', 'Bir doktora görünmem lazım.', '🩺'],
  ['le bateau', 'tekne, gemi', 'lö ba-TO', 'On fait un tour en bateau.', 'Tekneyle bir tur atıyoruz.', '⛵'],
  ['stupide', 'aptalca', 'stü-PİD', "C'est une question stupide.", 'Bu aptalca bir soru.', ''],
  ['la faim', 'açlık', 'la FEÑ', "J'ai faim.", 'Acıktım.', ''],
  ['autour', 'etrafında', 'o-TUR', 'Il y a des arbres autour.', 'Etrafta ağaçlar var.', ''],
  ['le fond', 'dip; arka', 'lö FOÑ', 'Les toilettes sont au fond.', 'Tuvalet en arkada.', ''],
  ['la surprise', 'sürpriz', 'la sür-PRİZ', 'Quelle surprise !', 'Ne sürpriz!', '🎁'],
  ['la ligne', 'çizgi; hat', 'la LİNY', 'Prends la ligne 2 du métro.', 'Metronun 2 numaralı hattına bin.', ''],
  ['porter', 'taşımak; giymek', 'por-TE', 'Elle porte une robe bleue.', 'Mavi bir elbise giyiyor.', ''],
  ['imaginer', 'hayal etmek', 'i-ma-ji-NE', 'Imagine une plage.', 'Bir plaj hayal et.', ''],
  ['la colère', 'öfke', 'la ko-LER', 'Il est en colère.', 'O kızgın.', ''],
  ['clair', 'açık, net', 'KLER', "C'est clair ?", 'Anlaşıldı mı?', ''],
  ['la balle', 'top; kurşun', 'la BAL', 'Le chien joue avec la balle.', 'Köpek topla oynuyor.', '⚽'],
  ['or', "oysa; altın (l'or)", 'OR', 'Il a une montre en or.', 'Altın bir saati var.', ''],
  ['hors', 'dışında', 'OR', 'Le bus est hors service.', 'Otobüs hizmet dışı.', ''],
  ['magnifique', 'muhteşem', 'ma-nyi-FİK', 'La vue est magnifique.', 'Manzara muhteşem.', ''],
  ['le risque', 'risk', 'lö RİSK', "C'est un gros risque.", 'Bu büyük bir risk.', ''],
  ['terminer', 'bitirmek', 'ter-mi-NE', "J'ai terminé mes devoirs.", 'Ödevlerimi bitirdim.', ''],
  ['la mission', 'görev', 'la mi-SYOÑ', 'La mission est finie.', 'Görev bitti.', ''],
  ['joli', 'güzel, hoş', 'jo-Lİ', 'Quelle jolie robe !', 'Ne güzel elbise!', ''],
  ['présent', 'mevcut; şimdiki', 'pre-ZAÑ', 'Tout le monde est présent.', 'Herkes burada.', ''],
  ['le cadeau', 'hediye', 'lö ka-DO', "C'est un cadeau pour toi.", 'Bu senin için bir hediye.', '🎁'],
  ['expliquer', 'açıklamak', 'eks-pli-KE', "Tu peux m'expliquer ?", 'Bana açıklayabilir misin?', ''],
  ['voler', 'uçmak; çalmak', 'vo-LE', "On m'a volé mon sac.", 'Çantamı çaldılar.', ''],
  ['plusieurs', 'birçok, birkaç', 'plü-ZYÖR', "J'ai plusieurs questions.", 'Birkaç sorum var.', ''],
  ['gauche', 'sol', 'GOŞ', 'Tourne à gauche.', 'Sola dön.', ''],
  ['neuf', 'dokuz; yepyeni', 'NÖF', "J'ai neuf ans.", 'Dokuz yaşındayım.', ''],
  ['ouvrir', 'açmak', 'u-VRİR', "Ouvre la porte, s'il te plaît.", 'Kapıyı aç, lütfen.', ''],
  ['dedans', 'içeride', 'dö-DAÑ', 'Il y a quoi dedans ?', 'İçinde ne var?', ''],
  ['suivre', 'izlemek, takip etmek', 'SÜİVR', "Suivez-moi, s'il vous plaît.", 'Beni takip edin, lütfen.', ''],
  ["l'inspecteur (m.)", 'müfettiş, komiser', 'leñs-pek-TÖR', "L'inspecteur pose des questions.", 'Komiser sorular soruyor.', ''],
  ['la réponse', 'cevap', 'la re-POÑS', 'Quelle est la réponse ?', 'Cevap ne?', ''],
  ['la lumière', 'ışık', 'la lü-MYER', 'Allume la lumière.', 'Işığı aç.', '💡'],
  ['le pied', 'ayak', 'lö PYE', 'Je vais à pied.', 'Yürüyerek gidiyorum.', '🦶'],
  ['le pote', 'kanka, arkadaş (argo)', 'lö POT', 'Je sors avec mes potes.', 'Kankalarımla dışarı çıkıyorum.', ''],
  ["l'espèce (f.)", 'tür', 'les-PES', "C'est une espèce rare.", 'Bu nadir bir tür.', ''],
  ['pareil', 'aynı, benzer', 'pa-REY', "C'est pareil.", 'Aynı şey.', ''],
  ['le soleil', 'güneş', 'lö so-LEY', 'Le soleil brille.', 'Güneş parlıyor.', '☀️'],
  ['le camp', 'kamp', 'lö KAÑ', 'On dort au camp.', 'Kampta uyuyoruz.', '⛺'],
  ['le coin', 'köşe', 'lö KUEÑ', 'Le café est au coin de la rue.', 'Kafe sokağın köşesinde.', ''],
  ['ignorer', 'bilmemek; görmezden gelmek', 'i-nyo-RE', "J'ignore son nom.", 'Adını bilmiyorum.', ''],
  ['la moitié', 'yarı', 'la mua-TYE', 'Je mange la moitié.', 'Yarısını yiyorum.', ''],
  ['selon', '-e göre', 'sö-LOÑ', "Selon moi, c'est vrai.", 'Bana göre doğru.', ''],
  ['la sortie', 'çıkış', 'la sor-Tİ', 'Où est la sortie ?', 'Çıkış nerede?', '🚪'],
  ['la recherche', 'araştırma; arama', 'la rö-ŞERŞ', 'Je fais une recherche.', 'Bir araştırma yapıyorum.', ''],
  ["l'arrière (m.)", 'arka', 'la-RYER', "Assieds-toi à l'arrière.", 'Arkaya otur.', ''],
  ['lire', 'okumak', 'LİR', "J'aime lire le soir.", 'Akşamları okumayı severim.', ''],
  ['doucement', 'yavaşça, usulca', 'dus-MAÑ', 'Parle doucement, le bébé dort.', 'Yavaş konuş, bebek uyuyor.', ''],
  ["l'avance (f.)", 'avans (en avance: erken)', 'la-VAÑS', 'Je suis en avance.', 'Erken geldim.', ''],
  ['exact', 'doğru, tam', 'eg-ZAKT', "C'est exact.", 'Doğru.', ''],
  ['le club', 'kulüp', 'lö KLÖB', 'Je vais au club de sport.', 'Spor kulübüne gidiyorum.', ''],
  ["l'arrivée (f.)", 'varış', 'la-ri-VE', "L'arrivée est à midi.", 'Varış öğlende.', ''],
  ['lequel', 'hangisi (laquelle)', 'lö-KEL', 'Lequel tu préfères ?', 'Hangisini tercih edersin?', ''],
  ['poser', 'koymak; sormak', 'po-ZE', 'Je peux poser une question ?', 'Bir soru sorabilir miyim?', ''],
  ['chaud', 'sıcak', 'ŞO', 'Le thé est chaud.', 'Çay sıcak.', ''],
  ['le professeur', 'öğretmen, profesör', 'lö pro-fe-SÖR', 'Le professeur est gentil.', 'Öğretmen nazik.', '🧑‍🏫'],
  ['quitter', 'terk etmek, ayrılmak', 'ki-TE', 'Je quitte le bureau à six heures.', 'Ofisten saat altıda çıkıyorum.', ''],
  ['la loi', 'yasa, kanun', 'la LUA', "C'est la loi.", 'Kanun bu.', ''],
  ['le tueur', 'katil', 'lö tü-ÖR', 'Le tueur est en prison.', 'Katil hapiste.', ''],
  ['le flic', 'polis (argo)', 'lö FLİK', 'Les flics arrivent !', 'Polisler geliyor!', ''],
  ['la lettre', 'mektup; harf', 'la LETR', "J'écris une lettre à ma mère.", 'Anneme bir mektup yazıyorum.', '✉️'],
  ['la forme', 'biçim; form', 'la FORM', 'Je suis en forme.', 'Formdayım.', ''],
  ['le conseil', 'tavsiye; kurul', 'lö koñ-SEY', 'Tu as un conseil pour moi ?', 'Bana bir tavsiyen var mı?', ''],
  ['le bar', 'bar', 'lö BAR', 'On se voit au bar ?', 'Barda görüşelim mi?', '🍸'],
  ['normal', 'normal', 'nor-MAL', "C'est normal.", 'Bu normal.', ''],
  ['le danger', 'tehlike', 'lö dañ-JE', 'Attention, danger !', 'Dikkat, tehlike!', '⚠️'],
  ['dangereux', 'tehlikeli', 'dañj-RÖ', 'Cette route est dangereuse.', 'Bu yol tehlikeli.', ''],
  ['jurer', 'yemin etmek', 'jü-RE', "Je te jure, c'est vrai !", 'Yemin ederim, doğru!', ''],
  ["l'offre (f.)", 'teklif', 'LOFR', "C'est une bonne offre.", 'Bu iyi bir teklif.', ''],
  ['le but', 'amaç; gol', 'lö BÜT', 'Quel est ton but ?', 'Amacın ne?', ''],
  ['froid', 'soğuk', 'FRUA', "J'ai froid.", 'Üşüyorum.', ''],
  ['tranquille', 'sakin', 'trañ-KİL', "C'est un quartier tranquille.", 'Sakin bir mahalle.', ''],
  ['le gamin', 'çocuk, velet (günlük)', 'lö ga-MEÑ', 'Ce gamin est malin.', 'Bu velet çok akıllı.', ''],
  ['la classe', 'sınıf', 'la KLAS', 'Ma classe est grande.', 'Sınıfım kalabalık.', ''],
  ['le poste', 'görev, pozisyon; karakol', 'lö POST', "J'ai un nouveau poste.", 'Yeni bir pozisyonum var.', ''],
  ["l'attaque (f.)", 'saldırı', 'la-TAK', "C'est une attaque !", 'Bu bir saldırı!', ''],
  ['la boîte', 'kutu', 'la BUAT', 'Il y a quoi dans la boîte ?', 'Kutuda ne var?', '📦'],
  ["l'enquête (f.)", 'soruşturma; anket', 'lañ-KET', 'La police fait une enquête.', 'Polis soruşturma yapıyor.', ''],
  ['la visite', 'ziyaret', 'la vi-ZİT', 'Merci pour ta visite.', 'Ziyaretin için teşekkürler.', ''],
  ['le juge', 'hâkim', 'lö JÜJ', 'Le juge est sévère.', 'Hâkim sert.', '⚖️'],
  ['le bord', 'kenar, kıyı', 'lö BOR', "J'habite au bord de la mer.", 'Deniz kenarında oturuyorum.', ''],
  ['debout', 'ayakta', 'dö-BU', 'Je suis debout depuis six heures.', 'Saat altıdan beri ayaktayım.', ''],
  ['la preuve', 'kanıt', 'la PRÖV', 'Tu as une preuve ?', 'Kanıtın var mı?', ''],
  ['vivant', 'canlı, yaşayan', 'vi-VAÑ', 'Il est vivant !', 'O yaşıyor!', ''],
  ['le ciel', 'gökyüzü', 'lö SYEL', 'Le ciel est bleu.', 'Gökyüzü mavi.', ''],
  ['toucher', 'dokunmak', 'tu-ŞE', 'Ne touche pas !', 'Dokunma!', ''],
  ['la télé', 'televizyon', 'la te-LE', 'Il regarde la télé.', 'Televizyon izliyor.', '📺'],
  ['pourtant', 'yine de, oysa', 'pur-TAÑ', 'Il est riche, pourtant il est triste.', 'Zengin, yine de mutsuz.', ''],
  ['triste', 'üzgün', 'TRİST', 'Pourquoi tu es triste ?', 'Neden üzgünsün?', ''],
  ['la droite', 'sağ', 'la DRUAT', 'Tournez à droite.', 'Sağa dönün.', ''],
  ['travers', 'çapraz (à travers: içinden)', 'tra-VER', 'On passe à travers le parc.', 'Parkın içinden geçiyoruz.', ''],
  ['la santé', 'sağlık', 'la sañ-TE', 'À ta santé !', 'Şerefe!', ''],
  ['le dossier', 'dosya', 'lö do-SYE', 'Le dossier est sur mon bureau.', 'Dosya masamın üstünde.', '📁'],
  ['coucher', 'yatırmak (se coucher: yatmak)', 'ku-ŞE', 'Je me couche à onze heures.', 'Saat on birde yatarım.', ''],
  ['la cuisine', 'mutfak; yemek pişirme', 'la küi-ZİN', 'Maman est dans la cuisine.', 'Annem mutfakta.', '🍳'],
  ['monter', 'çıkmak, binmek', 'moñ-TE', 'Monte dans la voiture.', 'Arabaya bin.', ''],
  ['signifier', 'anlamına gelmek', 'si-nyi-FYE', "Qu'est-ce que ça signifie ?", 'Bu ne anlama geliyor?', ''],
  ['la relation', 'ilişki', 'la rö-la-SYOÑ', 'Nous avons une bonne relation.', 'İyi bir ilişkimiz var.', ''],
  ['le centre', 'merkez', 'lö SAÑTR', 'Je vais au centre-ville.', 'Şehir merkezine gidiyorum.', ''],
  ['la dame', 'hanım, bayan', 'la DAM', 'Cette dame est ma voisine.', 'Bu hanım benim komşum.', ''],
  ['chacun', 'her biri, herkes', 'şa-KÖÑ', 'Chacun a son livre.', 'Herkesin kendi kitabı var.', ''],
  ['la chanson', 'şarkı', 'la şañ-SOÑ', "J'aime cette chanson.", 'Bu şarkıyı seviyorum.', '🎶'],
  ['blanc', 'beyaz (blanche)', 'BLAÑ', 'Je veux du vin blanc.', 'Beyaz şarap istiyorum.', ''],
  ['le don', 'bağış; yetenek', 'lö DOÑ', 'Elle a un don pour la musique.', 'Müziğe yeteneği var.', ''],
  ["l'âme (f.)", 'ruh', 'LAM', 'Il a une belle âme.', 'Güzel bir ruhu var.', ''],
  ['la manière', 'tarz, şekil', 'la ma-NYER', 'De quelle manière ?', 'Ne şekilde?', ''],
  ['la décision', 'karar', 'la de-si-ZYOÑ', "C'est ma décision.", 'Bu benim kararım.', ''],
  ['la compagnie', 'şirket; arkadaşlık', 'la koñ-pa-Nİ', 'Merci pour ta compagnie.', 'Arkadaşlığın için teşekkürler.', ''],
  ['le déjeuner', 'öğle yemeği', 'lö de-jö-NE', 'Le déjeuner est à midi.', 'Öğle yemeği saat on ikide.', '🥗'],
  ['différent', 'farklı', 'di-fe-RAÑ', "C'est très différent.", 'Bu çok farklı.', ''],
  ['la clé', 'anahtar', 'la KLE', 'Où est la clé ?', 'Anahtar nerede?', '🔑'],
  ['le vaisseau', 'gemi; uzay gemisi', 'lö ve-SO', "Le vaisseau part dans l'espace.", 'Uzay gemisi uzaya gidiyor.', '🚀'],
  ["l'enfer (m.)", 'cehennem', 'lañ-FER', "C'est l'enfer, ce bruit !", 'Bu gürültü cehennem gibi!', ''],
  ['vendre', 'satmak', 'VAÑDR', 'Je vends ma voiture.', 'Arabamı satıyorum.', ''],
  ['responsable', 'sorumlu', 'res-poñ-SABL', 'Qui est responsable ici ?', 'Burada sorumlu kim?', ''],
  ['nul', 'hiç; berbat (günlük)', 'NÜL', 'Ce film est nul.', 'Bu film berbat.', ''],
  ['le signe', 'işaret', 'lö SİNY', "C'est un bon signe.", 'Bu iyiye işaret.', ''],
  ['le lieutenant', 'teğmen', 'lö lyöt-NAÑ', 'Le lieutenant donne un ordre.', 'Teğmen bir emir veriyor.', ''],
  ['étrange', 'tuhaf', 'e-TRAÑJ', "C'est un bruit étrange.", 'Tuhaf bir ses.', ''],
  ['le diable', 'şeytan', 'lö DYABL', 'Il a peur du diable.', 'Şeytandan korkuyor.', '😈'],
  ['là-dedans', 'orada, onun içinde', 'la-dö-DAÑ', 'Il y a quoi là-dedans ?', 'Onun içinde ne var?', ''],
  ['capable', 'yetenekli, yapabilir', 'ka-PABL', 'Tu es capable de le faire.', 'Bunu yapabilirsin.', ''],
  ['emmener', 'götürmek', 'añm-NE', "Je t'emmène à l'école.", 'Seni okula götürüyorum.', ''],
  ['la honte', 'utanç', 'la OÑT', "J'ai honte.", 'Utanıyorum.', ''],
  ['la bouche', 'ağız', 'la BUŞ', 'Ouvre la bouche.', 'Ağzını aç.', '👄'],
  ['préférer', 'tercih etmek', 'pre-fe-RE', 'Je préfère le thé.', 'Çayı tercih ederim.', ''],
  ['coupable', 'suçlu', 'ku-PABL', "Il n'est pas coupable.", 'O suçlu değil.', ''],
  ['rire', 'gülmek', 'RİR', 'Tu me fais rire !', 'Beni güldürüyorsun!', ''],
  ['le soin', 'özen, bakım', 'lö SUEÑ', 'Prends soin de toi.', 'Kendine iyi bak.', ''],
  ['le milieu', 'orta', 'lö mi-LYÖ', 'Au milieu de la nuit.', 'Gecenin ortasında.', ''],
  ["l'appartement (m.)", 'daire', 'la-par-tö-MAÑ', 'Mon appartement est petit.', 'Dairem küçük.', '🏢'],
  ['le cerveau', 'beyin', 'lö ser-VO', 'Le cerveau est un organe.', 'Beyin bir organdır.', '🧠'],
  ['la blague', 'şaka', 'la BLAG', "C'est une blague ?", 'Bu bir şaka mı?', ''],
  ['choisir', 'seçmek', 'şua-ZİR', 'Choisis une carte.', 'Bir kart seç.', ''],
  ["l'époque (f.)", 'dönem, çağ', 'le-POK', "À cette époque, j'étais jeune.", 'O zamanlar gençtim.', ''],
  ['la voie', 'yol; peron hattı', 'la VUA', 'Le train part de la voie 3.', 'Tren 3. hattan kalkıyor.', ''],
  ['la réunion', 'toplantı', 'la re-ü-NYOÑ', "J'ai une réunion à dix heures.", 'Saat onda toplantım var.', ''],
  ["l'allée (f.)", 'yol, ara yol', 'la-LE', "L'allée mène au jardin.", 'Yol bahçeye çıkıyor.', ''],
  ["l'intérêt (m.)", 'ilgi; çıkar; faiz', 'leñ-te-RE', 'Tu as intérêt à venir !', 'Gelsen iyi olur!', ''],
  ['le cheval', 'at', 'lö şö-VAL', 'Le cheval court vite.', 'At hızlı koşuyor.', '🐎'],
  ['le combat', 'dövüş, mücadele', 'lö koñ-BA', 'Le combat commence.', 'Dövüş başlıyor.', ''],
  ['le silence', 'sessizlik', 'lö si-LAÑS', "Silence, s'il vous plaît !", 'Sessizlik, lütfen!', ''],
  ['exister', 'var olmak', 'eg-zis-TE', "Ça n'existe pas.", 'Öyle bir şey yok.', ''],
  ['tel', 'böyle, öyle (telle)', 'TEL', "Je n'ai jamais vu une telle chose.", 'Hiç böyle bir şey görmedim.', ''],
  ['le trou', 'delik', 'lö TRU', 'Il y a un trou dans mon pull.', 'Kazağımda bir delik var.', ''],
  ['public', 'kamu, halka açık', 'pü-BLİK', "C'est un jardin public.", 'Bu halka açık bir park.', ''],
  ['cacher', 'saklamak', 'ka-ŞE', 'Où as-tu caché les clés ?', 'Anahtarları nereye sakladın?', ''],
  ['amoureux', 'âşık', 'a-mu-RÖ', "Il est amoureux d'elle.", 'Ona âşık.', ''],
  ['la drogue', 'uyuşturucu', 'la DROG', 'La drogue est dangereuse.', 'Uyuşturucu tehlikelidir.', ''],
  ['le commandant', 'komutan', 'lö ko-mañ-DAÑ', 'Le commandant arrive.', 'Komutan geliyor.', ''],
  ['le gouvernement', 'hükümet', 'lö gu-ver-nö-MAÑ', 'Le gouvernement change.', 'Hükümet değişiyor.', ''],
  ['le client', 'müşteri', 'lö kli-YAÑ', 'Le client est roi.', 'Müşteri her zaman haklıdır.', ''],
  ["l'adresse (f.)", 'adres', 'la-DRES', 'Quelle est ton adresse ?', 'Adresin ne?', ''],
  ['le journal', 'gazete; günlük', 'lö jur-NAL', 'Je lis le journal.', 'Gazete okuyorum.', '📰'],
  ['le contact', 'temas, iletişim', 'lö koñ-TAKT', 'On reste en contact.', 'İletişimde kalalım.', ''],
  ['dingue', 'çılgın (günlük)', 'DEÑG', "C'est dingue !", 'Bu çılgınca!', ''],
  ['récupérer', 'geri almak', 're-kü-pe-RE', 'Je récupère mon sac.', 'Çantamı geri alıyorum.', ''],
  ['la base', 'temel; üs', 'la BAZ', "C'est la base.", 'Bu temel şey.', ''],
  ['présenter', 'tanıştırmak, sunmak', 'pre-zañ-TE', 'Je te présente ma femme.', 'Seni eşimle tanıştırayım.', ''],
  ['la peau', 'deri, cilt', 'la PO', "J'ai la peau sèche.", 'Cildim kuru.', ''],
  ['servir', 'hizmet etmek; servis yapmak', 'ser-VİR', 'Ça sert à quoi ?', 'Bu ne işe yarar?', ''],
  ['le peuple', 'halk', 'lö PÖPL', 'Le peuple a voté.', 'Halk oy verdi.', ''],
  ["l'exemple (m.)", 'örnek', 'leg-ZAÑPL', 'Par exemple, le pain.', 'Örneğin, ekmek.', ''],
  ['blesser', 'yaralamak', 'ble-SE', 'Il est blessé à la jambe.', 'Bacağından yaralı.', ''],
  ['la société', 'toplum; şirket', 'la so-sye-TE', 'Je travaille dans une grande société.', 'Büyük bir şirkette çalışıyorum.', ''],
  ['le tort', 'haksızlık (avoir tort)', 'lö TOR', 'Tu as tort.', 'Haksızsın.', ''],
  ['sept', 'yedi', 'SET', 'Il est sept heures.', 'Saat yedi.', ''],
  ['le héros', 'kahraman', 'lö e-RO', 'Tu es mon héros !', 'Sen benim kahramanımsın!', '🦸'],
  ['mentir', 'yalan söylemek', 'mañ-TİR', 'Ne me mens pas.', 'Bana yalan söyleme.', ''],
  ['la mer', 'deniz', 'la MER', 'On va à la mer.', 'Denize gidiyoruz.', '🌊'],
  ['jeter', 'atmak', 'jö-TE', 'Jette ça à la poubelle.', 'Bunu çöpe at.', ''],
  ['la bière', 'bira', 'la BYER', "Une bière, s'il vous plaît.", 'Bir bira, lütfen.', '🍺'],
  ['asseoir', "oturtmak (s'asseoir: oturmak)", 'a-SUAR', "Asseyez-vous, s'il vous plaît.", 'Oturun, lütfen.', ''],
  ['la robe', 'elbise', 'la ROB', 'Elle porte une robe rouge.', 'Kırmızı bir elbise giyiyor.', '👗'],
  ['les félicitations (f.)', 'tebrikler', 'le fe-li-si-ta-SYOÑ', 'Félicitations pour ton bébé !', 'Bebeğin için tebrikler!', ''],
  ["l'opération (f.)", 'ameliyat; operasyon', 'lo-pe-ra-SYOÑ', "L'opération s'est bien passée.", 'Ameliyat iyi geçti.', ''],
  ['prévoir', 'öngörmek, planlamak', 'pre-VUAR', "Qu'est-ce que tu as prévu ?", 'Ne planladın?', ''],
  ['répondre', 'cevap vermek', 're-POÑDR', 'Réponds au téléphone !', 'Telefona cevap ver!', ''],
  ["l'entrée (f.)", 'giriş; başlangıç yemeği', 'lañ-TRE', "L'entrée est gratuite.", 'Giriş ücretsiz.', ''],
  ['le vol', 'uçuş; hırsızlık', 'lö VOL', 'Mon vol part à midi.', 'Uçuşum öğlen kalkıyor.', ''],
  ['horrible', 'korkunç', 'o-RİBL', 'Quel temps horrible !', 'Ne korkunç hava!', ''],
  ['le vin', 'şarap', 'lö VEÑ', 'Un verre de vin rouge.', 'Bir kadeh kırmızı şarap.', '🍷'],
  ['le dommage', "zarar (c'est dommage: yazık)", 'lö do-MAJ', "C'est dommage !", 'Yazık!', ''],
  ['le colonel', 'albay', 'lö ko-lo-NEL', 'Le colonel parle aux soldats.', 'Albay askerlerle konuşuyor.', ''],
  ['ramener', 'geri getirmek', 'ram-NE', 'Je te ramène chez toi.', 'Seni evine bırakıyorum.', ''],
  ['la règle', 'kural; cetvel', 'la REGL', 'Ce sont les règles du jeu.', 'Oyunun kuralları bunlar.', '📏'],
  ['le nez', 'burun', 'lö NE', "J'ai le nez qui coule.", 'Burnum akıyor.', '👃'],
  ['la justice', 'adalet', 'la jüs-TİS', 'Je veux la justice.', 'Adalet istiyorum.', ''],
  ['découvrir', 'keşfetmek', 'de-ku-VRİR', 'Je découvre Paris.', "Paris'i keşfediyorum.", ''],
  ['le départ', 'kalkış, ayrılış', 'lö de-PAR', 'Le départ est à huit heures.', 'Kalkış saat sekizde.', ''],
  ['le bruit', 'gürültü, ses', 'lö BRÜİ', 'Il y a trop de bruit.', 'Çok gürültü var.', ''],
  ['le secours', 'yardım (au secours: imdat)', 'lö sö-KUR', 'Au secours !', 'İmdat!', ''],
  ['vérifier', 'kontrol etmek', 've-ri-FYE', 'Je vérifie mon billet.', 'Biletimi kontrol ediyorum.', ''],
  ['enceinte', 'hamile', 'añ-SEÑT', 'Ma sœur est enceinte.', 'Kız kardeşim hamile.', ''],
  ['le témoin', 'tanık', 'lö te-MUEÑ', 'Il y a un témoin.', 'Bir tanık var.', ''],
  ['le directeur', 'müdür', 'lö di-rek-TÖR', 'Le directeur est absent.', 'Müdür yok.', ''],
  ['intéressant', 'ilginç', 'eñ-te-re-SAÑ', 'Ce livre est intéressant.', 'Bu kitap ilginç.', ''],
  ["l'excuse (f.)", 'özür; bahane', 'leks-KÜZ', "Ce n'est pas une excuse.", 'Bu bir bahane değil.', ''],
  ['environ', 'yaklaşık', 'añ-vi-ROÑ', 'Il y a environ vingt personnes.', 'Yaklaşık yirmi kişi var.', ''],
  ['inutile', 'gereksiz, işe yaramaz', 'i-nü-TİL', "C'est inutile.", 'Bu gereksiz.', ''],
  ['terrible', 'korkunç; müthiş', 'te-RİBL', "C'est une nouvelle terrible.", 'Bu korkunç bir haber.', ''],
  ['la danse', 'dans', 'la DAÑS', "J'aime la danse.", 'Dansı severim.', '💃'],
  ['la position', 'konum, pozisyon', 'la po-zi-SYOÑ', 'Quelle est ta position ?', 'Konumun ne?', ''],
  ['humain', 'insan; insani', 'ü-MEÑ', "C'est humain.", 'Bu insanca.', ''],
  ['apparemment', 'görünüşe göre', 'a-pa-ra-MAÑ', 'Apparemment, il est malade.', 'Görünüşe göre hasta.', ''],
  ["l'avenir (m.)", 'gelecek', 'lav-NİR', 'Pense à ton avenir.', 'Geleceğini düşün.', ''],
  ['bête', 'aptal; hayvan (la bête)', 'BET', "Ce n'est pas bête !", 'Hiç de aptalca değil!', ''],
  ['sérieusement', 'ciddi olarak', 'se-ryöz-MAÑ', 'Sérieusement, tu viens ?', 'Cidden, geliyor musun?', ''],
  ['approcher', 'yaklaşmak', 'a-pro-ŞE', 'Approche, je ne mords pas.', 'Yaklaş, ısırmam.', ''],
  ['la nourriture', 'yiyecek', 'la nu-ri-TÜR', 'La nourriture est bonne ici.', 'Burada yemekler güzel.', '🍲'],
  ['la plupart', 'çoğu', 'la plü-PAR', 'La plupart des gens sont gentils.', 'İnsanların çoğu nazik.', ''],
  ['le lycée', 'lise', 'lö li-SE', 'Mon fils est au lycée.', 'Oğlum lisede.', '🏫'],
  ['le tas', 'yığın (un tas de: bir sürü)', 'lö TA', "J'ai un tas de travail.", 'Bir sürü işim var.', ''],
  ['empêcher', 'engellemek', 'añ-pe-ŞE', "Le bruit m'empêche de dormir.", 'Gürültü uyumama engel oluyor.', ''],
  ['le niveau', 'seviye', 'lö ni-VO', 'Quel est ton niveau de français ?', 'Fransızca seviyen ne?', ''],
  ['la banque', 'banka', 'la BAÑK', 'Je vais à la banque.', 'Bankaya gidiyorum.', '🏦'],
  ['éviter', 'kaçınmak', 'e-vi-TE', 'Évite le sucre.', 'Şekerden kaçın.', ''],
  ['la lune', 'ay (gökteki)', 'la LÜN', 'La lune est belle ce soir.', 'Bu akşam ay çok güzel.', '🌙'],
  ['la pitié', 'acıma', 'la pi-TYE', 'Pitié, aide-moi !', 'Ne olur, yardım et!', ''],
  ['la liberté', 'özgürlük', 'la li-ber-TE', 'Liberté, égalité, fraternité.', 'Özgürlük, eşitlik, kardeşlik.', ''],
  ["l'expérience (f.)", 'deneyim; deney', 'leks-pe-RYAÑS', "J'ai de l'expérience.", 'Deneyimim var.', ''],
  ['le procès', 'dava, duruşma', 'lö pro-SE', 'Le procès commence lundi.', 'Dava pazartesi başlıyor.', ''],
  ['la radio', 'radyo', 'la ra-DYO', "J'écoute la radio.", 'Radyo dinliyorum.', '📻'],
  ['le thé', 'çay', 'lö TE', "Un thé, s'il vous plaît.", 'Bir çay, lütfen.', '🍵'],
  ['le mur', 'duvar', 'lö MÜR', 'La photo est sur le mur.', 'Fotoğraf duvarda.', '🧱'],
  ['deuxième', 'ikinci', 'dö-ZYEM', "C'est la deuxième fois.", 'Bu ikinci sefer.', ''],
  ['la bande', 'grup, çete; bant', 'la BAÑD', "C'est ma bande d'amis.", 'Bu benim arkadaş grubum.', ''],
  ['ridicule', 'gülünç', 'ri-di-KÜL', "C'est ridicule !", 'Bu gülünç!', ''],
  ['le nord', 'kuzey', 'lö NOR', 'Lille est dans le nord.', 'Lille kuzeyde.', '🧭'],
  ['le copain', 'arkadaş; erkek arkadaş', 'lö ko-PEÑ', "C'est mon copain Marc.", 'Bu arkadaşım Marc.', ''],
  ['anglais', 'İngiliz; İngilizce', 'añ-GLE', 'Tu parles anglais ?', 'İngilizce konuşuyor musun?', ''],
  ['les toilettes (f.)', 'tuvalet', 'le tua-LET', 'Où sont les toilettes ?', 'Tuvalet nerede?', '🚻'],
  ['déranger', 'rahatsız etmek', 'de-rañ-JE', 'Désolé de vous déranger.', 'Rahatsız ettiğim için özür dilerim.', ''],
  ['le rôle', 'rol', 'lö ROL', 'Il joue le rôle du roi.', 'Kralı oynuyor.', ''],
  ['censé', '-mesi gereken, sözde', 'sañ-SE', 'Tu es censé être ici.', 'Burada olman gerekiyordu.', ''],
  ['la reine', 'kraliçe', 'la REN', 'La reine est au palais.', 'Kraliçe sarayda.', '👸'],
  ['la cour', 'avlu; mahkeme', 'la KUR', 'Les enfants jouent dans la cour.', 'Çocuklar avluda oynuyor.', ''],
  ["l'église (f.)", 'kilise', 'le-GLİZ', "L'église est très vieille.", 'Kilise çok eski.', '⛪'],
  ['vide', 'boş', 'VİD', 'Le frigo est vide.', 'Buzdolabı boş.', ''],
  ['obtenir', 'elde etmek', 'ob-tö-NİR', "J'ai obtenu mon visa.", 'Vizemi aldım.', ''],
  ["l'ennui (m.)", 'can sıkıntısı; dert', 'lañ-NÜİ', "J'ai des ennuis.", 'Başım dertte.', ''],
  ['personnel', 'kişisel; personel', 'per-so-NEL', "C'est personnel.", 'Bu kişisel.', ''],
  ['conduire', 'araba sürmek', 'koñ-DÜİR', 'Je conduis ma voiture.', 'Arabamı sürüyorum.', ''],
  ['le sol', 'zemin, yer', 'lö SOL', 'Le livre est sur le sol.', 'Kitap yerde.', ''],
  ['le code', 'kod, şifre', 'lö KOD', 'Quel est le code ?', 'Şifre ne?', ''],
  ['huit', 'sekiz', 'ÜİT', 'Il est huit heures.', 'Saat sekiz.', ''],
  ["l'espoir (m.)", 'umut', 'les-PUAR', "Il y a de l'espoir.", 'Umut var.', ''],
  ['spécial', 'özel', 'spe-SYAL', "C'est un jour spécial.", 'Bu özel bir gün.', ''],
  ['la vidéo', 'video', 'la vi-de-O', 'Regarde cette vidéo !', 'Şu videoya bak!', ''],
  ['le vêtement', 'giysi', 'lö vet-MAÑ', "J'achète des vêtements.", 'Kıyafet alıyorum.', '👕'],
  ['la défense', 'savunma', 'la de-FAÑS', 'Défense de fumer.', 'Sigara içmek yasaktır.', ''],
  ['le sud', 'güney', 'lö SÜD', 'Marseille est dans le sud.', 'Marsilya güneyde.', ''],
  ['la grand-mère', 'büyükanne', 'la grañ-MER', 'Ma grand-mère fait des gâteaux.', 'Babaannem pasta yapar.', '👵'],
  ['le match', 'maç', 'lö MAÇ', 'On regarde le match ?', 'Maçı izleyelim mi?', '⚽'],
  ['la bombe', 'bomba', 'la BOÑB', "La bombe n'a pas explosé.", 'Bomba patlamadı.', '💣'],
  ['intéresser', 'ilgilendirmek', 'eñ-te-re-SE', "Ça m'intéresse.", 'Bu ilgimi çekiyor.', ''],
  ['la zone', 'bölge', 'la ZON', "C'est une zone piétonne.", 'Bu yaya bölgesi.', ''],
  ['la tante', 'teyze, hala', 'la TAÑT', 'Ma tante habite à Lyon.', "Teyzem Lyon'da yaşıyor.", ''],
  ['paraître', 'görünmek', 'pa-RETR', "Il paraît qu'il va pleuvoir demain.", 'Yarın yağmur yağacakmış.', ''],
  ['le magasin', 'mağaza, dükkân', 'lö ma-ga-ZEÑ', 'Le magasin ferme à sept heures.', 'Mağaza saat yedide kapanıyor.', '🏪'],
  ['marier', 'evlendirmek (se marier)', 'ma-RYE', 'Ils se marient en mai.', 'Mayısta evleniyorlar.', ''],
  ['proche', 'yakın', 'PROŞ', 'La gare est proche.', 'Gar yakın.', ''],
  ['la douleur', 'acı, ağrı', 'la du-LÖR', "J'ai une douleur au dos.", 'Sırtımda bir ağrı var.', ''],
  ['la presse', 'basın', 'la PRES', 'La presse parle de lui.', 'Basın ondan bahsediyor.', ''],
  ['merveilleux', 'harika, olağanüstü', 'mer-ve-YÖ', "C'est un jour merveilleux.", 'Harika bir gün.', ''],
  ['ravi', 'çok memnun', 'ra-Vİ', 'Ravi de vous voir !', 'Sizi gördüğüme çok sevindim!', ''],
  ['la fenêtre', 'pencere', 'la fö-NETR', 'Ouvre la fenêtre.', 'Pencereyi aç.', '🪟'],
  ['le mien', 'benimki (la mienne)', 'lö MYEÑ', "Ce stylo, c'est le mien.", 'Bu kalem benimki.', ''],
  ['le terrain', 'arazi; saha', 'lö te-REÑ', 'Les enfants jouent sur le terrain.', 'Çocuklar sahada oynuyor.', ''],
  ['le sergent', 'çavuş', 'lö ser-JAÑ', 'Le sergent crie.', 'Çavuş bağırıyor.', ''],
  ['le projet', 'proje, plan', 'lö pro-JE', "J'ai un nouveau projet.", 'Yeni bir projem var.', ''],
  ['le quartier', 'mahalle, semt', 'lö kar-TYE', "J'aime mon quartier.", 'Mahallemi seviyorum.', ''],
  ['la planète', 'gezegen', 'la pla-NET', 'La Terre est une planète.', 'Dünya bir gezegendir.', '🪐'],
  ['certainement', 'kesinlikle, elbette', 'ser-ten-MAÑ', 'Certainement, monsieur.', 'Elbette, beyefendi.', ''],
  ['rapide', 'hızlı', 'ra-PİD', 'Le TGV est très rapide.', 'TGV çok hızlı.', ''],
  ['lorsque', '-dığında', 'LORSK', "Lorsqu'il pleut, je reste ici.", 'Yağmur yağdığında burada kalırım.', ''],
  ['assurer', 'sağlamak, temin etmek', 'a-sü-RE', "Je t'assure, c'est vrai.", 'Emin ol, doğru.', ''],
  ['mignon', 'sevimli, tatlı', 'mi-NYOÑ', 'Ton chat est mignon.', 'Kedin çok tatlı.', ''],
  ['tourner', 'dönmek, çevirmek', 'tur-NE', 'Tourne à droite.', 'Sağa dön.', ''],
  ['danser', 'dans etmek', 'dañ-SE', 'Tu veux danser ?', 'Dans etmek ister misin?', ''],
  ["l'importance (f.)", 'önem', 'leñ-por-TAÑS', "Ça n'a pas d'importance.", 'Önemi yok.', ''],
  ['mériter', 'hak etmek', 'me-ri-TE', 'Tu mérites des vacances.', 'Tatili hak ediyorsun.', ''],
  ['la machine', 'makine', 'la ma-ŞİN', 'La machine à café est cassée.', 'Kahve makinesi bozuk.', ''],
  ['le programme', 'program', 'lö pro-GRAM', 'Quel est le programme ?', 'Program ne?', ''],
  ['honnête', 'dürüst', 'o-NET', 'Il est très honnête.', 'O çok dürüst.', ''],
  ["l'occasion (f.)", 'fırsat', 'lo-ka-ZYOÑ', "C'est une bonne occasion.", 'Bu iyi bir fırsat.', ''],
  ['prouver', 'kanıtlamak', 'pru-VE', 'Tu peux le prouver ?', 'Bunu kanıtlayabilir misin?', ''],
  ['la glace', 'dondurma; buz; ayna', 'la GLAS', 'Une glace à la vanille.', 'Vanilyalı bir dondurma.', '🍦'],
  ['parier', 'bahse girmek', 'pa-RYE', 'Je parie que tu as faim.', 'Bahse girerim açsındır.', ''],
  ['le camion', 'kamyon', 'lö ka-MYOÑ', 'Le camion est très gros.', 'Kamyon çok büyük.', '🚚'],
  ['fier', 'gururlu', 'FYER', 'Je suis fier de toi.', 'Seninle gurur duyuyorum.', ''],
  ['discuter', 'tartışmak, sohbet etmek', 'dis-kü-TE', 'On discute un peu ?', 'Biraz sohbet edelim mi?', ''],
  ['le village', 'köy', 'lö vi-LAJ', 'Mon village est petit.', 'Köyüm küçük.', '🏘️'],
  ['le spectacle', 'gösteri', 'lö spek-TAKL', 'Le spectacle commence.', 'Gösteri başlıyor.', ''],
  ['rose', 'pembe; gül (la rose)', 'ROZ', 'Elle aime le rose.', 'Pembeyi seviyor.', ''],
  ['la parole', 'söz', 'la pa-ROL', 'Je te donne ma parole.', 'Sana söz veriyorum.', ''],
  ['la rencontre', 'karşılaşma, buluşma', 'la rañ-KOÑTR', 'Quelle belle rencontre !', 'Ne güzel bir tanışma!', ''],
  ['apprécier', 'beğenmek, takdir etmek', 'a-pre-SYE', "J'apprécie ton aide.", 'Yardımını takdir ediyorum.', ''],
  ['la réalité', 'gerçeklik', 'la re-a-li-TE', "C'est la réalité.", 'Gerçek bu.', ''],
  ['le respect', 'saygı', 'lö res-PE', "Un peu de respect, s'il te plaît !", 'Biraz saygı, lütfen!', ''],
  ['remettre', 'geri koymak; teslim etmek', 'rö-METR', 'Remets le livre à sa place.', 'Kitabı yerine koy.', ''],
  ['les vacances (f.)', 'tatil', 'le va-KAÑS', 'Bonnes vacances !', 'İyi tatiller!', '🏖️'],
  ['détruire', 'yok etmek', 'de-TRÜİR', 'La tempête a tout détruit.', 'Fırtına her şeyi yıktı.', ''],
  ["l'officier (m.)", 'subay', 'lo-fi-SYE', "L'officier donne des ordres.", 'Subay emir veriyor.', ''],
  ['la solution', 'çözüm', 'la so-lü-SYOÑ', "J'ai une solution.", 'Bir çözümüm var.', ''],
  ["l'information (f.)", 'bilgi', 'leñ-for-ma-SYOÑ', "Merci pour l'information.", 'Bilgi için teşekkürler.', ''],
  ['le monstre', 'canavar', 'lö MOÑSTR', "L'enfant a peur des monstres.", 'Çocuk canavarlardan korkuyor.', '👹'],
  ["l'ordinateur (m.)", 'bilgisayar', 'lor-di-na-TÖR', 'Mon ordinateur est lent.', 'Bilgisayarım yavaş.', '💻'],
  ['la nature', 'doğa', 'la na-TÜR', "J'aime marcher dans la nature.", 'Doğada yürümeyi severim.', '🌳'],
  ["l'énergie (f.)", 'enerji', 'le-ner-Jİ', "Je n'ai plus d'énergie.", 'Hiç enerjim kalmadı.', ''],
  ['la pierre', 'taş', 'la PYER', 'La maison est en pierre.', 'Ev taştan.', '🪨'],
  ['la pression', 'basınç; baskı', 'la pre-SYOÑ', 'Je suis sous pression.', 'Baskı altındayım.', ''],
  ['la chaussure', 'ayakkabı', 'la şo-SÜR', "J'achète des chaussures.", 'Ayakkabı alıyorum.', '👟'],
  ["l'espace (m.)", 'alan; uzay', 'les-PAS', "Il n'y a pas d'espace.", 'Yer yok.', ''],
  ['le portable', 'cep telefonu', 'lö por-TABL', "J'ai oublié mon portable.", 'Cep telefonumu unuttum.', '📱'],
  ['préparer', 'hazırlamak', 'pre-pa-RE', 'Je prépare le dîner.', 'Akşam yemeğini hazırlıyorum.', ''],
  ['nécessaire', 'gerekli', 'ne-se-SER', "C'est nécessaire ?", 'Gerekli mi?', ''],
  ['court', 'kısa', 'KUR', 'Mes cheveux sont courts.', 'Saçlarım kısa.', ''],
  ['offrir', 'hediye etmek, sunmak', 'o-FRİR', "Je t'offre un café.", 'Sana bir kahve ısmarlıyorum.', ''],
  ['envers', '-e karşı', 'añ-VER', 'Il est gentil envers moi.', 'Bana karşı nazik.', ''],
  ['le bain', 'banyo (küvet)', 'lö BEÑ', 'Je prends un bain.', 'Banyo yapıyorum.', '🛁'],
  ['la charge', 'yük; şarj', 'la ŞARJ', 'Mon téléphone est en charge.', 'Telefonum şarjda.', ''],
  ["l'ennemi (m.)", 'düşman', 'len-Mİ', "C'est mon ennemi.", 'O benim düşmanım.', ''],
  ['immédiatement', 'hemen', 'i-me-dyat-MAÑ', 'Viens immédiatement !', 'Hemen gel!', ''],
  ['finalement', 'sonunda', 'fi-nal-MAÑ', 'Finalement, il est venu.', 'Sonunda geldi.', ''],
  ['énorme', 'kocaman', 'e-NORM', 'Cette maison est énorme.', 'Bu ev kocaman.', ''],
  ['le grand-père', 'büyükbaba, dede', 'lö grañ-PER', 'Mon grand-père a quatre-vingts ans.', 'Dedem seksen yaşında.', '👴'],
  ['le test', 'test', 'lö TEST', "J'ai un test demain.", 'Yarın testim var.', ''],
  ['réfléchir', 'düşünmek, kafa yormak', 're-fle-ŞİR', 'Je vais réfléchir.', 'Düşüneceğim.', ''],
  ['chanter', 'şarkı söylemek', 'şañ-TE', 'Elle chante très bien.', 'Çok güzel şarkı söylüyor.', ''],
  ['le futur', 'gelecek', 'lö fü-TÜR', 'Parlons du futur.', 'Gelecekten konuşalım.', ''],
  ['lâcher', 'bırakmak, salmak', 'la-ŞE', 'Lâche-moi !', 'Bırak beni!', ''],
  ['mademoiselle', 'küçükhanım, bayan', 'mad-mua-ZEL', 'Merci, mademoiselle.', 'Teşekkürler, küçükhanım.', ''],
  ['enlever', 'çıkarmak', 'añl-VE', 'Enlève tes chaussures.', 'Ayakkabılarını çıkar.', ''],
  ['épouser', 'evlenmek (biriyle)', 'e-pu-ZE', "Tu veux m'épouser ?", 'Benimle evlenir misin?', ''],
  ['la fleur', 'çiçek', 'la FLÖR', "Je t'offre des fleurs.", 'Sana çiçek veriyorum.', '🌸'],
  ['arranger', 'düzenlemek; ayarlamak', 'a-rañ-JE', "Ça m'arrange.", 'Bu işime gelir.', ''],
  ['riche', 'zengin', 'RİŞ', 'Il est très riche.', 'O çok zengin.', ''],
  ['le fait', 'olgu, gerçek', 'lö FE', 'En fait, je suis fatigué.', 'Aslında yorgunum.', ''],
  ['ancien', 'eski', 'añ-SYEÑ', "C'est mon ancien professeur.", 'O benim eski öğretmenim.', ''],
  ['accepter', 'kabul etmek', 'ak-sep-TE', "J'accepte ton offre.", 'Teklifini kabul ediyorum.', ''],
  ['sauter', 'atlamak', 'so-TE', 'Le chat saute sur la table.', 'Kedi masaya atlıyor.', ''],
  ['le suspect', 'şüpheli', 'lö süs-PE', 'La police cherche le suspect.', 'Polis şüpheliyi arıyor.', ''],
  ['durant', 'boyunca', 'dü-RAÑ', 'Il a plu durant la nuit.', 'Gece boyunca yağmur yağdı.', ''],
  ["l'invité (m.)", 'misafir, davetli', 'leñ-vi-TE', 'Les invités arrivent à huit heures.', 'Misafirler saat sekizde geliyor.', ''],
  ['la politique', 'siyaset, politika', 'la po-li-TİK', "Je n'aime pas la politique.", 'Siyaseti sevmem.', ''],
  ['la dent', 'diş', 'la DAÑ', "J'ai mal aux dents.", 'Dişim ağrıyor.', '🦷'],
  ['le patient', 'hasta', 'lö pa-SYAÑ', 'Le patient attend le médecin.', 'Hasta doktoru bekliyor.', ''],
  ['le repas', 'yemek, öğün', 'lö rö-PA', 'Bon repas !', 'Afiyet olsun!', '🍽️'],
  ["l'urgence (f.)", 'acil durum', 'lür-JAÑS', "C'est une urgence !", 'Bu acil bir durum!', '🚑'],
  ['la jambe', 'bacak', 'la JAÑB', "J'ai mal à la jambe.", 'Bacağım ağrıyor.', '🦵'],
  ['la conversation', 'sohbet', 'la koñ-ver-sa-SYOÑ', "C'est une bonne conversation.", 'Güzel bir sohbet.', ''],
  ['le bus', 'otobüs', 'lö BÜS', 'Je prends le bus.', 'Otobüse biniyorum.', '🚌'],
  ['la mémoire', 'hafıza', 'la me-MUAR', "J'ai une bonne mémoire.", 'Hafızam iyidir.', ''],
  ['la série', 'dizi', 'la se-Rİ', 'Je regarde une série.', 'Bir dizi izliyorum.', ''],
  ['le contraire', 'zıt, tersi', 'lö koñ-TRER', 'Au contraire !', 'Tam tersine!', ''],
  ['le vent', 'rüzgâr', 'lö VAÑ', 'Il y a du vent.', 'Rüzgâr var.', '🌬️'],
  ['la taille', 'beden; boy', 'la TAY', 'Quelle est votre taille ?', 'Bedeniniz ne?', ''],
  ['le chat', 'kedi', 'lö ŞA', 'Le chat dort sur le lit.', 'Kedi yatakta uyuyor.', '🐈'],
  ['le contrat', 'sözleşme', 'lö koñ-TRA', 'Je signe le contrat.', 'Sözleşmeyi imzalıyorum.', '📄'],
  ['le couteau', 'bıçak', 'lö ku-TO', 'Passe-moi le couteau.', 'Bıçağı bana uzat.', '🔪'],
  ['double', 'çift, iki kat', 'DUBL', "Une chambre double, s'il vous plaît.", 'Çift kişilik bir oda, lütfen.', ''],
  ['la carrière', 'kariyer', 'la ka-RYER', 'Elle a une belle carrière.', 'Güzel bir kariyeri var.', ''],
  ['descendre', 'inmek', 'de-SAÑDR', 'Je descends du bus.', 'Otobüsten iniyorum.', ''],
  ["l'université (f.)", 'üniversite', 'lü-ni-ver-si-TE', "Je vais à l'université.", 'Üniversiteye gidiyorum.', '🎓'],
  ['le sentiment', 'duygu', 'lö sañ-ti-MAÑ', "C'est un beau sentiment.", 'Güzel bir duygu.', ''],
  ['le papier', 'kâğıt', 'lö pa-PYE', 'Tu as du papier ?', 'Kâğıdın var mı?', ''],
  ['remarquer', 'fark etmek', 'rö-mar-KE', 'Tu as remarqué ?', 'Fark ettin mi?', ''],
  ['le courage', 'cesaret', 'lö ku-RAJ', 'Bon courage !', 'Kolay gelsin!', ''],
  ['la beauté', 'güzellik', 'la bo-TE', 'Quelle beauté !', 'Ne güzellik!', ''],
  ['taire', 'susmak (se taire)', 'TER', "Tais-toi, s'il te plaît !", 'Sus, lütfen!', ''],
  ["l'après-midi (m.)", 'öğleden sonra', 'la-pre-mi-Dİ', 'À cet après-midi !', 'Öğleden sonra görüşürüz!', ''],
  ['excellent', 'mükemmel', 'ek-se-LAÑ', 'Ce repas est excellent.', 'Bu yemek mükemmel.', ''],
  ['parmi', 'arasında', 'par-Mİ', 'Il est parmi nous.', 'O aramızda.', ''],
  ['le couple', 'çift', 'lö KUPL', "C'est un beau couple.", 'Güzel bir çift.', ''],
  ['le permis', 'izin; ehliyet', 'lö per-Mİ', "J'ai mon permis de conduire.", 'Ehliyetim var.', ''],
  ['la différence', 'fark', 'la di-fe-RAÑS', 'Quelle est la différence ?', 'Fark ne?', ''],
  ['la course', 'koşu, yarış; alışveriş', 'la KURS', 'Je fais les courses.', 'Alışveriş yapıyorum.', ''],
  ['dégager', 'açmak, boşaltmak; defolmak', 'de-ga-JE', "Dégage la table, s'il te plaît.", 'Masayı boşalt, lütfen.', ''],
  ['mille', 'bin', 'MİL', 'Mille mercis !', 'Binlerce teşekkür!', ''],
  ["l'accès (m.)", 'erişim', 'lak-SE', "L'accès est interdit.", 'Giriş yasak.', ''],
  ['la cible', 'hedef', 'la SİBL', 'La cible est loin.', 'Hedef uzakta.', '🎯'],
  ['joyeux', 'neşeli, mutlu', 'jua-YÖ', 'Joyeux anniversaire !', 'Doğum günün kutlu olsun!', ''],
  ['le bonheur', 'mutluluk', 'lö bo-NÖR', 'Je te souhaite beaucoup de bonheur.', 'Sana çok mutluluk dilerim.', ''],
  ["l'action (f.)", 'eylem; hisse', 'lak-SYOÑ', "Il faut passer à l'action.", 'Harekete geçmek gerek.', ''],
  ['le taxi', 'taksi', 'lö tak-Sİ', 'Je prends un taxi.', 'Taksiye biniyorum.', '🚕'],
  ['le restaurant', 'restoran', 'lö res-to-RAÑ', 'On dîne au restaurant ?', 'Restoranda yemek yiyelim mi?', '🍴'],
  ['la crise', 'kriz', 'la KRİZ', "C'est la crise.", 'Kriz var.', ''],
  ['la piste', 'iz; pist', 'la PİST', 'La police a une piste.', 'Polisin bir ipucu var.', ''],
  ['puisque', 'madem, -diği için', 'PÜİSK', 'Puisque tu es là, aide-moi.', 'Madem buradasın, bana yardım et.', ''],
  ['la coupe', 'kupa; kesim', 'la KUP', 'On a gagné la coupe !', 'Kupayı kazandık!', '🏆'],
  ['le prince', 'prens', 'lö PREÑS', 'Le prince habite au château.', 'Prens şatoda yaşıyor.', '🤴'],
  ['marrant', 'komik (günlük)', 'ma-RAÑ', "C'est marrant !", 'Çok komik!', ''],
  ['refuser', 'reddetmek', 'rö-fü-ZE', 'Je refuse de partir.', 'Gitmeyi reddediyorum.', ''],
  ['apporter', 'getirmek', 'a-por-TE', "J'apporte le dessert.", 'Tatlıyı ben getiriyorum.', ''],
  ['casser', 'kırmak', 'ka-SE', "J'ai cassé mon téléphone.", 'Telefonumu kırdım.', ''],
  ['lors', 'sırasında (lors de)', 'LOR', 'Lors du dîner, il a parlé.', 'Akşam yemeğinde konuştu.', ''],
  ['la maladie', 'hastalık', 'la ma-la-Dİ', "C'est une maladie grave.", 'Bu ağır bir hastalık.', ''],
  ['le week-end', 'hafta sonu', 'lö vi-KEND', 'Bon week-end !', 'İyi hafta sonları!', ''],
  ['le kilomètre', 'kilometre', 'lö ki-lo-METR', "C'est à deux kilomètres.", 'İki kilometre uzakta.', ''],
  ["l'alcool (m.)", 'alkol', 'lal-KOL', "Je ne bois pas d'alcool.", 'Alkol içmem.', ''],
  ['le fil', 'iplik; tel', 'lö FİL', 'Il y a un fil sur ton pull.', 'Kazağında bir iplik var.', '🧵'],
  ['totalement', 'tamamen', 'to-tal-MAÑ', 'Tu as totalement raison.', 'Tamamen haklısın.', ''],
  ["l'île (f.)", 'ada', 'LİL', 'Nous visitons une île.', 'Bir adayı geziyoruz.', '🏝️'],
  ['remercier', 'teşekkür etmek', 'rö-mer-SYE', 'Je te remercie.', 'Sana teşekkür ederim.', ''],
  ['la caméra', 'kamera', 'la ka-me-RA', 'Souris à la caméra !', 'Kameraya gülümse!', '🎥'],
  ['pleurer', 'ağlamak', 'plö-RE', 'Ne pleure pas.', 'Ağlama.', ''],
  ['régler', 'ayarlamak; ödemek', 're-GLE', "Je règle l'addition.", 'Hesabı ödüyorum.', ''],
  ['entier', 'bütün, tam', 'añ-TYE', "J'ai mangé le gâteau entier.", 'Bütün pastayı yedim.', ''],
  ["l'animal (m.)", 'hayvan', 'la-ni-MAL', 'Tu as un animal ?', 'Evcil hayvanın var mı?', '🐾'],
  ["l'image (f.)", 'resim, görüntü', 'li-MAJ', 'Regarde cette image.', 'Şu resme bak.', '🖼️'],
  ["l'étage (m.)", 'kat', 'le-TAJ', "J'habite au deuxième étage.", 'İkinci katta oturuyorum.', ''],
  ['rejoindre', 'katılmak, buluşmak', 'rö-JUEÑDR', 'Je te rejoins au café.', 'Kafede yanına geliyorum.', ''],
  ['le soldat', 'asker', 'lö sol-DA', 'Le soldat protège le pays.', 'Asker ülkeyi korur.', '💂'],
  ['amuser', "eğlendirmek (s'amuser)", 'a-mü-ZE', 'Amuse-toi bien !', 'İyi eğlenceler!', ''],
  ['la langue', 'dil', 'la LAÑG', 'Le français est une belle langue.', 'Fransızca güzel bir dil.', '👅'],
  ['la direction', 'yön; yönetim', 'la di-rek-SYOÑ', "C'est la bonne direction ?", 'Doğru yön bu mu?', ''],
  ['frais', 'taze; serin', 'FRE', 'Le pain est frais.', 'Ekmek taze.', ''],
  ['la couleur', 'renk', 'la ku-LÖR', 'Quelle est ta couleur préférée ?', 'En sevdiğin renk ne?', '🎨'],
  ['frapper', 'vurmak; kapı çalmak', 'fra-PE', 'On frappe à la porte.', 'Kapı çalınıyor.', ''],
  ['rater', 'kaçırmak', 'ra-TE', "J'ai raté le bus.", 'Otobüsü kaçırdım.', ''],
  ['évidemment', 'elbette, tabii', 'e-vi-da-MAÑ', 'Évidemment, je viens !', 'Tabii ki geliyorum!', ''],
  ["l'épouse (f.)", 'eş, karı', 'le-PUZ', 'Je vous présente mon épouse.', 'Eşimi tanıştırayım.', ''],
  ['troisième', 'üçüncü', 'trua-ZYEM', "C'est au troisième étage.", 'Üçüncü katta.', ''],
  ['faible', 'zayıf', 'FEBL', 'Je me sens faible.', 'Kendimi halsiz hissediyorum.', ''],
  ['bleu', 'mavi', 'BLÖ', 'Le ciel est bleu.', 'Gökyüzü mavi.', ''],
  ['afin', 'için (afin de)', 'a-FEÑ', 'Je travaille afin de voyager.', 'Seyahat etmek için çalışıyorum.', ''],
  ['faillir', 'az kalsın …mek', 'fa-YİR', "J'ai failli tomber.", 'Az kalsın düşüyordum.', ''],
  ['courir', 'koşmak', 'ku-RİR', 'Je cours dans le parc.', 'Parkta koşuyorum.', ''],
  ['américain', 'Amerikalı', 'a-me-ri-KEÑ', 'Mon ami est américain.', 'Arkadaşım Amerikalı.', ''],
  ['le détail', 'ayrıntı', 'lö de-TAY', 'Explique-moi les détails.', 'Bana ayrıntıları anlat.', ''],
  ['le pont', 'köprü', 'lö POÑ', 'On traverse le pont.', 'Köprüden geçiyoruz.', '🌉'],
  ['attraper', 'yakalamak', 'a-tra-PE', 'Attrape la balle !', 'Topu yakala!', ''],
  ['le poisson', 'balık', 'lö pua-SOÑ', "J'aime le poisson grillé.", 'Izgara balığı severim.', '🐟'],
  ['la date', 'tarih (gün)', 'la DAT', "Quelle est la date aujourd'hui ?", 'Bugün tarih ne?', '📅'],
  ["l'intention (f.)", 'niyet', 'leñ-tañ-SYOÑ', "Je n'ai pas l'intention de partir.", 'Gitmeye niyetim yok.', ''],
  ['le procureur', 'savcı', 'lö pro-kü-RÖR', 'Le procureur parle au juge.', 'Savcı hâkimle konuşuyor.', ''],
  ['le goût', 'tat; zevk', 'lö GU', 'Ça a un goût bizarre.', 'Bunun tadı tuhaf.', ''],
  ['le shérif', 'şerif', 'lö şe-RİF', 'Le shérif arrive en ville.', 'Şerif kasabaya geliyor.', '🤠'],
  ["l'arrêt (m.)", 'durak; durma', 'la-RE', 'Je descends au prochain arrêt.', 'Bir sonraki durakta iniyorum.', '🚏'],
  ['le sourire', 'gülümseme', 'lö su-RİR', 'Tu as un beau sourire.', 'Güzel bir gülüşün var.', '😊'],
  ['le lait', 'süt', 'lö LE', "Un café au lait, s'il vous plaît.", 'Sütlü bir kahve, lütfen.', '🥛'],
  ['la chasse', 'av', 'la ŞAS', 'Il va à la chasse.', 'Ava gidiyor.', ''],
  ['le signal', 'sinyal, işaret', 'lö si-NYAL', "Il n'y a pas de signal ici.", 'Burada sinyal yok.', ''],
  ['le destin', 'kader', 'lö des-TEÑ', "C'est le destin.", 'Kader bu.', ''],
  ['français', 'Fransız; Fransızca', 'frañ-SE', "J'apprends le français.", 'Fransızca öğreniyorum.', ''],
  ['la princesse', 'prenses', 'la preñ-SES', 'La princesse est belle.', 'Prenses güzel.', '👸'],
  ['la foi', 'inanç', 'la FUA', 'Il a la foi.', 'İnancı var.', ''],
  ['la présence', 'varlık, bulunma', 'la pre-ZAÑS', 'Merci de votre présence.', 'Katılımınız için teşekkürler.', ''],
  ['le doigt', 'parmak', 'lö DUA', 'Je me suis coupé le doigt.', 'Parmağımı kestim.', '☝️'],
  ['le partenaire', 'ortak, partner', 'lö par-tö-NER', "C'est mon partenaire de tennis.", 'O benim tenis partnerim.', ''],
  ['adieu', 'elveda', 'a-DYÖ', 'Adieu, mon ami.', 'Elveda, dostum.', ''],
  ['le costume', 'takım elbise; kostüm', 'lö kos-TÜM', 'Il porte un costume noir.', 'Siyah takım elbise giyiyor.', '🤵'],
  ["l'entreprise (f.)", 'şirket, işletme', 'lañ-trö-PRİZ', 'Je travaille dans une petite entreprise.', 'Küçük bir şirkette çalışıyorum.', ''],
  ['utile', 'faydalı', 'ü-TİL', "C'est très utile.", 'Bu çok faydalı.', ''],
  ['calmer', 'sakinleştirmek', 'kal-ME', 'Calme-toi, tout va bien.', 'Sakin ol, her şey yolunda.', ''],
  ['le lien', 'bağ; bağlantı', 'lö LYEÑ', 'Envoie-moi le lien.', 'Bana linki gönder.', '🔗'],
  ['unique', 'tek, eşsiz', 'ü-NİK', "C'est un endroit unique.", 'Eşsiz bir yer.', ''],
  ['appartenir', 'ait olmak', 'a-par-tö-NİR', "Ce livre m'appartient.", 'Bu kitap bana ait.', ''],
  ['moindre', 'en ufak', 'MUEÑDR', "Je n'en ai pas la moindre idée.", 'En ufak fikrim yok.', ''],
  ['amener', 'getirmek (birini)', 'am-NE', 'Tu peux amener ton ami.', 'Arkadaşını getirebilirsin.', ''],
  ['le discours', 'konuşma, nutuk', 'lö dis-KUR', 'Le président fait un discours.', 'Başkan bir konuşma yapıyor.', ''],
  ['les données (f.)', 'veriler', 'le do-NE', "Les données sont sur l'ordinateur.", 'Veriler bilgisayarda.', ''],
  ["l'art (m.)", 'sanat', 'LAR', "J'aime l'art moderne.", 'Modern sanatı severim.', '🎨'],
  ['la magie', 'sihir', 'la ma-Jİ', 'Il fait de la magie.', 'Sihir yapıyor.', '🪄'],
  ['la bouteille', 'şişe', 'la bu-TEY', "Une bouteille d'eau, s'il vous plaît.", 'Bir şişe su, lütfen.', '🍾'],
  ['justement', 'tam da; haklı olarak', 'jüs-tö-MAÑ', "Justement, je voulais t'appeler.", 'Tam da seni arayacaktım.', ''],
  ['raconter', 'anlatmak', 'ra-koñ-TE', 'Raconte-moi ta journée.', 'Bana gününü anlat.', ''],
  ['rapidement', 'hızla', 'ra-pid-MAÑ', 'Il mange rapidement.', 'Hızlı yemek yiyor.', ''],
  ['bref', 'kısa; kısacası', 'BREF', 'Bref, tout va bien.', 'Kısacası, her şey yolunda.', ''],
  ['le tribunal', 'mahkeme', 'lö tri-bü-NAL', 'Il va au tribunal demain.', 'Yarın mahkemeye gidiyor.', ''],
  ['superbe', 'muhteşem', 'sü-PERB', 'Tu es superbe ce soir !', 'Bu akşam harika görünüyorsun!', ''],
  ['obliger', 'zorlamak', 'o-bli-JE', 'Je suis obligé de partir.', 'Gitmek zorundayım.', ''],
  ['formidable', 'harika', 'for-mi-DABL', "C'est formidable !", 'Harika!', ''],
  ['la pause', 'mola', 'la POZ', 'On fait une pause ?', 'Mola verelim mi?', '☕'],
  ["l'identité (f.)", 'kimlik', 'li-dañ-ti-TE', "Votre carte d'identité, s'il vous plaît.", 'Kimlik kartınız, lütfen.', '🪪'],
];
