// En sık 1000 İtalyanca kelime (lemma), sıklık sırasıyla.
// Kaynak: FrequencyWords (Hermit Dave), OpenSubtitles 2018 — https://github.com/hermitdave/FrequencyWords — CC BY-SA 4.0.
// Bu liste o kaynaktan türetilmiştir (lemmatize edildi, Türkçe anlam/okunuş/örnek eklendi) ve CC BY-SA 4.0 lisansıyla paylaşılır.
// Biçim: [kelime, Türkçesi, okunuş, örnek cümle, örneğin Türkçesi, emoji]
window.FREQ = window.FREQ || {};
window.FREQ.it = [
  ['non', 'değil, -me/-ma', 'NON', 'Non capisco.', 'Anlamıyorum.', ''],
  ['e', 've', 'E', 'Io e te.', 'Ben ve sen.', ''],
  ['che', 'ki; ne; -den (daha)', 'KE', 'Penso che sia vero.', 'Bence doğru.', ''],
  ['di', '-in; -den', 'Dİ', 'Il libro di Marco.', "Marco'nun kitabı.", ''],
  ['il', 'belirli artikel (the)', 'İL', 'Il sole è caldo.', 'Güneş sıcak.', ''],
  ['un', 'bir (belirsiz artikel)', 'UN', 'Ho un cane.', 'Bir köpeğim var.', ''],
  ['a', '-e, -de', 'A', 'Vado a Roma.', "Roma'ya gidiyorum.", ''],
  ['per', 'için', 'PER', 'Questo è per te.', 'Bu senin için.', ''],
  ['essere', 'olmak', 'ES-se-re', 'Sono italiano.', 'İtalyanım.', ''],
  ['in', 'içinde; -de', 'İN', 'Sono in casa.', 'Evdeyim.', ''],
  ['mi', 'beni, bana', 'Mİ', 'Mi chiami domani?', 'Beni yarın arar mısın?', ''],
  ['avere', 'sahip olmak', 'a-VE-re', 'Ho una sorella.', 'Bir kız kardeşim var.', ''],
  ['si', 'kendini; (edilgen) -ilir', 'Sİ', 'Come si dice?', 'Nasıl denir?', ''],
  ['ma', 'ama', 'MA', 'Voglio venire, ma non posso.', 'Gelmek istiyorum ama gelemem.', ''],
  ['cosa', 'ne; şey', 'KO-sa', 'Cosa fai?', 'Ne yapıyorsun?', ''],
  ['con', 'ile', 'KON', 'Vengo con te.', 'Seninle geliyorum.', ''],
  ['no', 'hayır', 'NO', 'No, grazie.', 'Hayır, teşekkürler.', ''],
  ['ti', 'seni, sana', 'Tİ', 'Ti amo.', 'Seni seviyorum.', ''],
  ['se', 'eğer', 'SE', 'Se vuoi, vengo.', 'İstersen gelirim.', ''],
  ['da', '-den; -e (birine)', 'DA', 'Vengo da Milano.', "Milano'dan geliyorum.", ''],
  ['come', 'nasıl; gibi', 'KO-me', 'Come stai?', 'Nasılsın?', ''],
  ['io', 'ben', 'İ-o', 'Io sono Ahmet.', "Ben Ahmet'im.", ''],
  ['ci', 'bizi; orada', 'Çİ', 'Ci vediamo domani.', 'Yarın görüşürüz.', ''],
  ['questo', 'bu', 'KUES-to', 'Questo è mio.', 'Bu benim.', ''],
  ['bene', 'iyi (zarf)', 'BE-ne', 'Sto bene, grazie.', 'İyiyim, teşekkürler.', ''],
  ['qui', 'burada', 'KUİ', 'Abito qui.', 'Burada oturuyorum.', ''],
  ['tu', 'sen', 'TU', 'Tu come ti chiami?', 'Senin adın ne?', ''],
  ['solo', 'sadece; yalnız', 'SO-lo', 'Solo un caffè.', 'Sadece bir kahve.', ''],
  ['mio', 'benim', 'Mİ-o', 'È il mio libro.', 'Bu benim kitabım.', ''],
  ['tutto', 'her şey; bütün', 'TUT-to', 'Tutto bene?', 'Her şey yolunda mı?', ''],
  ['fare', 'yapmak', 'FA-re', 'Cosa vuoi fare?', 'Ne yapmak istiyorsun?', ''],
  ['sapere', 'bilmek', 'sa-PE-re', 'Non lo so.', 'Bilmiyorum.', ''],
  ['quando', 'ne zaman', 'KUAN-do', 'Quando parti?', 'Ne zaman gidiyorsun?', ''],
  ['sì', 'evet', 'Sİ', 'Sì, certo.', 'Evet, tabii.', ''],
  ['ora', 'şimdi', 'O-ra', 'Ora sono libero.', 'Şimdi boşum.', ''],
  ['lei', 'o (kadın); siz (nezaket)', 'LEY', 'Lei è mia sorella.', 'O benim kız kardeşim.', ''],
  ['ne', 'ondan; -den (zamir)', 'NE', 'Ne voglio due.', 'Ondan iki tane istiyorum.', ''],
  ['dire', 'söylemek, demek', 'Dİ-re', 'Cosa vuoi dire?', 'Ne demek istiyorsun?', ''],
  ['andare', 'gitmek', 'an-DA-re', 'Vado a casa.', 'Eve gidiyorum.', ''],
  ['perché', 'neden; çünkü', 'per-KE', 'Perché ridi?', 'Neden gülüyorsun?', ''],
  ['quello', 'o, şu', 'KUEL-lo', 'Quello è mio padre.', 'O benim babam.', ''],
  ['mai', 'asla, hiç', 'MAY', 'Non fumo mai.', 'Asla sigara içmem.', ''],
  ['o', 'veya', 'O', 'Oggi o domani?', 'Bugün mü yarın mı?', ''],
  ['anche', 'de, da; ayrıca', 'AN-ke', 'Vengo anche io.', 'Ben de geliyorum.', ''],
  ['grazie', 'teşekkürler', 'GRA-tsye', 'Grazie mille!', 'Çok teşekkürler!', ''],
  ['chi', 'kim', 'Kİ', 'Chi è?', 'Kim o?', ''],
  ['stare', 'durmak; olmak (hâl)', 'STA-re', 'Stiamo a casa stasera.', 'Bu akşam evde kalıyoruz.', ''],
  ['molto', 'çok', 'MOL-to', 'È molto bello.', 'Çok güzel.', ''],
  ['più', 'daha; en', 'PYU', 'Voglio più tempo.', 'Daha fazla zaman istiyorum.', ''],
  ['volere', 'istemek', 'vo-LE-re', 'Voglio un gelato.', 'Dondurma istiyorum.', ''],
  ['tuo', 'senin', 'TU-o', 'È il tuo telefono?', 'Bu senin telefonun mu?', ''],
  ['lui', 'o (erkek)', 'LUİ', 'Lui è mio fratello.', 'O benim erkek kardeşim.', ''],
  ['allora', 'o zaman; peki', 'al-LO-ra', 'Allora, andiamo?', 'O zaman gidelim mi?', ''],
  ['potere', '-ebilmek', 'po-TE-re', "Posso venire anch'io?", 'Ben de gelebilir miyim?', ''],
  ['prima', 'önce', 'PRİ-ma', 'Prima mangiamo.', 'Önce yemek yiyelim.', ''],
  ['suo', 'onun', 'SU-o', 'È la sua casa.', 'Bu onun evi.', ''],
  ['niente', 'hiçbir şey', 'NYEN-te', 'Non ho niente.', 'Hiçbir şeyim yok.', ''],
  ['qualcosa', 'bir şey', 'kual-KO-sa', 'Vuoi qualcosa da bere?', 'İçecek bir şey ister misin?', ''],
  ['così', 'böyle, öyle', 'ko-Sİ', 'Non parlare così.', 'Böyle konuşma.', ''],
  ['davvero', 'gerçekten', 'dav-VE-ro', 'Davvero? Che bello!', 'Gerçekten mi? Ne güzel!', ''],
  ['ancora', 'hâlâ; yine', 'an-KO-ra', 'Sei ancora qui?', 'Hâlâ burada mısın?', ''],
  ['la casa', 'ev', 'la KA-sa', 'La mia casa è piccola.', 'Evim küçük.', '🏠'],
  ['uno', 'bir (sayı); biri', 'U-no', 'Uno, due, tre!', 'Bir, iki, üç!', ''],
  ['dove', 'nerede, nereye', 'DO-ve', 'Dove sei?', 'Neredesin?', ''],
  ['su', 'üzerinde; yukarı', 'SU', 'Le chiavi sono sul tavolo.', 'Anahtarlar masanın üstünde.', ''],
  ['vero', 'gerçek, doğru', 'VE-ro', 'È vero?', 'Doğru mu?', ''],
  ['noi', 'biz', 'NOY', 'Noi siamo amici.', 'Biz arkadaşız.', ''],
  ['due', 'iki', 'DU-e', 'Ho due fratelli.', 'İki erkek kardeşim var.', ''],
  ['quindi', 'bu yüzden', 'KUİN-di', 'Sono stanco, quindi vado a letto.', 'Yorgunum, bu yüzden yatıyorum.', ''],
  ['sempre', 'her zaman', 'SEM-pre', 'Sei sempre in ritardo.', 'Hep geç kalıyorsun.', ''],
  ['altro', 'başka, diğer', 'AL-tro', 'Vuoi un altro caffè?', 'Bir kahve daha ister misin?', ''],
  ["un po'", 'biraz', 'un PO', "Aspetta un po'.", 'Biraz bekle.', ''],
  ['loro', 'onlar; onların', 'LO-ro', 'Loro sono qui.', 'Onlar burada.', ''],
  ['dovere', 'zorunda olmak, -meli', 'do-VE-re', 'Devo andare.', 'Gitmem lazım.', ''],
  ['forse', 'belki', 'FOR-se', 'Forse piove.', 'Belki yağmur yağar.', ''],
  ['proprio', 'tam; gerçekten; kendi', 'PRO-pryo', 'È proprio bello.', 'Gerçekten güzel.', ''],
  ['certo', 'elbette; kesin', 'ÇER-to', 'Certo, va bene.', 'Elbette, olur.', ''],
  ['il tempo', 'zaman; hava', 'il TEM-po', 'Non ho tempo.', 'Vaktim yok.', ''],
  ['poi', 'sonra', 'POY', 'Prima studio, poi esco.', 'Önce ders çalışıyorum, sonra çıkıyorum.', ''],
  ['vi', 'sizi, size', 'Vİ', 'Vi piace Roma?', "Roma'yı seviyor musunuz?", ''],
  ['credere', 'inanmak, sanmak', 'KRE-de-re', 'Credo di sì.', 'Sanırım evet.', ''],
  ['la vita', 'hayat', 'la Vİ-ta', 'La vita è bella.', 'Hayat güzel.', ''],
  ['quanto', 'ne kadar', 'KUAN-to', 'Quanto tempo hai?', 'Ne kadar vaktin var?', ''],
  ['fuori', 'dışarı(da)', 'FUO-ri', 'Andiamo fuori.', 'Dışarı çıkalım.', ''],
  ["l'anno (m.)", 'yıl', 'LAN-no', "Quest'anno vado in Italia.", "Bu yıl İtalya'ya gidiyorum.", ''],
  ['cui', 'ki (o) (ilgi zamiri)', 'KUİ', 'La città in cui vivo.', 'Yaşadığım şehir.', ''],
  ['la parte', 'parça, kısım', 'la PAR-te', 'Una parte è mia.', 'Bir kısmı benim.', ''],
  ['vedere', 'görmek', 've-DE-re', 'Non vedo niente.', 'Hiçbir şey göremiyorum.', ''],
  ['qualcuno', 'biri', 'kual-KU-no', "C'è qualcuno?", 'Kimse var mı?', ''],
  ['il lavoro', 'iş', 'il la-VO-ro', 'Vado al lavoro.', 'İşe gidiyorum.', ''],
  ['voi', 'siz', 'VOY', 'Voi siete italiani?', 'Siz İtalyan mısınız?', ''],
  ['ciao', 'merhaba; hoşça kal', 'ÇAO', 'Ciao, come stai?', 'Selam, nasılsın?', ''],
  ['Dio', 'Tanrı', 'Dİ-o', 'Grazie a Dio!', 'Tanrıya şükür!', ''],
  ['la volta', 'kez, sefer', 'la VOL-ta', 'Ancora una volta.', 'Bir kez daha.', ''],
  ['dopo', 'sonra', 'DO-po', 'Ci vediamo dopo.', 'Sonra görüşürüz.', ''],
  ['adesso', 'şimdi', 'a-DES-so', 'Adesso arrivo.', 'Şimdi geliyorum.', ''],
  ["l'uomo (m.)", 'adam; insan', 'LUO-mo', "Quell'uomo è alto.", 'O adam uzun boylu.', '👨'],
  ['il padre', 'baba', 'il PA-dre', 'Mio padre lavora molto.', 'Babam çok çalışıyor.', ''],
  ['il bisogno', 'ihtiyaç', 'il bi-SON-yo', 'Ho bisogno di aiuto.', 'Yardıma ihtiyacım var.', ''],
  ['già', 'zaten, çoktan', 'CA', "L'ho già fatto.", 'Onu zaten yaptım.', ''],
  ["l'amico (m.)", 'arkadaş', 'la-Mİ-ko', 'Lui è un vecchio amico.', 'O eski bir arkadaş.', ''],
  ['il posto', 'yer', 'il POS-to', 'Questo posto è libero?', 'Bu yer boş mu?', ''],
  ['nessuno', 'hiç kimse', 'nes-SU-no', "Non c'è nessuno.", 'Kimse yok.', ''],
  ['via', 'uzağa; yol', 'Vİ-a', 'Vai via!', 'Git buradan!', ''],
  ['il signore', 'bey, beyefendi', 'il si-NYO-re', 'Buongiorno, signore.', 'Günaydın, beyefendi.', ''],
  ['meglio', 'daha iyi', 'ME-lyo', 'Sto meglio oggi.', 'Bugün daha iyiyim.', ''],
  ['sembrare', 'görünmek', 'sem-BRA-re', 'Sembri stanco.', 'Yorgun görünüyorsun.', ''],
  ['il giorno', 'gün', 'il COR-no', 'Che giorno è oggi?', 'Bugün günlerden ne?', ''],
  ['ogni', 'her', 'ON-yi', 'Ogni giorno studio.', 'Her gün ders çalışıyorum.', ''],
  ['il modo', 'yol, biçim', 'il MO-do', 'In che modo?', 'Ne şekilde?', ''],
  ['senza', '-sız, olmadan', 'SEN-tsa', 'Caffè senza zucchero.', 'Şekersiz kahve.', ''],
  ['qualche', 'birkaç, bazı', 'KUAL-ke', 'Qualche volta esco.', 'Bazen dışarı çıkarım.', ''],
  ['dispiacere', 'üzülmek; gücüne gitmek', 'dis-pya-ÇE-re', 'Mi dispiace molto.', 'Çok üzgünüm.', ''],
  ['pensare', 'düşünmek', 'pen-SA-re', 'Penso a te.', 'Seni düşünüyorum.', ''],
  ['ecco', 'işte', 'EK-ko', 'Ecco il tuo caffè.', 'İşte kahven.', ''],
  ['parlare', 'konuşmak', 'par-LA-re', 'Parli italiano?', 'İtalyanca konuşuyor musun?', ''],
  ['tra', 'arasında; içinde (zaman)', 'TRA', 'Il bar è tra due negozi.', 'Bar iki dükkân arasında.', ''],
  ['la mamma', 'anne', 'la MAM-ma', 'Ciao, mamma!', 'Selam anne!', ''],
  ['troppo', 'fazla, çok', 'TROP-po', 'È troppo caro.', 'Çok pahalı.', ''],
  ['nuovo', 'yeni', 'NUO-vo', 'Ho un telefono nuovo.', 'Yeni bir telefonum var.', ''],
  ['male', 'kötü (zarf); ağrı', 'MA-le', 'Mi sento male.', 'Kendimi kötü hissediyorum.', ''],
  ['la madre', 'anne', 'la MA-dre', 'Mia madre è gentile.', 'Annem nazik.', ''],
  ['tanto', 'çok; o kadar', 'TAN-to', 'Ti voglio tanto bene.', 'Seni çok seviyorum.', ''],
  ['il favore', 'iyilik', 'il fa-VO-re', 'Per favore, aiutami.', 'Lütfen bana yardım et.', ''],
  ['succedere', 'olmak, meydana gelmek', 'suç-ÇE-de-re', 'Cosa è successo?', 'Ne oldu?', ''],
  ['giusto', 'doğru, haklı', 'CUS-to', 'Hai ragione, è giusto.', 'Haklısın, doğru.', ''],
  ['aspettare', 'beklemek', 'as-pet-TA-re', 'Ti aspetto qui.', 'Seni burada bekliyorum.', ''],
  ['il momento', 'an', 'il mo-MEN-to', 'Un momento, per favore.', 'Bir dakika lütfen.', ''],
  ['il ragazzo', 'oğlan; genç; erkek arkadaş', 'il ra-GAT-tso', 'Il ragazzo gioca a calcio.', 'Çocuk futbol oynuyor.', '👦'],
  ['la persona', 'kişi', 'la per-SO-na', 'È una brava persona.', 'İyi bir insan.', '🧑'],
  ['nostro', 'bizim', 'NOS-tro', 'Questa è la nostra casa.', 'Bu bizim evimiz.', ''],
  ['il tipo', 'tip, tür; herif', 'il Tİ-po', 'Che tipo di musica ascolti?', 'Ne tür müzik dinliyorsun?', ''],
  ['prego', 'rica ederim; buyurun', 'PRE-go', 'Grazie! – Prego.', 'Teşekkürler! – Rica ederim.', ''],
  ['grande', 'büyük', 'GRAN-de', 'La casa è grande.', 'Ev büyük.', ''],
  ['sentire', 'duymak; hissetmek', 'sen-Tİ-re', 'Senti questa musica!', 'Bu müziği dinle!', ''],
  ['appena', 'henüz; az önce', 'ap-PE-na', 'Sono appena arrivato.', 'Az önce geldim.', ''],
  ['i soldi', 'para', 'i SOL-di', 'Non ho soldi.', 'Hiç param yok.', '💰'],
  ['tre', 'üç', 'TRE', 'Ho tre gatti.', 'Üç kedim var.', ''],
  ['oggi', 'bugün', 'OC-ci', 'Oggi è lunedì.', 'Bugün pazartesi.', ''],
  ['piacere', 'hoşa gitmek; memnun oldum', 'pya-ÇE-re', 'Ti piace il gelato?', 'Dondurmayı sever misin?', ''],
  ["l'idea (f.)", 'fikir', 'li-DE-a', 'Che bella idea!', 'Ne güzel fikir!', ''],
  ['il figlio', 'oğul', 'il Fİ-lyo', 'Mio figlio ha sei anni.', 'Oğlum altı yaşında.', ''],
  ["l'accordo (m.)", 'anlaşma', 'lak-KOR-do', "Sono d'accordo.", 'Katılıyorum.', ''],
  ['la gente', 'insanlar', 'la CEN-te', "C'è molta gente qui.", 'Burada çok insan var.', ''],
  ['sicuro', 'emin; güvenli', 'si-KU-ro', 'Sei sicuro?', 'Emin misin?', ''],
  ['venire', 'gelmek', 've-Nİ-re', 'Vieni con me?', 'Benimle geliyor musun?', ''],
  ['guardare', 'bakmak, izlemek', 'guar-DA-re', 'Guarda il mare!', 'Denize bak!', ''],
  ['dentro', 'içeride', 'DEN-tro', 'Vieni dentro!', 'İçeri gel!', ''],
  ['trovare', 'bulmak', 'tro-VA-re', 'Non trovo le chiavi.', 'Anahtarları bulamıyorum.', ''],
  ['il caso', 'durum; tesadüf', 'il KA-so', 'In ogni caso, grazie.', 'Her durumda teşekkürler.', ''],
  ['la forza', 'güç', 'la FOR-tsa', 'Forza, puoi farcela!', 'Haydi, başarabilirsin!', ''],
  ['la signora', 'hanım, bayan', 'la si-NYO-ra', 'La signora Rossi è gentile.', 'Rossi Hanım nazik.', ''],
  ['il nome', 'isim', 'il NO-me', 'Qual è il tuo nome?', 'Adın ne?', ''],
  ['il problema', 'sorun', 'il pro-BLE-ma', 'Nessun problema!', 'Sorun değil!', ''],
  ['il mondo', 'dünya', 'il MON-do', 'Il mondo è grande.', 'Dünya büyük.', '🌍'],
  ['prendere', 'almak', 'PREN-de-re', 'Prendo un caffè.', 'Bir kahve alıyorum.', ''],
  ['nulla', 'hiçbir şey', 'NUL-la', 'Non fa nulla.', 'Önemli değil.', ''],
  ['la donna', 'kadın', 'la DON-na', 'Quella donna è mia zia.', 'O kadın benim teyzem.', '👩'],
  ['bastare', 'yetmek', 'bas-TA-re', 'Basta così, grazie.', 'Bu kadar yeter, teşekkürler.', ''],
  ['insieme', 'birlikte', 'in-SYE-me', 'Mangiamo insieme?', 'Birlikte yiyelim mi?', ''],
  ['la ragazza', 'kız; kız arkadaş', 'la ra-GAT-tsa', 'La ragazza legge un libro.', 'Kız bir kitap okuyor.', '👧'],
  ['subito', 'hemen', 'SU-bi-to', 'Vengo subito.', 'Hemen geliyorum.', ''],
  ['la famiglia', 'aile', 'la fa-Mİ-lya', 'Amo la mia famiglia.', 'Ailemi seviyorum.', '👪'],
  ['stesso', 'aynı', 'STES-so', 'Abbiamo la stessa età.', 'Aynı yaştayız.', ''],
  ['la ragione', 'sebep; haklılık', 'la ra-CO-ne', 'Hai ragione.', 'Haklısın.', ''],
  ['capire', 'anlamak', 'ka-Pİ-re', "Capisci l'italiano?", 'İtalyanca anlıyor musun?', ''],
  ['la notte', 'gece', 'la NOT-te', 'Di notte dormo.', 'Geceleri uyurum.', ''],
  ['la testa', 'baş, kafa', 'la TES-ta', 'Ho mal di testa.', 'Başım ağrıyor.', ''],
  ['servire', 'işe yaramak; gerekmek', 'ser-Vİ-re', 'Ti serve aiuto?', 'Yardıma ihtiyacın var mı?', ''],
  ['il tesoro', 'hazine; tatlım', 'il te-SO-ro', 'Ciao, tesoro!', 'Selam tatlım!', ''],
  ['sotto', 'altında', 'SOT-to', 'Il gatto è sotto il tavolo.', 'Kedi masanın altında.', ''],
  ['bello', 'güzel', 'BEL-lo', 'Che bella giornata!', 'Ne güzel bir gün!', ''],
  ['scusare', 'affetmek', 'sku-SA-re', "Scusa, dov'è il bagno?", 'Pardon, tuvalet nerede?', ''],
  ['buono', 'iyi; lezzetli', 'BUO-no', 'Questa pizza è buona.', 'Bu pizza lezzetli.', ''],
  ['la porta', 'kapı', 'la POR-ta', 'Qualcuno bussa alla porta.', 'Biri kapıyı çalıyor.', '🚪'],
  ['la moglie', 'eş (kadın), karı', 'la MO-lye', 'Mia moglie è medico.', 'Karım doktor.', ''],
  ['la storia', 'hikâye; tarih', 'la STO-rya', 'È una lunga storia.', 'Uzun bir hikâye.', ''],
  ['morire', 'ölmek', 'mo-Rİ-re', 'Il pesce è morto.', 'Balık öldü.', ''],
  ['cercare', 'aramak', 'çer-KA-re', 'Cerco il mio telefono.', 'Telefonumu arıyorum.', ''],
  ['pronto', 'hazır; alo', 'PRON-to', 'Pronto? Chi parla?', 'Alo? Kim konuşuyor?', ''],
  ['meno', 'daha az', 'ME-no', 'Parla meno e ascolta.', 'Daha az konuş ve dinle.', ''],
  ['avanti', 'ileri; buyurun', 'a-VAN-ti', 'Avanti, entra!', 'Buyur, gir!', ''],
  ['secondo', 'ikinci; -e göre', 'se-KON-do', 'Secondo me, è giusto.', 'Bence doğru.', ''],
  ['la polizia', 'polis', 'la po-li-TSİ-a', 'Chiama la polizia!', 'Polisi ara!', '🚓'],
  ['lì', 'orada', 'Lİ', 'Il bar è lì.', 'Bar orada.', ''],
  ['mentre', '-iken', 'MEN-tre', 'Canto mentre cucino.', 'Yemek yaparken şarkı söylerim.', ''],
  ['il letto', 'yatak', 'il LET-to', 'Vado a letto.', 'Yatmaya gidiyorum.', '🛏️'],
  ['fino', '-e kadar', 'Fİ-no', 'Lavoro fino alle sei.', 'Altıya kadar çalışıyorum.', ''],
  ['la fine', 'son', 'la Fİ-ne', 'È la fine del film.', 'Filmin sonu.', ''],
  ["l'aiuto (m.)", 'yardım', 'la-YU-to', 'Aiuto!', 'İmdat!', ''],
  ['la paura', 'korku', 'la pa-U-ra', 'Non avere paura.', 'Korkma.', ''],
  ['il fratello', 'erkek kardeş', 'il fra-TEL-lo', 'Mio fratello è alto.', 'Erkek kardeşim uzun boylu.', ''],
  ['domani', 'yarın', 'do-MA-ni', 'A domani!', 'Yarın görüşürüz!', ''],
  ['abbastanza', 'yeterince', 'ab-bas-TAN-tsa', 'Ho mangiato abbastanza.', 'Yeterince yedim.', ''],
  ['il capo', 'patron, şef; baş', 'il KA-po', 'Il capo è in ufficio.', 'Patron ofiste.', ''],
  ["l'amore (m.)", 'aşk, sevgi', 'la-MO-re', "L'amore è bello.", 'Aşk güzeldir.', ''],
  ['uccidere', 'öldürmek', 'uç-Çİ-de-re', 'Non uccidere le api.', 'Arıları öldürme.', ''],
  ['piano', 'yavaşça', 'PYA-no', 'Parla piano, per favore.', 'Yavaş konuş lütfen.', ''],
  ['la macchina', 'araba; makine', 'la MAK-ki-na', 'La mia macchina è rossa.', 'Arabam kırmızı.', '🚗'],
  ['comunque', 'yine de; neyse', 'ko-MUN-kue', 'Grazie comunque.', 'Yine de teşekkürler.', ''],
  ['nemmeno', 'bile değil', 'nem-ME-no', 'Non ho nemmeno un euro.', 'Bir avrom bile yok.', ''],
  ['la mano', 'el', 'la MA-no', 'Dammi la mano.', 'Elini ver.', '✋'],
  ['presto', 'erken; yakında', 'PRES-to', 'A presto!', 'Yakında görüşürüz!', ''],
  ['il bambino', 'çocuk', 'il bam-Bİ-no', 'Il bambino dorme.', 'Çocuk uyuyor.', '👶'],
  ['tornare', 'dönmek', 'tor-NA-re', 'Torno a casa alle otto.', 'Saat sekizde eve dönüyorum.', ''],
  ['ciò', 'bu, o (şey)', 'ÇO', 'Ciò che dici è vero.', 'Söylediğin doğru.', ''],
  ['primo', 'birinci, ilk', 'PRİ-mo', 'È il mio primo giorno.', 'Bu benim ilk günüm.', ''],
  ['vostro', 'sizin', 'VOS-tro', 'È la vostra macchina?', 'Bu sizin arabanız mı?', ''],
  ['neanche', 'bile değil; ... de değil', 'ne-AN-ke', 'Neanche io lo so.', 'Ben de bilmiyorum.', ''],
  ['la sera', 'akşam', 'la SE-ra', 'Di sera leggo un libro.', 'Akşamları kitap okurum.', ''],
  ['il giro', 'tur; dolaşma', 'il Cİ-ro', 'Facciamo un giro?', 'Bir tur atalım mı?', ''],
  ['la morte', 'ölüm', 'la MOR-te', 'Ha paura della morte.', 'Ölümden korkuyor.', ''],
  ['qua', 'burada', 'KUA', 'Vieni qua!', 'Buraya gel!', ''],
  ['il diavolo', 'şeytan', 'il DYA-vo-lo', 'Il diavolo è nei dettagli.', 'Şeytan ayrıntılarda gizlidir.', '😈'],
  ['quasi', 'neredeyse', 'KUA-si', 'Sono quasi pronto.', 'Neredeyse hazırım.', ''],
  ['contro', 'karşı', 'KON-tro', 'Sono contro la guerra.', 'Savaşa karşıyım.', ''],
  ['felice', 'mutlu', 'fe-Lİ-çe', 'Sono molto felice.', 'Çok mutluyum.', ''],
  ['la colpa', 'suç, kabahat', 'la KOL-pa', 'Non è colpa mia.', 'Benim suçum değil.', ''],
  ['il punto', 'nokta', 'il PUN-to', 'Questo è il punto.', 'Mesele bu.', ''],
  ['quale', 'hangi', 'KUA-le', 'Quale preferisci?', 'Hangisini tercih edersin?', ''],
  ['chiedere', 'sormak, istemek', 'KYE-de-re', 'Posso chiedere una cosa?', 'Bir şey sorabilir miyim?', ''],
  ['invece', 'oysa; yerine', 'in-VE-çe', 'Io invece resto qui.', 'Ben ise burada kalıyorum.', ''],
  ['migliore', 'daha iyi; en iyi', 'mi-LYO-re', 'Sei il mio migliore amico.', 'Sen benim en iyi arkadaşımsın.', ''],
  ['finire', 'bitirmek, bitmek', 'fi-Nİ-re', 'Il film è finito.', 'Film bitti.', ''],
  ['la figlia', 'kız evlat', 'la Fİ-lya', 'Mia figlia studia medicina.', 'Kızım tıp okuyor.', ''],
  ['il papà', 'baba', 'il pa-PA', 'Papà, vieni qui!', 'Baba, buraya gel!', ''],
  ['almeno', 'en azından', 'al-ME-no', 'Almeno provaci.', 'En azından dene.', ''],
  ["l'ora (f.)", 'saat', 'LO-ra', 'Che ore sono?', 'Saat kaç?', ''],
  ['passare', 'geçmek; uğramak', 'pas-SA-re', 'Passo da te stasera.', 'Bu akşam sana uğrarım.', ''],
  ['magari', 'belki; keşke', 'ma-GA-ri', 'Magari domani.', 'Belki yarın.', ''],
  ['il minuto', 'dakika', 'il mi-NU-to', 'Arrivo tra cinque minuti.', 'Beş dakikaya geliyorum.', ''],
  ['la terra', 'toprak; dünya', 'la TER-ra', 'La terra è bagnata.', 'Toprak ıslak.', ''],
  ['la strada', 'yol, sokak', 'la STRA-da', 'Attraversa la strada.', 'Yolun karşısına geç.', '🛣️'],
  ['importante', 'önemli', 'im-por-TAN-te', 'È molto importante.', 'Çok önemli.', ''],
  ['salve', 'merhaba', 'SAL-ve', 'Salve, posso entrare?', 'Merhaba, girebilir miyim?', ''],
  ['la settimana', 'hafta', 'la set-ti-MA-na', 'Lavoro cinque giorni a settimana.', 'Haftada beş gün çalışıyorum.', ''],
  ['perdere', 'kaybetmek', 'PER-de-re', 'Ho perso le chiavi.', 'Anahtarları kaybettim.', ''],
  ['uscire', 'çıkmak', 'uş-Şİ-re', 'Esco con gli amici.', 'Arkadaşlarla dışarı çıkıyorum.', ''],
  ['stasera', 'bu akşam', 'sta-SE-ra', 'Cosa fai stasera?', 'Bu akşam ne yapıyorsun?', ''],
  ['il dollaro', 'dolar', 'il DOL-la-ro', 'Costa dieci dollari.', 'On dolar tutuyor.', '💵'],
  ["l'occhio (m.)", 'göz', 'LOK-kyo', 'Ha gli occhi azzurri.', 'Mavi gözleri var.', '👁️'],
  ['ultimo', 'son', 'UL-ti-mo', "È l'ultimo treno.", 'Bu son tren.', ''],
  ['possibile', 'mümkün', 'pos-Sİ-bi-le', 'Non è possibile!', 'Mümkün değil!', ''],
  ['la scuola', 'okul', 'la SKUO-la', 'Vado a scuola.', 'Okula gidiyorum.', '🏫'],
  ['significare', 'anlamına gelmek', 'si-nyi-fi-KA-re', 'Cosa significa?', 'Ne anlama geliyor?', ''],
  ['importare', 'önemli olmak', 'im-por-TA-re', 'Non importa.', 'Önemli değil.', ''],
  ['indietro', 'geri', 'in-DYE-tro', 'Torna indietro!', 'Geri dön!', ''],
  ['riuscire', 'başarmak, -ebilmek', 'ri-uş-Şİ-re', 'Non riesco a dormire.', 'Uyuyamıyorum.', ''],
  ['il sangue', 'kan', 'il SAN-gue', 'Ho paura del sangue.', 'Kandan korkarım.', '🩸'],
  ['chiamare', 'çağırmak, aramak', 'kya-MA-re', 'Ti chiamo stasera.', 'Bu akşam seni ararım.', ''],
  ['mettere', 'koymak', 'MET-te-re', 'Metti il latte in frigo.', 'Sütü buzdolabına koy.', ''],
  ['piccolo', 'küçük', 'PİK-ko-lo', 'Ho un cane piccolo.', 'Küçük bir köpeğim var.', ''],
  ['la traduzione', 'çeviri', 'la tra-du-TSYO-ne', 'La traduzione è corretta.', 'Çeviri doğru.', ''],
  ['tardi', 'geç', 'TAR-di', 'È tardi, andiamo.', 'Geç oldu, gidelim.', ''],
  ['il cuore', 'kalp', 'il KUO-re', 'Hai un grande cuore.', 'Büyük bir kalbin var.', '❤️'],
  ['il marito', 'koca', 'il ma-Rİ-to', 'Mio marito cucina bene.', 'Kocam iyi yemek yapar.', ''],
  ['ieri', 'dün', 'YE-ri', 'Ieri ho lavorato.', 'Dün çalıştım.', ''],
  ['sperare', 'ummak', 'spe-RA-re', 'Spero di sì.', 'Umarım öyledir.', ''],
  ['ricordare', 'hatırlamak', 'ri-kor-DA-re', 'Ti ricordi di me?', 'Beni hatırlıyor musun?', ''],
  ['lasciare', 'bırakmak', 'laş-ŞA-re', 'Lasciami in pace.', 'Beni rahat bırak.', ''],
  ['ascoltare', 'dinlemek', 'as-kol-TA-re', 'Ascolto la radio.', 'Radyo dinliyorum.', ''],
  ['difficile', 'zor', 'dif-Fİ-çi-le', "L'italiano non è difficile.", 'İtalyanca zor değil.', ''],
  ["l'auto (f.)", 'otomobil', 'LAU-to', "L'auto è nel garage.", 'Otomobil garajda.', ''],
  ['fantastico', 'harika', 'fan-TAS-ti-ko', "È un'idea fantastica!", 'Harika bir fikir!', ''],
  ['il numero', 'sayı; numara', 'il NU-me-ro', 'Qual è il tuo numero?', 'Numaran ne?', ''],
  ['veramente', 'gerçekten', 've-ra-MEN-te', 'È veramente buono.', 'Gerçekten lezzetli.', ''],
  ['serio', 'ciddi', 'SE-ryo', 'Sei serio?', 'Ciddi misin?', ''],
  ['entrare', 'girmek', 'en-TRA-re', 'Entra pure!', 'Gir tabii!', ''],
  ['qualsiasi', 'herhangi', 'kual-Sİ-a-si', 'Chiamami a qualsiasi ora.', 'Beni herhangi bir saatte ara.', ''],
  ["l'acqua (f.)", 'su', 'LAK-kua', "Un bicchiere d'acqua, per favore.", 'Bir bardak su lütfen.', '💧'],
  ['portare', 'getirmek, götürmek', 'por-TA-re', 'Porto io il vino.', 'Şarabı ben getiriyorum.', ''],
  ['la stanza', 'oda', 'la STAN-tsa', 'La mia stanza è piccola.', 'Odam küçük.', ''],
  ['forte', 'güçlü; yüksek sesle', 'FOR-te', 'Sei molto forte.', 'Çok güçlüsün.', ''],
  ['amare', 'sevmek', 'a-MA-re', "Amo l'Italia.", "İtalya'yı seviyorum.", ''],
  ['la roba', 'eşya, şey', 'la RO-ba', 'Prendi la tua roba.', 'Eşyalarını al.', ''],
  ["l'agente (m.)", 'ajan; polis memuru', 'la-CEN-te', "L'agente ferma la macchina.", 'Polis arabayı durduruyor.', ''],
  ['dietro', 'arkasında', 'DYE-tro', 'Il bagno è dietro la porta.', 'Tuvalet kapının arkasında.', ''],
  ['il corpo', 'vücut, beden', 'il KOR-po', 'Lo sport fa bene al corpo.', 'Spor vücuda iyi gelir.', ''],
  ['parere', 'görünmek; fikir', 'pa-RE-re', 'Mi pare giusto.', 'Bana doğru görünüyor.', ''],
  ['la foto', 'fotoğraf', 'la FO-to', 'Facciamo una foto!', 'Bir fotoğraf çekelim!', '📷'],
  ['il telefono', 'telefon', 'il te-LE-fo-no', 'Il telefono squilla.', 'Telefon çalıyor.', '☎️'],
  ['poco', 'az', 'PO-ko', 'Mangio poco la sera.', 'Akşamları az yerim.', ''],
  ['vicino', 'yakın; yanında', 'vi-Çİ-no', 'Abito vicino al mare.', 'Denize yakın oturuyorum.', ''],
  ['il sacco', 'çuval; torba', 'il SAK-ko', 'Un sacco di gente.', 'Bir sürü insan.', ''],
  ['cinque', 'beş', 'ÇİN-kue', 'Ho cinque euro.', 'Beş avrom var.', ''],
  ['strano', 'garip', 'STRA-no', 'Che strano!', 'Ne tuhaf!', ''],
  ['bravo', 'iyi, yetenekli; aferin', 'BRA-vo', 'Bravo, ottimo lavoro!', 'Aferin, harika iş!', ''],
  ['la festa', 'parti; bayram', 'la FES-ta', 'Vieni alla festa?', 'Partiye geliyor musun?', '🎉'],
  ['il senso', 'anlam; his', 'il SEN-so', 'Non ha senso.', 'Mantıklı değil.', ''],
  ['il genere', 'tür; cinsiyet', 'il CE-ne-re', 'Che genere di film ti piace?', 'Ne tür filmlerden hoşlanırsın?', ''],
  ['quattro', 'dört', 'KUAT-tro', 'Siamo in quattro.', 'Dört kişiyiz.', ''],
  ['dare', 'vermek', 'DA-re', 'Mi dai il sale?', 'Tuzu verir misin?', ''],
  ["l'attimo (m.)", 'an', 'LAT-ti-mo', 'Aspetta un attimo.', 'Bir saniye bekle.', ''],
  ['la sorella', 'kız kardeş', 'la so-REL-la', "Mia sorella ha vent'anni.", 'Kız kardeşim yirmi yaşında.', ''],
  ['pure', 'de; tabii', 'PU-re', 'Vieni pure tu.', 'Sen de gel.', ''],
  ['probabilmente', 'muhtemelen', 'pro-ba-bil-MEN-te', 'Probabilmente piove.', 'Muhtemelen yağmur yağacak.', ''],
  ['il film', 'film', 'il FİLM', 'Stasera guardiamo un film.', 'Bu akşam film izliyoruz.', '🎞️'],
  ["l'ufficio (m.)", 'ofis', 'luf-Fİ-ço', 'Sono in ufficio.', 'Ofisteyim.', ''],
  ['verso', '-e doğru', 'VER-so', 'Andiamo verso il centro.', 'Merkeze doğru gidiyoruz.', ''],
  ['il mese', 'ay', 'il ME-se', 'Il prossimo mese vado a Roma.', "Gelecek ay Roma'ya gidiyorum.", ''],
  ['unico', 'tek, eşsiz', 'U-ni-ko', 'Sei unico!', 'Sen eşsizsin!', ''],
  ['la signorina', 'genç hanım', 'la si-nyo-Rİ-na', 'Grazie, signorina.', 'Teşekkürler hanımefendi.', ''],
  ['vecchio', 'yaşlı; eski', 'VEK-kyo', 'Mio nonno è vecchio.', 'Dedem yaşlı.', ''],
  ['la domanda', 'soru', 'la do-MAN-da', 'Ho una domanda.', 'Bir sorum var.', ''],
  ['la guerra', 'savaş', 'la GUER-ra', 'La guerra è terribile.', 'Savaş korkunçtur.', ''],
  ['il dottore', 'doktor', 'il dot-TO-re', 'Devo andare dal dottore.', 'Doktora gitmem lazım.', '🧑‍⚕️'],
  ['conoscere', 'tanımak, bilmek', 'ko-NOŞ-şe-re', 'Piacere di conoscerti!', 'Tanıştığıma memnun oldum!', ''],
  ['vivere', 'yaşamak', 'Vİ-ve-re', 'Vivo a Istanbul.', "İstanbul'da yaşıyorum.", ''],
  ['la vista', 'manzara; görme', 'la VİS-ta', 'Che bella vista!', 'Ne güzel manzara!', ''],
  ['la prova', 'kanıt; deneme', 'la PRO-va', 'Non ci sono prove.', 'Kanıt yok.', ''],
  ['divertente', 'eğlenceli, komik', 'di-ver-TEN-te', 'Il film è divertente.', 'Film eğlenceli.', ''],
  ['il paio', 'çift', 'il PA-yo', 'Un paio di scarpe.', 'Bir çift ayakkabı.', ''],
  ['il conto', 'hesap', 'il KON-to', 'Il conto, per favore.', 'Hesap lütfen.', '🧾'],
  ['mezzo', 'yarım; orta', 'MED-dzo', 'Sono le due e mezzo.', 'Saat iki buçuk.', ''],
  ['lavorare', 'çalışmak', 'la-vo-RA-re', 'Lavoro in un negozio.', 'Bir dükkânda çalışıyorum.', ''],
  ['esattamente', 'tam olarak', 'e-sat-ta-MEN-te', 'Esattamente come dici tu.', 'Tam söylediğin gibi.', ''],
  ['la squadra', 'takım', 'la SKUA-dra', 'La mia squadra ha vinto.', 'Takımım kazandı.', ''],
  ['esatto', 'tam, doğru', 'e-SAT-to', 'Esatto, è così!', 'Aynen, öyle!', ''],
  ['la parola', 'kelime', 'la pa-RO-la', 'Non capisco questa parola.', 'Bu kelimeyi anlamıyorum.', ''],
  ['il piede', 'ayak', 'il PYE-de', 'Vado a piedi.', 'Yürüyerek gidiyorum.', '🦶'],
  ['sopra', 'üstünde', 'SO-pra', 'Il libro è sopra il tavolo.', 'Kitap masanın üstünde.', ''],
  ['il motivo', 'sebep', 'il mo-Tİ-vo', 'Per quale motivo?', 'Ne sebeple?', ''],
  ['il cavolo', 'lahana', 'il KA-vo-lo', 'Non mi piace il cavolo.', 'Lahanayı sevmem.', '🥬'],
  ['il capitano', 'kaptan', 'il ka-pi-TA-no', 'Il capitano è sulla nave.', 'Kaptan gemide.', ''],
  ['il gioco', 'oyun', 'il CO-ko', 'È solo un gioco.', 'Sadece bir oyun.', '🎲'],
  ['perfetto', 'mükemmel', 'per-FET-to', 'Perfetto, grazie!', 'Mükemmel, teşekkürler!', ''],
  ['la mente', 'zihin, akıl', 'la MEN-te', 'Rilassa la mente.', 'Zihnini rahatlat.', ''],
  ['mangiare', 'yemek yemek', 'man-CA-re', 'Mangiamo la pasta.', 'Makarna yiyoruz.', ''],
  ['il resto', 'kalan; para üstü', 'il RES-to', 'Tenga il resto.', 'Üstü kalsın.', ''],
  ['la fortuna', 'şans', 'la for-TU-na', 'Buona fortuna!', 'Bol şans!', ''],
  ['trattare', 'davranmak; ele almak', 'trat-TA-re', 'Di cosa si tratta?', 'Konu ne?', ''],
  ['là', 'orada', 'LA', 'Metti la borsa là.', 'Çantayı oraya koy.', ''],
  ['entrambi', 'her ikisi', 'en-TRAM-bi', 'Entrambi parlano inglese.', 'İkisi de İngilizce konuşuyor.', ''],
  ['la cena', 'akşam yemeği', 'la ÇE-na', 'La cena è pronta.', 'Akşam yemeği hazır.', ''],
  ['il controllo', 'kontrol', 'il kon-TROL-lo', 'Tutto sotto controllo.', 'Her şey kontrol altında.', ''],
  ["l'affare (m.)", 'iş; fırsat', 'laf-FA-re', 'È un buon affare.', 'İyi bir fırsat.', ''],
  ['facile', 'kolay', 'FA-çi-le', 'È facile!', 'Kolay!', ''],
  ['buongiorno', 'günaydın', 'buon-COR-no', 'Buongiorno, un caffè per favore.', 'Günaydın, bir kahve lütfen.', ''],
  ['davanti', 'önünde', 'da-VAN-ti', 'Ti aspetto davanti al bar.', 'Seni barın önünde bekliyorum.', ''],
  ['il tizio', 'herif, adam', 'il Tİ-tsyo', 'Chi è quel tizio?', 'O adam kim?', ''],
  ['la sicurezza', 'güvenlik', 'la si-ku-RET-tsa', 'La sicurezza è importante.', 'Güvenlik önemlidir.', ''],
  ['il matrimonio', 'düğün; evlilik', 'il ma-tri-MO-nyo', 'Il matrimonio è a giugno.', 'Düğün haziranda.', '💒'],
  ['il fuoco', 'ateş', 'il FUO-ko', 'Attento al fuoco!', 'Ateşe dikkat!', '🔥'],
  ['la pistola', 'tabanca', 'la pis-TO-la', 'Il poliziotto ha una pistola.', 'Polisin bir tabancası var.', '🔫'],
  ['il re', 'kral', 'il RE', 'Il re e la regina.', 'Kral ve kraliçe.', '🤴'],
  ['mandare', 'göndermek', 'man-DA-re', 'Ti mando un messaggio.', 'Sana bir mesaj gönderiyorum.', ''],
  ['cioè', 'yani', 'ço-E', 'Domani, cioè sabato.', 'Yarın, yani cumartesi.', ''],
  ["l'inizio (m.)", 'başlangıç', 'li-Nİ-tsyo', "All'inizio è difficile.", 'Başta zor.', ''],
  ['la causa', 'sebep; dava', 'la KAU-sa', 'Qual è la causa?', 'Sebebi ne?', ''],
  ['la voglia', 'istek, heves', 'la VO-lya', 'Ho voglia di un gelato.', 'Canım dondurma istiyor.', ''],
  ['però', 'ama, fakat', 'pe-RO', 'È caro, però è bello.', 'Pahalı ama güzel.', ''],
  ['il genitore', 'ebeveyn', 'il ce-ni-TO-re', 'I miei genitori vivono a Izmir.', "Annemle babam İzmir'de yaşıyor.", ''],
  ['il sesso', 'cinsiyet; seks', 'il SES-so', 'Nome, età e sesso?', 'İsim, yaş ve cinsiyet?', ''],
  ['ricevere', 'almak (gelen)', 'ri-ÇE-ve-re', 'Ho ricevuto la tua lettera.', 'Mektubunu aldım.', ''],
  ['vivo', 'canlı, diri', 'Vİ-vo', 'Il pesce è ancora vivo.', 'Balık hâlâ canlı.', ''],
  ['il presidente', 'başkan', 'il pre-si-DEN-te', 'Il presidente parla oggi.', 'Başkan bugün konuşuyor.', ''],
  ['la città', 'şehir', 'la çit-TA', 'Roma è una bella città.', 'Roma güzel bir şehir.', '🏙️'],
  ["l'ospedale (m.)", 'hastane', 'los-pe-DA-le', 'Mio padre è in ospedale.', 'Babam hastanede.', '🏥'],
  ['scrivere', 'yazmak', 'SKRİ-ve-re', 'Scrivo una mail a Luca.', "Luca'ya bir e-posta yazıyorum.", ''],
  ['smettere', 'bırakmak (bir alışkanlığı)', 'SMET-te-re', 'Smetti di fumare!', 'Sigarayı bırak!', ''],
  ["l'attenzione (f.)", 'dikkat', 'lat-ten-TSYO-ne', 'Attenzione, il pavimento è bagnato!', 'Dikkat, zemin ıslak!', ''],
  ['bere', 'içmek', 'BE-re', 'Cosa vuoi bere?', 'Ne içmek istersin?', ''],
  ['la situazione', 'durum', 'la si-tua-TSYO-ne', 'La situazione è difficile.', 'Durum zor.', ''],
  ["l'omicidio (m.)", 'cinayet', 'lo-mi-Çİ-dyo', "La polizia indaga sull'omicidio.", 'Polis cinayeti soruşturuyor.', ''],
  ['ottimo', 'mükemmel', 'OT-ti-mo', 'Il cibo è ottimo.', 'Yemek harika.', ''],
  ['la cura', 'bakım; tedavi', 'la KU-ra', 'Abbi cura di te.', 'Kendine iyi bak.', ''],
  ['durante', 'sırasında', 'du-RAN-te', 'Non parlare durante il film.', 'Film sırasında konuşma.', ''],
  ['provare', 'denemek', 'pro-VA-re', 'Posso provare questa giacca?', 'Bu ceketi deneyebilir miyim?', ''],
  ['prossimo', 'gelecek, sonraki', 'PROS-si-mo', 'Ci vediamo la prossima volta.', 'Bir dahaki sefere görüşürüz.', ''],
  ['arrivare', 'varmak, gelmek', 'ar-ri-VA-re', 'Il treno arriva alle nove.', 'Tren dokuzda varıyor.', ''],
  ['il paese', 'ülke; köy', 'il pa-E-se', "L'Italia è un bel paese.", 'İtalya güzel bir ülke.', ''],
  ['chiunque', 'kim olursa', 'ki-UN-kue', 'Chiunque può farlo.', 'Bunu herkes yapabilir.', ''],
  ['la pace', 'barış; huzur', 'la PA-çe', "Voglio un po' di pace.", 'Biraz huzur istiyorum.', ''],
  ['immaginare', 'hayal etmek', 'im-ma-ci-NA-re', 'Immagina una casa al mare.', 'Deniz kenarında bir ev hayal et.', ''],
  ['la musica', 'müzik', 'la MU-si-ka', 'Mi piace la musica italiana.', 'İtalyan müziğini severim.', '🎵'],
  ['tenere', 'tutmak', 'te-NE-re', 'Tieni la mia borsa.', 'Çantamı tut.', ''],
  ['il libro', 'kitap', 'il Lİ-bro', 'Leggo un libro.', 'Bir kitap okuyorum.', '📖'],
  ["l'amica (f.)", 'kız arkadaş (dost)', 'la-Mİ-ka', "Esco con un'amica.", 'Bir kız arkadaşla çıkıyorum.', ''],
  ['diventare', 'olmak (dönüşmek)', 'di-ven-TA-re', 'Voglio diventare medico.', 'Doktor olmak istiyorum.', ''],
  ['sbagliato', 'yanlış', 'zba-LYA-to', 'Il numero è sbagliato.', 'Numara yanlış.', ''],
  ['la scelta', 'seçim', 'la ŞEL-ta', 'È una buona scelta.', 'İyi bir seçim.', ''],
  ['assolutamente', 'kesinlikle', 'as-so-lu-ta-MEN-te', 'Assolutamente no!', 'Kesinlikle hayır!', ''],
  ['scoprire', 'keşfetmek', 'sko-PRİ-re', 'Voglio scoprire la città.', 'Şehri keşfetmek istiyorum.', ''],
  ['il fatto', 'olgu, gerçek', 'il FAT-to', 'È un fatto.', 'Bu bir gerçek.', ''],
  ['alcuno', 'bazı; hiçbir', 'al-KU-no', 'Ho alcuni amici a Roma.', "Roma'da birkaç arkadaşım var.", ''],
  ['la prigione', 'hapishane', 'la pri-CO-ne', 'È in prigione da un anno.', 'Bir yıldır hapiste.', ''],
  ['la giornata', 'gün (süre)', 'la cor-NA-ta', 'Buona giornata!', 'İyi günler!', ''],
  ['piuttosto', 'daha çok; oldukça', 'pyut-TOS-to', 'Piuttosto, prendo un tè.', 'Onun yerine bir çay alayım.', ''],
  ['lungo', 'uzun', 'LUN-go', 'Il viaggio è lungo.', 'Yolculuk uzun.', ''],
  ["l'avvocato (m.)", 'avukat', 'lav-vo-KA-to', 'Ho bisogno di un avvocato.', 'Bir avukata ihtiyacım var.', ''],
  ['decidere', 'karar vermek', 'de-Çİ-de-re', 'Decidi tu.', 'Sen karar ver.', ''],
  ['il messaggio', 'mesaj', 'il mes-SAC-co', 'Ho letto il tuo messaggio.', 'Mesajını okudum.', '💬'],
  ['dormire', 'uyumak', 'dor-Mİ-re', 'Voglio dormire.', 'Uyumak istiyorum.', ''],
  ['dieci', 'on', 'DYE-çi', 'Ho dieci anni.', 'On yaşındayım.', ''],
  ['stupido', 'aptal', 'STU-pi-do', 'Non è una domanda stupida.', 'Aptalca bir soru değil.', ''],
  ['usare', 'kullanmak', 'u-SA-re', 'Posso usare il bagno?', 'Tuvaleti kullanabilir miyim?', ''],
  ['il cielo', 'gökyüzü', 'il ÇE-lo', 'Il cielo è blu.', 'Gökyüzü mavi.', ''],
  ['il bagno', 'banyo, tuvalet', 'il BAN-yo', 'Il bagno è a destra.', 'Banyo sağda.', '🛁'],
  ["l'aria (f.)", 'hava', 'LA-rya', "Ho bisogno d'aria fresca.", 'Temiz havaya ihtiyacım var.', ''],
  ['la voce', 'ses', 'la VO-çe', 'Hai una bella voce.', 'Güzel bir sesin var.', ''],
  ['giù', 'aşağı', 'CU', 'Vieni giù!', 'Aşağı gel!', ''],
  ['benissimo', 'çok iyi', 'be-NİS-si-mo', 'Parli benissimo!', 'Çok iyi konuşuyorsun!', ''],
  ['la verità', 'gerçek', 'la ve-ri-TA', 'Dimmi la verità.', 'Bana gerçeği söyle.', ''],
  ['il cane', 'köpek', 'il KA-ne', 'Il cane abbaia.', 'Köpek havlıyor.', '🐕'],
  ['restare', 'kalmak', 'res-TA-re', 'Resto a casa oggi.', 'Bugün evde kalıyorum.', ''],
  ['il campo', 'tarla; saha', 'il KAM-po', 'I bambini giocano nel campo.', 'Çocuklar sahada oynuyor.', ''],
  ['la luce', 'ışık', 'la LU-çe', 'Accendi la luce.', 'Işığı aç.', '💡'],
  ['qualunque', 'herhangi', 'kua-LUN-kue', 'Qualunque cosa succeda.', 'Ne olursa olsun.', ''],
  ['giovane', 'genç', 'CO-va-ne', 'Sei ancora giovane.', 'Hâlâ gençsin.', ''],
  ['fra', 'arasında; sonra', 'FRA', 'Fra due giorni parto.', 'İki gün sonra gidiyorum.', ''],
  ['lontano', 'uzak', 'lon-TA-no', 'Casa mia è lontana.', 'Evim uzakta.', ''],
  ['il gruppo', 'grup', 'il GRUP-po', 'Studiamo in gruppo.', 'Grup halinde çalışıyoruz.', ''],
  ['continuare', 'devam etmek', 'kon-ti-nu-A-re', 'Continua a leggere.', 'Okumaya devam et.', ''],
  ['la realtà', 'gerçeklik', 'la re-al-TA', 'In realtà, non lo so.', 'Aslında bilmiyorum.', ''],
  ['il passo', 'adım', 'il PAS-so', 'Un passo alla volta.', 'Adım adım.', ''],
  ['insomma', 'kısacası', 'in-SOM-ma', 'Insomma, cosa vuoi?', 'Kısacası, ne istiyorsun?', ''],
  ['i capelli', 'saç', 'i ka-PEL-li', 'Ha i capelli lunghi.', 'Uzun saçları var.', '💇'],
  ["l'onore (m.)", 'onur', 'lo-NO-re', 'È un onore.', 'Bu bir onur.', ''],
  ['aiutare', 'yardım etmek', 'a-yu-TA-re', 'Puoi aiutarmi?', 'Bana yardım edebilir misin?', ''],
  ['funzionare', 'çalışmak (makine)', 'fun-tsyo-NA-re', 'Il telefono non funziona.', 'Telefon çalışmıyor.', ''],
  ['alto', 'uzun; yüksek', 'AL-to', 'La montagna è molto alta.', 'Dağ çok yüksek.', ''],
  ['il futuro', 'gelecek', 'il fu-TU-ro', 'Pensa al futuro.', 'Geleceği düşün.', ''],
  ['preoccupare', 'endişelendirmek', 'pre-ok-ku-PA-re', 'Non preoccuparti!', 'Merak etme!', ''],
  ["l'idiota (m.)", 'aptal, salak', 'li-DYO-ta', "Non fare l'idiota.", 'Aptallık etme.', ''],
  ['il cibo', 'yiyecek', 'il Çİ-bo', 'Il cibo italiano è buono.', 'İtalyan yemekleri güzel.', '🍲'],
  ['la fretta', 'acele', 'la FRET-ta', 'Ho fretta.', 'Acelem var.', ''],
  ['caro', 'sevgili; pahalı', 'KA-ro', 'Cara Anna, come stai?', 'Sevgili Anna, nasılsın?', ''],
  ['finalmente', 'nihayet', 'fi-nal-MEN-te', 'Finalmente sei qui!', 'Nihayet buradasın!', ''],
  ['odiare', 'nefret etmek', 'o-DYA-re', 'Odio il freddo.', 'Soğuktan nefret ederim.', ''],
  ['solito', 'alışılmış, her zamanki', 'SO-li-to', 'Il solito, per favore.', 'Her zamankinden lütfen.', ''],
  ["l'incidente (m.)", 'kaza', 'lin-çi-DEN-te', "C'è stato un incidente.", 'Bir kaza oldu.', ''],
  ["l'intenzione (f.)", 'niyet', 'lin-ten-TSYO-ne', 'Non era mia intenzione.', 'Niyetim bu değildi.', ''],
  ['speciale', 'özel', 'spe-ÇA-le', 'Sei una persona speciale.', 'Sen özel birisin.', ''],
  ['cambiare', 'değiştirmek', 'kam-BYA-re', 'Devo cambiare vestito.', 'Kıyafet değiştirmem lazım.', ''],
  ['la camera', 'oda', 'la KA-me-ra', 'Una camera doppia, per favore.', 'Çift kişilik oda lütfen.', ''],
  ['oltre', 'ötesinde; -den fazla', 'OL-tre', "Oltre il ponte c'è il paese.", 'Köprünün ötesinde köy var.', ''],
  ['semplice', 'basit', 'SEM-pli-çe', 'È molto semplice.', 'Çok basit.', ''],
  ['riguardo', 'hakkında', 'ri-GUAR-do', 'Riguardo a domani, va bene.', 'Yarın konusunda, tamam.', ''],
  ['finché', '-dığı sürece; -e kadar', 'fin-KE', 'Aspetto finché arrivi.', 'Sen gelene kadar beklerim.', ''],
  ['il viaggio', 'yolculuk', 'il VYAC-co', 'Buon viaggio!', 'İyi yolculuklar!', '🧳'],
  ['chiaro', 'açık, net', 'KYA-ro', 'È tutto chiaro?', 'Her şey açık mı?', ''],
  ['la chiamata', 'arama (telefon)', 'la kya-MA-ta', 'Ho una chiamata persa.', 'Cevapsız bir aramam var.', ''],
  ['la bocca', 'ağız', 'la BOK-ka', 'Apri la bocca.', 'Ağzını aç.', '👄'],
  ['il permesso', 'izin', 'il per-MES-so', 'Permesso, posso passare?', 'Pardon, geçebilir miyim?', ''],
  ['giocare', 'oynamak', 'co-KA-re', 'I bambini giocano fuori.', 'Çocuklar dışarıda oynuyor.', ''],
  ["l'ordine (m.)", 'düzen; sipariş', 'LOR-di-ne', 'La stanza è in ordine.', 'Oda düzenli.', ''],
  ['circa', 'yaklaşık', 'ÇİR-ka', 'Costa circa venti euro.', 'Yaklaşık yirmi avro tutuyor.', ''],
  ['ovviamente', 'tabii ki', 'ov-vya-MEN-te', 'Ovviamente hai ragione.', 'Tabii ki haklısın.', ''],
  ['il Natale', 'Noel', 'il na-TA-le', 'Buon Natale!', 'Mutlu Noeller!', '🎄'],
  ['la mattina', 'sabah', 'la mat-Tİ-na', 'Bevo caffè la mattina.', 'Sabahları kahve içerim.', '🌅'],
  ['il sistema', 'sistem', 'il sis-TE-ma', 'Il sistema è semplice.', 'Sistem basit.', ''],
  ['il fondo', 'dip; son', 'il FON-do', 'In fondo alla strada.', 'Sokağın sonunda.', ''],
  ['il milione', 'milyon', 'il mi-LYO-ne', 'Un milione di persone.', 'Bir milyon kişi.', ''],
  ['soltanto', 'sadece', 'sol-TAN-to', 'Soltanto un momento.', 'Sadece bir an.', ''],
  ["l'arma (f.)", 'silah', 'LAR-ma', 'Non ho armi.', 'Silahım yok.', ''],
  ['fermo', 'hareketsiz, duran', 'FER-mo', 'Stai fermo!', 'Kıpırdama!', ''],
  ['controllare', 'kontrol etmek', 'kon-trol-LA-re', 'Controllo la posta.', 'Postayı kontrol ediyorum.', ''],
  ["l'appuntamento (m.)", 'randevu', 'lap-pun-ta-MEN-to', 'Ho un appuntamento alle tre.', 'Saat üçte randevum var.', ''],
  ['il detective', 'dedektif', 'il de-TEK-tiv', 'Il detective trova la prova.', 'Dedektif kanıtı buluyor.', '🕵️'],
  ['il grado', 'derece', 'il GRA-do', 'Oggi ci sono trenta gradi.', 'Bugün otuz derece.', ''],
  ['la nave', 'gemi', 'la NA-ve', 'La nave parte alle otto.', 'Gemi sekizde kalkıyor.', '🚢'],
  ['iniziare', 'başlamak', 'i-ni-TSYA-re', 'Iniziamo la lezione.', 'Derse başlayalım.', ''],
  ["l'informazione (f.)", 'bilgi', 'lin-for-ma-TSYO-ne', "Mi serve un'informazione.", 'Bir bilgiye ihtiyacım var.', ''],
  ['libero', 'serbest; boş', 'Lİ-be-ro', 'Sei libero stasera?', 'Bu akşam boş musun?', ''],
  ['il pezzo', 'parça', 'il PET-tso', 'Un pezzo di pizza.', 'Bir dilim pizza.', ''],
  ['il segreto', 'sır', 'il se-GRE-to', 'È un segreto.', 'Bu bir sır.', ''],
  ['il colpo', 'darbe, vuruş', 'il KOL-po', 'Ho sentito un colpo.', 'Bir vuruş sesi duydum.', ''],
  ['il porto', 'liman', 'il POR-to', 'La barca è nel porto.', 'Tekne limanda.', '⚓'],
  ['oppure', 'ya da', 'op-PU-re', 'Vuoi tè oppure caffè?', 'Çay mı yoksa kahve mi istersin?', ''],
  ['completamente', 'tamamen', 'kom-ple-ta-MEN-te', 'Ho completamente dimenticato.', 'Tamamen unuttum.', ''],
  ['la lista', 'liste', 'la LİS-ta', 'Faccio la lista della spesa.', 'Alışveriş listesi yapıyorum.', '📝'],
  ['veloce', 'hızlı', 've-LO-çe', 'Il treno è veloce.', 'Tren hızlı.', ''],
  ["l'assassino (m.)", 'katil', 'las-sas-Sİ-no', "La polizia cerca l'assassino.", 'Polis katili arıyor.', ''],
  ['ormai', 'artık', 'or-MAY', 'Ormai è tardi.', 'Artık çok geç.', ''],
  ['interessare', 'ilgilendirmek', 'in-te-res-SA-re', "Mi interessa l'arte.", 'Sanat ilgimi çekiyor.', ''],
  ['generale', 'genel; general', 'ce-ne-RA-le', 'In generale, sto bene.', 'Genel olarak iyiyim.', ''],
  ['pazzo', 'deli', 'PAT-tso', 'Sei pazzo?', 'Deli misin?', ''],
  ['la vittima', 'kurban', 'la VİT-ti-ma', 'La vittima sta bene.', 'Kurbanın durumu iyi.', ''],
  ['giurare', 'yemin etmek', 'cu-RA-re', 'Te lo giuro!', 'Yemin ederim!', ''],
  ['il consiglio', 'tavsiye; kurul', 'il kon-Sİ-lyo', 'Ti do un consiglio.', 'Sana bir tavsiye vereyim.', ''],
  ['semplicemente', 'basitçe', 'sem-pli-çe-MEN-te', 'Dillo semplicemente.', 'Basitçe söyle.', ''],
  ['lo zio', 'amca, dayı', 'lo TSİ-o', 'Mio zio vive a Napoli.', "Amcam Napoli'de yaşıyor.", ''],
  ['il centro', 'merkez', 'il ÇEN-tro', 'Abito in centro.', 'Merkezde oturuyorum.', ''],
  ['la specie', 'tür', 'la SPE-çe', 'È una specie rara.', 'Nadir bir tür.', ''],
  ['mille', 'bin', 'MİL-le', 'Mille grazie!', 'Bin teşekkürler!', ''],
  ['il sogno', 'rüya; hayal', 'il SON-yo', 'Ho fatto un bel sogno.', 'Güzel bir rüya gördüm.', ''],
  ['carino', 'şirin, hoş', 'ka-Rİ-no', 'Che vestito carino!', 'Ne şirin bir elbise!', ''],
  ['brutto', 'çirkin; kötü', 'BRUT-to', 'Che brutto tempo!', 'Ne kötü hava!', ''],
  ['incredibile', 'inanılmaz', 'in-kre-Dİ-bi-le', 'È incredibile!', 'İnanılmaz!', ''],
  ['il sole', 'güneş', 'il SO-le', "Oggi c'è il sole.", 'Bugün hava güneşli.', '☀️'],
  ['la legge', 'kanun', 'la LEC-ce', 'Nessuno è sopra la legge.', 'Kimse kanunun üstünde değil.', ''],
  ['spesso', 'sık sık', 'SPES-so', 'Vado spesso al cinema.', 'Sık sık sinemaya giderim.', ''],
  ['la scena', 'sahne', 'la ŞE-na', 'È una bella scena.', 'Güzel bir sahne.', ''],
  ['gentile', 'nazik', 'cen-Tİ-le', 'Grazie, sei gentile.', 'Teşekkürler, naziksin.', ''],
  ['il rispetto', 'saygı', 'il ris-PET-to', 'Ho molto rispetto per te.', 'Sana çok saygım var.', ''],
  ['zitto', 'sessiz', 'TSİT-to', 'Stai zitto!', 'Sus!', ''],
  ["l'incontro (m.)", 'buluşma; toplantı', 'lin-KON-tro', "L'incontro è alle dieci.", 'Toplantı saat onda.', ''],
  ['il rapporto', 'ilişki; rapor', 'il rap-POR-to', 'Abbiamo un buon rapporto.', 'İyi bir ilişkimiz var.', ''],
  ["l'errore (m.)", 'hata', 'ler-RO-re', 'È stato un errore.', 'Bir hataydı.', ''],
  ['pagare', 'ödemek', 'pa-GA-re', "Devo pagare l'affitto.", 'Kirayı ödemem lazım.', ''],
  ['la sorpresa', 'sürpriz', 'la sor-PRE-sa', 'Che bella sorpresa!', 'Ne güzel bir sürpriz!', ''],
  ["l'occhiata (f.)", 'göz atma, bakış', 'lok-KYA-ta', "Dai un'occhiata qui.", 'Buraya bir göz at.', ''],
  ['la risposta', 'cevap', 'la ris-POS-ta', 'La risposta è sì.', 'Cevap evet.', ''],
  ['il servizio', 'hizmet', 'il ser-Vİ-tsyo', 'Il servizio è ottimo.', 'Hizmet mükemmel.', ''],
  ['il medico', 'doktor', 'il ME-di-ko', 'Chiama il medico!', 'Doktoru çağır!', '🩺'],
  ['lo schifo', 'iğrenç şey', 'lo SKİ-fo', 'Che schifo!', 'İğrenç!', ''],
  ['il dolore', 'acı, ağrı', 'il do-LO-re', 'Il dolore è forte.', 'Acı şiddetli.', ''],
  ['personale', 'kişisel; personel', 'per-so-NA-le', 'È una cosa personale.', 'Bu kişisel bir şey.', ''],
  ['peggio', 'daha kötü', 'PEC-co', 'Oggi sto peggio.', 'Bugün daha kötüyüm.', ''],
  ['addio', 'elveda', 'ad-Dİ-o', 'Addio, amico mio.', 'Elveda dostum.', ''],
  ['addosso', 'üstünde (giyili)', 'ad-DOS-so', 'Ho addosso una giacca.', 'Üstümde bir ceket var.', ''],
  ['pieno', 'dolu', 'PYE-no', 'Il bicchiere è pieno.', 'Bardak dolu.', ''],
  ['diverso', 'farklı', 'di-VER-so', 'Siamo molto diversi.', 'Çok farklıyız.', ''],
  ['il vestito', 'elbise; takım elbise', 'il ves-Tİ-to', 'Ti sta bene il vestito.', 'Elbise sana yakışmış.', '👗'],
  ['sparare', 'ateş etmek', 'spa-RA-re', 'Non sparare!', 'Ateş etme!', ''],
  ['normale', 'normal', 'nor-MA-le', 'È normale.', 'Bu normal.', ''],
  ['la fame', 'açlık', 'la FA-me', 'Ho molta fame.', 'Çok açım.', ''],
  ['il programma', 'program', 'il pro-GRAM-ma', 'Qual è il programma di oggi?', 'Bugünün programı ne?', ''],
  ['la nonna', 'büyükanne', 'la NON-na', 'La nonna racconta una storia.', 'Büyükanne bir hikâye anlatıyor.', '👵'],
  ['la notizia', 'haber', 'la no-Tİ-tsya', 'Ho una bella notizia.', 'Güzel bir haberim var.', ''],
  ['la posizione', 'konum', 'la po-si-TSYO-ne', 'Mandami la tua posizione.', 'Bana konumunu gönder.', ''],
  ['rimanere', 'kalmak', 'ri-ma-NE-re', 'Rimani con me.', 'Benimle kal.', ''],
  ['la compagnia', 'şirket; arkadaşlık', 'la kom-pa-NYİ-a', 'Grazie per la compagnia.', 'Arkadaşlığın için teşekkürler.', ''],
  ['il proposito', 'amaç, niyet', 'il pro-PO-si-to', 'A proposito, come stai?', 'Bu arada, nasılsın?', ''],
  ['chiudere', 'kapatmak', 'KYU-de-re', 'Chiudi la finestra.', 'Pencereyi kapat.', ''],
  ['terribile', 'korkunç', 'ter-Rİ-bi-le', 'Che giornata terribile!', 'Ne korkunç bir gün!', ''],
  ['il ritardo', 'gecikme', 'il ri-TAR-do', 'Scusa il ritardo.', 'Geciktiğim için özür dilerim.', ''],
  ['attento', 'dikkatli', 'at-TEN-to', 'Stai attento!', 'Dikkat et!', ''],
  ['il bar', 'bar, kafe', 'il BAR', 'Andiamo al bar.', 'Kafeye gidelim.', ''],
  ['dimenticare', 'unutmak', 'di-men-ti-KA-re', 'Non dimenticare le chiavi.', 'Anahtarları unutma.', ''],
  ['impossibile', 'imkânsız', 'im-pos-Sİ-bi-le', 'Niente è impossibile.', 'Hiçbir şey imkânsız değil.', ''],
  ['lo studio', 'çalışma; çalışma odası', 'lo STU-dyo', 'Il papà è nello studio.', 'Babam çalışma odasında.', ''],
  ["l'uscita (f.)", 'çıkış', 'luş-Şİ-ta', "Dov'è l'uscita?", 'Çıkış nerede?', ''],
  ['il guaio', 'dert, bela', 'il GUA-yo', 'Sono nei guai.', 'Başım dertte.', ''],
  ['intorno', 'etrafında', 'in-TOR-no', 'Guarda intorno.', 'Etrafına bak.', ''],
  ['il video', 'video', 'il Vİ-de-o', 'Guarda questo video!', 'Bu videoyu izle!', '📹'],
  ['mancare', 'eksik olmak; özlemek', 'man-KA-re', 'Mi manchi.', 'Seni özlüyorum.', ''],
  ['grosso', 'kalın, büyük', 'GROS-so', 'È un grosso problema.', 'Büyük bir sorun.', ''],
  ['dolce', 'tatlı', 'DOL-çe', 'Il dolce è buonissimo.', 'Tatlı çok lezzetli.', ''],
  ['la chiave', 'anahtar', 'la KYA-ve', "Dov'è la chiave?", 'Anahtar nerede?', '🔑'],
  ['il cervello', 'beyin', 'il çer-VEL-lo', 'Usa il cervello!', 'Beynini kullan!', '🧠'],
  ['il coraggio', 'cesaret', 'il ko-RAC-co', 'Ci vuole coraggio.', 'Cesaret gerekir.', ''],
  ['interessante', 'ilginç', 'in-te-res-SAN-te', 'Il libro è interessante.', 'Kitap ilginç.', ''],
  ['il peccato', 'günah; yazık', 'il pek-KA-to', 'Che peccato!', 'Ne yazık!', ''],
  ['la questione', 'mesele', 'la kues-TYO-ne', 'È una questione di tempo.', 'Bu bir zaman meselesi.', ''],
  ['adorare', 'bayılmak', 'a-do-RA-re', 'Adoro la pizza.', 'Pizzaya bayılırım.', ''],
  ["l'aereo (m.)", 'uçak', 'la-E-re-o', "L'aereo parte alle sei.", 'Uçak altıda kalkıyor.', '✈️'],
  ['rubare', 'çalmak (hırsızlık)', 'ru-BA-re', 'Mi hanno rubato la borsa.', 'Çantamı çaldılar.', ''],
  ['la sala', 'salon', 'la SA-la', 'La sala da pranzo è grande.', 'Yemek odası büyük.', ''],
  ['la base', 'temel', 'la BA-se', 'È la base di tutto.', 'Her şeyin temeli bu.', ''],
  ['sette', 'yedi', 'SET-te', 'La settimana ha sette giorni.', 'Haftada yedi gün var.', ''],
  ['il compleanno', 'doğum günü', 'il kom-ple-AN-no', 'Buon compleanno!', 'İyi ki doğdun!', '🎂'],
  ['la relazione', 'ilişki', 'la re-la-TSYO-ne', 'Ha una relazione seria.', 'Ciddi bir ilişkisi var.', ''],
  ['il cliente', 'müşteri', 'il kli-EN-te', 'Il cliente ha sempre ragione.', 'Müşteri her zaman haklıdır.', ''],
  ['la spalla', 'omuz', 'la SPAL-la', 'Porta lo zaino sulla spalla.', 'Sırt çantasını omzunda taşıyor.', ''],
  ['valere', 'değmek', 'va-LE-re', 'Ne vale la pena.', 'Buna değer.', ''],
  ['il diritto', 'hak', 'il di-RİT-to', 'È un tuo diritto.', 'Bu senin hakkın.', ''],
  ['sicuramente', 'kesinlikle', 'si-ku-ra-MEN-te', 'Sicuramente arriva domani.', 'Kesin yarın gelir.', ''],
  ["l'appartamento (m.)", 'daire', 'lap-par-ta-MEN-to', "L'appartamento ha tre stanze.", 'Dairenin üç odası var.', ''],
  ['il pranzo', 'öğle yemeği', 'il PRAN-tso', 'A che ora è il pranzo?', 'Öğle yemeği saat kaçta?', '🥪'],
  ['il denaro', 'para', 'il de-NA-ro', 'Il denaro non è tutto.', 'Para her şey değil.', '💶'],
  ['la serata', 'akşam (süre)', 'la se-RA-ta', 'Buona serata!', 'İyi akşamlar!', ''],
  ['nero', 'siyah', 'NE-ro', 'Ho un gatto nero.', 'Siyah bir kedim var.', ''],
  ['la carta', 'kâğıt; kart', 'la KAR-ta', 'Posso pagare con la carta?', 'Kartla ödeyebilir miyim?', '💳'],
  ['otto', 'sekiz', 'OT-to', 'Mi sveglio alle otto.', 'Saat sekizde uyanırım.', ''],
  ['la zona', 'bölge', 'la DZO-na', 'Abito in questa zona.', 'Bu bölgede oturuyorum.', ''],
  ['intendere', 'kastetmek', 'in-TEN-de-re', 'Cosa intendi?', 'Ne demek istiyorsun?', ''],
  ['il negozio', 'dükkân', 'il ne-GO-tsyo', 'Il negozio apre alle nove.', 'Dükkân dokuzda açılıyor.', '🏪'],
  ['la partita', 'maç', 'la par-Tİ-ta', 'Guardiamo la partita?', 'Maçı izleyelim mi?', ''],
  ['la tv', 'televizyon', 'la tiv-VU', 'Guardo la tv.', 'Televizyon izliyorum.', '📺'],
  ['lo spazio', 'uzay; alan', 'lo SPA-tsyo', "Non c'è spazio.", 'Yer yok.', ''],
  ['la linea', 'hat, çizgi', 'la Lİ-ne-a', 'La linea è occupata.', 'Hat meşgul.', ''],
  ['riguardare', 'ilgilendirmek', 'ri-guar-DA-re', 'Non ti riguarda.', 'Seni ilgilendirmez.', ''],
  ['il poliziotto', 'polis memuru', 'il po-li-TSYOT-to', 'Il poliziotto è gentile.', 'Polis nazik.', '👮'],
  ['scappare', 'kaçmak', 'skap-PA-re', 'Il gatto è scappato.', 'Kedi kaçtı.', ''],
  ['vincere', 'kazanmak', 'VİN-çe-re', 'Voglio vincere.', 'Kazanmak istiyorum.', ''],
  ['la fronte', 'alın; ön', 'la FRON-te', "Di fronte c'è un bar.", 'Karşıda bir bar var.', ''],
  ['tranquillo', 'sakin', 'tran-KUİL-lo', 'Stai tranquillo.', 'Sakin ol.', ''],
  ['il silenzio', 'sessizlik', 'il si-LEN-tsyo', 'Silenzio, per favore.', 'Sessizlik lütfen.', ''],
  ['simile', 'benzer', 'Sİ-mi-le', 'Sono molto simili.', 'Çok benzerler.', ''],
  ['la calma', 'sakinlik', 'la KAL-ma', 'Calma, calma!', 'Sakin, sakin!', ''],
  ['santo', 'kutsal; aziz', 'SAN-to', 'Santo cielo!', 'Aman Tanrım!', ''],
  ['la ricerca', 'araştırma', 'la ri-ÇER-ka', 'Faccio una ricerca.', 'Bir araştırma yapıyorum.', ''],
  ['la pena', 'ceza; acı', 'la PE-na', 'Mi fa pena.', 'Ona acıyorum.', ''],
  ['esistere', 'var olmak', 'e-SİS-te-re', 'I fantasmi non esistono.', 'Hayaletler yoktur.', ''],
  ['altrimenti', 'yoksa', 'al-tri-MEN-ti', 'Corri, altrimenti perdi il treno.', 'Koş, yoksa treni kaçırırsın.', ''],
  ['il luogo', 'yer', 'il LUO-go', "Il luogo dell'incontro è qui.", 'Buluşma yeri burası.', ''],
  ['la lettera', 'mektup; harf', 'la LET-te-ra', 'È arrivata una lettera per te.', 'Sana bir mektup geldi.', '✉️'],
  ['salvare', 'kurtarmak', 'sal-VA-re', 'Mi hai salvato la vita.', 'Hayatımı kurtardın.', ''],
  ['la canzone', 'şarkı', 'la kan-TSO-ne', 'Che bella canzone!', 'Ne güzel şarkı!', '🎶'],
  ['pubblico', 'kamusal; seyirci', 'PUB-bli-ko', 'È un parco pubblico.', 'Bu halka açık bir park.', ''],
  ['il corso', 'kurs; ders', 'il KOR-so', 'Faccio un corso di italiano.', 'İtalyanca kursuna gidiyorum.', ''],
  ['il regalo', 'hediye', 'il re-GA-lo', 'Questo regalo è per te.', 'Bu hediye senin için.', '🎁'],
  ['né', 'ne... ne', 'NE', 'Né io né lui.', 'Ne ben ne o.', ''],
  ['scherzare', 'şaka yapmak', 'sker-TSA-re', 'Sto scherzando!', 'Şaka yapıyorum!', ''],
  ['stamattina', 'bu sabah', 'sta-mat-Tİ-na', 'Stamattina piove.', 'Bu sabah yağmur yağıyor.', ''],
  ['la missione', 'görev', 'la mis-SYO-ne', 'La missione è finita.', 'Görev bitti.', ''],
  ['il test', 'test', 'il TEST', 'Faccio il test di italiano.', 'İtalyanca testine giriyorum.', ''],
  ['la salute', 'sağlık', 'la sa-LU-te', 'Alla salute!', 'Şerefe!', ''],
  ['scegliere', 'seçmek', 'ŞE-lye-re', 'Scegli tu il ristorante.', 'Restoranı sen seç.', ''],
  ['duro', 'sert; zor', 'DU-ro', 'Il pane è duro.', 'Ekmek bayat.', ''],
  ['il computer', 'bilgisayar', 'il kom-PYU-ter', 'Il computer è nuovo.', 'Bilgisayar yeni.', '💻'],
  ['il contatto', 'temas; bağlantı', 'il kon-TAT-to', 'Restiamo in contatto.', 'İletişimde kalalım.', ''],
  ['il pericolo', 'tehlike', 'il pe-Rİ-ko-lo', 'Attenzione, pericolo!', 'Dikkat, tehlike!', ''],
  ['entro', 'içinde (süre)', 'EN-tro', 'Finisco entro domani.', 'Yarına kadar bitiririm.', ''],
  ['freddo', 'soğuk', 'FRED-do', 'Oggi fa freddo.', 'Bugün hava soğuk.', ''],
  ['triste', 'üzgün', 'TRİS-te', 'Perché sei triste?', 'Neden üzgünsün?', ''],
  ['promettere', 'söz vermek', 'pro-MET-te-re', 'Te lo prometto.', 'Sana söz veriyorum.', ''],
  ["l'esercito (m.)", 'ordu', 'le-SER-çi-to', "Mio fratello è nell'esercito.", 'Kardeşim orduda.', ''],
  ['dunque', 'öyleyse', 'DUN-kue', 'Dunque, cominciamo.', 'Öyleyse başlayalım.', ''],
  ['la guardia', 'bekçi, muhafız', 'la GUAR-dya', 'La guardia è alla porta.', 'Muhafız kapıda.', '💂'],
  ['infatti', 'nitekim, gerçekten de', 'in-FAT-ti', 'Infatti, è così.', 'Gerçekten de öyle.', ''],
  ['la possibilità', 'olasılık, imkân', 'la pos-si-bi-li-TA', "C'è una possibilità.", 'Bir ihtimal var.', ''],
  ['il casino', 'karmaşa; gürültü', 'il ka-Sİ-no', 'Che casino!', 'Ne karmaşa!', ''],
  ['buonanotte', 'iyi geceler', 'buo-na-NOT-te', 'Buonanotte, a domani.', 'İyi geceler, yarın görüşürüz.', ''],
  ['la caccia', 'av', 'la KAÇ-ça', 'Andiamo a caccia.', 'Ava gidiyoruz.', ''],
  ['certamente', 'elbette', 'çer-ta-MEN-te', 'Certamente, signore.', 'Elbette efendim.', ''],
  ['la regola', 'kural', 'la RE-go-la', 'Rispetta le regole.', 'Kurallara uy.', ''],
  ['il ballo', 'dans; balo', 'il BAL-lo', 'Mi concedi questo ballo?', 'Bu dansı bana lütfeder misin?', ''],
  ['la birra', 'bira', 'la BİR-ra', 'Una birra fredda, per favore.', 'Soğuk bir bira lütfen.', '🍺'],
  ['ovunque', 'her yerde', 'o-VUN-kue', 'Ti cerco ovunque.', 'Seni her yerde arıyorum.', ''],
  ['il governo', 'hükümet', 'il go-VER-no', 'Il governo decide oggi.', 'Hükümet bugün karar veriyor.', ''],
  ["l'oro (m.)", 'altın', 'LO-ro', "Un anello d'oro.", 'Altın bir yüzük.', '🥇'],
  ['la cucina', 'mutfak; mutfak kültürü', 'la ku-Çİ-na', 'Mamma è in cucina.', 'Annem mutfakta.', '🍳'],
  ['la decisione', 'karar', 'la de-çi-SYO-ne', 'È una decisione difficile.', 'Zor bir karar.', ''],
  ["l'anima (f.)", 'ruh', 'LA-ni-ma', "Canta con l'anima.", 'Ruhuyla şarkı söylüyor.', ''],
  ['la forma', 'şekil; form', 'la FOR-ma', 'Sono in forma.', 'Formdayım.', ''],
  ["l'esempio (m.)", 'örnek', 'le-SEM-pyo', 'Per esempio, la pizza.', 'Örneğin pizza.', ''],
  ['incontrare', 'karşılaşmak, buluşmak', 'in-kon-TRA-re', 'Ho incontrato Marco al bar.', "Marco'yla kafede karşılaştım.", ''],
  ["l'occasione (f.)", 'fırsat', 'lok-ka-SYO-ne', 'È una bella occasione.', 'Güzel bir fırsat.', ''],
  ['stanotte', 'bu gece', 'sta-NOT-te', 'Stanotte dormo da te.', 'Bu gece sende kalıyorum.', ''],
  ['la droga', 'uyuşturucu', 'la DRO-ga', 'La droga è pericolosa.', 'Uyuşturucu tehlikelidir.', ''],
  ['il cellulare', 'cep telefonu', 'il çel-lu-LA-re', 'Ho dimenticato il cellulare.', 'Cep telefonumu unuttum.', '📱'],
  ['necessario', 'gerekli', 'ne-çes-SA-ryo', 'Non è necessario.', 'Gerekli değil.', ''],
  ['fermare', 'durdurmak', 'fer-MA-re', 'Ferma la macchina!', 'Arabayı durdur!', ''],
  ['la borsa', 'çanta', 'la BOR-sa', 'La mia borsa è nera.', 'Çantam siyah.', '👜'],
  ['il nonno', 'dede', 'il NON-no', 'Il nonno legge il giornale.', 'Dede gazete okuyor.', '👴'],
  ["l'attacco (m.)", 'saldırı', 'lat-TAK-ko', 'È un attacco di panico.', 'Bu bir panik atak.', ''],
  ['affatto', 'hiç (değil)', 'af-FAT-to', 'Non sono affatto stanco.', 'Hiç yorgun değilim.', ''],
  ['colpire', 'vurmak', 'kol-Pİ-re', 'La palla mi ha colpito.', 'Top bana çarptı.', ''],
  ['sedersi', 'oturmak', 'se-DER-si', 'Siediti qui.', 'Buraya otur.', ''],
  ['reale', 'gerçek; kraliyet', 're-A-le', 'È una storia reale.', 'Bu gerçek bir hikâye.', ''],
  ['comprare', 'satın almak', 'kom-PRA-re', 'Compro il pane.', 'Ekmek alıyorum.', ''],
  ["l'inferno (m.)", 'cehennem', 'lin-FER-no', "Fa un caldo d'inferno.", 'Cehennem gibi sıcak.', ''],
  ['la regina', 'kraliçe', 'la re-Cİ-na', 'La regina saluta.', 'Kraliçe selam veriyor.', '👑'],
  ['il braccio', 'kol', 'il BRAÇ-ço', 'Ho il braccio rotto.', 'Kolum kırık.', '💪'],
  ['il crimine', 'suç', 'il KRİ-mi-ne', 'Il crimine non paga.', 'Suç kazandırmaz.', ''],
  ['la chiesa', 'kilise', 'la KYE-sa', 'La domenica vado in chiesa.', 'Pazar günleri kiliseye giderim.', '⛪'],
  ["l'effetto (m.)", 'etki', 'lef-FET-to', 'Il farmaco fa effetto.', 'İlaç etki ediyor.', ''],
  ['il tenente', 'teğmen', 'il te-NEN-te', 'Il tenente dà un ordine.', 'Teğmen bir emir veriyor.', ''],
  ['scommettere', 'bahse girmek', 'skom-MET-te-re', 'Scommetto che vince lui.', 'Bahse girerim o kazanır.', ''],
  ['il paziente', 'hasta', 'il pa-TSYEN-te', 'Il paziente sta meglio.', 'Hasta daha iyi.', ''],
  ['la scarpa', 'ayakkabı', 'la SKAR-pa', 'Queste scarpe sono comode.', 'Bu ayakkabılar rahat.', '👟'],
  ['il livello', 'seviye', 'il li-VEL-lo', 'Il mio livello è A1.', 'Seviyem A1.', ''],
  ['mentire', 'yalan söylemek', 'men-Tİ-re', 'Non mentire!', 'Yalan söyleme!', ''],
  ['lo spettacolo', 'gösteri', 'lo spet-TA-ko-lo', 'Lo spettacolo inizia presto.', 'Gösteri yakında başlıyor.', '🎭'],
  ['la visita', 'ziyaret', 'la Vİ-si-ta', 'Grazie della visita.', 'Ziyaretin için teşekkürler.', ''],
  ['mica', 'hiç, sakın (vurgu)', 'Mİ-ka', 'Non è mica facile.', 'Hiç de kolay değil.', ''],
  ['la sinistra', 'sol', 'la si-NİS-tra', 'Gira a sinistra.', 'Sola dön.', ''],
  ['perciò', 'bu yüzden', 'per-ÇO', 'Piove, perciò resto a casa.', 'Yağmur yağıyor, bu yüzden evde kalıyorum.', ''],
  ['il processo', 'dava, süreç', 'il pro-ÇES-so', 'Il processo inizia domani.', 'Dava yarın başlıyor.', ''],
  ['il mare', 'deniz', 'il MA-re', 'Andiamo al mare!', 'Denize gidelim!', '🌊'],
  ['il direttore', 'müdür', 'il di-ret-TO-re', 'Il direttore è in riunione.', 'Müdür toplantıda.', ''],
  ['intelligente', 'zeki', 'in-tel-li-CEN-te', 'Sei molto intelligente.', 'Çok zekisin.', ''],
  ['rendere', 'geri vermek; -leştirmek', 'REN-de-re', 'Mi rendi felice.', 'Beni mutlu ediyorsun.', ''],
  ['la classe', 'sınıf', 'la KLAS-se', 'La classe è piena.', 'Sınıf dolu.', ''],
  ['il cambio', 'değişim; döviz', 'il KAM-byo', "Dov'è l'ufficio cambio?", 'Döviz bürosu nerede?', ''],
  ['scorso', 'geçen', 'SKOR-so', "L'anno scorso ero a Roma.", "Geçen yıl Roma'daydım.", ''],
  ['bianco', 'beyaz', 'BYAN-ko', 'Il gatto è bianco.', 'Kedi beyaz.', ''],
  ['il tavolo', 'masa', 'il TA-vo-lo', 'Un tavolo per due, per favore.', 'İki kişilik bir masa lütfen.', ''],
  ['la stagione', 'mevsim', 'la sta-CO-ne', "L'estate è la mia stagione preferita.", 'Yaz en sevdiğim mevsim.', ''],
  ['il cavallo', 'at', 'il ka-VAL-lo', 'Il cavallo corre veloce.', 'At hızlı koşuyor.', '🐎'],
  ['il sergente', 'çavuş', 'il ser-CEN-te', 'Il sergente grida.', 'Çavuş bağırıyor.', ''],
  ['incinta', 'hamile', 'in-ÇİN-ta', 'Mia sorella è incinta.', 'Kız kardeşim hamile.', ''],
  ['rompere', 'kırmak', 'ROM-pe-re', 'Ho rotto il bicchiere.', 'Bardağı kırdım.', ''],
  ["l'episodio (m.)", 'bölüm', 'le-pi-SO-dyo', 'Guardiamo un altro episodio.', 'Bir bölüm daha izleyelim.', ''],
  ['rispondere', 'cevap vermek', 'ris-PON-de-re', 'Rispondi al telefono!', 'Telefona bak!', ''],
  ['contento', 'memnun', 'kon-TEN-to', 'Sono contento di vederti.', 'Seni gördüğüme sevindim.', ''],
  ['inglese', 'İngiliz; İngilizce', 'in-GLE-se', 'Parli inglese?', 'İngilizce konuşuyor musun?', ''],
  ['il volo', 'uçuş', 'il VO-lo', 'Il volo è in ritardo.', 'Uçuş rötarlı.', ''],
  ['attraverso', 'içinden, boyunca', 'at-tra-VER-so', 'Passiamo attraverso il parco.', 'Parkın içinden geçelim.', ''],
  ['la differenza', 'fark', 'la dif-fe-REN-tsa', 'Qual è la differenza?', 'Fark ne?', ''],
  ['aprire', 'açmak', 'a-PRİ-re', 'Apri la porta, per favore.', 'Kapıyı aç lütfen.', ''],
  ['il codice', 'kod', 'il KO-di-çe', 'Qual è il codice?', 'Kod ne?', ''],
  ['il lato', 'taraf', 'il LA-to', "Dall'altro lato della strada.", 'Yolun öbür tarafında.', ''],
  ["l'hotel (m.)", 'otel', 'lo-TEL', "L'hotel è vicino alla stazione.", 'Otel istasyona yakın.', '🏨'],
  ['maggiore', 'daha büyük', 'mac-CO-re', 'Mio fratello maggiore.', 'Ağabeyim.', ''],
  ['la carne', 'et', 'la KAR-ne', 'Non mangio carne.', 'Et yemem.', '🥩'],
  ['umano', 'insani', 'u-MA-no', 'È un errore umano.', 'İnsani bir hata.', ''],
  ['caldo', 'sıcak', 'KAL-do', 'Il caffè è caldo.', 'Kahve sıcak.', ''],
  ['la pelle', 'deri, cilt', 'la PEL-le', 'Ha la pelle chiara.', 'Açık tenli.', ''],
  ['interno', 'iç', 'in-TER-no', 'La parte interna è rossa.', 'İç kısmı kırmızı.', ''],
  ['temere', 'korkmak', 'te-ME-re', 'Temo di sì.', 'Korkarım öyle.', ''],
  ['leggere', 'okumak', 'LEC-ce-re', 'Mi piace leggere.', 'Okumayı severim.', ''],
  ['il comandante', 'komutan', 'il ko-man-DAN-te', 'Sì, comandante!', 'Emredersiniz komutanım!', ''],
  ['il pomeriggio', 'öğleden sonra', 'il po-me-RİC-co', 'Ci vediamo nel pomeriggio.', 'Öğleden sonra görüşürüz.', ''],
  ['il documento', 'belge', 'il do-ku-MEN-to', 'Un documento, per favore.', 'Kimlik lütfen.', '📄'],
  ['il giudice', 'yargıç', 'il CU-di-çe', 'Il giudice decide.', 'Yargıç karar veriyor.', ''],
  ['il mostro', 'canavar', 'il MOS-tro', 'Il bambino ha paura del mostro.', 'Çocuk canavardan korkuyor.', '👹'],
  ['la destra', 'sağ', 'la DES-tra', 'Gira a destra.', 'Sağa dön.', ''],
  ['la luna', 'ay (gökteki)', 'la LU-na', "Stanotte c'è la luna piena.", 'Bu gece dolunay var.', '🌙'],
  ['ringraziare', 'teşekkür etmek', 'rin-gra-TSYA-re', 'Ti ringrazio molto.', 'Sana çok teşekkür ederim.', ''],
  ['pericoloso', 'tehlikeli', 'pe-ri-ko-LO-so', 'È una strada pericolosa.', 'Tehlikeli bir yol.', ''],
  ['il vino', 'şarap', 'il Vİ-no', 'Un bicchiere di vino rosso.', 'Bir kadeh kırmızı şarap.', '🍷'],
  ['presente', 'mevcut; hazır', 'pre-SEN-te', 'Tutti presenti?', 'Herkes burada mı?', ''],
  ['arrivederci', 'hoşça kalın', 'ar-ri-ve-DER-çi', 'Arrivederci e grazie!', 'Hoşça kalın, teşekkürler!', ''],
  ['il caffè', 'kahve', 'il kaf-FE', 'Il caffè italiano è forte.', 'İtalyan kahvesi sert.', '☕'],
  ['la barca', 'tekne', 'la BAR-ka', 'Andiamo in barca.', 'Tekneyle gidelim.', '⛵'],
  ['la lezione', 'ders', 'la le-TSYO-ne', 'La lezione è finita.', 'Ders bitti.', ''],
  ['intero', 'bütün', 'in-TE-ro', 'Ho mangiato una pizza intera.', 'Koca bir pizza yedim.', ''],
  ['partire', 'yola çıkmak', 'par-Tİ-re', 'Parto domani mattina.', 'Yarın sabah yola çıkıyorum.', ''],
  ['il nord', 'kuzey', 'il NORD', 'Milano è al nord.', 'Milano kuzeyde.', ''],
  ['congratulazioni', 'tebrikler', 'kon-gra-tu-la-TSYO-ni', 'Congratulazioni per il lavoro!', 'İş için tebrikler!', ''],
  ['la data', 'tarih', 'la DA-ta', 'Qual è la data di oggi?', 'Bugünün tarihi ne?', ''],
  ['sposare', 'evlenmek', 'spo-SA-re', 'Mi vuoi sposare?', 'Benimle evlenir misin?', ''],
  ['il treno', 'tren', 'il TRE-no', 'Prendo il treno.', 'Trene biniyorum.', '🚆'],
  ['la radio', 'radyo', 'la RA-dyo', 'Accendi la radio.', 'Radyoyu aç.', '📻'],
  ['comune', 'ortak; belediye', 'ko-MU-ne', 'Abbiamo molto in comune.', 'Çok ortak noktamız var.', ''],
  ['cattivo', 'kötü', 'kat-Tİ-vo', 'Non essere cattivo.', 'Kötü olma.', ''],
  ['imparare', 'öğrenmek', 'im-pa-RA-re', "Imparo l'italiano.", 'İtalyanca öğreniyorum.', ''],
  ['responsabile', 'sorumlu', 'res-pon-SA-bi-le', 'Sei responsabile tu.', 'Sorumlu sensin.', ''],
  ['la bomba', 'bomba', 'la BOM-ba', 'La bomba è esplosa.', 'Bomba patladı.', '💣'],
  ['il periodo', 'dönem', 'il pe-Rİ-o-do', 'È un periodo difficile.', 'Zor bir dönem.', ''],
  ["l'energia (f.)", 'enerji', 'le-ner-Cİ-a', 'Non ho energia oggi.', 'Bugün enerjim yok.', ''],
  ['il segno', 'işaret', 'il SEN-yo', 'È un buon segno.', 'İyiye işaret.', ''],
  ['calmarsi', 'sakinleşmek', 'kal-MAR-si', 'Calmati, per favore.', 'Sakin ol lütfen.', ''],
  ['la speranza', 'umut', 'la spe-RAN-tsa', "C'è ancora speranza.", 'Hâlâ umut var.', ''],
  ['il rischio', 'risk', 'il RİS-kyo', 'È un rischio.', 'Bu bir risk.', ''],
  ['rosso', 'kırmızı', 'ROS-so', 'Mi piace il colore rosso.', 'Kırmızı rengi severim.', ''],
  ['soprattutto', 'özellikle', 'so-prat-TUT-to', 'Mi piace soprattutto il mare.', 'Özellikle denizi severim.', ''],
  ['combattere', 'savaşmak', 'kom-BAT-te-re', 'Dobbiamo combattere.', 'Savaşmalıyız.', ''],
  ['toccare', 'dokunmak', 'tok-KA-re', 'Non toccare!', 'Dokunma!', ''],
  ["l'operazione (f.)", 'ameliyat; operasyon', 'lo-pe-ra-TSYO-ne', "L'operazione è andata bene.", 'Ameliyat iyi geçti.', ''],
  ['la zia', 'teyze, hala', 'la TSİ-a', 'Mia zia vive a Roma.', "Teyzem Roma'da yaşıyor.", ''],
  ['la gamba', 'bacak', 'la GAM-ba', 'Ho le gambe stanche.', 'Bacaklarım yorgun.', '🦵'],
  ['il biglietto', 'bilet', 'il bi-LYET-to', 'Un biglietto per Roma, per favore.', "Roma'ya bir bilet lütfen.", '🎫'],
  ['ufficiale', 'resmî; subay', 'uf-fi-ÇA-le', 'È una notizia ufficiale.', 'Resmî bir haber.', ''],
  ['la pressione', 'basınç; tansiyon', 'la pres-SYO-ne', 'Ho la pressione alta.', 'Tansiyonum yüksek.', ''],
  ['nascondere', 'saklamak', 'nas-KON-de-re', 'Dove hai nascosto il regalo?', 'Hediyeyi nereye sakladın?', ''],
  ['il maestro', 'öğretmen; usta', 'il ma-ES-tro', 'Il maestro spiega la lezione.', 'Öğretmen dersi anlatıyor.', ''],
  ['benvenuto', 'hoş geldin', 'ben-ve-NU-to', 'Benvenuto in Italia!', "İtalya'ya hoş geldin!", ''],
  ["l'offerta (f.)", 'teklif; indirim', 'lof-FER-ta', "È un'offerta speciale.", 'Özel bir teklif.', ''],
  ['lo scherzo', 'şaka', 'lo SKER-tso', 'È solo uno scherzo.', 'Sadece bir şaka.', ''],
  ['il testimone', 'tanık', 'il tes-ti-MO-ne', 'Il testimone parla.', 'Tanık konuşuyor.', ''],
  ['la banca', 'banka', 'la BAN-ka', 'Vado in banca.', 'Bankaya gidiyorum.', '🏦'],
  ["l'indirizzo (m.)", 'adres', 'lin-di-RİT-tso', 'Qual è il tuo indirizzo?', 'Adresin ne?', ''],
  ['tale', 'öyle, böyle bir', 'TA-le', 'Tale padre, tale figlio.', 'Armut dibine düşer.', ''],
  ['ottenere', 'elde etmek', 'ot-te-NE-re', 'Voglio ottenere il visto.', 'Vizeyi almak istiyorum.', ''],
  ["l'esperienza (f.)", 'deneyim', 'les-pe-RYEN-tsa', 'È stata una bella esperienza.', 'Güzel bir deneyimdi.', ''],
  ['piangere', 'ağlamak', 'PYAN-ce-re', 'Non piangere.', 'Ağlama.', ''],
  ['il sud', 'güney', 'il SUD', 'Napoli è al sud.', 'Napoli güneyde.', ''],
  ['il pianeta', 'gezegen', 'il pya-NE-ta', 'La Terra è un pianeta.', 'Dünya bir gezegen.', '🪐'],
  ['inoltre', 'ayrıca', 'i-NOL-tre', 'Inoltre, è economico.', 'Ayrıca ucuz.', ''],
  ['la serie', 'dizi', 'la SE-rye', 'Guardo una serie nuova.', 'Yeni bir dizi izliyorum.', ''],
  ['la guida', 'rehber; sürüş', 'la GUİ-da', 'La guida parla inglese.', 'Rehber İngilizce konuşuyor.', ''],
  ['il prezzo', 'fiyat', 'il PRET-tso', 'Il prezzo è giusto.', 'Fiyat uygun.', '🏷️'],
  ['arrabbiato', 'kızgın', 'ar-rab-BYA-to', 'Sei arrabbiato con me?', 'Bana kızgın mısın?', ''],
  ['orribile', 'korkunç', 'or-Rİ-bi-le', 'Il tempo è orribile.', 'Hava berbat.', ''],
  ['il ritorno', 'dönüş', 'il ri-TOR-no', 'Un biglietto di andata e ritorno.', 'Gidiş-dönüş bir bilet.', ''],
  ["l'animale (m.)", 'hayvan', 'la-ni-MA-le', 'Ami gli animali?', 'Hayvanları sever misin?', '🐾'],
  ['enorme', 'kocaman', 'e-NOR-me', 'La casa è enorme.', 'Ev kocaman.', ''],
  ['il passaggio', 'geçit; arabayla götürme', 'il pas-SAC-co', 'Mi dai un passaggio?', 'Beni arabayla bırakır mısın?', ''],
  ['il progetto', 'proje', 'il pro-CET-to', 'È un progetto nuovo.', 'Yeni bir proje.', ''],
  ['il danno', 'zarar', 'il DAN-no', 'Il danno è grave.', 'Zarar ağır.', ''],
  ['naturalmente', 'doğal olarak', 'na-tu-ral-MEN-te', 'Naturalmente parlo italiano.', 'Doğal olarak İtalyanca konuşuyorum.', ''],
  ['colpevole', 'suçlu', 'kol-PE-vo-le', "L'uomo è colpevole.", 'Adam suçlu.', ''],
  ['il metro', 'metre', 'il ME-tro', 'È a cento metri.', 'Yüz metre ötede.', ''],
  ['la mossa', 'hamle', 'la MOS-sa', 'Buona mossa!', 'İyi hamle!', ''],
  ['la finestra', 'pencere', 'la fi-NES-tra', 'La finestra è aperta.', 'Pencere açık.', '🪟'],
  ['supporre', 'varsaymak', 'sup-POR-re', 'Suppongo di sì.', 'Sanırım öyle.', ''],
  ['il destino', 'kader', 'il des-Tİ-no', 'È il destino.', 'Kader bu.', ''],
  ['saltare', 'atlamak', 'sal-TA-re', 'Il gatto salta sul letto.', 'Kedi yatağa atlıyor.', ''],
  ['correre', 'koşmak', 'KOR-re-re', 'Corro ogni mattina.', 'Her sabah koşarım.', ''],
  ["l'edificio (m.)", 'bina', 'le-di-Fİ-ço', "L'edificio è molto alto.", 'Bina çok yüksek.', '🏢'],
  ['la colazione', 'kahvaltı', 'la ko-la-TSYO-ne', 'Faccio colazione alle sette.', 'Saat yedide kahvaltı yaparım.', '🥐'],
  ['il collo', 'boyun', 'il KOL-lo', 'Ho mal di collo.', 'Boynum ağrıyor.', ''],
  ['la difesa', 'savunma', 'la di-FE-sa', 'La difesa è forte.', 'Savunma güçlü.', ''],
  ['la fiducia', 'güven', 'la fi-DU-ça', 'Ho fiducia in te.', 'Sana güveniyorum.', ''],
  ['il ristorante', 'restoran', 'il ris-to-RAN-te', 'Andiamo al ristorante?', 'Restorana gidelim mi?', '🍽️'],
  ['il laboratorio', 'laboratuvar', 'il la-bo-ra-TO-ryo', 'Lavoro in un laboratorio.', 'Bir laboratuvarda çalışıyorum.', '🔬'],
  ['il comando', 'komuta; emir', 'il ko-MAN-do', 'Chi ha il comando?', 'Komuta kimde?', ''],
  ["l'arte (f.)", 'sanat', 'LAR-te', "Amo l'arte italiana.", 'İtalyan sanatını seviyorum.', ''],
  ['la metà', 'yarı', 'la me-TA', 'Mangio metà pizza.', 'Pizzanın yarısını yiyorum.', ''],
  ['il discorso', 'konuşma', 'il dis-KOR-so', 'Che bel discorso!', 'Ne güzel bir konuşma!', ''],
  ['nove', 'dokuz', 'NO-ve', 'Sono le nove.', 'Saat dokuz.', ''],
  ['il segnale', 'sinyal; işaret', 'il se-NYA-le', "Non c'è segnale qui.", 'Burada sinyal yok.', ''],
  ['fortunato', 'şanslı', 'for-tu-NA-to', 'Sei fortunato!', 'Şanslısın!', ''],
  ['la carriera', 'kariyer', 'la kar-RYE-ra', 'Pensa alla tua carriera.', 'Kariyerini düşün.', ''],
  ['blu', 'mavi', 'BLU', 'Ho una macchina blu.', 'Mavi bir arabam var.', ''],
  ['cominciare', 'başlamak', 'ko-min-ÇA-re', 'Cominciamo!', 'Başlayalım!', ''],
  ['il muro', 'duvar', 'il MU-ro', "C'è un quadro sul muro.", 'Duvarda bir tablo var.', '🧱'],
  ['tranne', 'hariç', 'TRAN-ne', 'Tutti tranne lui.', 'O hariç herkes.', ''],
  ['proteggere', 'korumak', 'pro-TEC-ce-re', 'Voglio proteggerti.', 'Seni korumak istiyorum.', ''],
  ['il dubbio', 'şüphe', 'il DUB-byo', 'Senza dubbio!', 'Şüphesiz!', ''],
  ['la stazione', 'istasyon', 'la sta-TSYO-ne', "Dov'è la stazione?", 'İstasyon nerede?', '🚉'],
  ["l'emergenza (f.)", 'acil durum', 'le-mer-CEN-tsa', "È un'emergenza!", 'Acil durum!', ''],
  ['la giustizia', 'adalet', 'la cus-Tİ-tsya', 'Voglio giustizia.', 'Adalet istiyorum.', ''],
  ['immediatamente', 'hemen', 'im-me-dya-ta-MEN-te', 'Vieni qui immediatamente!', 'Hemen buraya gel!', ''],
  ["l'odore (m.)", 'koku', 'lo-DO-re', 'Che buon odore!', 'Ne güzel koku!', ''],
  ['contrario', 'karşıt, zıt', 'kon-TRA-ryo', 'Al contrario!', 'Tam tersine!', ''],
  ['terzo', 'üçüncü', 'TER-tso', 'Abito al terzo piano.', 'Üçüncü katta oturuyorum.', ''],
  ['locale', 'yerel; mekân', 'lo-KA-le', 'È un locale carino.', 'Şirin bir mekân.', ''],
  ['la battaglia', 'muharebe', 'la bat-TA-lya', 'La battaglia è finita.', 'Muharebe bitti.', ''],
  ['notare', 'fark etmek', 'no-TA-re', 'Hai notato qualcosa?', 'Bir şey fark ettin mi?', ''],
  ['lo sceriffo', 'şerif', 'lo şe-RİF-fo', 'Lo sceriffo arriva.', 'Şerif geliyor.', '🤠'],
  ['evitare', 'kaçınmak', 'e-vi-TA-re', 'Evita il traffico.', 'Trafikten kaçın.', ''],
  ['lo spirito', 'ruh; espri', 'lo SPİ-ri-to', 'Ha molto spirito.', 'Çok esprili.', ''],
  ['la lingua', 'dil', 'la LİN-gua', 'Parlo tre lingue.', 'Üç dil konuşuyorum.', ''],
  ['il dipartimento', 'bölüm, departman', 'il di-par-ti-MEN-to', 'Lavoro nel dipartimento vendite.', 'Satış departmanında çalışıyorum.', ''],
  ['massimo', 'en fazla, azami', 'MAS-si-mo', 'Al massimo due ore.', 'En fazla iki saat.', ''],
  ['praticamente', 'neredeyse, pratikte', 'pra-ti-ka-MEN-te', 'È praticamente finito.', 'Neredeyse bitti.', ''],
  ['la riunione', 'toplantı', 'la ryu-NYO-ne', 'La riunione è lunga.', 'Toplantı uzun.', ''],
  ['il rumore', 'gürültü', 'il ru-MO-re', "Che cos'è questo rumore?", 'Bu gürültü ne?', ''],
  ['la torta', 'pasta (kek)', 'la TOR-ta', 'La torta è buonissima.', 'Pasta çok lezzetli.', '🍰'],
  ['accanto', 'yanında', 'ak-KAN-to', 'Siediti accanto a me.', 'Yanıma otur.', ''],
  ["l'eroe (m.)", 'kahraman', 'le-RO-e', 'Sei il mio eroe.', 'Sen benim kahramanımsın.', '🦸'],
  ['il turno', 'sıra; vardiya', 'il TUR-no', 'È il tuo turno.', 'Sıra sende.', ''],
  ['il fiore', 'çiçek', 'il FYO-re', 'Ti ho portato dei fiori.', 'Sana çiçek getirdim.', '🌸'],
  ['persino', 'bile', 'per-Sİ-no', 'Persino lui ride.', 'O bile gülüyor.', ''],
  ['ovvio', 'belli, açık', 'OV-vyo', 'È ovvio!', 'Belli!', ''],
  ['il furgone', 'kamyonet', 'il fur-GO-ne', 'Il furgone è bianco.', 'Kamyonet beyaz.', '🚐'],
  ['la coppia', 'çift', 'la KOP-pya', 'Sono una bella coppia.', 'Güzel bir çiftler.', '💑'],
  ['ridere', 'gülmek', 'Rİ-de-re', 'Mi fai ridere!', 'Beni güldürüyorsun!', ''],
  ['la pausa', 'mola', 'la PAU-sa', 'Facciamo una pausa.', 'Mola verelim.', ''],
  ['grave', 'ciddi, ağır', 'GRA-ve', 'Non è grave.', 'Ciddi değil.', ''],
  ['la memoria', 'hafıza', 'la me-MO-rya', 'Ho una buona memoria.', 'Hafızam iyidir.', ''],
  ['il naso', 'burun', 'il NA-so', 'Ha il naso piccolo.', 'Burnu küçük.', '👃'],
  ['il nemico', 'düşman', 'il ne-Mİ-ko', 'Non sono tuo nemico.', 'Senin düşmanın değilim.', ''],
  ['il colonnello', 'albay', 'il ko-lon-NEL-lo', 'Il colonnello è arrivato.', 'Albay geldi.', ''],
  ['la palla', 'top', 'la PAL-la', 'Passami la palla!', 'Topu bana at!', '⚽'],
  ['costare', 'mal olmak, tutmak', 'kos-TA-re', 'Il biglietto costa dieci euro.', 'Bilet on avro.', ''],
  ['laggiù', 'orada (aşağıda)', 'lag-CU', 'Guarda laggiù!', 'Oraya bak!', ''],
  ['la scatola', 'kutu', 'la SKA-to-la', 'La scatola è vuota.', 'Kutu boş.', '📦'],
  ["l'albero (m.)", 'ağaç', 'LAL-be-ro', "C'è un albero in giardino.", 'Bahçede bir ağaç var.', '🌳'],
  ['il tribunale', 'mahkeme', 'il tri-bu-NA-le', 'Ci vediamo in tribunale.', 'Mahkemede görüşürüz.', ''],
  ['la razza', 'ırk; cins', 'la RAT-tsa', 'Che razza di cane è?', 'Bu ne cins köpek?', ''],
  ["l'anello (m.)", 'yüzük', 'la-NEL-lo', "Che bell'anello!", 'Ne güzel yüzük!', '💍'],
  ['la ferita', 'yara', 'la fe-Rİ-ta', 'La ferita fa male.', 'Yara acıyor.', ''],
  ['il sentimento', 'duygu', 'il sen-ti-MEN-to', 'È un sentimento forte.', 'Güçlü bir duygu.', ''],
  ["l'arresto (m.)", 'tutuklama', 'lar-RES-to', 'Sei in arresto!', 'Tutuklusun!', ''],
  ['il soldato', 'asker', 'il sol-DA-to', 'Il soldato è coraggioso.', 'Asker cesur.', '🪖'],
  ['la natura', 'doğa', 'la na-TU-ra', 'Amo la natura.', 'Doğayı seviyorum.', ''],
  ['inutile', 'gereksiz, yararsız', 'i-NU-ti-le', 'È inutile piangere.', 'Ağlamak boşuna.', ''],
  ['il colore', 'renk', 'il ko-LO-re', 'Qual è il tuo colore preferito?', 'En sevdiğin renk ne?', '🎨'],
  ['basso', 'alçak; kısa (boy)', 'BAS-so', 'Sono basso.', 'Ben kısayım.', ''],
  ["l'uso (m.)", 'kullanım', 'LU-so', 'Solo per uso personale.', 'Sadece kişisel kullanım için.', ''],
  ['anzi', 'aksine; hatta', 'AN-tsi', 'Non è brutto, anzi!', 'Çirkin değil, aksine!', ''],
  ['preferire', 'tercih etmek', 'pre-fe-Rİ-re', 'Preferisco il tè.', 'Çayı tercih ederim.', ''],
  ['utile', 'faydalı', 'U-ti-le', 'Questo libro è utile.', 'Bu kitap faydalı.', ''],
  ['il professore', 'öğretmen, profesör', 'il pro-fes-SO-re', 'Il professore è simpatico.', 'Öğretmen sevimli.', ''],
  ['il fidanzato', 'nişanlı; erkek arkadaş', 'il fi-dan-TSA-to', 'Il mio fidanzato è italiano.', 'Erkek arkadaşım İtalyan.', ''],
  ['la sensazione', 'his', 'la sen-sa-TSYO-ne', 'Ho una brutta sensazione.', 'İçimde kötü bir his var.', ''],
  ['legale', 'yasal', 'le-GA-le', 'È tutto legale.', 'Her şey yasal.', ''],
  ['il compito', 'görev; ödev', 'il KOM-pi-to', 'Hai fatto i compiti?', 'Ödevlerini yaptın mı?', ''],
  ['la corte', 'mahkeme; avlu', 'la KOR-te', 'La corte decide domani.', 'Mahkeme yarın karar veriyor.', ''],
  ['il pesce', 'balık', 'il PEŞ-şe', 'Mangio pesce il venerdì.', 'Cuma günleri balık yerim.', '🐟'],
  ["l'obiettivo (m.)", 'hedef', 'lo-byet-Tİ-vo', 'Il mio obiettivo è parlare italiano.', 'Hedefim İtalyanca konuşmak.', '🎯'],
  ['nascere', 'doğmak', 'NAŞ-şe-re', 'Sono nato in Turchia.', "Türkiye'de doğdum.", ''],
  ['contare', 'saymak; önemli olmak', 'kon-TA-re', 'Conta fino a dieci.', 'Ona kadar say.', ''],
  ["l'accesso (m.)", 'erişim', 'laç-ÇES-so', 'Non ho accesso a internet.', 'İnternete erişimim yok.', ''],
  ['breve', 'kısa', 'BRE-ve', 'Una breve pausa.', 'Kısa bir mola.', ''],
  ['risolvere', 'çözmek', 'ri-SOL-ve-re', 'Possiamo risolvere il problema.', 'Sorunu çözebiliriz.', ''],
  ["l'isola (f.)", 'ada', 'Lİ-so-la', "La Sicilia è un'isola.", 'Sicilya bir ada.', '🏝️'],
  ['povero', 'fakir; zavallı', 'PO-ve-ro', 'Povero gatto!', 'Zavallı kedi!', ''],
  ['stavolta', 'bu sefer', 'sta-VOL-ta', 'Stavolta pago io.', 'Bu sefer ben ödüyorum.', ''],
  ['affrontare', 'yüzleşmek', 'af-fron-TA-re', 'Devi affrontare la paura.', 'Korkunla yüzleşmelisin.', ''],
  ["l'opera (f.)", 'eser; opera', 'LO-pe-ra', "È un'opera d'arte.", 'Bu bir sanat eseri.', ''],
  ['ballare', 'dans etmek', 'bal-LA-re', 'Ti piace ballare?', 'Dans etmeyi sever misin?', ''],
  ['il bacio', 'öpücük', 'il BA-ço', 'Dammi un bacio.', 'Bana bir öpücük ver.', '💋'],
  ['il bordo', 'kenar; güverte', 'il BOR-do', 'Benvenuti a bordo!', 'Gemiye hoş geldiniz!', ''],
  ['lo sbaglio', 'hata', 'lo ZBA-lyo', 'Ho fatto uno sbaglio.', 'Bir hata yaptım.', ''],
  ['verde', 'yeşil', 'VER-de', 'La mela è verde.', 'Elma yeşil.', ''],
  ['improvviso', 'ani', 'im-prov-Vİ-so', "All'improvviso piove.", 'Birden yağmur başlıyor.', ''],
  ['il fianco', 'yan, böğür', 'il FYAN-ko', 'Siediti al mio fianco.', 'Yanıma otur.', ''],
  ['alzarsi', 'kalkmak', 'al-TSAR-si', 'Mi alzo alle sette.', 'Saat yedide kalkarım.', ''],
  ['accettare', 'kabul etmek', 'aç-çet-TA-re', 'Accetto la tua offerta.', 'Teklifini kabul ediyorum.', ''],
  ['il peso', 'ağırlık', 'il PE-so', 'Qual è il tuo peso?', 'Kilon kaç?', ''],
  ['lo stile', 'stil', 'lo STİ-le', 'Mi piace il tuo stile.', 'Tarzını beğeniyorum.', ''],
  ['la corsa', 'koşu; yarış', 'la KOR-sa', 'Faccio una corsa al parco.', 'Parkta koşu yapıyorum.', ''],
  ["l'entrata (f.)", 'giriş', 'len-TRA-ta', "L'entrata è gratuita.", 'Giriş ücretsiz.', ''],
  ['la soluzione', 'çözüm', 'la so-lu-TSYO-ne', "C'è sempre una soluzione.", 'Her zaman bir çözüm vardır.', ''],
  ['il contratto', 'sözleşme', 'il kon-TRAT-to', 'Firma il contratto qui.', 'Sözleşmeyi buradan imzala.', ''],
  ['meraviglioso', 'harika', 'me-ra-vi-LYO-so', 'È un posto meraviglioso.', 'Harika bir yer.', ''],
  ['guidare', 'araba kullanmak', 'gui-DA-re', 'Sai guidare?', 'Araba kullanabiliyor musun?', ''],
  ['il dente', 'diş', 'il DEN-te', 'Lavati i denti!', 'Dişlerini fırçala!', '🦷'],
  ['fidarsi', 'güvenmek', 'fi-DAR-si', 'Fidati di me.', 'Bana güven.', ''],
  ['la sveglia', 'çalar saat', 'la ZVE-lya', 'La sveglia suona alle sei.', 'Çalar saat altıda çalıyor.', '⏰'],
  ['ultimamente', 'son zamanlarda', 'ul-ti-ma-MEN-te', 'Ultimamente lavoro molto.', 'Son zamanlarda çok çalışıyorum.', ''],
  ['creare', 'yaratmak', 'kre-A-re', 'Mi piace creare cose nuove.', 'Yeni şeyler yaratmayı severim.', ''],
  ['dipendere', 'bağlı olmak', 'di-PEN-de-re', 'Dipende da te.', 'Sana bağlı.', ''],
  ['innocente', 'masum', 'in-no-ÇEN-te', 'Sono innocente!', 'Masumum!', ''],
  ['lo scopo', 'amaç', 'lo SKO-po', 'Qual è lo scopo?', 'Amaç ne?', ''],
  ['il coltello', 'bıçak', 'il kol-TEL-lo', 'Passami il coltello.', 'Bıçağı uzat.', '🔪'],
  ['la fila', 'sıra, kuyruk', 'la Fİ-la', "C'è una lunga fila.", 'Uzun bir kuyruk var.', ''],
  ['la magia', 'sihir', 'la ma-Cİ-a', 'Sembra magia!', 'Sihir gibi!', ''],
  ['il procuratore', 'savcı', 'il pro-ku-ra-TO-re', 'Il procuratore parla con il giudice.', 'Savcı yargıçla konuşuyor.', ''],
  ['vendere', 'satmak', 'VEN-de-re', 'Vendo la mia macchina.', 'Arabamı satıyorum.', ''],
  ['i pantaloni', 'pantolon', 'i pan-ta-LO-ni', 'Questi pantaloni sono lunghi.', 'Bu pantolon uzun.', '👖'],
  ['centrale', 'merkezi', 'çen-TRA-le', 'La stazione centrale è lontana.', 'Merkez istasyon uzak.', ''],
  ["l'azione (f.)", 'eylem; aksiyon', 'la-TSYO-ne', "È un film d'azione.", 'Bu bir aksiyon filmi.', ''],
  ['il principe', 'prens', 'il PRİN-çi-pe', 'Il principe sposa la principessa.', 'Prens prensesle evleniyor.', ''],
  ['il cadavere', 'ceset', 'il ka-DA-ve-re', 'Hanno trovato un cadavere.', 'Bir ceset buldular.', ''],
  ['la fede', 'inanç; alyans', 'la FE-de', 'Ha una fede forte.', 'Güçlü bir inancı var.', ''],
  ['il nipote', 'torun; yeğen', 'il ni-PO-te', 'Mio nipote ha tre anni.', 'Torunum üç yaşında.', ''],
  ['la stampa', 'basın', 'la STAM-pa', 'La stampa è qui.', 'Basın burada.', ''],
  ["l'assistente (m.)", 'asistan', 'las-sis-TEN-te', 'Il mio assistente è bravo.', 'Asistanım işini iyi yapıyor.', ''],
  ['ognuno', 'herkes, her biri', 'on-YU-no', 'Ognuno ha un libro.', 'Herkesin bir kitabı var.', ''],
  ['debole', 'zayıf', 'DE-bo-le', 'Mi sento debole.', 'Kendimi zayıf hissediyorum.', ''],
  ['il risultato', 'sonuç', 'il ri-sul-TA-to', 'Il risultato è buono.', 'Sonuç iyi.', ''],
  ['ridicolo', 'gülünç', 'ri-Dİ-ko-lo', 'Non essere ridicolo.', 'Saçmalama.', ''],
  ['grandioso', 'muhteşem', 'gran-DYO-so', 'È uno spettacolo grandioso!', 'Muhteşem bir gösteri!', ''],
  ['americano', 'Amerikalı', 'a-me-ri-KA-no', 'Lui è americano.', 'O Amerikalı.', ''],
  ['francese', 'Fransız; Fransızca', 'fran-ÇE-se', "Parlo un po' di francese.", 'Biraz Fransızca konuşuyorum.', ''],
  ['il taxi', 'taksi', 'il TAK-si', 'Prendiamo un taxi.', 'Taksiye binelim.', '🚕'],
  ['peggiore', 'daha kötü; en kötü', 'pec-CO-re', 'È il giorno peggiore.', 'En kötü gün.', ''],
  ["l'angolo (m.)", 'köşe', 'LAN-go-lo', "Il bar è all'angolo.", 'Bar köşede.', ''],
  ['il latte', 'süt', 'il LAT-te', 'Un caffè con latte.', 'Sütlü kahve.', '🥛'],
  ['il buio', 'karanlık', 'il BU-yo', 'È già buio.', 'Hava çoktan karardı.', ''],
  ['la malattia', 'hastalık', 'la ma-lat-Tİ-a', 'È una malattia grave.', 'Ciddi bir hastalık.', ''],
  ['il gatto', 'kedi', 'il GAT-to', 'Il gatto dorme sul divano.', 'Kedi kanepede uyuyor.', '🐈'],
  ['suonare', 'çalmak (müzik, zil)', 'suo-NA-re', 'Suono la chitarra.', 'Gitar çalarım.', ''],
  ["l'estate (f.)", 'yaz', 'les-TA-te', "D'estate vado al mare.", 'Yazın denize giderim.', ''],
  ['scomparire', 'kaybolmak', 'skom-pa-Rİ-re', 'Il sole è scomparso.', 'Güneş kayboldu.', ''],
  ['la condizione', 'koşul; durum', 'la kon-di-TSYO-ne', 'A una condizione.', 'Bir şartla.', ''],
  ['muoversi', 'hareket etmek, acele etmek', 'MUO-ver-si', 'Muoviti, siamo in ritardo!', 'Acele et, geç kaldık!', ''],
  ['il fiume', 'nehir', 'il FYU-me', 'Il fiume è lungo.', 'Nehir uzun.', '🏞️'],
  ['la schiena', 'sırt', 'la SKYE-na', 'Ho mal di schiena.', 'Sırtım ağrıyor.', ''],
  ['il sindaco', 'belediye başkanı', 'il SİN-da-ko', 'Il sindaco parla in piazza.', 'Belediye başkanı meydanda konuşuyor.', ''],
  ['nonostante', '-e rağmen', 'no-nos-TAN-te', 'Esco nonostante la pioggia.', 'Yağmura rağmen çıkıyorum.', ''],
  ['la campagna', 'kırsal; kampanya', 'la kam-PA-nya', 'Vivo in campagna.', 'Kırsalda yaşıyorum.', ''],
  ['la paga', 'maaş', 'la PA-ga', 'La paga è bassa.', 'Maaş düşük.', ''],
  ['seguire', 'takip etmek', 'se-GUİ-re', 'Seguimi!', 'Beni takip et!', ''],
  ['il dettaglio', 'ayrıntı', 'il det-TA-lyo', 'Raccontami i dettagli.', 'Bana ayrıntıları anlat.', ''],
  ['chiaramente', 'açıkça', 'kya-ra-MEN-te', 'Parla chiaramente.', 'Açıkça konuş.', ''],
  ['capace', 'yetenekli, -ebilen', 'ka-PA-çe', 'Sei capace di farlo.', 'Bunu yapabilirsin.', ''],
  ['distruggere', 'yok etmek', 'dis-TRUC-ce-re', 'Il fuoco distrugge tutto.', 'Ateş her şeyi yok eder.', ''],
  ["l'importanza (f.)", 'önem', 'lim-por-TAN-tsa', 'Non ha importanza.', 'Önemi yok.', ''],
  ['particolare', 'özel; belirli', 'par-ti-ko-LA-re', 'Niente di particolare.', 'Özel bir şey yok.', ''],
  ['stanco', 'yorgun', 'STAN-ko', 'Sono molto stanco.', 'Çok yorgunum.', ''],
  ['il piano', 'plan; kat', 'il PYA-no', 'Qual è il piano?', 'Plan ne?', ''],
  ['mantenere', 'korumak; tutmak', 'man-te-NE-re', 'Mantieni la promessa.', 'Sözünü tut.', ''],
  ['la richiesta', 'talep, rica', 'la ri-KYES-ta', 'Ho una richiesta.', 'Bir ricam var.', ''],
  ['parecchio', 'epey', 'pa-REK-kyo', 'Ho aspettato parecchio.', 'Epey bekledim.', ''],
  ['principale', 'ana, başlıca', 'prin-çi-PA-le', 'È la via principale.', 'Bu ana cadde.', ''],
  ['insegnare', 'öğretmek', 'in-se-NYA-re', "Mi insegni l'italiano?", 'Bana İtalyanca öğretir misin?', ''],
  ['la faccenda', 'mesele, iş', 'la faç-ÇEN-da', 'È una faccenda seria.', 'Ciddi bir mesele.', ''],
  ['il vento', 'rüzgâr', 'il VEN-to', "C'è molto vento oggi.", 'Bugün çok rüzgâr var.', '🌬️'],
  ['matto', 'deli', 'MAT-to', 'Vado matto per il gelato.', 'Dondurmaya bayılırım.', ''],
  ['convinto', 'ikna olmuş, emin', 'kon-VİN-to', 'Non sono convinto.', 'İkna olmadım.', ''],
  ['rovinare', 'mahvetmek', 'ro-vi-NA-re', 'Hai rovinato tutto!', 'Her şeyi mahvettin!', ''],
  ['il campione', 'şampiyon; numune', 'il kam-PYO-ne', 'È un campione di tennis.', 'O bir tenis şampiyonu.', '🏆'],
  ['buonasera', 'iyi akşamlar', 'buo-na-SE-ra', 'Buonasera a tutti!', 'Herkese iyi akşamlar!', ''],
  ['decisamente', 'kesinlikle', 'de-çi-sa-MEN-te', 'È decisamente meglio.', 'Kesinlikle daha iyi.', ''],
  ['il mercato', 'pazar', 'il mer-KA-to', 'Vado al mercato il sabato.', 'Cumartesi pazara giderim.', ''],
  ['il valore', 'değer', 'il va-LO-re', 'Ha un grande valore.', 'Büyük bir değeri var.', ''],
  ['sbrigarsi', 'acele etmek', 'zbri-GAR-si', 'Sbrigati, il treno parte!', 'Acele et, tren kalkıyor!', ''],
  ['salire', 'çıkmak, binmek', 'sa-Lİ-re', 'Sali in macchina.', 'Arabaya bin.', ''],
  ['spiegare', 'açıklamak', 'spye-GA-re', 'Puoi spiegare meglio?', 'Daha iyi açıklayabilir misin?', ''],
  ['la principessa', 'prenses', 'la prin-çi-PES-sa', 'La principessa vive nel castello.', 'Prenses şatoda yaşıyor.', '👸'],
  ['la bellezza', 'güzellik', 'la bel-LET-tsa', 'Che bellezza!', 'Ne güzellik!', ''],
  ['rilassarsi', 'rahatlamak', 'ri-las-SAR-si', "Rilassati un po'.", 'Biraz rahatla.', ''],
  ['il buco', 'delik', 'il BU-ko', "C'è un buco nel muro.", 'Duvarda bir delik var.', ''],
  ['la conversazione', 'sohbet', 'la kon-ver-sa-TSYO-ne', 'È una bella conversazione.', 'Güzel bir sohbet.', ''],
  ["l'attesa (f.)", 'bekleme', 'lat-TE-sa', "La sala d'attesa è piena.", 'Bekleme salonu dolu.', ''],
  ['il pensiero', 'düşünce', 'il pen-SYE-ro', 'Un pensiero gentile.', 'Nazik bir düşünce.', ''],
  ['la conoscenza', 'bilgi; tanışıklık', 'la ko-noş-ŞEN-tsa', 'La conoscenza è potere.', 'Bilgi güçtür.', ''],
  ['il ponte', 'köprü', 'il PON-te', 'Il ponte è vecchio.', 'Köprü eski.', '🌉'],
  ['malato', 'hasta', 'ma-LA-to', 'Oggi sono malato.', 'Bugün hastayım.', ''],
  ['la sedia', 'sandalye', 'la SE-dya', 'Prendi una sedia.', 'Bir sandalye al.', '🪑'],
  ['finale', 'son, final', 'fi-NA-le', 'È la partita finale.', 'Final maçı.', ''],
  ["l'impronta (f.)", 'iz, parmak izi', 'lim-PRON-ta', 'Ci sono impronte sul vetro.', 'Camda parmak izleri var.', ''],
  ['sistemare', 'düzeltmek, yerleştirmek', 'sis-te-MA-re', 'Devo sistemare la camera.', 'Odayı toplamam lazım.', ''],
  ['il ghiaccio', 'buz', 'il GYAÇ-ço', 'Acqua con ghiaccio, per favore.', 'Buzlu su lütfen.', '🧊'],
  ['la traccia', 'iz', 'la TRAÇ-ça', "Non c'è nessuna traccia.", 'Hiç iz yok.', ''],
  ['la bottiglia', 'şişe', 'la bot-Tİ-lya', "Una bottiglia d'acqua.", 'Bir şişe su.', '🍾'],
  ["l'indagine (f.)", 'soruşturma', 'lin-DA-ci-ne', "L'indagine continua.", 'Soruşturma devam ediyor.', ''],
  ['eppure', 'yine de', 'ep-PU-re', 'Eppure è vero.', 'Yine de doğru.', ''],
  ['il tiro', 'atış', 'il Tİ-ro', 'Bel tiro!', 'Güzel atış!', ''],
  ['cadere', 'düşmek', 'ka-DE-re', 'Attento, non cadere!', 'Dikkat et, düşme!', ''],
  ['lo sguardo', 'bakış', 'lo ZGUAR-do', 'Ha uno sguardo dolce.', 'Tatlı bir bakışı var.', ''],
  ['la perdita', 'kayıp', 'la PER-di-ta', 'È una grande perdita.', 'Büyük bir kayıp.', ''],
  ['camminare', 'yürümek', 'kam-mi-NA-re', 'Camminiamo lungo il fiume.', 'Nehir boyunca yürüyelim.', ''],
  ['la pratica', 'uygulama, pratik', 'la PRA-ti-ka', 'Serve molta pratica.', 'Çok pratik gerekir.', ''],
  ['il villaggio', 'köy', 'il vil-LAC-co', 'Vivo in un piccolo villaggio.', 'Küçük bir köyde yaşıyorum.', ''],
  ['la scusa', 'özür; bahane', 'la SKU-sa', 'Ti chiedo scusa.', 'Senden özür dilerim.', ''],
  ['il fantasma', 'hayalet', 'il fan-TAZ-ma', 'Credi ai fantasmi?', 'Hayaletlere inanır mısın?', '👻'],
  ["l'ispettore (m.)", 'müfettiş', 'lis-pet-TO-re', "L'ispettore fa domande.", 'Müfettiş sorular soruyor.', ''],
  ['la teoria', 'teori', 'la te-o-Rİ-a', 'È solo una teoria.', 'Sadece bir teori.', ''],
  ['il camion', 'kamyon', 'il KA-myon', 'Il camion è grande.', 'Kamyon büyük.', '🚚'],
  ['il parco', 'park', 'il PAR-ko', 'Andiamo al parco.', 'Parka gidelim.', ''],
  ['il palazzo', 'saray; bina', 'il pa-LAT-tso', 'Il palazzo è antico.', 'Saray eski.', '🏛️'],
  ['privato', 'özel', 'pri-VA-to', 'È una festa privata.', 'Özel bir parti.', ''],
  ['purtroppo', 'maalesef', 'pur-TROP-po', 'Purtroppo non posso venire.', 'Maalesef gelemem.', ''],
  ["l'area (f.)", 'alan', 'LA-re-a', "È un'area per fumatori.", 'Burası sigara içme alanı.', ''],
  ["l'accusa (f.)", 'suçlama', 'lak-KU-sa', "L'accusa è grave.", 'Suçlama ağır.', ''],
  ['la stella', 'yıldız', 'la STEL-la', 'Guarda le stelle!', 'Yıldızlara bak!', '⭐'],
  ['direttamente', 'doğrudan', 'di-ret-ta-MEN-te', 'Vado direttamente a casa.', 'Doğrudan eve gidiyorum.', ''],
  ['cento', 'yüz (sayı)', 'ÇEN-to', 'Costa cento euro.', 'Yüz avro tutuyor.', ''],
  ['la fidanzata', 'nişanlı; kız arkadaş', 'la fi-dan-TSA-ta', 'La mia fidanzata è bellissima.', 'Kız arkadaşım çok güzel.', ''],
  ['seriamente', 'ciddi olarak', 'se-rya-MEN-te', 'Parliamo seriamente.', 'Ciddi konuşalım.', ''],
];
