// En sık 1000 İngilizce kelime (lemma), sıklık sırasıyla.
// Kaynak: FrequencyWords (Hermit Dave), OpenSubtitles 2018 — https://github.com/hermitdave/FrequencyWords — CC BY-SA 4.0.
// Bu liste o kaynaktan türetilmiştir (lemmatize edildi, Türkçe anlam/okunuş/örnek eklendi) ve CC BY-SA 4.0 lisansıyla paylaşılır.
// Biçim: [kelime, Türkçesi, okunuş, örnek cümle, örneğin Türkçesi, emoji]
window.FREQ = window.FREQ || {};
window.FREQ.en = [
  ['you', 'sen, siz', 'YU', 'You are my friend.', 'Sen benim arkadaşımsın.', ''],
  ['I', 'ben (me: beni, my: benim)', 'AY', 'I am happy today.', 'Bugün mutluyum.', ''],
  ['the', 'belirli tanımlık (-ı/-i)', 'DI', 'The dog is here.', 'Köpek burada.', ''],
  ['to', '-e/-a; -mek (to go: gitmek)', 'TU', 'I go to school.', 'Okula giderim.', ''],
  ['a', 'bir (a/an)', 'EY', 'I have a cat.', 'Bir kedim var.', ''],
  ['it', 'o (cansız/hayvan)', 'İT', 'It is very cold.', 'Hava çok soğuk.', ''],
  ['and', 've', 'END', 'Tea and coffee, please.', 'Çay ve kahve, lütfen.', ''],
  ['that', 'şu, o; -ki', 'DET', 'That is my car.', 'Şu benim arabam.', ''],
  ['not', 'değil, -me/-ma', 'NAT', 'I am not tired.', 'Yorgun değilim.', ''],
  ['of', '-in/-ın; -den', 'AV', 'A cup of tea, please.', 'Bir fincan çay, lütfen.', ''],
  ['be', 'olmak (am/is/are)', 'Bİİ', 'I want to be a doctor.', 'Doktor olmak istiyorum.', ''],
  ['in', 'içinde, -de/-da', 'İN', 'The cat is in the box.', 'Kedi kutunun içinde.', ''],
  ['what', 'ne, hangi', 'UAT', 'What is your name?', 'Adın ne?', ''],
  ['we', 'biz (us: bizi, our: bizim)', 'Uİİ', 'We live in Ankara.', "Ankara'da yaşıyoruz.", ''],
  ['this', 'bu (these: bunlar)', 'DİS', 'This is my house.', 'Bu benim evim.', ''],
  ['he', 'o (erkek)', 'Hİİ', 'He is my brother.', 'O benim erkek kardeşim.', ''],
  ['for', 'için', 'FOR', 'This gift is for you.', 'Bu hediye senin için.', ''],
  ['on', 'üstünde, -de/-da', 'AN', 'The book is on the table.', 'Kitap masanın üstünde.', ''],
  ['have', 'sahip olmak; -si var', 'HEV', 'I have two brothers.', 'İki erkek kardeşim var.', ''],
  ['do', 'yapmak', 'DU', 'What do you do?', 'Ne iş yaparsın?', ''],
  ['no', 'hayır; hiç', 'NOU', 'No, thank you.', 'Hayır, teşekkürler.', ''],
  ['know', 'bilmek, tanımak', 'NOU', 'I know his name.', 'Onun adını biliyorum.', ''],
  ['can', '-ebilmek', 'KEN', 'I can swim.', 'Yüzebilirim.', ''],
  ['with', 'ile, -le/-la', 'UİT', 'I live with my family.', 'Ailemle yaşıyorum.', ''],
  ['but', 'ama, fakat', 'BAT', 'I am tired, but happy.', 'Yorgunum ama mutluyum.', ''],
  ['all', 'hepsi, bütün', 'OL', 'All my friends are here.', 'Bütün arkadaşlarım burada.', ''],
  ['so', 'çok; bu yüzden', 'SOU', 'I am so happy!', 'Çok mutluyum!', ''],
  ['just', 'sadece; az önce', 'CAST', 'I just want water.', 'Sadece su istiyorum.', ''],
  ['there', 'orada; (there is: var)', 'DER', 'There is a cat here.', 'Burada bir kedi var.', ''],
  ['here', 'burada, buraya', 'HİİR', 'Come here, please.', 'Buraya gel, lütfen.', ''],
  ['they', 'onlar', 'DEY', 'They are my parents.', 'Onlar benim annem ve babam.', ''],
  ['like', 'sevmek; gibi', 'LAYK', 'I like pizza.', 'Pizzayı severim.', ''],
  ['will', '-ecek (gelecek zaman)', 'UİL', 'I will call you.', 'Seni arayacağım.', ''],
  ['get', 'almak; olmak; varmak', 'GET', 'I get up at seven.', 'Yedide kalkarım.', ''],
  ['she', 'o (kadın)', 'Şİİ', 'She is my sister.', 'O benim kız kardeşim.', ''],
  ['go', 'gitmek', 'GOU', 'I go to work by bus.', 'İşe otobüsle giderim.', ''],
  ['if', 'eğer, -se/-sa', 'İF', 'If it rains, I stay home.', 'Yağmur yağarsa evde kalırım.', ''],
  ['right', 'doğru; sağ', 'RAYT', 'You are right.', 'Haklısın.', ''],
  ['out', 'dışarı, dışarıda', 'AUT', "Let's go out tonight.", 'Bu akşam dışarı çıkalım.', ''],
  ['about', 'hakkında; yaklaşık', 'ı-BAUT', 'Tell me about your day.', 'Bana gününü anlat.', ''],
  ['up', 'yukarı', 'AP', 'Stand up, please.', 'Ayağa kalk, lütfen.', ''],
  ['at', '-de/-da (yer, saat)', 'ET', 'I am at home.', 'Evdeyim.', ''],
  ['now', 'şimdi', 'NAU', 'I am busy now.', 'Şimdi meşgulüm.', ''],
  ['one', 'bir', 'UAN', 'I have one sister.', 'Bir kız kardeşim var.', ''],
  ['come', 'gelmek', 'KAM', 'Come with me.', 'Benimle gel.', ''],
  ['well', 'iyi; şey...', 'UEL', 'I feel well today.', 'Bugün kendimi iyi hissediyorum.', ''],
  ['how', 'nasıl', 'HAU', 'How are you?', 'Nasılsın?', ''],
  ['want', 'istemek', 'UANT', 'I want a coffee.', 'Bir kahve istiyorum.', ''],
  ['think', 'düşünmek, sanmak', 'TİNK', 'I think you are right.', 'Bence haklısın.', ''],
  ['as', 'olarak; kadar; gibi', 'EZ', 'He works as a teacher.', 'Öğretmen olarak çalışıyor.', ''],
  ['see', 'görmek', 'Sİİ', 'I can see the sea.', 'Denizi görebiliyorum.', ''],
  ['good', 'iyi (better, best)', 'GUD', 'This is a good book.', 'Bu iyi bir kitap.', ''],
  ['who', 'kim', 'HUU', 'Who is that man?', 'Şu adam kim?', ''],
  ['why', 'neden, niçin', 'UAY', 'Why are you sad?', 'Neden üzgünsün?', ''],
  ['from', '-den/-dan', 'FRAM', 'I am from Turkey.', "Türkiye'denim.", ''],
  ['let', "izin vermek; let's: hadi", 'LET', 'Let me help you.', 'Sana yardım edeyim.', ''],
  ['yes', 'evet', 'YES', 'Yes, I understand.', 'Evet, anlıyorum.', ''],
  ['when', 'ne zaman; -dığında', 'UEN', 'When is your birthday?', 'Doğum günün ne zaman?', ''],
  ['time', 'zaman; saat; kez', 'TAYM', 'What time is it?', 'Saat kaç?', ''],
  ['okay', 'tamam', 'ou-KEY', 'Okay, see you later.', 'Tamam, sonra görüşürüz.', ''],
  ['back', 'geri; sırt', 'BEK', 'I will be back soon.', 'Birazdan döneceğim.', ''],
  ['look', 'bakmak; görünmek', 'LUK', 'Look at this photo.', 'Şu fotoğrafa bak.', ''],
  ['would', '-erdi; kibar istek', 'UUD', 'I would like some tea.', 'Biraz çay rica ederim.', ''],
  ['where', 'nerede, nereye', 'UER', 'Where is the station?', 'İstasyon nerede?', ''],
  ['take', 'almak, götürmek', 'TEYK', 'Take your umbrella.', 'Şemsiyeni al.', ''],
  ['then', 'sonra; o zaman', 'DEN', 'First eat, then play.', 'Önce ye, sonra oyna.', ''],
  ['or', 'veya, ya da', 'OR', 'Tea or coffee?', 'Çay mı, kahve mi?', ''],
  ['tell', 'söylemek, anlatmak', 'TEL', 'Tell me the truth.', 'Bana doğruyu söyle.', ''],
  ['really', 'gerçekten', 'Rİİ-li', 'I really like this song.', 'Bu şarkıyı gerçekten seviyorum.', ''],
  ['man', 'adam, erkek', 'MEN', 'That man is my teacher.', 'Şu adam benim öğretmenim.', '👨'],
  ['some', 'biraz, bazı', 'SAM', 'I want some water.', 'Biraz su istiyorum.', ''],
  ['say', 'söylemek, demek', 'SEY', 'What did you say?', 'Ne dedin?', ''],
  ['could', '-ebilirdi; -ebilir misin', 'KUD', 'Could you help me?', 'Bana yardım edebilir misiniz?', ''],
  ['by', 'ile; tarafından; yanında', 'BAY', 'I go to work by car.', 'İşe arabayla giderim.', ''],
  ['need', 'ihtiyacı olmak', 'NİİD', 'I need your help.', 'Yardımına ihtiyacım var.', ''],
  ['something', 'bir şey', 'SAM-ting', 'I want something to eat.', 'Yiyecek bir şey istiyorum.', ''],
  ['too', 'de/da; fazla', 'TUU', 'I love you too.', 'Ben de seni seviyorum.', ''],
  ['much', 'çok (more: daha)', 'MAÇ', 'Thank you very much.', 'Çok teşekkür ederim.', ''],
  ['way', 'yol; yöntem', 'UEY', 'This is the way home.', 'Eve giden yol bu.', ''],
  ['down', 'aşağı', 'DAUN', 'Please sit down.', 'Lütfen oturun.', ''],
  ['make', 'yapmak, hazırlamak', 'MEYK', 'I make breakfast every day.', 'Her gün kahvaltı hazırlarım.', ''],
  ['very', 'çok', 'VE-ri', 'It is very hot today.', 'Bugün hava çok sıcak.', ''],
  ['never', 'asla, hiç', 'NE-vır', 'I never drink coffee.', 'Hiç kahve içmem.', ''],
  ['only', 'sadece, yalnız', 'OUN-li', 'I have only one brother.', 'Sadece bir erkek kardeşim var.', ''],
  ['person', 'kişi (people: insanlar)', 'PÖR-sın', 'She is a nice person.', 'O iyi bir insan.', ''],
  ['over', 'üzerinde; bitmiş', 'OU-vır', 'The game is over.', 'Oyun bitti.', ''],
  ['because', 'çünkü', 'bi-KAZ', 'I stay home because I am sick.', 'Hasta olduğum için evde kalıyorum.', ''],
  ['little', 'küçük; biraz', 'Lİ-tıl', 'I have a little dog.', 'Küçük bir köpeğim var.', ''],
  ['please', 'lütfen', 'PLİİZ', 'Sit down, please.', 'Oturun, lütfen.', ''],
  ['love', 'sevmek; aşk', 'LAV', 'I love my family.', 'Ailemi seviyorum.', ''],
  ['should', '-meli, -malı', 'ŞUD', 'You should sleep early.', 'Erken uyumalısın.', ''],
  ['mean', 'anlamına gelmek; kastetmek', 'MİİN', 'What does this word mean?', 'Bu kelime ne demek?', ''],
  ['sorry', 'üzgün; özür dilerim', 'SA-ri', 'Sorry, I am late.', 'Özür dilerim, geç kaldım.', ''],
  ['give', 'vermek', 'GİV', 'Give me the book, please.', 'Kitabı bana ver, lütfen.', ''],
  ['off', 'kapalı; -den ayrı', 'OF', 'Turn off the light.', 'Işığı kapat.', ''],
  ['thank', 'teşekkür etmek', 'TENK', 'Thank you for the gift.', 'Hediye için teşekkürler.', ''],
  ['any', 'hiç, herhangi', 'E-ni', 'Do you have any questions?', 'Hiç sorunuz var mı?', ''],
  ['two', 'iki', 'TUU', 'I have two cats.', 'İki kedim var.', ''],
  ['even', 'bile', 'İİ-vın', 'He works even on Sunday.', 'Pazar günü bile çalışıyor.', ''],
  ['sure', 'emin; tabii', 'ŞUR', 'Are you sure?', 'Emin misin?', ''],
  ['thing', 'şey', 'TİNG', 'What is that thing?', 'O şey ne?', ''],
  ['help', 'yardım etmek; yardım', 'HELP', 'Please help me with this bag.', 'Lütfen bu çantayla bana yardım et.', ''],
  ['first', 'ilk; önce', 'FÖRST', 'This is my first day.', 'Bu benim ilk günüm.', ''],
  ['into', 'içine', 'İN-tu', 'Put it into the bag.', 'Onu çantanın içine koy.', ''],
  ['anything', 'bir şey; hiçbir şey', 'E-ni-ting', 'Do you need anything?', 'Bir şeye ihtiyacın var mı?', ''],
  ['still', 'hâlâ', 'STİL', 'I still live here.', 'Hâlâ burada yaşıyorum.', ''],
  ['find', 'bulmak', 'FAYND', "I can't find my keys.", 'Anahtarlarımı bulamıyorum.', ''],
  ['life', 'hayat', 'LAYF', 'Life is beautiful.', 'Hayat güzel.', ''],
  ['nothing', 'hiçbir şey', 'NA-ting', 'I have nothing to say.', 'Söyleyecek bir şeyim yok.', ''],
  ['sir', 'efendim, beyefendi', 'SÖR', 'Yes, sir.', 'Evet, efendim.', ''],
  ['day', 'gün', 'DEY', 'Have a nice day!', 'İyi günler!', ''],
  ['God', 'Tanrı', 'GAD', 'Oh my God!', 'Aman Tanrım!', ''],
  ['work', 'çalışmak; iş', 'UÖRK', 'I work in an office.', 'Bir ofiste çalışıyorum.', ''],
  ['again', 'tekrar, yine', 'ı-GEN', 'Please say it again.', 'Lütfen tekrar söyle.', ''],
  ['maybe', 'belki', 'MEY-bi', 'Maybe tomorrow.', 'Belki yarın.', ''],
  ['must', '-meli, zorunda olmak', 'MAST', 'I must go now.', 'Şimdi gitmeliyim.', ''],
  ['before', 'önce', 'bi-FOR', 'Wash your hands before dinner.', 'Akşam yemeğinden önce ellerini yıka.', ''],
  ['other', 'diğer, başka', 'A-dır', 'Where is the other shoe?', 'Öbür ayakkabı nerede?', ''],
  ['wait', 'beklemek', 'UEYT', 'Wait for me, please.', 'Beni bekle, lütfen.', ''],
  ['stop', 'durmak, durdurmak', 'STAP', 'Stop the car, please.', 'Arabayı durdur, lütfen.', ''],
  ['call', 'aramak; çağırmak', 'KOL', 'I will call you tonight.', 'Bu akşam seni ararım.', ''],
  ['after', 'sonra', 'EF-tır', 'I sleep after lunch.', 'Öğle yemeğinden sonra uyurum.', ''],
  ['talk', 'konuşmak', 'TOK', 'Can we talk now?', 'Şimdi konuşabilir miyiz?', ''],
  ['away', 'uzakta, uzağa', 'ı-UEY', 'My school is far away.', 'Okulum çok uzakta.', ''],
  ['than', '-den daha', 'DEN', 'He is taller than me.', 'O benden daha uzun.', ''],
  ['home', 'ev, evde, eve', 'HOUM', 'I am going home now.', 'Şimdi eve gidiyorum.', '🏠'],
  ['night', 'gece', 'NAYT', 'Good night, Mom.', 'İyi geceler, anne.', '🌙'],
  ['put', 'koymak', 'PUT', 'Put the milk in the fridge.', 'Sütü buzdolabına koy.', ''],
  ['great', 'harika; büyük', 'GREYT', 'That is a great idea!', 'Bu harika bir fikir!', ''],
  ['last', 'son; geçen', 'LEST', 'I saw him last week.', 'Onu geçen hafta gördüm.', ''],
  ['everything', 'her şey', 'EV-ri-ting', 'Everything is ready.', 'Her şey hazır.', ''],
  ['new', 'yeni', 'NUU', 'I have a new phone.', 'Yeni bir telefonum var.', ''],
  ['always', 'her zaman, hep', 'OL-ueyz', 'I always drink tea in the morning.', 'Sabahları hep çay içerim.', ''],
  ['keep', 'tutmak; saklamak; devam etmek', 'KİİP', 'Keep the change.', 'Para üstü kalsın.', ''],
  ['long', 'uzun; uzun süre', 'LONG', 'She has long hair.', 'Onun uzun saçları var.', ''],
  ['year', 'yıl', 'YİİR', 'I am twenty years old.', 'Yirmi yaşındayım.', ''],
  ['leave', 'ayrılmak; bırakmak', 'LİİV', 'I leave home at eight.', 'Evden sekizde çıkarım.', ''],
  ['money', 'para', 'MA-ni', "I don't have much money.", 'Fazla param yok.', '💵'],
  ['around', 'etrafında; civarında', 'ı-RAUND', 'We walk around the park.', 'Parkın etrafında yürüyoruz.', ''],
  ['name', 'isim, ad', 'NEYM', 'My name is Ahmet.', 'Benim adım Ahmet.', ''],
  ['place', 'yer', 'PLEYS', 'This is a nice place.', 'Burası güzel bir yer.', ''],
  ['ever', 'hiç (soru); hep', 'E-vır', 'Have you ever been to London?', "Hiç Londra'ya gittin mi?", ''],
  ['feel', 'hissetmek', 'FİİL', 'I feel very tired.', 'Kendimi çok yorgun hissediyorum.', ''],
  ['guy', 'adam, herif', 'GAY', 'He is a nice guy.', 'O iyi bir adam.', ''],
  ['father', 'baba (dad)', 'FAA-dır', 'My father is a doctor.', 'Babam doktor.', '👨'],
  ['old', 'yaşlı; eski', 'OULD', 'This is an old house.', 'Bu eski bir ev.', ''],
  ['which', 'hangi; ki o', 'UİÇ', 'Which bag is yours?', 'Hangi çanta senin?', ''],
  ['big', 'büyük', 'BİG', 'They have a big garden.', 'Büyük bir bahçeleri var.', ''],
  ['lot', 'çok (a lot of)', 'LAT', 'I have a lot of work.', 'Çok işim var.', ''],
  ['hello', 'merhaba', 'he-LOU', 'Hello, how are you?', 'Merhaba, nasılsın?', ''],
  ['nice', 'güzel, hoş, iyi', 'NAYS', 'Nice to meet you.', 'Tanıştığıma memnun oldum.', ''],
  ['believe', 'inanmak', 'bi-LİİV', 'I believe you.', 'Sana inanıyorum.', ''],
  ['girl', 'kız', 'GÖRL', 'The girl is reading a book.', 'Kız kitap okuyor.', '👧'],
  ['someone', 'birisi', 'SAM-uan', 'Someone is at the door.', 'Kapıda birisi var.', ''],
  ['fine', 'iyi; güzel; ceza', 'FAYN', 'I am fine, thank you.', 'İyiyim, teşekkürler.', ''],
  ['kind', 'tür; nazik', 'KAYND', 'What kind of music do you like?', 'Ne tür müzik seversin?', ''],
  ['house', 'ev', 'HAUS', 'My house is near the sea.', 'Evim denize yakın.', '🏠'],
  ['every', 'her', 'EV-ri', 'I run every morning.', 'Her sabah koşarım.', ''],
  ['through', 'içinden, boyunca', 'TRUU', 'We drove through the city.', 'Şehrin içinden arabayla geçtik.', ''],
  ['course', 'kurs; of course: tabii ki', 'KORS', 'Of course I can help.', 'Tabii ki yardım edebilirim.', ''],
  ['stay', 'kalmak', 'STEY', 'I stay at a hotel.', 'Bir otelde kalıyorum.', ''],
  ['enough', 'yeterli, yeterince', 'i-NAF', 'I have enough time.', 'Yeterince vaktim var.', ''],
  ['happen', 'olmak, meydana gelmek', 'HE-pın', 'What happened?', 'Ne oldu?', ''],
  ['may', '-ebilir; izin (may I)', 'MEY', 'May I come in?', 'Girebilir miyim?', ''],
  ['mother', 'anne (mom)', 'MA-dır', 'My mother is a teacher.', 'Annem öğretmen.', '👩'],
  ['wrong', 'yanlış', 'RONG', 'Sorry, wrong number.', 'Özür dilerim, yanlış numara.', ''],
  ['world', 'dünya', 'UÖRLD', 'I want to see the world.', 'Dünyayı görmek istiyorum.', '🌍'],
  ['bad', 'kötü (worse, worst)', 'BED', 'The weather is bad today.', 'Bugün hava kötü.', ''],
  ['might', '-ebilir (belki)', 'MAYT', 'It might rain today.', 'Bugün yağmur yağabilir.', ''],
  ['three', 'üç', 'TRİİ', 'I have three children.', 'Üç çocuğum var.', ''],
  ['today', 'bugün', 'tı-DEY', 'Today is Monday.', 'Bugün pazartesi.', ''],
  ['listen', 'dinlemek', 'Lİ-sın', 'Listen to me, please.', 'Lütfen beni dinle.', ''],
  ['another', 'başka bir; bir tane daha', 'ı-NA-dır', 'Can I have another tea?', 'Bir çay daha alabilir miyim?', ''],
  ['understand', 'anlamak', 'an-dır-STEND', "I don't understand.", 'Anlamıyorum.', ''],
  ['hear', 'duymak', 'HİİR', 'Can you hear me?', 'Beni duyabiliyor musun?', ''],
  ['remember', 'hatırlamak', 'ri-MEM-bır', 'I remember your name.', 'Adını hatırlıyorum.', ''],
  ['ask', 'sormak; istemek', 'ESK', 'Can I ask a question?', 'Bir soru sorabilir miyim?', ''],
  ['own', 'kendi; sahip olmak', 'OUN', 'I have my own room.', 'Kendi odam var.', ''],
  ['same', 'aynı', 'SEYM', 'We are the same age.', 'Aynı yaştayız.', ''],
  ['show', 'göstermek; gösteri', 'ŞOU', 'Show me your photos.', 'Bana fotoğraflarını göster.', ''],
  ['else', 'başka', 'ELS', 'Anything else?', 'Başka bir şey?', ''],
  ['kill', 'öldürmek', 'KİL', 'Smoking can kill you.', 'Sigara seni öldürebilir.', ''],
  ['next', 'sonraki, gelecek', 'NEKST', 'See you next week.', 'Gelecek hafta görüşürüz.', ''],
  ['care', 'önemsemek; bakım', 'KER', 'Take care!', 'Kendine iyi bak!', ''],
  ['car', 'araba', 'KAAR', 'My car is red.', 'Arabam kırmızı.', '🚗'],
  ['son', 'oğul', 'SAN', 'Their son is five years old.', 'Oğulları beş yaşında.', '👦'],
  ['try', 'denemek, çalışmak', 'TRAY', 'Try this cake.', 'Bu keki dene.', ''],
  ['woman', 'kadın (women)', 'UU-mın', 'That woman is my aunt.', 'Şu kadın benim teyzem.', '👩'],
  ['hi', 'selam, merhaba', 'HAY', 'Hi, I am Ahmet.', 'Selam, ben Ahmet.', ''],
  ['dead', 'ölü', 'DED', 'The plant is dead.', 'Bitki ölmüş.', ''],
  ['many', 'çok (sayılabilen)', 'ME-ni', 'I have many friends.', 'Çok arkadaşım var.', ''],
  ['mind', 'zihin, akıl; sakıncası olmak', 'MAYND', 'Do you mind if I sit here?', 'Buraya otursam sakıncası var mı?', ''],
  ['friend', 'arkadaş', 'FREND', 'He is my best friend.', 'O benim en iyi arkadaşım.', ''],
  ['morning', 'sabah', 'MOR-ning', 'Good morning!', 'Günaydın!', ''],
  ['boy', 'oğlan, erkek çocuk', 'BOY', 'The boy is playing football.', 'Oğlan futbol oynuyor.', '👦'],
  ['together', 'birlikte', 'tı-GE-dır', "Let's eat together.", 'Hadi birlikte yiyelim.', ''],
  ['job', 'iş, meslek', 'CAB', 'I have a new job.', 'Yeni bir işim var.', ''],
  ['family', 'aile', 'FE-mı-li', 'I love my family.', 'Ailemi seviyorum.', '👪'],
  ['real', 'gerçek', 'Rİİ-ıl', 'Is this a real diamond?', 'Bu gerçek bir elmas mı?', ''],
  ['without', '-sız, olmadan', 'ui-DAUT', 'I drink coffee without sugar.', 'Kahveyi şekersiz içerim.', ''],
  ['baby', 'bebek', 'BEY-bi', 'The baby is sleeping.', 'Bebek uyuyor.', '👶'],
  ['room', 'oda', 'RUUM', 'My room is small.', 'Odam küçük.', ''],
  ['already', 'zaten, çoktan', 'ol-RE-di', 'I already ate.', 'Ben zaten yedim.', ''],
  ['move', 'hareket etmek; taşınmak', 'MUUV', 'We moved to a new house.', 'Yeni bir eve taşındık.', ''],
  ['live', 'yaşamak, oturmak', 'LİV', 'I live in Istanbul.', "İstanbul'da yaşıyorum.", ''],
  ['miss', 'özlemek; kaçırmak', 'MİS', 'I miss you.', 'Seni özledim.', ''],
  ['actually', 'aslında', 'EK-çu-ı-li', 'Actually, I like it.', 'Aslında onu sevdim.', ''],
  ['both', 'ikisi de', 'BOUT', 'Both my sisters are doctors.', 'İki kız kardeşim de doktor.', ''],
  ['once', 'bir kez; bir zamanlar', 'UANS', 'I go to the gym once a week.', 'Haftada bir kez spor salonuna giderim.', ''],
  ['ready', 'hazır', 'RE-di', 'Dinner is ready.', 'Akşam yemeği hazır.', ''],
  ['head', 'baş, kafa', 'HED', 'My head hurts.', 'Başım ağrıyor.', ''],
  ['use', 'kullanmak', 'YUUZ', 'Can I use your phone?', 'Telefonunu kullanabilir miyim?', ''],
  ['idea', 'fikir', 'ay-Dİİ-ı', 'That is a good idea.', 'Bu iyi bir fikir.', ''],
  ['hold', 'tutmak', 'HOULD', 'Hold my hand.', 'Elimi tut.', ''],
  ['happy', 'mutlu', 'HE-pi', 'I am very happy today.', 'Bugün çok mutluyum.', ''],
  ['door', 'kapı', 'DOR', 'Please close the door.', 'Lütfen kapıyı kapat.', '🚪'],
  ['such', 'öyle, böyle; çok', 'SAÇ', 'It was such a nice day.', 'Çok güzel bir gündü.', ''],
  ['brother', 'erkek kardeş', 'BRA-dır', 'My brother lives in Izmir.', "Erkek kardeşim İzmir'de yaşıyor.", ''],
  ['also', 'de/da, ayrıca', 'OL-sou', 'I also speak English.', 'Ben de İngilizce konuşuyorum.', ''],
  ['pretty', 'güzel, sevimli; oldukça', 'PRİ-ti', 'She has a pretty dress.', 'Onun güzel bir elbisesi var.', ''],
  ['bit', 'biraz (a bit)', 'BİT', 'I am a bit tired.', 'Biraz yorgunum.', ''],
  ['yet', 'henüz; daha', 'YET', "I haven't eaten yet.", 'Henüz yemedim.', ''],
  ['whole', 'bütün, tüm', 'HOUL', 'I ate the whole pizza.', 'Bütün pizzayı yedim.', ''],
  ['start', 'başlamak', 'STAART', 'The film starts at nine.', 'Film dokuzda başlıyor.', ''],
  ['while', '-iken; bir süre', 'UAYL', 'I listen to music while I cook.', 'Yemek yaparken müzik dinlerim.', ''],
  ['since', '-den beri', 'SİNS', 'I have lived here since 2010.', "2010'dan beri burada yaşıyorum.", ''],
  ['wife', 'eş, karı', 'UAYF', 'His wife is very kind.', 'Onun eşi çok nazik.', ''],
  ['guess', 'tahmin etmek', 'GES', 'Guess my age.', 'Yaşımı tahmin et.', ''],
  ['tomorrow', 'yarın', 'tı-MA-rou', 'See you tomorrow.', 'Yarın görüşürüz.', ''],
  ['matter', 'önemli olmak; mesele', 'ME-tır', "It doesn't matter.", 'Önemli değil.', ''],
  ['meet', 'tanışmak, buluşmak', 'MİİT', "Let's meet at six.", 'Altıda buluşalım.', ''],
  ['bring', 'getirmek', 'BRİNG', 'Bring your friends.', 'Arkadaşlarını getir.', ''],
  ['tonight', 'bu gece, bu akşam', 'tı-NAYT', 'What are you doing tonight?', 'Bu akşam ne yapıyorsun?', ''],
  ['everyone', 'herkes', 'EV-ri-uan', 'Hello, everyone!', 'Herkese merhaba!', ''],
  ['run', 'koşmak', 'RAN', 'I run in the park.', 'Parkta koşarım.', ''],
  ['hard', 'zor; sert; çok (çalışmak)', 'HAARD', 'This test is hard.', 'Bu sınav zor.', ''],
  ['alone', 'yalnız', 'ı-LOUN', 'I live alone.', 'Yalnız yaşıyorum.', ''],
  ['school', 'okul', 'SKUUL', 'My son goes to school.', 'Oğlum okula gidiyor.', '🏫'],
  ['end', 'son; bitmek', 'END', 'The end of the film is sad.', 'Filmin sonu üzücü.', ''],
  ['phone', 'telefon', 'FOUN', 'Where is my phone?', 'Telefonum nerede?', '📱'],
  ['play', 'oynamak; çalmak', 'PLEY', 'The children play in the garden.', 'Çocuklar bahçede oynuyor.', ''],
  ['problem', 'sorun', 'PRA-blım', 'No problem!', 'Sorun değil!', ''],
  ['few', 'az; a few: birkaç', 'FYUU', 'I have a few questions.', 'Birkaç sorum var.', ''],
  ['ago', 'önce (zaman)', 'ı-GOU', 'I came here two years ago.', 'Buraya iki yıl önce geldim.', ''],
  ['open', 'açmak; açık', 'OU-pın', 'Open the window, please.', 'Pencereyi aç, lütfen.', ''],
  ['anyone', 'kimse; herhangi biri', 'E-ni-uan', 'Is anyone home?', 'Evde kimse var mı?', ''],
  ['hope', 'ummak; umut', 'HOUP', 'I hope you feel better.', 'Umarım daha iyi hissedersin.', ''],
  ['face', 'yüz', 'FEYS', 'Wash your face.', 'Yüzünü yıka.', ''],
  ['until', '-e kadar', 'ın-TİL', 'I work until five.', 'Beşe kadar çalışırım.', ''],
  ['lose', 'kaybetmek', 'LUUZ', 'I often lose my keys.', 'Anahtarlarımı sık sık kaybederim.', ''],
  ['police', 'polis', 'pı-LİİS', 'Call the police!', 'Polisi ara!', '👮'],
  ['excuse', 'affetmek; bahane', 'ik-SKYUUZ', 'Excuse me, where is the bank?', 'Affedersiniz, banka nerede?', ''],
  ['turn', 'dönmek; çevirmek; sıra', 'TÖRN', 'Turn left here.', 'Burada sola dön.', ''],
  ['business', 'iş, ticaret', 'BİZ-nıs', 'My father has a small business.', 'Babamın küçük bir işletmesi var.', ''],
  ['case', 'durum; dava; kutu', 'KEYS', 'In that case, I will stay.', 'O durumda kalacağım.', ''],
  ['true', 'doğru, gerçek', 'TRUU', 'Is it true?', 'Bu doğru mu?', ''],
  ['die', 'ölmek', 'DAY', 'My plants died.', 'Bitkilerim öldü.', ''],
  ['heart', 'kalp', 'HAART', 'My heart is beating fast.', 'Kalbim hızlı atıyor.', '❤️'],
  ['soon', 'yakında, birazdan', 'SUUN', 'See you soon.', 'Yakında görüşürüz.', ''],
  ['each', 'her bir', 'İİÇ', 'Each room has a bed.', 'Her odada bir yatak var.', ''],
  ['worry', 'endişelenmek', 'UÖ-ri', "Don't worry.", 'Endişelenme.', ''],
  ['late', 'geç', 'LEYT', 'Sorry, I am late.', 'Üzgünüm, geç kaldım.', ''],
  ['watch', 'izlemek; kol saati', 'UAÇ', 'I watch TV in the evening.', 'Akşamları televizyon izlerim.', '⌚'],
  ['music', 'müzik', 'MYUU-zik', 'I love music.', 'Müziği severim.', '🎵'],
  ['hand', 'el', 'HEND', 'Wash your hands.', 'Ellerini yıka.', '✋'],
  ['probably', 'muhtemelen', 'PRA-bı-bli', 'He is probably at home.', 'Muhtemelen evde.', ''],
  ['beautiful', 'güzel', 'BYUU-tı-fıl', 'What a beautiful day!', 'Ne güzel bir gün!', ''],
  ['doctor', 'doktor', 'DAK-tır', 'I need a doctor.', 'Bir doktora ihtiyacım var.', '👨‍⚕️'],
  ['sit', 'oturmak', 'SİT', 'Sit here, please.', 'Buraya otur, lütfen.', ''],
  ['eat', 'yemek (yemek yemek)', 'İİT', 'I eat fruit every day.', 'Her gün meyve yerim.', ''],
  ['young', 'genç', 'YANG', 'My mother looks young.', 'Annem genç görünüyor.', ''],
  ['second', 'ikinci; saniye', 'SE-kınd', 'This is my second visit.', 'Bu benim ikinci ziyaretim.', ''],
  ['water', 'su', 'UO-tır', 'Can I have some water?', 'Biraz su alabilir miyim?', '💧'],
  ['part', 'parça, bölüm', 'PAART', 'This is the best part.', 'Bu en iyi bölüm.', ''],
  ['kid', 'çocuk; şaka yapmak', 'KİD', 'The kids are at school.', 'Çocuklar okulda.', '🧒'],
  ['stuff', 'şeyler, eşya', 'STAF', 'Where is my stuff?', 'Eşyalarım nerede?', ''],
  ['exactly', 'tam olarak, aynen', 'ig-ZEKT-li', 'That is exactly right.', 'Aynen öyle, çok doğru.', ''],
  ['under', 'altında', 'AN-dır', 'The cat is under the bed.', 'Kedi yatağın altında.', ''],
  ['death', 'ölüm', 'DET', 'His death was a shock.', 'Onun ölümü bir şoktu.', ''],
  ['minute', 'dakika', 'Mİ-nit', 'Wait a minute, please.', 'Bir dakika bekle, lütfen.', ''],
  ['pay', 'ödemek', 'PEY', 'Can I pay by card?', 'Kartla ödeyebilir miyim?', ''],
  ['crazy', 'deli, çılgın', 'KREY-zi', 'This is crazy!', 'Bu çılgınca!', ''],
  ['forget', 'unutmak', 'fır-GET', "Don't forget your keys.", 'Anahtarlarını unutma.', ''],
  ['everybody', 'herkes', 'EV-ri-ba-di', 'Everybody is here.', 'Herkes burada.', ''],
  ['change', 'değiştirmek; değişim', 'ÇEYNC', 'I want to change my job.', 'İşimi değiştirmek istiyorum.', ''],
  ['five', 'beş', 'FAYV', 'I have five apples.', 'Beş elmam var.', ''],
  ['drink', 'içmek; içecek', 'DRİNK', 'I drink a lot of water.', 'Çok su içerim.', ''],
  ['far', 'uzak', 'FAAR', 'Is the station far?', 'İstasyon uzak mı?', ''],
  ['whatever', 'her neyse; her ne', 'uat-E-vır', 'Eat whatever you want.', 'Ne istersen ye.', ''],
  ['eye', 'göz', 'AY', 'She has blue eyes.', 'Onun mavi gözleri var.', '👁️'],
  ['shut', 'kapatmak', 'ŞAT', 'Shut the door, please.', 'Kapıyı kapat, lütfen.', ''],
  ['hit', 'vurmak, çarpmak', 'HİT', "Don't hit your brother.", 'Kardeşine vurma.', ''],
  ['easy', 'kolay', 'İİ-zi', 'This game is easy.', 'Bu oyun kolay.', ''],
  ['check', 'kontrol etmek; hesap', 'ÇEK', 'Check your email.', 'E-postanı kontrol et.', ''],
  ['deal', 'anlaşma; ilgilenmek', 'DİİL', "OK, it's a deal.", 'Tamam, anlaştık.', ''],
  ['different', 'farklı', 'Dİ-fı-rınt', 'We are very different.', 'Biz çok farklıyız.', ''],
  ['point', 'nokta; amaç; işaret etmek', 'POYNT', 'What is the point?', 'Ne anlamı var?', ''],
  ['inside', 'içeride, içine', 'in-SAYD', "Let's go inside.", 'Hadi içeri girelim.', ''],
  ['somebody', 'birisi', 'SAM-ba-di', 'Somebody called you.', 'Birisi seni aradı.', ''],
  ['body', 'vücut, beden', 'BA-di', 'Sport is good for your body.', 'Spor vücuduna iyi gelir.', ''],
  ['afraid', 'korkmuş; maalesef', 'ı-FREYD', 'I am afraid of dogs.', 'Köpeklerden korkarım.', ''],
  ['sleep', 'uyumak; uyku', 'SLİİP', 'I sleep eight hours.', 'Sekiz saat uyurum.', ''],
  ['chance', 'şans, fırsat', 'ÇENS', 'Give me a chance.', 'Bana bir şans ver.', ''],
  ['dear', 'sevgili, canım', 'DİİR', 'Dear Anna, thank you.', 'Sevgili Anna, teşekkürler.', ''],
  ['quite', 'oldukça', 'KUAYT', 'It is quite cold today.', 'Bugün hava oldukça soğuk.', ''],
  ['four', 'dört', 'FOR', 'We are four people.', 'Dört kişiyiz.', ''],
  ['anyway', 'neyse; yine de', 'E-ni-uey', 'Anyway, see you later.', 'Neyse, sonra görüşürüz.', ''],
  ['close', 'kapatmak; yakın', 'KLOUZ', 'Close your eyes.', 'Gözlerini kapat.', ''],
  ['party', 'parti, eğlence', 'PAAR-ti', 'Come to my party.', 'Partime gel.', '🎉'],
  ['fun', 'eğlence; eğlenceli', 'FAN', 'The trip was fun.', 'Gezi eğlenceliydi.', ''],
  ['against', 'karşı', 'ı-GENST', 'I am against this idea.', 'Bu fikre karşıyım.', ''],
  ['word', 'kelime, söz', 'UÖRD', 'I learn ten words a day.', 'Günde on kelime öğreniyorum.', ''],
  ['important', 'önemli', 'im-POR-tınt', 'Family is very important.', 'Aile çok önemli.', ''],
  ['set', 'koymak, kurmak; takım', 'SET', 'Set the table, please.', 'Sofrayı kur, lütfen.', ''],
  ['shall', '-elim mi; -ecek', 'ŞEL', 'Shall we go?', 'Gidelim mi?', ''],
  ['story', 'hikâye', 'STO-ri', 'Tell me a story.', 'Bana bir hikâye anlat.', ''],
  ['number', 'sayı, numara', 'NAM-bır', 'What is your phone number?', 'Telefon numaran ne?', ''],
  ['daughter', 'kız evlat', 'DO-tır', 'My daughter is ten.', 'Kızım on yaşında.', '👧'],
  ['hurt', 'acıtmak; incitmek', 'HÖRT', 'My leg hurts.', 'Bacağım acıyor.', ''],
  ['wish', 'dilemek; keşke', 'UİŞ', 'I wish you a happy birthday.', 'Sana mutlu yıllar dilerim.', ''],
  ['moment', 'an', 'MOU-mınt', 'Just a moment, please.', 'Bir dakika, lütfen.', ''],
  ['fight', 'kavga etmek; savaşmak', 'FAYT', "Don't fight, boys!", 'Kavga etmeyin çocuklar!', ''],
  ['week', 'hafta', 'UİİK', 'I work five days a week.', 'Haftada beş gün çalışırım.', ''],
  ['husband', 'koca, eş', 'HAZ-bınd', 'Her husband is a cook.', 'Kocası aşçı.', ''],
  ['rest', 'dinlenmek; geri kalan', 'REST', 'You need some rest.', 'Biraz dinlenmen lazım.', ''],
  ['marry', 'evlenmek', 'ME-ri', 'Will you marry me?', 'Benimle evlenir misin?', ''],
  ['fire', 'ateş, yangın; kovmak', 'FAYR', "Don't touch the fire.", 'Ateşe dokunma.', '🔥'],
  ['game', 'oyun; maç', 'GEYM', "Let's play a game.", 'Hadi bir oyun oynayalım.', '🎮'],
  ['nobody', 'hiç kimse', 'NOU-ba-di', 'Nobody is at home.', 'Evde kimse yok.', ''],
  ['child', 'çocuk (children)', 'ÇAYLD', 'The child is very smart.', 'Çocuk çok akıllı.', '🧒'],
  ['side', 'taraf, yan', 'SAYD', 'Sit by my side.', 'Yanıma otur.', ''],
  ['stand', 'ayakta durmak', 'STEND', 'Please stand here.', 'Lütfen burada dur.', ''],
  ['read', 'okumak', 'RİİD', 'I read every night.', 'Her gece okurum.', ''],
  ['though', 'gerçi; yine de', 'DOU', "It's cold. I like it, though.", 'Hava soğuk. Yine de seviyorum.', ''],
  ['cut', 'kesmek', 'KAT', 'Cut the bread, please.', 'Ekmeği kes, lütfen.', ''],
  ['sister', 'kız kardeş', 'SİS-tır', 'My sister is a nurse.', 'Kız kardeşim hemşire.', ''],
  ['suppose', 'sanmak, varsaymak', 'sı-POUZ', 'I suppose you are right.', 'Sanırım haklısın.', ''],
  ['between', 'arasında', 'bi-TUİİN', 'The bank is between two shops.', 'Banka iki dükkânın arasında.', ''],
  ['hour', 'saat (süre)', 'AUR', 'I waited for an hour.', 'Bir saat bekledim.', ''],
  ['speak', 'konuşmak', 'SPİİK', 'Do you speak English?', 'İngilizce konuşuyor musun?', ''],
  ['behind', 'arkasında', 'bi-HAYND', 'The car is behind the house.', 'Araba evin arkasında.', ''],
  ['almost', 'neredeyse', 'OL-moust', 'I am almost ready.', 'Neredeyse hazırım.', ''],
  ['truth', 'gerçek, doğru', 'TRUUT', 'Tell me the truth.', 'Bana gerçeği söyle.', ''],
  ['blood', 'kan', 'BLAD', 'I gave blood today.', 'Bugün kan verdim.', '🩸'],
  ['able', '-ebilen, yapabilir', 'EY-bıl', 'I am able to swim.', 'Yüzebiliyorum.', ''],
  ['lady', 'hanımefendi, bayan', 'LEY-di', 'That lady is my teacher.', 'Şu hanım benim öğretmenim.', ''],
  ['anymore', 'artık (olumsuz)', 'e-ni-MOR', "I don't smoke anymore.", 'Artık sigara içmiyorum.', ''],
  ['shoot', 'ateş etmek; çekim yapmak', 'ŞUUT', "Don't shoot!", 'Ateş etme!', ''],
  ['reason', 'sebep, neden', 'Rİİ-zın', 'What is the reason?', 'Sebebi ne?', ''],
  ['trouble', 'dert, sorun, bela', 'TRA-bıl', 'Are you in trouble?', 'Başın dertte mi?', ''],
  ['break', 'kırmak; mola', 'BREYK', "Let's take a break.", 'Hadi mola verelim.', ''],
  ['war', 'savaş', 'UOR', 'War is terrible.', 'Savaş korkunçtur.', ''],
  ['city', 'şehir', 'Sİ-ti', 'Istanbul is a big city.', 'İstanbul büyük bir şehir.', '🏙️'],
  ['walk', 'yürümek', 'UOK', 'I walk to work.', 'İşe yürüyerek giderim.', ''],
  ['town', 'kasaba, şehir', 'TAUN', 'I live in a small town.', 'Küçük bir kasabada yaşıyorum.', ''],
  ['trust', 'güvenmek; güven', 'TRAST', 'I trust you.', 'Sana güveniyorum.', ''],
  ['office', 'ofis, büro', 'O-fis', 'My office is on the third floor.', 'Ofisim üçüncü katta.', '🏢'],
  ['question', 'soru', 'KUES-çın', 'I have a question.', 'Bir sorum var.', ''],
  ['welcome', 'hoş geldin; buyurun', 'UEL-kım', 'Welcome to our home!', 'Evimize hoş geldin!', ''],
  ['high', 'yüksek', 'HAY', 'The mountain is very high.', 'Dağ çok yüksek.', ''],
  ['couple', 'çift; birkaç', 'KA-pıl', 'They are a nice couple.', 'Onlar güzel bir çift.', ''],
  ['half', 'yarım, yarı', 'HEF', 'I will be there in half an hour.', 'Yarım saate orada olurum.', ''],
  ['cool', 'serin; havalı', 'KUUL', 'Your new car is cool.', 'Yeni araban çok havalı.', ''],
  ['free', 'özgür; bedava; boş', 'FRİİ', 'Are you free tonight?', 'Bu akşam boş musun?', ''],
  ['either', 'ikisinden biri; de (olumsuz)', 'İİ-dır', "I don't like it either.", 'Ben de sevmiyorum.', ''],
  ['seem', 'görünmek, gibi gelmek', 'SİİM', 'You seem tired.', 'Yorgun görünüyorsun.', ''],
  ['power', 'güç; elektrik', 'PAU-ır', 'The power is off.', 'Elektrik yok.', ''],
  ['goodbye', 'hoşça kal (bye)', 'gud-BAY', 'Goodbye, see you soon.', 'Hoşça kal, yakında görüşürüz.', ''],
  ['buy', 'satın almak', 'BAY', 'I want to buy a new bag.', 'Yeni bir çanta almak istiyorum.', ''],
  ['honey', 'bal; tatlım', 'HA-ni', 'I put honey in my tea.', 'Çayıma bal koyarım.', '🍯'],
  ['front', 'ön', 'FRANT', 'Meet me in front of the school.', 'Benimle okulun önünde buluş.', ''],
  ['team', 'takım', 'TİİM', 'Which team do you support?', 'Hangi takımı tutuyorsun?', ''],
  ['answer', 'cevap; cevaplamak', 'EN-sır', 'Please answer the phone.', 'Lütfen telefonu aç.', ''],
  ['gun', 'silah, tabanca', 'GAN', 'The police officer has a gun.', 'Polis memurunun silahı var.', '🔫'],
  ['line', 'çizgi; sıra, kuyruk; hat', 'LAYN', 'Please wait in line.', 'Lütfen sırada bekleyin.', ''],
  ['send', 'göndermek', 'SEND', 'Send me a message.', 'Bana bir mesaj gönder.', ''],
  ['news', 'haber(ler)', 'NUUZ', 'I have good news!', 'İyi haberlerim var!', '📰'],
  ['stupid', 'aptal, saçma', 'STUU-pid', 'This is a stupid idea.', 'Bu saçma bir fikir.', ''],
  ['bed', 'yatak', 'BED', 'I go to bed at eleven.', 'On birde yatarım.', '🛏️'],
  ['hurry', 'acele etmek', 'HÖ-ri', 'Hurry up, the bus is here!', 'Acele et, otobüs geldi!', ''],
  ['full', 'dolu; tok', 'FUL', 'The bus is full.', 'Otobüs dolu.', ''],
  ['month', 'ay (takvim)', 'MANT', 'I visit my parents every month.', 'Her ay ailemi ziyaret ederim.', ''],
  ['save', 'kurtarmak; biriktirmek', 'SEYV', 'I save money every month.', 'Her ay para biriktiririm.', ''],
  ['sometimes', 'bazen', 'SAM-taymz', 'Sometimes I walk to work.', 'Bazen işe yürüyerek giderim.', ''],
  ['become', 'olmak, haline gelmek', 'bi-KAM', 'She became a doctor.', 'O doktor oldu.', ''],
  ['along', 'boyunca', 'ı-LONG', 'We walked along the beach.', 'Sahil boyunca yürüdük.', ''],
  ['hate', 'nefret etmek', 'HEYT', 'I hate cold weather.', 'Soğuk havadan nefret ederim.', ''],
  ['food', 'yiyecek, yemek', 'FUUD', 'The food is delicious.', 'Yemek çok lezzetli.', '🍲'],
  ['outside', 'dışarıda, dışarı', 'aut-SAYD', 'The children are playing outside.', 'Çocuklar dışarıda oynuyor.', ''],
  ['light', 'ışık; hafif', 'LAYT', 'Turn on the light, please.', 'Işığı aç, lütfen.', '💡'],
  ['dog', 'köpek', 'DOG', 'I have a black dog.', 'Siyah bir köpeğim var.', '🐕'],
  ['country', 'ülke; kırsal', 'KAN-tri', 'Turkey is a beautiful country.', 'Türkiye güzel bir ülke.', ''],
  ['clear', 'açık, net; temizlemek', 'KLİİR', 'The sky is clear today.', 'Bugün gökyüzü açık.', ''],
  ['order', 'sipariş; emir; sıra', 'OR-dır', 'Can I order now?', 'Şimdi sipariş verebilir miyim?', ''],
  ['fact', 'gerçek, olgu', 'FEKT', 'That is a fact.', 'Bu bir gerçek.', ''],
  ['captain', 'kaptan', 'KEP-tın', 'The captain is on the ship.', 'Kaptan gemide.', ''],
  ['six', 'altı', 'SİKS', 'I get up at six.', 'Altıda kalkarım.', ''],
  ['hot', 'sıcak; acı', 'HAT', 'The tea is very hot.', 'Çay çok sıcak.', ''],
  ['funny', 'komik', 'FA-ni', 'He is a funny man.', 'O komik bir adam.', ''],
  ['black', 'siyah', 'BLEK', 'I have a black cat.', 'Siyah bir kedim var.', ''],
  ['alive', 'canlı, hayatta', 'ı-LAYV', 'The fish is still alive.', 'Balık hâlâ canlı.', ''],
  ['pick', 'seçmek; toplamak; almak', 'PİK', 'I will pick you up at eight.', 'Seni sekizde alırım.', ''],
  ['feeling', 'his, duygu', 'Fİİ-ling', 'I have a good feeling.', 'İçimde iyi bir his var.', ''],
  ['cause', 'neden olmak; sebep', 'KOZ', 'Smoking causes cancer.', 'Sigara kansere neden olur.', ''],
  ['ahead', 'ileride, önde', 'ı-HED', 'Go straight ahead.', 'Dümdüz ilerle.', ''],
  ['king', 'kral', 'KİNG', 'The king lives in a castle.', 'Kral bir şatoda yaşıyor.', '🤴'],
  ['plan', 'plan; planlamak', 'PLEN', 'What are your plans for today?', 'Bugün için planların ne?', ''],
  ['dinner', 'akşam yemeği', 'Dİ-nır', 'Dinner is at seven.', 'Akşam yemeği yedide.', '🍽️'],
  ['sort', 'tür; sıralamak', 'SORT', 'What sort of food do you like?', 'Ne tür yemek seversin?', ''],
  ['boss', 'patron, şef', 'BOS', 'My boss is very nice.', 'Patronum çok iyi biri.', ''],
  ['promise', 'söz vermek; söz', 'PRA-mis', 'I promise to call you.', 'Seni arayacağıma söz veriyorum.', ''],
  ['safe', 'güvenli; kasa', 'SEYF', 'This street is safe.', 'Bu sokak güvenli.', ''],
  ['book', 'kitap; rezervasyon yapmak', 'BUK', 'I am reading a good book.', 'İyi bir kitap okuyorum.', '📖'],
  ['white', 'beyaz', 'UAYT', 'I want a white shirt.', 'Beyaz bir gömlek istiyorum.', ''],
  ['anybody', 'kimse, herhangi biri', 'E-ni-ba-di', 'Is anybody here?', 'Burada kimse var mı?', ''],
  ['small', 'küçük', 'SMOL', 'I live in a small flat.', 'Küçük bir dairede yaşıyorum.', ''],
  ['perfect', 'mükemmel', 'PÖR-fikt', 'Your English is perfect!', 'İngilizcen mükemmel!', ''],
  ['special', 'özel', 'SPE-şıl', 'Today is a special day.', 'Bugün özel bir gün.', ''],
  ['parent', 'ebeveyn (parents: anne-baba)', 'PE-rınt', 'My parents live in Bursa.', "Annemle babam Bursa'da yaşıyor.", ''],
  ['perhaps', 'belki', 'pır-HEPS', 'Perhaps he is sick.', 'Belki hastadır.', ''],
  ['sound', 'ses; gibi gelmek', 'SAUND', 'That sounds good!', 'Kulağa hoş geliyor!', ''],
  ['serious', 'ciddi', 'Sİİ-ri-ıs', 'Are you serious?', 'Ciddi misin?', ''],
  ['sick', 'hasta', 'SİK', 'I feel sick today.', 'Bugün kendimi hasta hissediyorum.', ''],
  ['company', 'şirket; arkadaşlık', 'KAM-pı-ni', 'I work for a big company.', 'Büyük bir şirkette çalışıyorum.', ''],
  ['scared', 'korkmuş', 'SKERD', 'The child is scared.', 'Çocuk korkmuş.', ''],
  ['uncle', 'amca, dayı', 'AN-kıl', 'My uncle lives in Germany.', "Amcam Almanya'da yaşıyor.", ''],
  ['poor', 'fakir; zavallı', 'PUR', 'They are poor but happy.', 'Fakirler ama mutlular.', ''],
  ['red', 'kırmızı', 'RED', 'I like red apples.', 'Kırmızı elmaları severim.', ''],
  ['past', 'geçmiş; geçe', 'PEST', 'It is ten past five.', 'Saat beşi on geçiyor.', ''],
  ['earth', 'dünya; toprak', 'ÖRT', 'The Earth is round.', 'Dünya yuvarlaktır.', '🌍'],
  ['possible', 'mümkün', 'PA-sı-bıl', 'Is it possible?', 'Bu mümkün mü?', ''],
  ['touch', 'dokunmak', 'TAÇ', "Don't touch the painting.", 'Tabloya dokunma.', ''],
  ['top', 'tepe, üst', 'TAP', 'The book is on top of the box.', 'Kitap kutunun üstünde.', ''],
  ['win', 'kazanmak', 'UİN', 'Our team won the game.', 'Takımımız maçı kazandı.', ''],
  ['glad', 'memnun, sevinçli', 'GLED', 'I am glad to see you.', 'Seni gördüğüme sevindim.', ''],
  ['control', 'kontrol; kontrol etmek', 'kın-TROUL', 'Stay in control.', 'Kontrolü elinde tut.', ''],
  ['human', 'insan', 'HYUU-mın', 'We are all human.', 'Hepimiz insanız.', ''],
  ['drive', 'araba sürmek', 'DRAYV', 'Can you drive?', 'Araba sürebiliyor musun?', ''],
  ['hair', 'saç', 'HER', 'She has long hair.', 'Onun saçı uzun.', '💇'],
  ['luck', 'şans', 'LAK', 'Good luck!', 'İyi şanslar!', ''],
  ['murder', 'cinayet; öldürmek', 'MÖR-dır', 'The police are investigating the murder.', 'Polis cinayeti araştırıyor.', ''],
  ['air', 'hava', 'ER', 'I need some fresh air.', 'Biraz temiz havaya ihtiyacım var.', ''],
  ['ten', 'on', 'TEN', 'I have ten euros.', 'On eurom var.', ''],
  ['finally', 'sonunda', 'FAY-nı-li', 'Finally, the bus is here!', 'Sonunda otobüs geldi!', ''],
  ['fast', 'hızlı', 'FEST', 'He drives very fast.', 'Arabayı çok hızlı sürüyor.', ''],
  ['cold', 'soğuk; nezle', 'KOULD', 'The water is cold.', 'Su soğuk.', ''],
  ['hospital', 'hastane', 'HAS-pi-tıl', 'She works at a hospital.', 'O bir hastanede çalışıyor.', '🏥'],
  ['street', 'sokak, cadde', 'STRİİT', 'I live on this street.', 'Bu sokakta yaşıyorum.', ''],
  ['hang', 'asmak', 'HENG', 'Hang your coat here.', 'Ceketini buraya as.', ''],
  ['dance', 'dans etmek; dans', 'DENS', "Let's dance!", 'Hadi dans edelim!', '💃'],
  ['meeting', 'toplantı', 'Mİİ-ting', 'I have a meeting at ten.', 'Saat onda toplantım var.', ''],
  ['till', '-e kadar', 'TİL', 'I work till six.', 'Altıya kadar çalışırım.', ''],
  ['catch', 'yakalamak', 'KEÇ', 'Catch the ball!', 'Topu yakala!', ''],
  ['follow', 'takip etmek, izlemek', 'FA-lou', 'Follow me, please.', 'Beni takip edin, lütfen.', ''],
  ['sense', 'his, duyu; anlam', 'SENS', 'That makes sense.', 'Bu mantıklı.', ''],
  ['lie', 'yalan söylemek; uzanmak', 'LAY', "Don't lie to me.", 'Bana yalan söyleme.', ''],
  ['evening', 'akşam', 'İİV-ning', 'Good evening!', 'İyi akşamlar!', ''],
  ['master', 'usta; efendi', 'MES-tır', 'He is a master chef.', 'O usta bir aşçı.', ''],
  ['dream', 'rüya; hayal etmek', 'DRİİM', 'I had a strange dream.', 'Garip bir rüya gördüm.', ''],
  ['write', 'yazmak', 'RAYT', 'Write your name here.', 'Adını buraya yaz.', ''],
  ['million', 'milyon', 'MİL-yın', 'The city has two million people.', 'Şehirde iki milyon insan var.', ''],
  ['voice', 'ses', 'VOYS', 'She has a beautiful voice.', 'Onun güzel bir sesi var.', ''],
  ['sweet', 'tatlı', 'SUİİT', 'This cake is too sweet.', 'Bu kek çok tatlı.', ''],
  ['rather', 'oldukça; tercihen', 'RE-dır', 'I would rather stay home.', 'Evde kalmayı tercih ederim.', ''],
  ['sign', 'işaret; imzalamak', 'SAYN', 'Please sign here.', 'Lütfen buraya imza atın.', ''],
  ['lucky', 'şanslı', 'LA-ki', 'You are very lucky.', 'Çok şanslısın.', ''],
  ['somewhere', 'bir yerde, bir yere', 'SAM-uer', "Let's go somewhere quiet.", 'Sessiz bir yere gidelim.', ''],
  ['bet', 'bahse girmek', 'BET', 'I bet you are hungry.', 'Eminim acıkmışsındır.', ''],
  ['quiet', 'sessiz, sakin', 'KUAY-ıt', 'Please be quiet.', 'Lütfen sessiz olun.', ''],
  ['pull', 'çekmek', 'PUL', 'Pull the door.', 'Kapıyı çek.', ''],
  ['beat', 'yenmek; dövmek; ritim', 'BİİT', 'We beat them 2-0.', 'Onları 2-0 yendik.', ''],
  ['careful', 'dikkatli', 'KER-fıl', 'Be careful!', 'Dikkatli ol!', ''],
  ['coffee', 'kahve', 'KA-fi', 'I drink coffee every morning.', 'Her sabah kahve içerim.', '☕'],
  ['return', 'dönmek; iade etmek', 'ri-TÖRN', 'I will return on Monday.', 'Pazartesi döneceğim.', ''],
  ['secret', 'sır; gizli', 'Sİİ-krıt', 'Can you keep a secret?', 'Sır tutabilir misin?', ''],
  ['date', 'tarih; randevu, buluşma', 'DEYT', 'What is the date today?', 'Bugün ayın kaçı?', ''],
  ['fall', 'düşmek; sonbahar', 'FOL', "Be careful, don't fall!", 'Dikkat et, düşme!', ''],
  ['fault', 'hata, kusur', 'FOLT', "It's not my fault.", 'Benim hatam değil.', ''],
  ['straight', 'düz, dümdüz', 'STREYT', 'Go straight on.', 'Dümdüz devam et.', ''],
  ['song', 'şarkı', 'SONG', 'This is my favorite song.', 'Bu en sevdiğim şarkı.', '🎵'],
  ['future', 'gelecek', 'FYUU-çır', 'I think about the future.', 'Geleceği düşünüyorum.', ''],
  ['gentleman', 'beyefendi', 'CEN-tıl-mın', 'He is a real gentleman.', 'O gerçek bir beyefendi.', ''],
  ['road', 'yol', 'ROUD', 'This road goes to the sea.', 'Bu yol denize gidiyor.', '🛣️'],
  ['calm', 'sakin', 'KAAM', 'Stay calm, please.', 'Lütfen sakin olun.', ''],
  ['wonderful', 'harika', 'UAN-dır-fıl', 'What a wonderful day!', 'Ne harika bir gün!', ''],
  ['mad', 'kızgın; deli', 'MED', 'Are you mad at me?', 'Bana kızgın mısın?', ''],
  ['drop', 'düşürmek; damla', 'DRAP', "Don't drop the glass.", 'Bardağı düşürme.', ''],
  ['learn', 'öğrenmek', 'LÖRN', 'I am learning English.', 'İngilizce öğreniyorum.', ''],
  ['step', 'adım; basamak', 'STEP', 'Take one step forward.', 'Bir adım ileri at.', ''],
  ['absolutely', 'kesinlikle', 'eb-sı-LUUT-li', 'You are absolutely right.', 'Kesinlikle haklısın.', ''],
  ['early', 'erken', 'ÖR-li', 'I get up early.', 'Erken kalkarım.', ''],
  ['explain', 'açıklamak', 'ik-SPLEYN', 'Can you explain this word?', 'Bu kelimeyi açıklayabilir misin?', ''],
  ['clean', 'temiz; temizlemek', 'KLİİN', 'My room is clean.', 'Odam temiz.', ''],
  ['piece', 'parça, dilim', 'PİİS', 'Can I have a piece of cake?', 'Bir dilim kek alabilir miyim?', ''],
  ['yesterday', 'dün', 'YES-tır-dey', 'I saw her yesterday.', 'Onu dün gördüm.', ''],
  ['throw', 'atmak, fırlatmak', 'TROU', 'Throw the ball to me.', 'Topu bana at.', ''],
  ['picture', 'resim, fotoğraf', 'PİK-çır', 'Look at this picture.', 'Şu resme bak.', '🖼️'],
  ['land', 'kara, arazi; iniş yapmak', 'LEND', 'The plane will land soon.', 'Uçak birazdan inecek.', ''],
  ['foot', 'ayak (feet)', 'FUT', 'My foot hurts.', 'Ayağım acıyor.', '🦶'],
  ['wonder', 'merak etmek; harika', 'UAN-dır', 'I wonder where he is.', 'Nerede olduğunu merak ediyorum.', ''],
  ['worth', 'değer; değmek', 'UÖRT', 'This car is worth a lot.', 'Bu araba çok değerli.', ''],
  ['darling', 'sevgilim, canım', 'DAAR-ling', 'Good night, darling.', 'İyi geceler, canım.', ''],
  ['dude', 'ahbap, dostum', 'DUUD', 'Hey dude, how are you?', 'Selam dostum, nasılsın?', ''],
  ['president', 'başkan, cumhurbaşkanı', 'PRE-zi-dınt', 'He is the president of the club.', 'O kulübün başkanı.', ''],
  ['quick', 'hızlı, çabuk', 'KUİK', 'Can I ask a quick question?', 'Kısa bir soru sorabilir miyim?', ''],
  ['figure', 'rakam; şekil; anlamak', 'Fİ-gyır', "I can't figure it out.", 'Bunu çözemiyorum.', ''],
  ['state', 'eyalet; devlet; durum', 'STEYT', 'Texas is a big state.', 'Teksas büyük bir eyalet.', ''],
  ['strong', 'güçlü', 'STRONG', 'My father is very strong.', 'Babam çok güçlü.', ''],
  ['none', 'hiçbiri', 'NAN', 'None of my friends came.', 'Arkadaşlarımın hiçbiri gelmedi.', ''],
  ['amazing', 'muhteşem, inanılmaz', 'ı-MEY-zing', 'The view is amazing.', 'Manzara muhteşem.', ''],
  ['act', 'davranmak; rol yapmak', 'EKT', "Don't act like a child.", 'Çocuk gibi davranma.', ''],
  ['weird', 'tuhaf, garip', 'UİİRD', 'That is a weird name.', 'Bu tuhaf bir isim.', ''],
  ['law', 'kanun, hukuk', 'LO', 'She studies law.', 'O hukuk okuyor.', ''],
  ['worried', 'endişeli', 'UÖ-rid', 'I am worried about my son.', 'Oğlum için endişeliyim.', ''],
  ['report', 'rapor; bildirmek', 'ri-PORT', 'I have to write a report.', 'Bir rapor yazmam lazım.', ''],
  ['choice', 'seçim, tercih', 'ÇOYS', 'You have no choice.', 'Başka seçeneğin yok.', ''],
  ['chief', 'şef, başkan; baş', 'ÇİİF', 'He is the chief of police.', 'O emniyet müdürü.', ''],
  ['wedding', 'düğün', 'UE-ding', "My sister's wedding is in June.", 'Kız kardeşimin düğünü haziranda.', '💒'],
  ['strange', 'garip, tuhaf', 'STREYNC', 'I heard a strange noise.', 'Garip bir ses duydum.', ''],
  ['general', 'genel; general', 'CE-nı-rıl', 'In general, I am happy.', 'Genel olarak mutluyum.', ''],
  ['pain', 'acı, ağrı', 'PEYN', 'I have a pain in my back.', 'Sırtımda ağrı var.', ''],
  ['decide', 'karar vermek', 'di-SAYD', "I can't decide.", 'Karar veremiyorum.', ''],
  ['pass', 'geçmek; uzatmak', 'PES', 'Pass me the salt, please.', 'Tuzu uzatır mısın, lütfen?', ''],
  ['tired', 'yorgun', 'TAY-ırd', 'I am very tired.', 'Çok yorgunum.', ''],
  ['class', 'sınıf; ders', 'KLES', 'My English class starts at nine.', 'İngilizce dersim dokuzda başlıyor.', ''],
  ['officer', 'memur; subay', 'O-fi-sır', 'Thank you, officer.', 'Teşekkürler, memur bey.', ''],
  ['wake', 'uyanmak, uyandırmak', 'UEYK', 'I wake up at seven.', 'Yedide uyanırım.', ''],
  ['busy', 'meşgul, yoğun', 'Bİ-zi', 'I am busy today.', 'Bugün meşgulüm.', ''],
  ['mistake', 'hata', 'mi-STEYK', 'Everyone makes mistakes.', 'Herkes hata yapar.', ''],
  ['kiss', 'öpmek; öpücük', 'KİS', 'Give me a kiss.', 'Bana bir öpücük ver.', '💋'],
  ['court', 'mahkeme; kort', 'KORT', 'The case is in court.', 'Dava mahkemede.', ''],
  ['building', 'bina', 'BİL-ding', 'I work in that building.', 'Şu binada çalışıyorum.', '🏢'],
  ['finish', 'bitirmek', 'Fİ-niş', 'I finish work at five.', 'İşi beşte bitiririm.', ''],
  ['during', 'sırasında, boyunca', 'DU-ring', "Don't talk during the film.", 'Film sırasında konuşma.', ''],
  ['age', 'yaş; çağ', 'EYC', 'What is your age?', 'Kaç yaşındasın?', ''],
  ['ship', 'gemi', 'ŞİP', 'The ship is very big.', 'Gemi çok büyük.', '🚢'],
  ['sell', 'satmak', 'SEL', 'They sell fresh bread.', 'Taze ekmek satıyorlar.', ''],
  ['dark', 'karanlık; koyu', 'DAARK', 'It is dark outside.', 'Dışarısı karanlık.', ''],
  ['system', 'sistem', 'SİS-tım', 'The system is not working.', 'Sistem çalışmıyor.', ''],
  ['evidence', 'kanıt, delil', 'E-vi-dıns', 'The police have no evidence.', 'Polisin hiç kanıtı yok.', ''],
  ['movie', 'film', 'MUU-vi', "Let's watch a movie tonight.", 'Bu akşam film izleyelim.', '🎬'],
  ['ride', 'binmek, sürmek', 'RAYD', 'I ride my bike to school.', 'Okula bisikletle giderim.', ''],
  ['completely', 'tamamen', 'kım-PLİİT-li', 'I completely forgot.', 'Tamamen unuttum.', ''],
  ['mouth', 'ağız', 'MAUT', 'Open your mouth, please.', 'Ağzını aç, lütfen.', '👄'],
  ['totally', 'tamamen, kesinlikle', 'TOU-tı-li', 'I totally agree.', 'Kesinlikle katılıyorum.', ''],
  ['birthday', 'doğum günü', 'BÖRT-dey', 'Happy birthday!', 'Doğum günün kutlu olsun!', '🎂'],
  ['forgive', 'affetmek', 'fır-GİV', 'Please forgive me.', 'Lütfen beni affet.', ''],
  ['born', 'doğmuş (be born: doğmak)', 'BORN', 'I was born in 1990.', "1990'da doğdum.", ''],
  ['imagine', 'hayal etmek', 'i-ME-cin', 'Imagine a world without war.', 'Savaşsız bir dünya hayal et.', ''],
  ['information', 'bilgi', 'in-fır-MEY-şın', 'I need more information.', 'Daha fazla bilgiye ihtiyacım var.', ''],
  ['instead', 'yerine', 'in-STED', 'Drink water instead of cola.', 'Kola yerine su iç.', ''],
  ['definitely', 'kesinlikle', 'DE-fı-nıt-li', 'I will definitely come.', 'Kesinlikle geleceğim.', ''],
  ['security', 'güvenlik', 'si-KYU-rı-ti', 'Airport security is very strict.', 'Havalimanı güvenliği çok sıkı.', ''],
  ['certainly', 'kesinlikle, elbette', 'SÖR-tın-li', 'Certainly, sir.', 'Elbette, efendim.', ''],
  ['film', 'film', 'FİLM', 'The film was very good.', 'Film çok güzeldi.', '🎬'],
  ['unless', '-medikçe, -mezse', 'ın-LES', 'I will go unless it rains.', 'Yağmur yağmazsa gideceğim.', ''],
  ['train', 'tren; antrenman yapmak', 'TREYN', 'The train is late.', 'Tren gecikti.', '🚆'],
  ['seven', 'yedi', 'SE-vın', 'The shop opens at seven.', 'Dükkân yedide açılıyor.', ''],
  ['wear', 'giymek, takmak', 'UER', 'I wear glasses.', 'Gözlük takarım.', ''],
  ['clothes', 'giysiler, kıyafet', 'KLOUZ', 'I need new clothes.', 'Yeni kıyafetlere ihtiyacım var.', '👕'],
  ['hotel', 'otel', 'hou-TEL', 'Our hotel is near the beach.', 'Otelimiz plaja yakın.', '🏨'],
  ['Christmas', 'Noel', 'KRİS-mıs', 'Merry Christmas!', 'Mutlu Noeller!', '🎄'],
  ['attack', 'saldırı; saldırmak', 'ı-TEK', 'The dog attacked the cat.', 'Köpek kediye saldırdı.', ''],
  ['round', 'yuvarlak; tur', 'RAUND', 'The table is round.', 'Masa yuvarlak.', ''],
  ['expect', 'beklemek, ummak', 'ik-SPEKT', 'I expect a call today.', 'Bugün bir telefon bekliyorum.', ''],
  ['sing', 'şarkı söylemek', 'SİNG', 'She sings very well.', 'Çok güzel şarkı söylüyor.', ''],
  ['terrible', 'korkunç, berbat', 'TE-rı-bıl', 'The weather is terrible.', 'Hava berbat.', ''],
  ['bag', 'çanta', 'BEG', 'My bag is heavy.', 'Çantam ağır.', '👜'],
  ['history', 'tarih (geçmiş)', 'HİS-tı-ri', 'I love history.', 'Tarihi çok severim.', ''],
  ['blue', 'mavi', 'BLUU', 'The sky is blue.', 'Gökyüzü mavi.', ''],
  ['near', 'yakın, yakında', 'NİİR', 'Is there a bank near here?', 'Buralarda banka var mı?', ''],
  ['station', 'istasyon', 'STEY-şın', 'Where is the train station?', 'Tren istasyonu nerede?', '🚉'],
  ['seriously', 'ciddi olarak; cidden', 'Sİİ-ri-ıs-li', "Seriously? I don't believe it.", 'Cidden mi? İnanamıyorum.', ''],
  ['forever', 'sonsuza dek', 'fı-RE-vır', 'I will love you forever.', 'Seni sonsuza dek seveceğim.', ''],
  ['except', 'hariç, dışında', 'ik-SEPT', 'I work every day except Sunday.', 'Pazar hariç her gün çalışırım.', ''],
  ['message', 'mesaj', 'ME-sic', 'I sent you a message.', 'Sana bir mesaj gönderdim.', ''],
  ['entire', 'bütün, tüm', 'in-TAYR', 'I slept the entire day.', 'Bütün gün uyudum.', ''],
  ['table', 'masa', 'TEY-bıl', 'The keys are on the table.', 'Anahtarlar masanın üstünde.', ''],
  ['across', 'karşısında; karşıya', 'ı-KROS', 'The bank is across the street.', 'Banka caddenin karşısında.', ''],
  ['rock', 'kaya; rock müzik', 'RAK', 'He sat on a big rock.', 'Büyük bir kayanın üstüne oturdu.', '🪨'],
  ['lovely', 'hoş, güzel, sevimli', 'LAV-li', 'What a lovely garden!', 'Ne hoş bir bahçe!', ''],
  ['handle', 'halletmek; sap', 'HEN-dıl', 'I can handle it.', 'Ben hallederim.', ''],
  ['middle', 'orta', 'Mİ-dıl', 'The table is in the middle.', 'Masa ortada.', ''],
  ['buddy', 'dost, kanka', 'BA-di', 'He is my old buddy.', 'O benim eski dostum.', ''],
  ['protect', 'korumak', 'prı-TEKT', 'Parents protect their children.', 'Ebeveynler çocuklarını korur.', ''],
  ['floor', 'yer, zemin; kat', 'FLOR', 'I live on the second floor.', 'İkinci katta oturuyorum.', ''],
  ['swear', 'yemin etmek; küfretmek', 'SUER', "I swear it's true.", 'Yemin ederim, bu doğru.', ''],
  ['spend', 'harcamak; geçirmek', 'SPEND', 'I spend a lot on food.', 'Yemeğe çok para harcıyorum.', ''],
  ['situation', 'durum', 'si-çu-EY-şın', 'This is a difficult situation.', 'Bu zor bir durum.', ''],
  ['ring', 'yüzük; çalmak (zil)', 'RİNG', 'She has a gold ring.', 'Onun altın bir yüzüğü var.', '💍'],
  ['anywhere', 'herhangi bir yer; hiçbir yer', 'E-ni-uer', "I can't find it anywhere.", 'Onu hiçbir yerde bulamıyorum.', ''],
  ['dangerous', 'tehlikeli', 'DEYN-cı-rıs', 'This road is dangerous.', 'Bu yol tehlikeli.', ''],
  ['bill', 'fatura, hesap', 'BİL', 'Can I have the bill, please?', 'Hesabı alabilir miyim, lütfen?', '🧾'],
  ['army', 'ordu', 'AAR-mi', 'My brother is in the army.', 'Erkek kardeşim askerde.', ''],
  ['lead', 'yönetmek, önderlik etmek', 'LİİD', 'She leads a big team.', 'Büyük bir ekibi yönetiyor.', ''],
  ['fair', 'adil; fuar', 'FER', "That's not fair!", 'Bu adil değil!', ''],
  ['sun', 'güneş', 'SAN', 'The sun is very hot today.', 'Bugün güneş çok sıcak.', '☀️'],
  ['letter', 'mektup; harf', 'LE-tır', 'I wrote a letter to my friend.', 'Arkadaşıma bir mektup yazdım.', '✉️'],
  ['fool', 'aptal; kandırmak', 'FUUL', "Don't be a fool.", 'Aptallık etme.', ''],
  ['attention', 'dikkat', 'ı-TEN-şın', 'Pay attention, please.', 'Lütfen dikkat edin.', ''],
  ['club', 'kulüp', 'KLAB', 'I joined a book club.', 'Bir kitap kulübüne katıldım.', ''],
  ['simple', 'basit', 'SİM-pıl', 'The question is very simple.', 'Soru çok basit.', ''],
  ['interesting', 'ilginç', 'İN-trıs-ting', 'This book is interesting.', 'Bu kitap ilginç.', ''],
  ['space', 'uzay; yer, boşluk', 'SPEYS', 'Is there space for me?', 'Bana yer var mı?', ''],
  ['test', 'sınav, test', 'TEST', 'I have a test tomorrow.', 'Yarın sınavım var.', ''],
  ['box', 'kutu', 'BAKS', 'The box is empty.', 'Kutu boş.', '📦'],
  ['group', 'grup', 'GRUUP', 'We travel in a group.', 'Grup halinde seyahat ediyoruz.', ''],
  ['single', 'tek; bekâr', 'SİN-gıl', 'Are you single?', 'Bekâr mısın?', ''],
  ['marriage', 'evlilik', 'ME-ric', 'They have a happy marriage.', 'Mutlu bir evlilikleri var.', ''],
  ['join', 'katılmak', 'COYN', 'Can I join you?', 'Size katılabilir miyim?', ''],
  ['fear', 'korku; korkmak', 'FİİR', 'I have a fear of flying.', 'Uçmaktan korkarım.', ''],
  ['peace', 'barış; huzur', 'PİİS', 'We want peace.', 'Barış istiyoruz.', '🕊️'],
  ['force', 'güç; zorlamak', 'FORS', "Don't force me.", 'Beni zorlama.', ''],
  ['short', 'kısa', 'ŞORT', 'My sister is short.', 'Kız kardeşim kısa boylu.', ''],
  ['normal', 'normal', 'NOR-mıl', 'Everything is normal.', 'Her şey normal.', ''],
  ['present', 'hediye; şimdiki; sunmak', 'PRE-zınt', 'This present is for you.', 'Bu hediye senin için.', '🎁'],
  ['enjoy', 'keyif almak, tadını çıkarmak', 'in-COY', 'Enjoy your meal!', 'Afiyet olsun!', ''],
  ['crime', 'suç', 'KRAYM', 'Crime is a big problem here.', 'Burada suç büyük bir sorun.', ''],
  ['horse', 'at', 'HORS', 'She rides a white horse.', 'Beyaz bir ata biniyor.', '🐎'],
  ['ground', 'yer, zemin', 'GRAUND', 'Sit on the ground.', 'Yere otur.', ''],
  ['American', 'Amerikalı', 'ı-ME-ri-kın', 'My teacher is American.', 'Öğretmenim Amerikalı.', ''],
  ['count', 'saymak', 'KAUNT', 'Count from one to ten.', 'Birden ona kadar say.', ''],
  ['area', 'bölge, alan', 'E-ri-ı', 'This is a quiet area.', 'Burası sakin bir bölge.', ''],
  ['charge', 'ücret; şarj etmek; sorumlu', 'ÇAARC', 'I need to charge my phone.', 'Telefonumu şarj etmem lazım.', ''],
  ['honor', 'onur, şeref', 'A-nır', 'It is an honor to meet you.', 'Sizinle tanışmak bir onur.', ''],
  ['lunch', 'öğle yemeği', 'LANÇ', "Let's have lunch together.", 'Hadi birlikte öğle yemeği yiyelim.', '🥪'],
  ['mile', 'mil (1,6 km)', 'MAYL', 'The beach is two miles away.', 'Plaj iki mil uzakta.', ''],
  ['radio', 'radyo', 'REY-di-ou', 'I listen to the radio in the car.', 'Arabada radyo dinlerim.', '📻'],
  ['idiot', 'aptal, salak', 'İ-di-ıt', 'I feel like an idiot.', 'Kendimi aptal gibi hissediyorum.', ''],
  ['ball', 'top', 'BOL', 'The children play with a ball.', 'Çocuklar topla oynuyor.', '⚽'],
  ['surprise', 'sürpriz; şaşırtmak', 'sır-PRAYZ', 'What a nice surprise!', 'Ne güzel bir sürpriz!', ''],
  ['paper', 'kâğıt; gazete', 'PEY-pır', 'I need a pen and paper.', 'Kalem ve kâğıda ihtiyacım var.', '📄'],
  ['key', 'anahtar', 'Kİİ', 'I lost my key.', 'Anahtarımı kaybettim.', '🔑'],
  ['boat', 'tekne, kayık', 'BOUT', 'We went on a boat trip.', 'Tekne gezisine çıktık.', '⛵'],
  ['quickly', 'hızla, çabucak', 'KUİK-li', 'Come here quickly!', 'Çabuk buraya gel!', ''],
  ['gold', 'altın', 'GOULD', 'This ring is gold.', 'Bu yüzük altın.', '🥇'],
  ['bar', 'bar; çubuk; kalıp', 'BAAR', "Let's meet at the bar.", 'Barda buluşalım.', ''],
  ['fish', 'balık; balık tutmak', 'FİŞ', 'I eat fish on Fridays.', 'Cuma günleri balık yerim.', '🐟'],
  ['mark', 'işaret; not', 'MAARK', 'I got a good mark.', 'İyi bir not aldım.', ''],
  ['cry', 'ağlamak; bağırmak', 'KRAY', 'The baby is crying.', 'Bebek ağlıyor.', ''],
  ['accident', 'kaza', 'EK-si-dınt', 'He had a car accident.', 'Araba kazası geçirdi.', ''],
  ['government', 'hükümet', 'GA-vırn-mınt', 'The government has a new plan.', 'Hükümetin yeni bir planı var.', ''],
  ['eight', 'sekiz', 'EYT', 'I start work at eight.', 'İşe sekizde başlarım.', ''],
  ['cover', 'örtmek; kapak', 'KA-vır', 'Cover the food, please.', 'Yemeğin üstünü ört, lütfen.', ''],
  ['certain', 'emin; belirli', 'SÖR-tın', 'Are you certain?', 'Emin misin?', ''],
  ['interested', 'ilgili, meraklı', 'İN-trıs-tid', 'I am interested in art.', 'Sanatla ilgileniyorum.', ''],
  ['deep', 'derin', 'DİİP', 'The lake is very deep.', 'Göl çok derin.', ''],
  ['star', 'yıldız', 'STAAR', 'Look at the stars!', 'Yıldızlara bak!', '⭐'],
  ['sea', 'deniz', 'Sİİ', 'We swim in the sea.', 'Denizde yüzüyoruz.', '🌊'],
  ['agree', 'katılmak, aynı fikirde olmak', 'ı-GRİİ', 'I agree with you.', 'Sana katılıyorum.', ''],
  ['detective', 'dedektif', 'di-TEK-tiv', 'The detective found the killer.', 'Dedektif katili buldu.', ''],
  ['prison', 'hapishane', 'PRİ-zın', 'He was in prison for two years.', 'İki yıl hapiste kaldı.', ''],
  ['major', 'büyük, önemli; binbaşı', 'MEY-cır', 'This is a major problem.', 'Bu büyük bir sorun.', ''],
  ['stick', 'sopa; yapışmak', 'STİK', 'The dog has a stick.', 'Köpeğin ağzında bir sopa var.', ''],
  ['offer', 'teklif; teklif etmek', 'O-fır', 'Thank you for the offer.', 'Teklif için teşekkürler.', ''],
  ['difficult', 'zor', 'Dİ-fi-kılt', 'English is not difficult.', 'İngilizce zor değil.', ''],
  ['smart', 'akıllı; şık', 'SMAART', 'She is a smart girl.', 'O akıllı bir kız.', ''],
  ['personal', 'kişisel', 'PÖR-sı-nıl', 'This is a personal question.', 'Bu kişisel bir soru.', ''],
  ['record', 'kayıt; kaydetmek; rekor', 'RE-kırd', 'He broke the world record.', 'Dünya rekorunu kırdı.', ''],
  ['hide', 'saklanmak, saklamak', 'HAYD', 'The cat is hiding under the bed.', 'Kedi yatağın altında saklanıyor.', ''],
  ['whether', '-ip -mediği', 'UE-dır', "I don't know whether he is coming.", 'Gelip gelmediğini bilmiyorum.', ''],
  ['bank', 'banka', 'BENK', 'The bank opens at nine.', 'Banka dokuzda açılıyor.', '🏦'],
  ['trip', 'gezi, yolculuk', 'TRİP', 'Have a nice trip!', 'İyi yolculuklar!', ''],
  ['relax', 'rahatlamak', 'ri-LEKS', 'Relax and have a drink.', 'Rahatla ve bir şey iç.', ''],
  ['public', 'halka açık; halk', 'PAB-lik', 'This is a public park.', 'Bu halka açık bir park.', ''],
  ['list', 'liste', 'LİST', 'I have a shopping list.', 'Bir alışveriş listem var.', '📝'],
  ['afternoon', 'öğleden sonra', 'ef-tır-NUUN', 'Good afternoon!', 'Tünaydın!', ''],
  ['brain', 'beyin', 'BREYN', 'Your brain needs sleep.', 'Beyninin uykuya ihtiyacı var.', '🧠'],
  ['fix', 'tamir etmek', 'FİKS', 'Can you fix my bike?', 'Bisikletimi tamir edebilir misin?', ''],
  ['proud', 'gururlu', 'PRAUD', 'I am proud of you.', 'Seninle gurur duyuyorum.', ''],
  ['tea', 'çay', 'Tİİ', 'Would you like some tea?', 'Biraz çay ister misin?', '🍵'],
  ['service', 'hizmet, servis', 'SÖR-vis', 'The service here is very good.', 'Buradaki hizmet çok iyi.', ''],
  ['forward', 'ileri', 'FOR-uırd', 'Move forward, please.', 'İleri gidin, lütfen.', ''],
  ['angry', 'kızgın', 'EN-gri', 'Why are you angry?', 'Neden kızgınsın?', ''],
  ['park', 'park; park etmek', 'PAARK', "Let's go to the park.", 'Hadi parka gidelim.', ''],
  ['soul', 'ruh', 'SOUL', 'Music is good for the soul.', 'Müzik ruha iyi gelir.', ''],
  ['rich', 'zengin', 'RİÇ', 'He is a rich man.', 'O zengin bir adam.', ''],
  ['agent', 'ajan; temsilci', 'EY-cınt', 'He is a secret agent.', 'O bir gizli ajan.', ''],
  ['blow', 'üflemek; esmek', 'BLOU', 'Blow out the candles!', 'Mumları üfle!', ''],
  ['dress', 'elbise; giyinmek', 'DRES', 'She is wearing a red dress.', 'Kırmızı bir elbise giyiyor.', '👗'],
  ['scene', 'sahne; olay yeri', 'SİİN', 'I love this scene.', 'Bu sahneye bayılıyorum.', ''],
  ['respect', 'saygı; saygı duymak', 'ri-SPEKT', 'Respect your parents.', 'Anne babana saygı göster.', ''],
  ['killer', 'katil', 'Kİ-lır', 'The police caught the killer.', 'Polis katili yakaladı.', ''],
  ['ice', 'buz', 'AYS', 'I want water with ice.', 'Buzlu su istiyorum.', '🧊'],
  ['mess', 'dağınıklık, karmaşa', 'MES', 'Your room is a mess!', 'Odan darmadağın!', ''],
  ['tough', 'zor; sert, dayanıklı', 'TAF', 'It was a tough day.', 'Zor bir gündü.', ''],
  ['church', 'kilise', 'ÇÖRÇ', 'The church is very old.', 'Kilise çok eski.', '⛪'],
  ['sad', 'üzgün', 'SED', 'Why are you sad?', 'Neden üzgünsün?', ''],
  ['cell', 'hücre; cep telefonu', 'SEL', 'Call me on my cell.', 'Beni cep telefonumdan ara.', ''],
  ['drunk', 'sarhoş', 'DRANK', 'He is drunk again.', 'Yine sarhoş.', ''],
  ['share', 'paylaşmak', 'ŞER', "Let's share the pizza.", 'Pizzayı paylaşalım.', ''],
  ['camera', 'fotoğraf makinesi, kamera', 'KEM-rı', 'I have a new camera.', 'Yeni bir fotoğraf makinem var.', '📷'],
  ['within', 'içinde, dahilinde', 'ui-DİN', 'I will call you within an hour.', 'Bir saat içinde seni ararım.', ''],
  ['card', 'kart', 'KAARD', 'Can I pay by card?', 'Kartla ödeyebilir miyim?', '💳'],
  ['fly', 'uçmak; sinek', 'FLAY', 'Birds can fly.', 'Kuşlar uçabilir.', ''],
  ['girlfriend', 'kız arkadaş, sevgili', 'GÖRL-frend', 'This is my girlfriend, Ayşe.', 'Bu kız arkadaşım Ayşe.', ''],
  ['laugh', 'gülmek', 'LEF', "Don't laugh at me.", 'Bana gülme.', ''],
  ['smell', 'kokmak; koku', 'SMEL', 'The bread smells good.', 'Ekmek güzel kokuyor.', ''],
  ['honest', 'dürüst', 'A-nist', 'He is an honest man.', 'O dürüst bir adam.', ''],
  ['often', 'sık sık', 'O-fın', 'I often go to the cinema.', 'Sık sık sinemaya giderim.', ''],
  ['third', 'üçüncü', 'TÖRD', 'This is my third coffee today.', 'Bu bugünkü üçüncü kahvem.', ''],
  ['English', 'İngilizce; İngiliz', 'İNG-gliş', 'I speak a little English.', 'Biraz İngilizce konuşurum.', ''],
  ['visit', 'ziyaret etmek', 'Vİ-zit', 'I visit my grandma on Sundays.', 'Pazarları büyükannemi ziyaret ederim.', ''],
  ['judge', 'hâkim; yargılamak', 'CAC', 'The judge is very fair.', 'Hâkim çok adil.', ''],
  ['window', 'pencere', 'UİN-dou', 'Open the window, please.', 'Pencereyi aç, lütfen.', '🪟'],
  ['hungry', 'aç', 'HAN-gri', 'I am very hungry.', 'Çok açım.', ''],
  ['dare', 'cesaret etmek', 'DER', "Don't you dare!", 'Sakın ha!', ''],
  ['relationship', 'ilişki', 'ri-LEY-şın-şip', 'They have a good relationship.', 'İyi bir ilişkileri var.', ''],
  ['prove', 'kanıtlamak', 'PRUUV', 'Can you prove it?', 'Bunu kanıtlayabilir misin?', ''],
  ['private', 'özel', 'PRAY-vıt', 'This is a private room.', 'Bu özel bir oda.', ''],
  ['wall', 'duvar', 'UOL', 'There is a clock on the wall.', 'Duvarda bir saat var.', '🧱'],
  ['seat', 'koltuk, oturacak yer', 'SİİT', 'Is this seat free?', 'Bu koltuk boş mu?', '💺'],
  ['position', 'konum; pozisyon', 'pı-Zİ-şın', 'What is your position in the team?', 'Takımdaki pozisyonun ne?', ''],
  ['lieutenant', 'teğmen', 'luu-TE-nınt', 'The lieutenant gave an order.', 'Teğmen bir emir verdi.', ''],
  ['realize', 'fark etmek', 'Rİİ-ı-layz', "I didn't realize it was late.", 'Geç olduğunu fark etmedim.', ''],
  ['especially', 'özellikle', 'i-SPE-şı-li', 'I love fruit, especially apples.', 'Meyveyi, özellikle elmayı severim.', ''],
  ['machine', 'makine', 'mı-ŞİİN', 'The coffee machine is broken.', 'Kahve makinesi bozuk.', ''],
  ['art', 'sanat', 'AART', 'I love modern art.', 'Modern sanatı severim.', '🎨'],
  ['pleasure', 'zevk; memnuniyet', 'PLE-jır', "It's my pleasure.", 'Rica ederim, ne demek.', ''],
  ['college', 'üniversite, yüksekokul', 'KA-lic', 'My son is in college.', 'Oğlum üniversitede.', ''],
  ['French', 'Fransızca; Fransız', 'FRENÇ', 'I want to learn French.', 'Fransızca öğrenmek istiyorum.', ''],
  ['involved', 'dahil, karışmış', 'in-VALVD', "I don't want to get involved.", 'Bu işe karışmak istemiyorum.', ''],
  ['impossible', 'imkânsız', 'im-PA-sı-bıl', 'Nothing is impossible.', 'Hiçbir şey imkânsız değildir.', ''],
  ['obviously', 'belli ki, tabii ki', 'AB-vi-ıs-li', 'Obviously, he is tired.', 'Belli ki yorgun.', ''],
  ['neither', 'hiçbiri; ne ... ne', 'Nİİ-dır', 'Neither of us can swim.', 'İkimiz de yüzemiyoruz.', ''],
  ['accept', 'kabul etmek', 'ık-SEPT', 'Do you accept cards?', 'Kart kabul ediyor musunuz?', ''],
  ['boyfriend', 'erkek arkadaş, sevgili', 'BOY-frend', 'Her boyfriend is from Spain.', 'Erkek arkadaşı İspanyol.', ''],
  ['besides', 'ayrıca; -den başka', 'bi-SAYDZ', 'Besides, I am tired.', 'Ayrıca yorgunum.', ''],
  ['queen', 'kraliçe', 'KUİİN', 'The queen lives in a palace.', 'Kraliçe bir sarayda yaşıyor.', '👑'],
  ['teacher', 'öğretmen', 'Tİİ-çır', 'My mother is a teacher.', 'Annem öğretmen.', '🧑‍🏫'],
  ['cop', 'polis (argo)', 'KAP', 'The cops are here.', 'Polisler geldi.', '👮'],
  ['sake', 'hatır (for ... sake)', 'SEYK', 'Do it for my sake.', 'Benim hatırım için yap.', ''],
  ['carry', 'taşımak', 'KE-ri', 'Can you carry this box?', 'Bu kutuyu taşıyabilir misin?', ''],
  ['teach', 'öğretmek', 'TİİÇ', 'She teaches English.', 'İngilizce öğretiyor.', ''],
  ['apartment', 'daire, apartman dairesi', 'ı-PAART-mınt', 'I live in a small apartment.', 'Küçük bir dairede yaşıyorum.', ''],
  ['upset', 'üzgün, keyifsiz', 'ap-SET', 'She is upset with me.', 'Bana kırgın.', ''],
  ['green', 'yeşil', 'GRİİN', 'I like green tea.', 'Yeşil çayı severim.', ''],
  ['cute', 'sevimli, tatlı', 'KYUUT', 'What a cute baby!', 'Ne tatlı bir bebek!', ''],
  ['evil', 'kötü, şeytani', 'İİ-vıl', 'He is an evil man.', 'O kötü bir adam.', ''],
  ['professor', 'profesör', 'prı-FE-sır', 'My professor is very kind.', 'Profesörüm çok nazik.', ''],
  ['contact', 'iletişim; iletişime geçmek', 'KAN-tekt', 'Please contact me tomorrow.', 'Lütfen yarın benimle iletişime geç.', ''],
  ['joke', 'şaka; şaka yapmak', 'COUK', 'Tell me a joke.', 'Bana bir fıkra anlat.', ''],
  ['huge', 'kocaman, dev', 'HYUUC', 'They have a huge house.', 'Kocaman bir evleri var.', ''],
  ['holy', 'kutsal', 'HOU-li', 'This is a holy place.', 'Burası kutsal bir yer.', ''],
  ['store', 'mağaza, dükkân', 'STOR', 'The store closes at ten.', 'Mağaza onda kapanıyor.', '🏪'],
  ['jail', 'hapishane', 'CEYL', 'He is in jail.', 'O hapiste.', ''],
  ['lawyer', 'avukat', 'LO-yır', 'I need a lawyer.', 'Bir avukata ihtiyacım var.', ''],
  ['doubt', 'şüphe; şüphe etmek', 'DAUT', 'I doubt it.', 'Hiç sanmıyorum.', ''],
  ['continue', 'devam etmek', 'kın-Tİ-nyu', 'Please continue.', 'Lütfen devam edin.', ''],
  ['appreciate', 'takdir etmek; minnettar olmak', 'ı-PRİİ-şi-eyt', 'I appreciate your help.', 'Yardımın için minnettarım.', ''],
  ['cat', 'kedi', 'KET', 'My cat sleeps all day.', 'Kedim bütün gün uyur.', '🐈'],
  ['shop', 'dükkân; alışveriş yapmak', 'ŞAP', 'I shop on Saturdays.', 'Cumartesileri alışveriş yaparım.', '🏪'],
  ['congratulations', 'tebrikler', 'kın-gre-çı-LEY-şınz', 'Congratulations on your new job!', 'Yeni işin için tebrikler!', ''],
  ['village', 'köy', 'Vİ-lic', 'My grandparents live in a village.', 'Büyükannemle büyükbabam bir köyde yaşıyor.', ''],
  ['quit', 'bırakmak (işi, sigarayı)', 'KUİT', 'I quit smoking last year.', 'Geçen yıl sigarayı bıraktım.', ''],
  ['field', 'tarla; alan, saha', 'FİİLD', 'The cows are in the field.', 'İnekler tarlada.', ''],
  ['wine', 'şarap', 'UAYN', 'A glass of red wine, please.', 'Bir kadeh kırmızı şarap, lütfen.', '🍷'],
  ['decision', 'karar', 'di-Sİ-jın', 'It is a big decision.', 'Bu büyük bir karar.', ''],
  ['south', 'güney', 'SAUT', 'We live in the south.', 'Güneyde yaşıyoruz.', ''],
  ['slow', 'yavaş', 'SLOU', 'The bus is very slow.', 'Otobüs çok yavaş.', ''],
  ['island', 'ada', 'AY-lınd', 'We spent a week on an island.', 'Bir adada bir hafta geçirdik.', '🏝️'],
  ['glass', 'bardak; cam', 'GLES', 'Can I have a glass of water?', 'Bir bardak su alabilir miyim?', '🥛'],
  ['begin', 'başlamak', 'bi-GİN', 'The lesson begins at ten.', 'Ders onda başlıyor.', ''],
  ['cash', 'nakit', 'KEŞ', 'Do you have any cash?', 'Yanında hiç nakit var mı?', '💵'],
  ['hundred', 'yüz (100)', 'HAN-drıd', 'It costs a hundred lira.', 'Yüz lira tutuyor.', ''],
  ['difference', 'fark', 'Dİ-fı-rıns', 'What is the difference?', 'Fark ne?', ''],
  ['plane', 'uçak', 'PLEYN', 'The plane leaves at noon.', 'Uçak öğlen kalkıyor.', '✈️'],
  ['push', 'itmek', 'PUŞ', 'Push the door.', 'Kapıyı it.', ''],
  ['north', 'kuzey', 'NORT', 'It is cold in the north.', 'Kuzeyde hava soğuk.', ''],
  ['tree', 'ağaç', 'TRİİ', 'There is a big tree in our garden.', 'Bahçemizde büyük bir ağaç var.', '🌳'],
  ['gift', 'hediye', 'GİFT', 'This gift is for you.', 'Bu hediye senin için.', '🎁'],
  ['truck', 'kamyon', 'TRAK', 'The truck is very big.', 'Kamyon çok büyük.', '🚚'],
  ['bear', 'ayı; katlanmak', 'BER', 'I saw a bear in the forest.', 'Ormanda bir ayı gördüm.', '🐻'],
  ['board', 'tahta, pano; binmek', 'BORD', 'Write on the board, please.', 'Lütfen tahtaya yaz.', ''],
  ['grab', 'kapmak, yakalamak', 'GREB', "Let's grab a coffee.", 'Hadi bir kahve alalım.', ''],
  ['beer', 'bira', 'BİİR', 'Two beers, please.', 'İki bira, lütfen.', '🍺'],
  ['stuck', 'sıkışmış, takılmış', 'STAK', 'I am stuck in traffic.', 'Trafikte sıkıştım.', ''],
  ['magic', 'sihir; sihirli', 'ME-cik', 'He can do magic tricks.', 'Sihirbazlık numaraları yapabiliyor.', ''],
  ['support', 'desteklemek; destek', 'sı-PORT', 'My family supports me.', 'Ailem beni destekliyor.', ''],
  ['rule', 'kural', 'RUUL', 'Those are the rules.', 'Kurallar bunlar.', ''],
  ['partner', 'ortak; eş, partner', 'PAART-nır', 'She is my business partner.', 'O benim iş ortağım.', ''],
  ['reach', 'ulaşmak, uzanmak', 'RİİÇ', "I can't reach the top shelf.", 'Üst rafa uzanamıyorum.', ''],
  ['wind', 'rüzgâr', 'UİND', 'The wind is very strong today.', 'Bugün rüzgâr çok sert.', '💨'],
  ['colonel', 'albay', 'KÖR-nıl', 'The colonel is here.', 'Albay burada.', ''],
  ['immediately', 'hemen, derhal', 'i-Mİİ-di-ıt-li', 'Come here immediately!', 'Hemen buraya gel!', ''],
  ['thousand', 'bin (1000)', 'TAU-zınd', 'It costs a thousand dollars.', 'Bin dolar tutuyor.', ''],
  ['experience', 'deneyim; yaşamak', 'ik-SPİİ-ri-ıns', 'I have no experience.', 'Hiç deneyimim yok.', ''],
  ['cheer', 'şerefe (cheers); alkışlamak', 'ÇİİR', 'Cheers! To your health!', 'Şerefe! Sağlığına!', ''],
  ['victim', 'kurban, mağdur', 'VİK-tim', 'The victim is in hospital.', 'Mağdur hastanede.', ''],
  ['upon', 'üzerine, üstüne', 'ı-PAN', 'Once upon a time...', 'Bir zamanlar...', ''],
  ['computer', 'bilgisayar', 'kım-PYUU-tır', 'My computer is very slow.', 'Bilgisayarım çok yavaş.', '💻'],
  ['planet', 'gezegen', 'PLE-nit', 'Earth is our planet.', 'Dünya bizim gezegenimiz.', '🪐'],
  ['bus', 'otobüs', 'BAS', 'I take the bus to work.', 'İşe otobüsle giderim.', '🚌'],
  ['dirty', 'kirli', 'DÖR-ti', 'My shoes are dirty.', 'Ayakkabılarım kirli.', ''],
  ['search', 'aramak; arama', 'SÖRÇ', 'I am searching for my keys.', 'Anahtarlarımı arıyorum.', ''],
  ['arrest', 'tutuklamak', 'ı-REST', 'The police arrested him.', 'Polis onu tutukladı.', ''],
  ['suddenly', 'aniden', 'SA-dın-li', 'Suddenly, the lights went out.', 'Aniden ışıklar söndü.', ''],
  ['usually', 'genellikle', 'YUU-ju-ı-li', 'I usually walk to work.', 'Genellikle işe yürüyerek giderim.', ''],
  ['shoe', 'ayakkabı', 'ŞUU', 'I need new shoes.', 'Yeni ayakkabılara ihtiyacım var.', '👟'],
  ['jump', 'zıplamak, atlamak', 'CAMP', 'The children jump on the bed.', 'Çocuklar yatakta zıplıyor.', ''],
  ['rid', 'kurtulmak (get rid of)', 'RİD', 'Get rid of this old sofa.', 'Bu eski kanepeden kurtul.', ''],
  ['knock', 'kapıyı çalmak, vurmak', 'NAK', 'Please knock before you enter.', 'Lütfen girmeden önce kapıyı çal.', ''],
  ['owe', 'borçlu olmak', 'OU', 'I owe you ten dollars.', 'Sana on dolar borcum var.', ''],
  ['grow', 'büyümek; yetiştirmek', 'GROU', 'Children grow fast.', 'Çocuklar hızlı büyür.', ''],
  ['river', 'nehir', 'Rİ-vır', 'We swim in the river.', 'Nehirde yüzeriz.', '🏞️'],
  ['aunt', 'teyze, hala', 'ENT', 'My aunt lives in Izmir.', "Teyzem İzmir'de yaşıyor.", ''],
  ['patient', 'hasta; sabırlı', 'PEY-şınt', 'Please be patient.', 'Lütfen sabırlı olun.', ''],
  ['kitchen', 'mutfak', 'Kİ-çın', 'Mom is in the kitchen.', 'Annem mutfakta.', ''],
  ['fat', 'şişman; yağ', 'FET', 'My cat is very fat.', 'Kedim çok şişman.', ''],
  ['final', 'son, final', 'FAY-nıl', 'This is the final question.', 'Bu son soru.', ''],
  ['summer', 'yaz', 'SA-mır', 'We go to the sea every summer.', 'Her yaz denize gideriz.', '☀️'],
  ['escape', 'kaçmak', 'i-SKEYP', 'The bird escaped from its cage.', 'Kuş kafesinden kaçtı.', ''],
  ['everywhere', 'her yerde', 'EV-ri-uer', 'I looked everywhere.', 'Her yere baktım.', ''],
  ['moon', 'ay (gök cismi)', 'MUUN', 'The moon is bright tonight.', 'Bu gece ay çok parlak.', '🌙'],
  ['arm', 'kol', 'AARM', 'My arm hurts.', 'Kolum ağrıyor.', '💪'],
  ['address', 'adres', 'ı-DRES', 'What is your address?', 'Adresin ne?', ''],
  ['match', 'maç; kibrit; uymak', 'MEÇ', "Let's watch the match.", 'Hadi maçı izleyelim.', ''],
  ['grand', 'büyük, görkemli', 'GREND', 'This is a grand hotel.', 'Bu görkemli bir otel.', ''],
  ['nervous', 'gergin, sinirli', 'NÖR-vıs', 'I am nervous about the exam.', 'Sınav yüzünden gerginim.', ''],
  ['choose', 'seçmek', 'ÇUUZ', 'Choose a color.', 'Bir renk seç.', ''],
  ['mate', 'arkadaş, dost', 'MEYT', 'He is my best mate.', 'O benim en yakın dostum.', ''],
  ['press', 'basmak; basın', 'PRES', 'Press the button.', 'Düğmeye bas.', ''],
  ['bother', 'rahatsız etmek', 'BA-dır', 'Sorry to bother you.', 'Rahatsız ettiğim için özür dilerim.', ''],
  ['blame', 'suçlamak', 'BLEYM', "Don't blame me.", 'Beni suçlama.', ''],
  ['drug', 'ilaç; uyuşturucu', 'DRAG', 'This drug is for headaches.', 'Bu ilaç baş ağrısı için.', ''],
  ['type', 'tür, tip; yazmak (klavye)', 'TAYP', 'He is not my type.', 'O benim tipim değil.', ''],
  ['mission', 'görev', 'Mİ-şın', 'The mission was a success.', 'Görev başarılı oldu.', ''],
  ['heaven', 'cennet', 'HE-vın', 'This beach is like heaven.', 'Bu plaj cennet gibi.', ''],
  ['race', 'yarış; ırk', 'REYS', 'He won the race.', 'Yarışı kazandı.', ''],
  ['risk', 'risk, tehlike', 'RİSK', "It's a big risk.", 'Bu büyük bir risk.', ''],
  ['action', 'eylem, hareket; aksiyon', 'EK-şın', 'I love action films.', 'Aksiyon filmlerini severim.', ''],
  ['allow', 'izin vermek', 'ı-LAU', 'Dogs are not allowed here.', 'Buraya köpek girmesi yasak.', ''],
  ['price', 'fiyat', 'PRAYS', 'What is the price?', 'Fiyatı ne?', '🏷️'],
  ['arrive', 'varmak, gelmek', 'ı-RAYV', 'The train arrives at five.', 'Tren beşte varıyor.', ''],
  ['otherwise', 'yoksa; aksi takdirde', 'A-dır-uayz', 'Hurry, otherwise we will be late.', 'Acele et, yoksa geç kalacağız.', ''],
  ['fit', 'uymak; formda', 'FİT', "These shoes don't fit.", 'Bu ayakkabılar bana olmuyor.', ''],
  ['smoke', 'duman; sigara içmek', 'SMOUK', "I don't smoke.", 'Sigara içmem.', ''],
  ['favor', 'iyilik', 'FEY-vır', 'Can you do me a favor?', 'Bana bir iyilik yapar mısın?', ''],
  ['notice', 'fark etmek; duyuru', 'NOU-tis', 'Did you notice his new car?', 'Onun yeni arabasını fark ettin mi?', ''],
  ['awesome', 'müthiş, harika', 'O-sım', 'The concert was awesome!', 'Konser müthişti!', ''],
  ['smile', 'gülümsemek; gülümseme', 'SMAYL', 'She has a beautiful smile.', 'Onun güzel bir gülümsemesi var.', '😊'],
  ['director', 'yönetmen; müdür', 'dı-REK-tır', 'He is a film director.', 'O bir film yönetmeni.', ''],
  ['guard', 'bekçi, muhafız; korumak', 'GAARD', 'The guard is at the door.', 'Bekçi kapıda.', ''],
  ['spot', 'yer, nokta; fark etmek', 'SPAT', 'This is a nice spot for a picnic.', 'Burası piknik için güzel bir yer.', ''],
  ['surprised', 'şaşırmış', 'sır-PRAYZD', 'I was surprised to see him.', 'Onu görünce şaşırdım.', ''],
  ['innocent', 'masum', 'İ-nı-sınt', 'He is innocent.', 'O masum.', ''],
  ['enemy', 'düşman', 'E-nı-mi', 'He is not your enemy.', 'O senin düşmanın değil.', ''],
  ['battle', 'savaş, muharebe', 'BE-tıl', 'They won the battle.', 'Muharebeyi kazandılar.', ''],
  ['dollar', 'dolar', 'DA-lır', 'It costs five dollars.', 'Beş dolar tutuyor.', '💲'],
  ['nine', 'dokuz', 'NAYN', 'The shop opens at nine.', 'Dükkân dokuzda açılıyor.', ''],
  ['department', 'bölüm; departman', 'di-PAART-mınt', 'She works in the sales department.', 'Satış departmanında çalışıyor.', ''],
  ['guilty', 'suçlu', 'GİL-ti', 'I feel guilty.', 'Kendimi suçlu hissediyorum.', ''],
  ['apart', 'ayrı; aralıklı', 'ı-PAART', 'We live apart now.', 'Artık ayrı yaşıyoruz.', ''],
  ['duty', 'görev; vergi', 'DUU-ti', 'It is my duty.', 'Bu benim görevim.', ''],
  ['suit', 'takım elbise; yakışmak', 'SUUT', 'He is wearing a black suit.', 'Siyah bir takım elbise giyiyor.', '🤵'],
  ['bell', 'zil, çan', 'BEL', 'The bell is ringing.', 'Zil çalıyor.', '🔔'],
  ['west', 'batı', 'UEST', 'The sun sets in the west.', 'Güneş batıdan batar.', ''],
  ['leg', 'bacak', 'LEG', 'I broke my leg.', 'Bacağımı kırdım.', '🦵'],
  ['hero', 'kahraman', 'Hİİ-rou', 'My father is my hero.', 'Babam benim kahramanım.', ''],
  ['destroy', 'yok etmek, mahvetmek', 'di-STROY', 'The fire destroyed the house.', 'Yangın evi yok etti.', ''],
  ['stage', 'sahne; aşama', 'STEYC', 'The band is on stage.', 'Grup sahnede.', ''],
  ['bunch', 'demet; bir sürü', 'BANÇ', 'I bought a bunch of flowers.', 'Bir demet çiçek aldım.', ''],
  ['according', '-e göre (according to)', 'ı-KOR-ding', 'According to the news, it will rain.', 'Haberlere göre yağmur yağacak.', ''],
  ['chicken', 'tavuk', 'Çİ-kın', 'I want chicken and rice.', 'Tavuk ve pilav istiyorum.', '🐔'],
  ['low', 'alçak, düşük', 'LOU', 'The price is very low.', 'Fiyat çok düşük.', ''],
  ['admit', 'itiraf etmek, kabul etmek', 'ıd-MİT', 'I admit it was my fault.', 'Hatanın bende olduğunu kabul ediyorum.', ''],
  ['witness', 'tanık', 'UİT-nıs', 'She was a witness to the accident.', 'Kazanın tanığıydı.', ''],
  ['upstairs', 'üst kat, yukarıda', 'ap-STERZ', 'My room is upstairs.', 'Odam üst katta.', ''],
  ['steal', 'çalmak (hırsızlık)', 'STİİL', 'Someone stole my bike.', 'Birisi bisikletimi çaldı.', ''],
  ['kick', 'tekmelemek', 'KİK', 'Kick the ball!', 'Topa vur!', ''],
  ['twice', 'iki kez', 'TUAYS', 'I brush my teeth twice a day.', 'Günde iki kez dişlerimi fırçalarım.', ''],
  ['cross', 'geçmek; çapraz; kızgın', 'KROS', 'Cross the street carefully.', 'Caddeyi dikkatle geç.', ''],
  ['sergeant', 'çavuş', 'SAAR-cınt', 'The sergeant is very strict.', 'Çavuş çok sert.', ''],
  ['indeed', 'gerçekten, aslında', 'in-DİİD', 'It is indeed a nice day.', 'Gerçekten güzel bir gün.', ''],
  ['gas', 'gaz; benzin', 'GES', 'We need gas for the car.', 'Arabaya benzin lazım.', '⛽'],
  ['energy', 'enerji', 'E-nır-ci', 'I have no energy today.', 'Bugün hiç enerjim yok.', ''],
  ['pregnant', 'hamile', 'PREG-nınt', 'My sister is pregnant.', 'Kız kardeşim hamile.', ''],
  ['waste', 'israf etmek; atık', 'UEYST', "Don't waste water.", 'Suyu israf etme.', ''],
  ['favorite', 'en sevilen, favori', 'FEY-vı-rit', 'Blue is my favorite color.', 'En sevdiğim renk mavi.', ''],
  ['taste', 'tat; tadına bakmak', 'TEYST', 'This soup tastes great.', 'Bu çorbanın tadı harika.', ''],
  ['lock', 'kilit; kilitlemek', 'LAK', 'Lock the door, please.', 'Kapıyı kilitle, lütfen.', '🔒'],
  ['prince', 'prens', 'PRİNS', 'The prince lives in a palace.', 'Prens bir sarayda yaşıyor.', '🤴'],
  ['form', 'form; biçim', 'FORM', 'Please fill in this form.', 'Lütfen bu formu doldurun.', ''],
  ['silly', 'aptalca, saçma', 'Sİ-li', "Don't be silly.", 'Saçmalama.', ''],
  ['mention', 'bahsetmek', 'MEN-şın', 'He mentioned your name.', 'Senin adından bahsetti.', ''],
  ['build', 'inşa etmek', 'BİLD', 'They are building a new school.', 'Yeni bir okul inşa ediyorlar.', ''],
  ['throat', 'boğaz', 'TROUT', 'I have a sore throat.', 'Boğazım ağrıyor.', ''],
  ['hole', 'delik, çukur', 'HOUL', 'There is a hole in my sock.', 'Çorabımda bir delik var.', ''],
  ['track', 'iz; ray; parça (şarkı)', 'TREK', 'The train is on track two.', 'Tren ikinci yolda.', ''],
  ['above', 'üstünde, yukarısında', 'ı-BAV', 'The picture is above the bed.', 'Resim yatağın üstünde.', ''],
  ['breakfast', 'kahvaltı', 'BREK-fıst', 'I eat breakfast at seven.', 'Yedide kahvaltı ederim.', '🍳'],
  ['engine', 'motor', 'EN-cin', 'The engine is making a noise.', 'Motor ses çıkarıyor.', ''],
  ['complete', 'tamamlamak; tam', 'kım-PLİİT', 'Complete the sentence.', 'Cümleyi tamamla.', ''],
  ['video', 'video', 'Vİ-di-ou', 'Watch this funny video.', 'Bu komik videoyu izle.', ''],
  ['however', 'ancak, ne var ki', 'hau-E-vır', 'However, I am still hungry.', 'Ancak hâlâ açım.', ''],
  ['pressure', 'baskı; basınç', 'PRE-şır', 'I work under pressure.', 'Baskı altında çalışıyorum.', ''],
  ['fresh', 'taze', 'FREŞ', 'I buy fresh bread every day.', 'Her gün taze ekmek alırım.', ''],
  ['weapon', 'silah', 'UE-pın', 'The police found the weapon.', 'Polis silahı buldu.', ''],
  ['sky', 'gökyüzü', 'SKAY', 'The sky is blue today.', 'Bugün gökyüzü mavi.', ''],
  ['study', 'ders çalışmak; incelemek', 'STA-di', 'I study English every day.', 'Her gün İngilizce çalışırım.', ''],
  ['burn', 'yakmak, yanmak', 'BÖRN', "Don't burn the food.", 'Yemeği yakma.', ''],
  ['crowd', 'kalabalık', 'KRAUD', 'There is a big crowd outside.', 'Dışarıda büyük bir kalabalık var.', ''],
  ['treat', 'davranmak; ısmarlamak; ikram', 'TRİİT', 'Dinner is my treat.', 'Akşam yemeği benden.', ''],
  ['roll', 'yuvarlamak; rulo', 'ROUL', 'The ball rolled under the car.', 'Top arabanın altına yuvarlandı.', ''],
  ['double', 'çift, iki kat', 'DA-bıl', 'I want a double room.', 'Çift kişilik oda istiyorum.', ''],
  ['spirit', 'ruh; moral', 'SPİ-rit', 'Keep your spirits up!', 'Moralini yüksek tut!', ''],
  ['danger', 'tehlike', 'DEYN-cır', 'Danger! Do not enter.', 'Tehlike! Girmeyin.', ''],
  ['cost', 'mal olmak; maliyet', 'KOST', 'How much does it cost?', 'Bu ne kadar?', ''],
  ['empty', 'boş', 'EMP-ti', 'The fridge is empty.', 'Buzdolabı boş.', ''],
  ['level', 'seviye', 'LE-vıl', 'What is your English level?', 'İngilizce seviyen ne?', ''],
  ['memory', 'hafıza; anı', 'ME-mı-ri', 'I have a bad memory.', 'Hafızam kötü.', ''],
  ['interest', 'ilgi; faiz', 'İN-trıst', 'I have no interest in football.', 'Futbola hiç ilgim yok.', ''],
  ['nose', 'burun', 'NOUZ', 'My nose is cold.', 'Burnum üşüdü.', '👃'],
  ['bathroom', 'banyo, tuvalet', 'BET-ruum', 'Where is the bathroom?', 'Tuvalet nerede?', '🛁'],
  ['band', 'müzik grubu; bant', 'BEND', 'My brother plays in a band.', 'Erkek kardeşim bir grupta çalıyor.', ''],
  ['apparently', 'görünüşe göre', 'ı-PE-rınt-li', 'Apparently, he is sick.', 'Görünüşe göre hasta.', ''],
  ['excited', 'heyecanlı', 'ik-SAY-tid', 'I am so excited!', 'Çok heyecanlıyım!', ''],
  ['animal', 'hayvan', 'E-ni-mıl', 'What is your favorite animal?', 'En sevdiğin hayvan ne?', ''],
  ['flight', 'uçuş', 'FLAYT', 'My flight is at six.', 'Uçuşum altıda.', ''],
  ['nature', 'doğa', 'NEY-çır', 'I love nature.', 'Doğayı severim.', ''],
  ['raise', 'kaldırmak; yetiştirmek', 'REYZ', 'Raise your hand.', 'Elini kaldır.', ''],
  ['pop', 'patlamak; pop müzik', 'PAP', 'I like pop music.', 'Pop müziği severim.', ''],
  ['client', 'müşteri', 'KLAY-ınt', 'I have a meeting with a client.', 'Bir müşteriyle toplantım var.', ''],
  ['bomb', 'bomba', 'BAM', 'The bomb did not explode.', 'Bomba patlamadı.', '💣'],
  ['neck', 'boyun', 'NEK', 'My neck hurts.', 'Boynum ağrıyor.', ''],
  ['suspect', 'şüpheli; şüphelenmek', 'SAS-pekt', 'The police caught the suspect.', 'Polis şüpheliyi yakaladı.', ''],
  ['warm', 'ılık, sıcak', 'UORM', 'It is warm today.', 'Bugün hava ılık.', ''],
  ['extra', 'ekstra, fazladan', 'EK-strı', 'Can I have an extra bag?', 'Fazladan bir poşet alabilir miyim?', ''],
  ['bottle', 'şişe', 'BA-tıl', 'A bottle of water, please.', 'Bir şişe su, lütfen.', '🍾'],
  ['van', 'minibüs, kamyonet', 'VEN', 'We moved with a small van.', 'Küçük bir kamyonetle taşındık.', '🚐'],
  ['heavy', 'ağır', 'HE-vi', 'This bag is very heavy.', 'Bu çanta çok ağır.', ''],
  ['wild', 'vahşi, yabani', 'UAYLD', 'Lions are wild animals.', 'Aslanlar vahşi hayvanlardır.', ''],
  ['ridiculous', 'gülünç, saçma', 'ri-Dİ-kyu-lıs', "That's ridiculous!", 'Bu çok saçma!', ''],
  ['simply', 'basitçe; sadece', 'SİM-pli', "I simply don't know.", 'Sadece bilmiyorum.', ''],
  ['camp', 'kamp; kamp yapmak', 'KEMP', 'We camp by the lake.', 'Gölün kenarında kamp yapıyoruz.', '⛺'],
  ['medical', 'tıbbi', 'ME-di-kıl', 'He needs medical help.', 'Tıbbi yardıma ihtiyacı var.', ''],
  ['shame', 'utanç; yazık', 'ŞEYM', 'What a shame!', 'Ne yazık!', ''],
  ['bird', 'kuş', 'BÖRD', 'A bird is singing.', 'Bir kuş ötüyor.', '🐦'],
  ['flower', 'çiçek', 'FLAU-ır', 'These flowers are for you.', 'Bu çiçekler senin için.', '🌸'],
  ['famous', 'ünlü', 'FEY-mıs', 'He is a famous singer.', 'O ünlü bir şarkıcı.', ''],
  ['asleep', 'uykuda', 'ı-SLİİP', 'The baby is asleep.', 'Bebek uyuyor.', ''],
  ['beauty', 'güzellik', 'BYUU-ti', 'I love the beauty of nature.', 'Doğanın güzelliğini severim.', ''],
  ['driver', 'sürücü, şoför', 'DRAY-vır', 'The bus driver is very kind.', 'Otobüs şoförü çok nazik.', ''],
  ['rain', 'yağmur; yağmur yağmak', 'REYN', 'It is raining.', 'Yağmur yağıyor.', '🌧️'],
  ['awful', 'berbat, korkunç', 'O-fıl', 'The food was awful.', 'Yemek berbattı.', ''],
  ['large', 'büyük, geniş', 'LAARC', 'A large coffee, please.', 'Büyük bir kahve, lütfen.', ''],
  ['local', 'yerel', 'LOU-kıl', 'I shop at the local market.', 'Yerel pazardan alışveriş yaparım.', ''],
  ['deserve', 'hak etmek', 'di-ZÖRV', 'You deserve a break.', 'Bir molayı hak ediyorsun.', ''],
  ['stone', 'taş', 'STOUN', 'The house is made of stone.', 'Ev taştan yapılmış.', '🪨'],
  ['consider', 'düşünmek, göz önüne almak', 'kın-Sİ-dır', 'Please consider my offer.', 'Lütfen teklifimi düşün.', ''],
  ['weekend', 'hafta sonu', 'UİİK-end', 'Have a nice weekend!', 'İyi hafta sonları!', ''],
  ['lay', 'koymak, yatırmak', 'LEY', 'Lay the baby on the bed.', 'Bebeği yatağa yatır.', ''],
  ['plenty', 'bol bol, çok', 'PLEN-ti', 'We have plenty of time.', 'Bol bol vaktimiz var.', ''],
  ['willing', 'istekli, gönüllü', 'Uİ-ling', 'I am willing to help.', 'Yardım etmeye hazırım.', ''],
  ['pants', 'pantolon', 'PENTS', 'These pants are too long.', 'Bu pantolon çok uzun.', '👖'],
  ['sweetheart', 'tatlım, sevgilim', 'SUİİT-haart', 'Good morning, sweetheart.', 'Günaydın, tatlım.', ''],
  ['skin', 'cilt, deri', 'SKİN', 'She has beautiful skin.', 'Onun cildi çok güzel.', ''],
  ['excellent', 'mükemmel', 'EK-sı-lınt', 'Your work is excellent.', 'İşin mükemmel.', ''],
  ['beach', 'plaj, sahil', 'BİİÇ', "Let's go to the beach.", 'Hadi plaja gidelim.', '🏖️'],
  ['faith', 'inanç', 'FEYT', 'Have faith in yourself.', 'Kendine inan.', ''],
  ['beg', 'yalvarmak; dilenmek', 'BEG', 'I beg you, please help me.', 'Yalvarırım, bana yardım et.', ''],
  ['responsible', 'sorumlu', 'ri-SPAN-sı-bıl', 'You are responsible for this.', 'Bundan sen sorumlusun.', ''],
  ['military', 'askeri; ordu', 'Mİ-lı-te-ri', 'He is in the military.', 'O askerde.', ''],
  ['opportunity', 'fırsat', 'a-pır-TUU-nı-ti', 'This is a great opportunity.', 'Bu harika bir fırsat.', ''],
  ['common', 'yaygın; ortak', 'KA-mın', 'This is a common name.', 'Bu yaygın bir isim.', ''],
  ['bottom', 'alt, dip', 'BA-tım', 'My keys are at the bottom.', 'Anahtarlarım en altta.', ''],
  ['German', 'Almanca; Alman', 'CÖR-mın', 'My friend speaks German.', 'Arkadaşım Almanca konuşuyor.', ''],
  ['whoever', 'her kim', 'huu-E-vır', 'Whoever comes first wins.', 'İlk gelen kazanır.', ''],
  ['cook', 'yemek pişirmek; aşçı', 'KUK', 'My father cooks dinner.', 'Babam akşam yemeğini pişirir.', '🧑‍🍳'],
  ['justice', 'adalet', 'CAS-tis', 'We want justice.', 'Adalet istiyoruz.', ''],
  ['hall', 'salon; koridor', 'HOL', 'Wait in the hall, please.', 'Lütfen koridorda bekleyin.', ''],
  ['commander', 'komutan', 'kı-MEN-dır', 'The commander gave the order.', 'Komutan emri verdi.', ''],
  ['main', 'ana, asıl', 'MEYN', 'This is the main street.', 'Burası ana cadde.', ''],
  ['knife', 'bıçak', 'NAYF', 'Be careful with that knife.', 'O bıçağa dikkat et.', '🔪'],
  ['devil', 'şeytan', 'DE-vıl', 'He is a little devil.', 'O küçük bir şeytan.', '😈'],
  ['necessary', 'gerekli', 'NE-sı-se-ri', 'Is it necessary?', 'Bu gerekli mi?', ''],
  ['although', '-e rağmen, gerçi', 'ol-DOU', 'Although it was cold, we swam.', 'Hava soğuk olmasına rağmen yüzdük.', ''],
  ['princess', 'prenses', 'PRİN-ses', 'She looks like a princess.', 'Bir prenses gibi görünüyor.', '👸'],
  ['rose', 'gül', 'ROUZ', 'He gave me a red rose.', 'Bana kırmızı bir gül verdi.', '🌹'],
  ['clearly', 'açıkça, net', 'KLİİR-li', 'Please speak clearly.', 'Lütfen açık konuş.', ''],
  ['hat', 'şapka', 'HET', 'I like your hat.', 'Şapkanı beğendim.', '🎩'],
  ['corner', 'köşe', 'KOR-nır', 'The shop is on the corner.', 'Dükkân köşede.', ''],
  ['code', 'kod, şifre', 'KOUD', 'What is the code?', 'Şifre ne?', ''],
  ['note', 'not; nota', 'NOUT', 'I left you a note.', 'Sana bir not bıraktım.', '📝'],
  ['due', '-den dolayı; vadesi gelen', 'DUU', 'The train is due at five.', 'Trenin beşte gelmesi bekleniyor.', ''],
  ['correct', 'doğru; düzeltmek', 'kı-REKT', 'That is the correct answer.', 'Bu doğru cevap.', ''],
  ['apologize', 'özür dilemek', 'ı-PA-lı-cayz', 'I apologize for being late.', 'Geç kaldığım için özür dilerim.', ''],
  ['language', 'dil (lisan)', 'LENG-guic', 'I speak two languages.', 'İki dil konuşurum.', ''],
  ['folk', 'insanlar (folks); halk', 'FOUK', 'Hi, folks!', 'Selam millet!', ''],
  ['fellow', 'adam; arkadaş, dost', 'FE-lou', 'He is a nice fellow.', 'O iyi bir adam.', ''],
  ['several', 'birkaç', 'SEV-rıl', 'I have several friends there.', 'Orada birkaç arkadaşım var.', ''],
  ['grandmother', 'büyükanne (grandma)', 'GREND-ma-dır', 'My grandmother is ninety.', 'Büyükannem doksan yaşında.', '👵'],
  ['leader', 'lider', 'Lİİ-dır', 'She is a good leader.', 'O iyi bir lider.', ''],
  ['restaurant', 'restoran', 'RES-tı-rant', "Let's eat at a restaurant.", 'Hadi bir restoranda yiyelim.', '🍴'],
  ['east', 'doğu', 'İİST', 'The sun rises in the east.', 'Güneş doğudan doğar.', ''],
  ['blind', 'kör', 'BLAYND', 'The old man is blind.', 'Yaşlı adam kör.', ''],
  ['ghost', 'hayalet', 'GOUST', "I don't believe in ghosts.", 'Hayaletlere inanmam.', '👻'],
  ['cup', 'fincan; kupa', 'KAP', 'A cup of coffee, please.', 'Bir fincan kahve, lütfen.', '☕'],
  ['tight', 'sıkı, dar', 'TAYT', 'These jeans are too tight.', 'Bu kot pantolon çok dar.', ''],
  ['conversation', 'sohbet, konuşma', 'kan-vır-SEY-şın', 'We had a long conversation.', 'Uzun bir sohbet ettik.', ''],
];
